### ISSUE TITLE
LLSE建议添加声音吧播放功能如原版指令playsound此类型的接口

### ISSUE THREAD

**Issue by xinge4088** [LiteLDev/LiteLoader#1002]
### 您的建议是否与现存的某个问题相关?请描述问题?

声音也是游戏很重要的一个组成部分，玩家良好的游戏体验直接体现在视觉，听觉等主要方面，此接口能极大丰富玩家的交互性

### 您认为还缺少什么?如何解决您的问题?

建议添加声音吧播放功能如原版指令playsound此类型的接口

**Comment by ImYoyoData** [comment]
播放 mp3 ? 最好还能支持服务器远程地址? 🤭

**Comment by lgc2333** [comment]
#630 :(

**Comment by lgc2333** [comment]
https://github.com/lgc2333/LLSEPlugins/blob/main/NbsPlayer/src/index.ts#L79

**Comment by Jaciezyt** [comment]
Duplicate of #630
