### ISSUE TITLE
CommandSelector 缓冲区溢出漏洞

### ISSUE THREAD

**Issue by kkj9333** [LiteLDev/LiteLoader#1006]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.9.1

### BDS 版本

1.19.51

### 发生了什么?

在编写原生插件时发现使用commandselector的类有概率会发生如下错误：
![image](https://user-images.githubusercontent.com/51207072/212384098-680d12fc-23c2-4819-889d-07d1f9f5a3cd.png)
分析后发现：
是由于commandselector结构大小分配错误，析构时调用bds内部的函数移除了错误大小的内存导致的，析构方式未知，进一步发现实际大小应为200，（LL内部为192），如果commandselector处于类的末端就有可能导致这个问题：
![image](https://user-images.githubusercontent.com/51207072/212386633-578736a9-41d4-41ff-af1c-a9ff26d24821.png)
由于头文件不可修改，希望尽快修复这个问题，目前的解决方案只能是栈上的后边添加大小至少为8的变量作为缓冲区。

### 复现此问题的步骤

1.随便一个函数或类里构造一个commandselector对象，且后面无其他局部变量或类成员
2.当函数执行完或类析构时，会造成堆栈溢出异常或者系统中断

**Comment by Jaciezyt** [comment]
为什么要构造CommandSelector

**Comment by kkj9333** [comment]
> 为什么要构造CommandSelector

很显然是command里需要选择器，然后绑定回传结果

**Comment by kkj9333** [comment]
> 为什么要构造CommandSelector

参考liteloader tpdim的用法，在command类中构造CommandSelector

**Comment by Jaciezyt** [comment]
@kkj9333 按理说是在bds里构造的，而不是插件

**Comment by kkj9333** [comment]
> @kkj9333 按理说是在bds里构造的，而不是插件
我的构造方法和liteloader的原生命令tpdim是完全一样的，唯一不同的是tpdim里面的commandselector把下面的其他类成员当成缓冲区了。
的确是调用了bds的构造函数，但是内存空间的大小是由插件（通过commandselector的头文件定义）分配

**Comment by Jaciezyt** [comment]
@kkj9333 你说的对

**Comment by kkj9333** [comment]
> @kkj9333 按理说是在bds里构造的，而不是插件

事实就是如此，这个漏洞甚至有可能作为远程代码执行的后门
