### ISSUE TITLE
LLSE ScoreBoard API 操作分数问题

### ISSUE THREAD

**Issue by lgc2333** [LiteLDev/LiteLoader#1007]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows 10

### LiteLoader 版本

2.9.1

### BDS 版本

1.19.51.01

### 发生了什么?

relative to #860

![image](https://user-images.githubusercontent.com/59048777/212397166-1c7a0bb5-f809-4c92-af6f-a988078b9fe2.png)

**Comment by Jaciezyt** [comment]
Duplicate of #860

**Comment by kkj9333** [comment]
建议使用离线计分板经济方式，仅需要知道uuid即可修改（在线或者不在线均可）

**Comment by kkj9333** [comment]
建议使用离线计分板经济方式，仅需要知道uuid即可修改（在线或者不在线均可）

**Comment by kkj9333** [comment]
离线修改是强制进行的，如果不存在计分板就会创建计分板，不存在玩家计分板记录（但是玩家在服务器登录过）就会强制创建
