### ISSUE TITLE
为权限组添加更多可由插件操作的api

### ISSUE THREAD

**Issue by harry-xi** [LiteLDev/LiteLoader#1008]
### 您的建议是否与现存的某个问题相关?请描述问题?

在我编写一个插件时，我发现我无法在插件内直接利用ll提供的api来获取在全局存在的权限实例和身份组的列表

### 您认为还缺少什么?如何解决您的问题?

让权限组的所有命令可进行的操作能力和信息获取能力都有其对应的api（在ll和llse）

**Comment by RimuruChan** [comment]
将会在3.0重构。
