### ISSUE TITLE
LLSE 离线读写计分板API 报错问题与修改建议

### ISSUE THREAD

**Issue by Hurry1027** [LiteLDev/LiteLoader#1014]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2019

### LiteLoader 版本

2.9.1

### BDS 版本

1.19.51

### 发生了什么?

1、新建存档，没有玩家进过服，获取不存在的计分项（a）值报错。
2、新建存档，没有玩家进过服，设置玩家计分板值（a）报错，但自动了创建计分项（a）。
3、新建存档，玩家进服，计分项（a）已创建，获取玩家计分项（a）值报错。
4、新建存档，玩家进服，计分项（a）已创建，获取玩家【不存在的计分项（b）】值报错。
5、新建存档，玩家进服，计分项（a）已创建，获取【不存在的玩家】计分项（a）值报错。
以上问题是一连串的，详情见附录图片。
（以上问题在新建存档发生）
.
6、**离线获取计分项的api**，
**计分项a**已创建，但玩家没有设定该**计分项a**的值，但mc.getPlayerScore('uuid', 'a')返回值为**0**，这个应该返回**null**才对。
因为我在做跨服计分板同步，如果返回**0**会造成另一服务器同步计分板值为0，而实际该玩家没有该计分项的值。

**Comment by Hurry1027** [comment]
![获取离线计分板](https://user-images.githubusercontent.com/81138587/212615611-5308591c-59ef-454f-8615-b2c24006b404.png)

**Comment by ShrBox** [comment]
![image](https://user-images.githubusercontent.com/53301243/212894121-0080a451-40df-4892-b3e7-6af0a25eec0c.png)
我不能理解

**Comment by Hurry1027** [comment]
> ![image](https://user-images.githubusercontent.com/53301243/212894121-0080a451-40df-4892-b3e7-6af0a25eec0c.png) 我不能理解

这两种情况当然是错误的使用方法，但可以优化api的稳定性，返回null就好。
主要是 “玩家进服，计分板已创建，获取分数失败” 这个会影响api正常使用，
以及在玩家没有分数时，会返回0而不是null，这个需要修改。

**Comment by kkj9333** [comment]
getPlayerScore的设计就是玩家有分数才返回分数，没分数返回NULL，如果在getPlayerScore时强制创建ScoreboardId，现有的deletescore就无意义了

>

**Comment by kkj9333** [comment]
存档里没有某个玩家的记录去获取分数是非法的，我等下试试看能不能把报错去了

**Comment by kkj9333** [comment]
[1][2][4][5]实际上都是由于对不存在的玩家进行不当操作而导致的；
[3]是因为玩家没有分数，返回option::null，但貌似在llse层直接抛出异常了
