### ISSUE TITLE
`File`行为异常

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#1021]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.9.1 Actions#129 0800d60

### BDS 版本

1.19.51.01

### 发生了什么?

`File.open`遇到了类似#1017 的问题

**Comment by Redbeanw44602** [comment]
请给出复现代码

**Comment by Yushu2606** [comment]
> 请给出复现代码

https://github.com/LiteLScript-Dev/LXL-Plugins/blob/main/BehaviorLog.lxl.js
