### ISSUE TITLE
俯仰角得到的数据小于-90°

### ISSUE THREAD

**Issue by uncharity** [LiteLDev/LiteLoader#1024]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows 10

### LiteLoader 版本

2.9.0

### BDS 版本

1.19.51

### 发生了什么?

![image](https://user-images.githubusercontent.com/101495423/213156963-410759ab-3677-4dec-9440-48145ef5067d.png)
![image](https://user-images.githubusercontent.com/101495423/213156978-65d37ef0-76cd-4190-8b28-a18ff0000efd.png)
![image](https://user-images.githubusercontent.com/101495423/213156984-cd5f8004-5640-4b52-8a5d-5ac49e0ccf62.png)

### 复现此问题的步骤

1.玩家的键盘和鼠标设置为全键盘
2.然后只用全键盘抬头

**Comment by OEOTYAN** [comment]
这个问题还在吗？
