### ISSUE TITLE
当安装有Addon时 SimulatedPlayer会导致崩服

### ISSUE THREAD

**Issue by lgc2333** [LiteLDev/LiteLoader#1026]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

其他操作系统

### LiteLoader 版本

2.9.1

### BDS 版本

1.19.51.01

### 发生了什么?

[log.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/10448804/log.zip)

### 复现此问题的步骤

安装Addon https://mcpedl.com/morningstar-war-addon/  
安装LL插件 https://github.com/lgc2333/LLSEPlugins/blob/main/Airdrop/Airdrop.js  
当使用 `pluginConfig.triggerItem` 时，就会导致崩服  

稳定复现，后台显示SimulatedPlayer加入后就直接崩掉了

### 有关的日志/输出

```raw
见发生了什么
```

### 插件列表

```raw
见复现步骤
```

**Comment by Yushu2606** [comment]
bds的空指针bug（

**Comment by Redbeanw44602** [comment]
1. 有可能是addon的问题，因为bds对addon的操作基本不设防
2. 就算稳定复现，你也应该提供崩服日志

**Comment by Yushu2606** [comment]
> 1. 有可能是addon的问题，因为bds对addon的操作基本不设防
> 
> 2. 就算稳定复现，你也应该提供崩服日志

发生了什么里有日志和转储（

**Comment by Redbeanw44602** [comment]
抱歉，看漏了。

仔细看了下插件和log，感觉不是addon问题就是mcbug。建议试试不用onUseItem看看问题会不会出现

**Comment by lgc2333** [comment]
补充，使用其他addon不会崩

**Comment by harry-xi** [comment]
> 抱歉，看漏了。
> 
> 仔细看了下插件和log，感觉不是addon问题就是mcbug。建议试试不用onUseItem看看问题会不会出现

> 补充，使用其他addon不会崩

简单看来眼出问题这个Addon
极有可能问题出现minecraft的SAPI（行为包的脚本系统）里，或许是LL的虚拟玩家与真实玩家的差异引起了本addon的行为包在执行时内部的脚本时引发了SAPI的异常。

另外 @lgc2333  如果是自己使用，我强烈建议换一个addon，一个存在后门（指特定玩家可以通过特定聊天栏消息获得addon物品）且每tick通过SAPI执行大量命令的addon不会是一个好选择。

**Comment by lgc2333** [comment]
> > 抱歉，看漏了。
> > 仔细看了下插件和log，感觉不是addon问题就是mcbug。建议试试不用onUseItem看看问题会不会出现
> 
> > 补充，使用其他addon不会崩
> 
> 简单看来眼出问题这个Addon 极有可能问题出现minecraft的SAPI（行为包的脚本系统）里，或许是LL的虚拟玩家与真实玩家的差异引起了本addon的行为包在执行时内部的脚本时引发了SAPI的异常。
> 
> 另外 @lgc2333 如果是自己使用，我强烈建议换一个addon，一个存在后门（指特定玩家可以通过特定聊天栏消息获得addon物品）且每tick通过SAPI执行大量命令的addon不会是一个好选择。

好的，感谢解惑
