### ISSUE TITLE
让 LLSE 的 mc.listen 可以取消自己的监听

### ISSUE THREAD

**Issue by lgc2333** [LiteLDev/LiteLoader#1030]
### 您的建议是否与现存的某个问题相关?请描述问题?

`mc.listen` 无法取消监听

### 您认为还缺少什么?如何解决您的问题?

可以让 `mc.listen` 返回一个函数，调用这个函数可以取消该事件监听

**Comment by Yushu2606** [comment]
我觉得得做成`Event.addListen`（或者当`Event.listen`的别名）和`Event.removeListen`的形式更舒服些（

**Comment by lgc2333** [comment]
https://github.com/LiteLDev/Documentation/pull/68
