### ISSUE TITLE
增加发送表情（Emote）事件

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#1034]
### 您的建议是否与现存的某个问题相关?请描述问题?

缺少发送[表情](https://minecraft.fandom.com/zh/wiki/%E8%A1%A8%E6%83%85)事件

### 您认为还缺少什么?如何解决您的问题?

增加发送[表情](https://minecraft.fandom.com/zh/wiki/%E8%A1%A8%E6%83%85)事件

**Comment by XiaoXiaoYang233** [comment]
你在说什么

**Comment by StarsDream00** [comment]
> 你在说什么

我在说**增加发送表情事件**

**Comment by XiaoXiaoYang233** [comment]
你是懂发issues的

**Comment by Jaciezyt** [comment]
> 你是懂发issues的

他说的大概是那个皮肤里面的动作

**Comment by dreamguxiang** [comment]
@Jasonzyt 😎😎

**Comment by Jasonzyt** [comment]
WTF

**Comment by Yushu2606** [comment]
> > _攻击性语言_
> 
> 他说的大概是那个皮肤里面的动作

参考官方译名，正确称呼应为`表情`

> > 表情（Emote）是角色创建器的一部分，可以让玩家在游戏中做出各种动作。
>
> ——摘自[Minecraft Fandom Wiki](https://minecraft.fandom.com/zh/wiki/%E8%A1%A8%E6%83%85)

**Comment by XiaoXiaoYang233** [comment]
哦哦那没事了，抱歉，还以为又是一个无脑与表述意义不明的issues

**Comment by StarsDream00** [comment]
找到一个可能相关符号（`?addPersonaEmotePlayed@EventingRequest@@SA?AU1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_NH@Z`），等待测试

**Comment by StarsDream00** [comment]
找到可用符号`??0EmotePacket@@QEAA@XZ`

**Comment by dreamguxiang** [comment]
hook handle不就好了吗

**Comment by Yushu2606** [comment]
> hook handle不就好了吗

我是菜鸡xwx

**Comment by Yushu2606** [comment]
非大量使用的事件建议自行hook

_Originally posted by @WangYneos in https://github.com/LiteLDev/LiteLoaderBDS/issues/1211#issuecomment-1518569474_
