### ISSUE TITLE
DirectionAngle存在问题

### ISSUE THREAD

**Issue by uncharity** [LiteLDev/LiteLoader#1035]
### Exceptions module

ScriptEngine

### Operating System

Windows 10

### LiteLoader version

2.9.2

### BDS version

1.19.51

### What happened?

pl.teleport(x,y,z,dimid[,rot])
rot参数无用
![image](https://user-images.githubusercontent.com/101495423/213699914-a1e8f32c-7300-412c-8fff-fdd03084ff5f.png)

### Steps to reproduce?

我不到啊,就是teleport的rot参数使用时无效,然后问了一下harryxi大佬,他表示这个问题确实存在,然后就发了个issue

**Comment by Redbeanw44602** [comment]
起码给下复现代码

**Comment by uncharity** [comment]
> 起码给下复现代码

有两个睿智(是真的丢人)

**Comment by uncharity** [comment]
> 起码给下复现代码

我和harryxi眼瞎了

**Comment by Redbeanw44602** [comment]
所以复现代码呢，如果没有问题麻烦自己把issue关了。
