### ISSUE TITLE
自定义BossBar导致很久更新一次其他玩家位置

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#1038]
### 异常模块

Minecraft

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.9.2

### BDS 版本

1.19.51.01

### 发生了什么?

持续向玩家发送BossBar后会导致该玩家很久更新一次其他玩家位置
与[MCPE-62517](https://bugs.mojang.com/browse/MCPE-62517)类似

### 复现此问题的步骤

```js
pl.setBossBar(
    0,
    "",
    Math.floor(Math.random() * 101),
    Math.floor(Math.random() * 7)
)
```

### 插件列表

https://github.com/SourceLandDev/PtrarcScript/blob/main/LLSE/HubInfo.js

**Comment by wzyyyyyyy** [comment]
@StarsDream00 这是liteloader的bug？

**Comment by StarsDream00** [comment]
> @StarsDream00 这是liteloader的bug？

是BDS的TwT

**Comment by Redbeanw44602** [comment]
LL不处理mcbug，除非其危害性极大。

**Comment by StarsDream00** [comment]
need reopen
