### ISSUE TITLE
fix the bug please! thank you

### ISSUE THREAD

**Issue by kimdaejin12** [LiteLDev/LiteLoader#1042]
### Exceptions module

Core

### Operating System

Windows 10

### LiteLoader version

2.9.2+56fe822

### BDS version

1.19.51.01

### What happened?

Event::PlayerAttackEvent::subscribe([](const Event::PlayerAttackEvent& event) {
    float x = event.mPlayer->getPosition().x;
    cout << x << endl;

    return true;
    
12:27:23 ERROR [LiteLoader] Uncaught SEH Exception Detected!
12:27:23 ERROR [LiteLoader] Error: Code [-1073741819] SEH_UNKNOW_ERROR
12:27:23 ERROR [LiteLoader] In Event (class Event::PlayerAttackEvent)
12:27:23 ERROR [LiteLoader] In Plugin <plugin.dll 1.0.0>

**Comment by KobeBryant114514** [comment]
use " cout << std::to_string(x) << endl; " please.

**Comment by futrime** [comment]
Please change the title to a more informative one.
