### ISSUE TITLE
在Release中添加版本等元数据信息

### ISSUE THREAD

**Issue by hhhxiao** [LiteLDev/LiteLoader#1045]
### 您的建议是否与现存的某个问题相关?请描述问题?

有时候想知道装了LL的BDS是什么版本，LL自身又是什么版本等信息。方便做兼容检查和环境检测等。

### 您认为还缺少什么?如何解决您的问题?

可以给`bedorck_server_mod.exe`加上`--version`参数或者类似的，让它使用这个参数启动时不要启动BDS而是打印相关元数据信息。当然仅仅是参考方案，只是希望能有一个获取相关信息的渠道。

**Comment by yqs112358** [comment]
完成了么，在哪个commit？
