### ISSUE TITLE
能否增加java程序的加载器

### ISSUE THREAD

**Issue by Misakait** [LiteLDev/LiteLoader#1048]

**Comment by Jaciezyt** [comment]
@misakajialin LL.NET应该可以实现，但这都是后话了

**Comment by Yushu2606** [comment]
可以，但没必要
如果真的是刚需，那为什么不用Nukkit/Geyser呢？

**Comment by RimuruChan** [comment]
Java 语言对于 FFI 的支持较差，且当前正在重构 LL3.0，暂时没有添加 Java 程序加载器的规划。

**Comment by Yushu2606** [comment]
可以用LiteLoader.NET+ikvm曲线救国（）

**Comment by KawaiiNahida** [comment]
可以但没必要，ScriptEngine是为了方便，.NET Support是cpp ffi完善，而jvm系ffi过于麻烦，能力有限，现阶段应先维护好CPP相关内容，再考虑拓展功能
