### ISSUE TITLE
插件在没有ll unload的情况下用ll load会刷屏

### ISSUE THREAD

**Issue by omscsamilcup** [LiteLDev/LiteLoader#1051]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.9.3

### BDS 版本

1.19.50

### 发生了什么?

![image](https://user-images.githubusercontent.com/112487226/216767616-38ec80fc-3a5e-44fa-b3cd-f731a0bbe86f.png)

### 复现此问题的步骤

在没有使用ll unload的时候用ll load会出现刷屏/插件功能重复出现，包括pl.addScore(),mc.listen('onChat'),mc.listen('onJoin')等功能

**Comment by yqs112358** [comment]
什么叫 没有使用ll unload的时候用ll load
插件是不允许load两次的，如果需要重新加载使用 ll reload

**Comment by omscsamilcup** [comment]
![image](https://user-images.githubusercontent.com/112487226/217213005-3a6fe2bd-7d7a-4604-bd53-32fa141a5cb0.png)
![image](https://user-images.githubusercontent.com/112487226/217213079-4a9dfd61-cc06-4939-93fe-6e29a9a85ae2.png)
确定哦

**Comment by omscsamilcup** [comment]
在没有unload的情况下，再次load插件，会导致插件再次执行功能

**Comment by yqs112358** [comment]
无法复现
![image](https://user-images.githubusercontent.com/37969157/227723586-89404a85-9085-482e-85e3-5eb7134fb499.png)

**Comment by omscsamilcup** [comment]
好像已经修复了

**Comment by yqs112358** [comment]
ok
