### ISSUE TITLE
2.10以后还是来一个完整llbds组件包吧

### ISSUE THREAD

**Issue by zevlaoxie2010** [LiteLDev/LiteLoader#1063]
### 您的建议是否与现存的某个问题相关?请描述问题?

原因：
LiteLoaderBDS发行方式改动说明：
自2.10.0-beta.1版本开始，将会增加以组件形式分别打包的发行方式。
旧有发行方式依旧有效，LiteLoaderBDS.zip这一文件为LL+LLSE的所有组件，可以直接下载使用。
非必须组件（如LLMoney、LLPermission、LLParticle等）则不再包含于LiteLoaderBDS.zip中，用户需要手动下载LLMoney.zip，解压到plugins/；手动下载LLParticle.zip和LLPermission.zip，解压到plugins/LiteLoader。
同时，lip install ll依然能够安装完整的LiteLoaderBDS。

### 您认为还缺少什么?如何解决您的问题?

这样影响更新服务器时的效率
且更容易忘记更新

**Comment by zevlaoxie2010** [comment]
单独一个完整包

**Comment by Singl-Daemon** [comment]
等lip完善了直接lip upgrade不就好了，还自己下什么(((

**Comment by futrime** [comment]
beta.2版本给完整包，但LLMoney依然不会在beta版本出现，因为LLMoney是另外编译的，需要等main分支SDK。

**Comment by zevlaoxie2010** [comment]
解决
