### ISSUE TITLE
假人api问题：在未加载区块创建的假人无法互动

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LiteLoader#1083]
如题
复现方法：在开服后，任何玩家进入之前先使用模拟玩家api创建一个假人，随后进服观察。
可以发现这个假人不受重力影响，不会捡物品，无法使用api操纵进行攻击、走路或者使用物品。不过这个假人可以正常加载其周围的区块，机器以及实体，只有他自己卡死，非常奇怪
在正常玩家加载范围内创建的假人无此问题。

**Comment by dreamguxiang** [comment]
已修复

**Comment by Yushu2606** [comment]
> 已修复

此功能无法由`FixMCBug`配置项控制

**Comment by dreamguxiang** [comment]
@StarsDream00 不考虑加入，主要为了修复LL假人API，使其功能正常
