### ISSUE TITLE
监听: 增加服务器关闭事件

### ISSUE THREAD

**Issue by Singl-Daemon** [LiteLDev/LiteLoader#1085]
### 您的建议是否与现存的某个问题相关?请描述问题?

没有这个api，我晚上睡不着觉(划)

增加这个api可以更好地让插件在关服时做出反应

### 您认为还缺少什么?如何解决您的问题?

增加一个新的监听事件，在服务器关闭时触发

**Comment by KawaiiNahida** [comment]
LL3.0: Plugin Interface

**Comment by Yushu2606** [comment]
https://github.com/LiteLDev/LiteLoaderBDS/blob/4de5cd6d5d7e063c10398fbb85b949b60b54cbfb/LiteLoader/src/llapi/EventAPI.cpp#L1899-L1909
