### ISSUE TITLE
Proposal: 插件间通信机制

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LiteLoader#1091]
作为模块化最重要的一块，需要提供完善的插件间通信机制。目前有两种应用场景：
- [x] **插件注册自定义事件**
举例：LLMoney目前导出了几个函数，用于其他插件在LLMoney金额变动时得到通知，也就是自定义事件监听。在LL3中需要提供完善的插件自定义事件注册机制，提供类似于内置事件的listen接口

- [x] **插件导入导出函数**
此功能类似于LLSE的export和import，重要性不言自明。目前LL2提供了基础的类似机制，使用LoadLibrary实现，不过考虑到插件类型不仅限于CPP插件，相关接口不能仅仅像LL2一样简单根据原型查找符号并调用。需要提出更好的跨语言、跨插件导入导出机制

- [x] **插件间直接通信接口**
便于插件间直接进行部分消息的通信，比如服务端监听某地址，客户端直接向目标地址发送数据包。可以对内核中的管道进行简单封装来实现。

**Comment by StarsDream00** [comment]
#973

**Comment by RimuruChan** [comment]
#1435
