### ISSUE TITLE
爆炸类事件增加受影响方块数组参数

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#1096]
### 您的建议是否与现存的某个问题相关?请描述问题?

ScriptAPI的爆炸事件可以获取所有受影响方块，可以方便地选择性摧毁
而LL现有的API只能直接拦截爆炸，不能细化至单个方块

### 您认为还缺少什么?如何解决您的问题?

向爆炸类事件增加受影响方块数组参数

**Comment by quizhizhe** [comment]
感觉有点难做到，在`Explosion::explode`计算出需要破坏的方块并且存起来，之后也是在`Explosion::explode`里使用了这些数据，并且破坏了方块

**Comment by Yushu2606** [comment]
> 感觉有点难做到，在`Explosion::explode`计算出需要破坏的方块并且存起来，之后也是在`Explosion::explode`里使用了这些数据，并且破坏了方块

直接参考gametest的实现就行

**Comment by quizhizhe** [comment]
> > 感觉有点难做到，在`Explosion::explode`计算出需要破坏的方块并且存起来，之后也是在`Explosion::explode`里使用了这些数据，并且破坏了方块
> 
> 直接参考gametest的实现就行

这样需要更改事件点位，直接使用bds内的事件系统，我怕一些使用了这个事件的插件会因为这个改动，而不能达到想要的操作。bds的这个内部事件是在`Explosion::explode`里面，所以会晚触发。增加新事件？

**Comment by Yushu2606** [comment]
> > > 感觉有点难做到，在`Explosion::explode`计算出需要破坏的方块并且存起来，之后也是在`Explosion::explode`里使用了这些数据，并且破坏了方块
> 
> > 
> 
> > 直接参考gametest的实现就行
> 
> 
> 
> 这样需要更改事件点位，直接使用bds内的事件系统，我怕一些使用了这个事件的插件会因为这个改动，而不能达到想要的操作。bds的这个内部事件是在`Explosion::explode`里面，所以会晚触发

gametest所有事件都分before和after，用before事件应该就没问题了吧？🤔

**Comment by quizhizhe** [comment]
应该没问题吧，大概测试过代码了，但是我担心会有性能上的影响，使用的是这个`BlockSource::postGameEvent`函数点位，BDS是通过这个函数里的GameEvent参数来提交不同的事件，所以会在别的事件也会触发，但前后没有很好的点位。。。。。要不存破坏方块数据还没有，或者已经在使用准备破坏方块了，要达到ScriptAPI的那种效果，需要改动这个存有方块的数据，至少在使用前修改

**Comment by quizhizhe** [comment]
突然想到个问题，使用这个点位，就无法拦截了，只能阻止方块破坏，不能阻止爆炸伤害

**Comment by Yushu2606** [comment]
最新版`ExplosionBeforeEvent`只有`cancel`和`setImpactedBlocks()`了
