### ISSUE TITLE
PluginTemplate改进：当检测到SDK版本与lib版本不同时，自动删除旧lib

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LiteLoader#1102]
RT
想办法在SDK中和LibraryBuilder生成的lib中，分别记录当前的版本号
然后当Plugin编译时，检查版本号是否匹配，如果不匹配则把SDK/lib/***.lib删掉，重新调LibraryBuilder

**Comment by RimuruChan** [comment]
@yqs112358 顺便一提，ll3已经不需要sdk仓库了

**Comment by yqs112358** [comment]
> @yqs112358 顺便一提，ll3已经不需要sdk仓库了

哦豁，那方便啊
新方案是什么来着
