### ISSUE TITLE
[Logger] logfile error

### ISSUE THREAD

**Issue by ShrBox** [LiteLDev/LiteLoader#111]
**Describe the bug**
When I defined `Logger logger("xxx")` in plugin, that plugin will redirect server output to its log file

**To Reproduce**
https://github.com/LiteLDev/LiteLoaderPlugins/blob/d1c1c69774579f683bda942009f478f2833fc70c/LLHelper/Helper.cpp#L9

**Expected behavior**

**Screenshots or log**
![image](https://user-images.githubusercontent.com/53301243/145815042-9db46bfc-0955-4197-8816-19ccb8c131b8.png)

**Environment (please complete the following information):**
 - OS: [Windows 11]
 - Version [2.0.1]

**Additional context**

**Comment by RimuruChan** [comment]
The function `setFile` is globally.
https://github.com/LiteLDev/LiteLoaderPlugins/blob/d1c1c69774579f683bda942009f478f2833fc70c/LLHelper/Helper.cpp#L49
