### ISSUE TITLE
Text in sign disappear when cancel "onDestroyBlock"

### ISSUE THREAD

**Issue by PLATONG34821** [LiteLDev/LiteLoader#1113]
### Exceptions module

Core

### Operating System

Windows 10

### LiteLoader version

2.11.0+

### BDS version

1.19.63.1

### What happened?

I write script to cancel when player try to break block and when I destroy sign. text inside the sign will disappear.

**Comment by PLATONG34821** [comment]
https://user-images.githubusercontent.com/121702673/222890471-406562e8-ff82-4c3f-a3db-641fe9c75d71.mp4

**Comment by ShrBox** [comment]
It's client's behavior, we can't solve it, but it is possible to send packet to let client show the text again.

**Comment by PLATONG34821** [comment]
That mean if player rejoined. text will show again right?

**Comment by ShrBox** [comment]
> That mean if player rejoined. text will show again right?

yeap
