### ISSUE TITLE
Event::ContainerChangeEvent bug

### ISSUE THREAD

**Issue by ABOTHET** [LiteLDev/LiteLoader#1119]
### Exceptions module

Core

### Operating System

Windows 10

### LiteLoader version

2.11.1

### BDS version

1.19.63.1

### What happened?

EVENT cannot put a link to the ender chest in the callback function.
I can't put anything in an ender chest, I can't remove items from there, but I can work with regular chests or barrels. However, if I get an instance of the ender chest via mPlayer, then everything works.

Event::ContainerChangeEvent::subscribe([](const Event::ContainerChangeEvent &ev) {

	logger.info(ev.mContainer->getTypeName()); // if it is a chest, then -> "CONTAINER"
	logger.info(ev.mContainer->getTypeName()); // if it is a ender_chest, then -> "EXCEPTION"

	logger.info(ev.mPlayer->getEnderChestContainer()->getTypeName()); // "CONTAINER"

	return true;
});

### Relevant log output

```raw
15:24:20 ERROR [LiteLoader] Uncaught SEH Exception Detected!
15:24:20 ERROR [LiteLoader] Error: Code [-1073741819] SEH_UNKNOW_ERROR
15:24:20 ERROR [LiteLoader] In Event (class Event::ContainerChangeEvent)
15:24:20 ERROR [LiteLoader] In Plugin <ShalkerEnder 0.1.0>
```

**Comment by yqs112358** [comment]
![image](https://user-images.githubusercontent.com/37969157/227755653-3b69f130-282e-491c-ad50-c3fbb799ae6c.png)

I have tested in LLSE 
`mc.listen("onContainerChange", function(player,container,slotNum,oldItem,newItem){log(slotNum)});`
and it works well. 

Can you explain "put a link to the ender chest in the callback function" more clearly?
