### ISSUE TITLE
Actor::isOnGround() always returns false.

### ISSUE THREAD

**Issue by Dasciam** [LiteLDev/LiteLoader#1120]
### Exceptions module

Core

### Operating System

Windows 11

### LiteLoader version

2.11.1

### BDS version

1.19.63

### What happened?

```Actor::isOnGround()``` always returns false.

### Steps to reproduce?

1. Make a plugin that checks the on ground state every second.
```cpp
Schedule::repeat(
    [ ]( void ) -> void{
        for( auto * player : Level::getAllPlayers( ) )
		std::cout << player->getRealName( ) << ": " << ( player->isOnGround( ) ? "true" : "false" ) << std::endl;
    }, 20ull
);
```
2. It won't take long for the result to show up.

**Comment by dreamguxiang** [comment]
fixed
