### ISSUE TITLE
Command对象 setEnum等方法 实际返回值与文档不符

### ISSUE THREAD

**Issue by lgc2333** [LiteLDev/LiteLoader#1121]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2022

### LiteLoader 版本

无关

### BDS 版本

无关

### 发生了什么?

https://github.com/LiteLDev/LiteLoaderBDS/blob/5d477bab0645385f513ae361ae6f662991f7a22f/ScriptEngine/src/api/CommandAPI.cpp#L265
https://docs.litebds.com/zh-Hans/#/LLSEPluginDevelopment/GameAPI/Command?id=%e6%96%b0%e5%a2%9e%e4%b8%80%e4%b8%aa%e6%8c%87%e4%bb%a4%e6%9e%9a%e4%b8%be%e9%80%89%e9%a1%b9
此处应返回 Boolean，但源码中实际返回 String

**Comment by lgc2333** [comment]
如果你们是刻意这样设计的话，那就是文档错误，需要修改文档

**Comment by lgc2333** [comment]
但其实我想让command对象的方法返回this，这样可以链式调用，会比较方便 (如果不行的话那当我在想桃吧

**Comment by harry-xi** [comment]
> 如果你们是刻意这样设计的话，那就是文档错误，需要修改文档

应该是文档有误，我印象里之前这里在文档里写的就是string

**Comment by yqs112358** [comment]
文档写错了，这个应该返回的是新的enum的标识符名字
文档已修复
