### ISSUE TITLE
Crash on Actor::getAllEffects()

### ISSUE THREAD

**Issue by KobeBryant114514** [LiteLDev/LiteLoader#1129]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.11.0

### BDS 版本

1.19.63

### 发生了什么?

MCAPI Actor::getAllEffects()无效且造成崩溃。
经过多次测试，崩溃均发生在Actor::getAllEffects()这个函数。

### 复现此问题的步骤

获取任意有效的实体指针（非空指针）
执行Actor::getAllEffects()函数。

服务器崩溃。

**Comment by dreamguxiang** [comment]
1.19.70未复现
