### ISSUE TITLE
LLSE Python 将插件源码目录加入模块搜索路径

### ISSUE THREAD

**Issue by lgc2333** [LiteLDev/LiteLoader#1136]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows 11

### LiteLoader 版本

https://github.com/LiteLDev/LiteLoaderBDS/actions/runs/4467975916

### BDS 版本

1.19.71.02

### 发生了什么?

插件import报错

下面这个报错猜测是py插件没有作为一个py包导入加载，不算太严重
![image](https://user-images.githubusercontent.com/59048777/226371426-81304a30-9eb6-4e53-a9bb-f0dee410fc4d.png)

而下面这个报错则有些严重了，无法导入文件同级目录下已经存在的py包
![image](https://user-images.githubusercontent.com/59048777/226371251-358d6294-5d6c-409b-87aa-277fd65b0f64.png)

测试了单文件也是如此
![image](https://user-images.githubusercontent.com/59048777/226371945-7016f0b7-fbd8-446e-9e46-675b46568946.png)

请接着往下看复现步骤

### 复现此问题的步骤

这里是 `src/plugins/python/testnb2` 目录的结构
![image](https://user-images.githubusercontent.com/59048777/226372377-399eaef8-db7f-46cf-98b1-24beefbdb61e.png)

下面我们把 `plugins/python/testnb2/__init__.py` 称作 `__init__.py`

（相对导入）
当在 `__init__.py` 里写上 `from . import const` (或者 `from .const import *`) 时，则会出现第一张图片样式的报错

（绝对导入）
当在 `__init__.py` 里写上 `import src` (或者 `from src import *`) 时，会出现第二张图片样式的报错（import包）
写上 `import const` (或者 `from const import *`) 时，会出现第三张图片的报错（import单文件）

**上面的文本可能陈述不够清晰，如果需要更多信息，请联系我**

**Comment by lgc2333** [comment]
还有一个建议，其实可以把llse的接口做成一个模块，然后
```py
from llpy import mc, ll, logger

mc.listen('onServerStarted', lambda : logger.info('Server Started!'))

ll.registerPlugin('test', 'test', [0, 1, 0], {})
```

**Comment by yqs112358** [comment]
上面说的两个问题，第一个是刻意为之。因为LLSE底层工作机制和包大相径庭，目前方案比导入包相比有极大的隔离优势和性能优势，因此不会修改
第二个问题稍后将修复

**Comment by yqs112358** [comment]
补全库还麻烦大佬们一起努力想办法了

**Comment by lgc2333** [comment]
> 上面说的两个问题，第一个是刻意为之。因为LLSE底层工作机制和包大相径庭，目前方案比导入包相比有极大的隔离优势和性能优势，因此不会修改 第二个问题稍后将修复

```py
import sys
sys.path.append("path")
```
这样可能应该就没问题了

**Comment by yqs112358** [comment]
对了，单文件插件我就不支持import了，只在多文件插件支持，尽量引导人都去用现代项目管理机制
另一方面单文件加载那里代码是通用的，要加特判也不优雅

**Comment by lgc2333** [comment]
> 对了，单文件插件我就不支持import了，只在多文件插件支持，尽量引导人都去用现代项目管理机制 另一方面单文件加载那里代码是通用的，要加特判也不优雅

单文件只要不影响内置模块import就行

**Comment by yqs112358** [comment]
![image](https://user-images.githubusercontent.com/37969157/226393427-2300aa7a-7950-4969-bb54-f57d44f63717.png)
源码路径import修好了，见最新actions

**Comment by lgc2333** [comment]
![image](https://user-images.githubusercontent.com/59048777/226427979-25444816-6edf-45c5-b8c1-c03996f0ab11.png)
奇怪了

**Comment by lgc2333** [comment]
我这边还是不行……
`print(sys.path)`发现这里用的是相对路径，可能需要绝对路径？
![image](https://user-images.githubusercontent.com/59048777/226430595-915a2eee-0bd1-424a-bdd5-c375c82ce909.png)

**Comment by lgc2333** [comment]
![image](https://user-images.githubusercontent.com/59048777/226430871-1b028582-5fd2-4794-9890-88a30a2a44df.png)
插件文件夹的结构

**Comment by yqs112358** [comment]
已修复
