### ISSUE TITLE
py引擎没有提供__file__等特殊变量

### ISSUE THREAD

**Issue by lgc2333** [LiteLDev/LiteLoader#1139]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows 11

### LiteLoader 版本

https://github.com/LiteLDev/LiteLoaderBDS/actions/runs/4470232939

### BDS 版本

1.19.71.02

### 发生了什么?

![image](https://user-images.githubusercontent.com/59048777/226435866-f315334e-4909-4e28-bafd-2a4aa73cc6eb.png)

### 复现此问题的步骤

![image](https://user-images.githubusercontent.com/59048777/226435959-c455955e-c240-44af-88f2-69430af8da40.png)

**Comment by yqs112358** [comment]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/37969157/226503865-a5f812ba-6a18-400e-85cc-85cc8f2817ff.png">
已修复
