### ISSUE TITLE
sendNetworkPacket函数在插件中无法实现

### ISSUE THREAD

**Issue by Milvona** [LiteLDev/LiteLoader#1142]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows 11

### LiteLoader 版本

LiteLoaderBDS 2.12.0-dev.0+e256e2c

### BDS 版本

 Version 1.19.71.02(ProtocolVersion 575)

### 发生了什么?

对照组A:
```cpp
     Event::PlayerChatEvent::subscribe([](const Event::PlayerChatEvent& ev) {
         auto pl = ev.mPlayer;
     SetDisplayObjectivePacket pkt =
         SetDisplayObjectivePacket("sidebar", "title", "name", "dummy", ObjectiveSortOrder((char)0));
     pl->sendNetworkPacket(pkt);
         return true;
         });
```
这是按照LL的sendSetDisplayObjectivePacket()直接构造的,无法显示出title。(这种构造方式在1.19.63可用)  
对照组B:
```cpp
     Event::PlayerChatEvent::subscribe([](const Event::PlayerChatEvent& ev) {
         auto pl = ev.mPlayer;
     pl->sendSetDisplayObjectivePacket("title", "name", (char)0);
         return true;
         });
```
这是使用了LIAPI，能够显示出title。  
类似构造PLayerListPacket等等插件无法使用pl->sendNetworkPacket()结构，但是可以使用LoopbackPacketSender.hpp构造  
`LoopbackPacketSender* pktSender = (LoopbackPacketSender*)Global<Level>->getPacketSender();`使用pktSender->send(pkt)则依旧能对原本的构造包进行全员发送。  
其他方面信息:  
1.即使玩家不能收到该数据包，客户端和服务端均没有相关信息提示。  
2.从打点判断以上两个测试插件都在事件监听时，完成了全部的功能。  
3.编译使用的SDK是在中午11:30进行git clone。  
4.使用了两个账号进入测试服务器都有这种情况。

### 复现此问题的步骤

由于之前发送PlayerListPacket的插件失效，对sendNetworkPacket函数进行反复对照讨论和分析

### 有关的日志/输出

```raw
无log输出，无崩溃及崩溃日志。
```

### 插件列表

```raw
测试监听PlayerChatEvent（上图测试插件）
```

**Comment by dreamguxiang** [comment]
等待新sdk，目前develop为1.19.70，测试后发现与bds1.19.71/72不兼容
