### ISSUE TITLE
Adapt block parameter in command

### ISSUE THREAD

**Issue by superx101** [LiteLDev/LiteLoader#1146]
### Is your feature request related to a problem? Please describe.

According to [new syntax](https://minecraft.fandom.com/wiki/Argument_types#Bedrock_Edition), "tileData" has been replaced by "blockStates"
e.g. `fill <from: x y z> <to: x y z> <tileName: Block> [blockStates: block states] [oldBlockHandling: FillMode]`

In version [2.12.0-beta.1](https://github.com/LiteLDev/LiteLoaderBDS/releases/tag/2.12.0-beta.1) ,there is a syntax error displayed as `wool>>[<<"color":"r` in my custom command `/test wool["color":"red"]`
Command format: `test <block: Block>`

### Describe the solution you'd like

Modify syntax checking of command or add a new parameter type

**Comment by OEOTYAN** [comment]
有这么几点，首先，1.19.70开始，BE也在逐渐把方块名称扁平化了，wool已经被移除了 现在 white_wool red_wool都是独立的了，.80的木头也会独立；其次，方块名称和方块状态是两个单独的参数，中间需要空格隔开，我们目前还没来及添加方块状态参数的API，之后会补上。

**Comment by superx101** [comment]
It's right, wool was indeed removed, this command (`setblock ~ ~ ~ wool["color":"red"]`) also can be run in original Minecraft (1.19.72). I gave a bad example, you can ignore it.
But, here is a [official example](https://minecraft.fandom.com/wiki/Commands/fill): `/fill ~-1 ~ ~ ~1 ~ ~ minecraft:prismarine_brick_stairs[facing=south,waterlogged=true]` , the two parameters can be connected without any space. After testing, this command can be run in the game (1.19.72), regardless of whether there is a space between the two parameters.

**Comment by OEOTYAN** [comment]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/58554322/226971044-d676d75d-08a8-4f52-ab0e-73a97006fa33.png">
我不是很能理解你是如何测得 

> minecraft:prismarine_brick_stairs[facing=south,waterlogged=true]

 这段在BE是合法的，这段很显然是JE的格式，首先BE的方块状态中没有 waterlogged ，JE的含水方块是特殊状态，而BE是一层单独的附加层，同时BE的命令格式是 ["<state1>":<value1>,"<state2>":<value2>,...] 需要双引号和冒号，而不是等于号。
<img width="839" alt="image" src="https://user-images.githubusercontent.com/58554322/226971883-9f1a01df-55ba-45d0-ab79-cf11094d146c.png">

**Comment by superx101** [comment]
Thank you for your correction. 
My bad, I made a mistake when pasting the command. You can try 
`setblock ~ ~2 ~ stone_slab["stone_slab_type":"quartz","top_slot_bit":true]` 
and
`setblock ~ ~2 ~ stone_slab ["stone_slab_type":"quartz","top_slot_bit":true]` 
from https://minecraft.fandom.com/wiki/Commands/setblock, both are legal.

**Comment by OEOTYAN** [comment]
> My bad, I made a mistake when pasting the command. You can try `setblock ~ ~2 ~ stone_slab["stone_slab_type":"quartz","top_slot_bit":true]` and `setblock ~ ~2 ~ stone_slab ["stone_slab_type":"quartz","top_slot_bit":true]` from https://minecraft.fandom.com/wiki/Commands/setblock, both are legal.

好的
