### ISSUE TITLE
CrashLogger优化

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LiteLoader#1147]
如图
![image](https://user-images.githubusercontent.com/37969157/226945756-a4485b12-966c-41d1-bfb1-1baa8e929b81.png)
第一行为真实函数信息
第二行 at File 改成合并进第一行一起输出
第三行 为跳转点，不是函数，如何判断并屏蔽此信息？

**Comment by yqs112358** [comment]
不过不是所有的日志都和上面的一样有问题，比如这个就是正常的
![-20ff794a40eec9b9.jpg](https://user-images.githubusercontent.com/37969157/228112121-64967158-5bd5-4a0e-9382-c243c6d09cb7.jpg)

**Comment by RimuruChan** [comment]
原 CrashLogger 宏展开不当导致文件日志中多了一行pc，已经在重写项目中修复。

https://github.com/LiteLDev/CrashLogger
