### ISSUE TITLE
LLSE `BinaryStream`对象缺少文档中的方法`writeCompountTag`

### ISSUE THREAD

**Issue by lgc2333** [LiteLDev/LiteLoader#1149]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows 11

### LiteLoader 版本

暂时无关

### BDS 版本

无关

### 发生了什么?

rt

**Comment by yqs112358** [comment]
绷，写的时候忘记注册了

**Comment by yqs112358** [comment]
已修复，请等待最新github actions构建完成
