### ISSUE TITLE
LLSE Permission对象方法与文档不符

### ISSUE THREAD

**Issue by lgc2333** [LiteLDev/LiteLoader#1153]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows 11

### LiteLoader 版本

暂时无关

### BDS 版本

无关

### 发生了什么?

![image](https://user-images.githubusercontent.com/59048777/227611660-c3dff1d6-3d73-4227-9aa3-a7ecfc4a8fe9.png)

源码中找不到文档中提到的`Permission.deleteRole()`
文档中找不到源码中写着的`Permission.deletePermission()`

**Comment by yqs112358** [comment]
已修复，请等待最新github actions构建完成
