### ISSUE TITLE
LLSE Python 操作 `Command` 对象出现 `SEH_Unknown_Error`

### ISSUE THREAD

**Issue by lgc2333** [LiteLDev/LiteLoader#1154]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows 11

### LiteLoader 版本

2.12.0

### BDS 版本

1.19.71.02

### 发生了什么?

![image](https://user-images.githubusercontent.com/59048777/227636708-866a38ab-6057-49d8-9405-a83aa6fd5f5f.png)

js 做同样操作 是正常的
![image](https://user-images.githubusercontent.com/59048777/227637177-178aeac7-203c-49ac-91f0-332e88c0ac32.png)

### 复现此问题的步骤

如上图

**Comment by lgc2333** [comment]
测试了几个其他`constructor`为`nullptr`的类都会出现这种问题
![image](https://user-images.githubusercontent.com/59048777/227643116-2af85007-fd03-4666-b086-19a26473fe1d.png)

而有`constructor`的`IntPos`则没有问题
![image](https://user-images.githubusercontent.com/59048777/227643326-2888e256-68c0-4c0d-9b3d-cb2b82e75b75.png)

**Comment by yqs112358** [comment]
已修复。等待新版本发布
