### ISSUE TITLE
LLSE Python & NodeJS 启动子进程时会启动成 LL

### ISSUE THREAD

**Issue by lgc2333** [LiteLDev/LiteLoader#1157]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows 11

### LiteLoader 版本

2.12.0

### BDS 版本

1.19.71.02

### 发生了什么?

![image](https://user-images.githubusercontent.com/59048777/227648454-cc84dd36-9e9f-4e1f-9ce8-c16483e8410f.png)

![image](https://user-images.githubusercontent.com/59048777/227652478-f838f49e-a467-42e0-9e5c-e1d69178f1d6.png)

**Comment by yqs112358** [comment]
这个问题应该也不太好处理。因为实际执行的主程序就是BDS，而非各自的解释器运行时。
Python还好歹携带了完整的embedding运行时环境（仅仅为了执行Pip）；而NodeJs甚至只有libnode.dll。这种情况下将主程序设置为解释器exe是不合适，甚至不可行的行为。

写这方面插件的时候需要改变一下思路：在插件代码中，不再是各自的主程序（node.exe / python.exe）作为启动环境，脚本引擎运行时是作为一个嵌入式引擎工作的。LLSE引擎和平时直接使用引擎执行源码文件有较大的架构上的区别。

因此如果需要分开执行额外的代码，有几种选择：
1. 充分使用setTimeout setInterval API，将插件按事件驱动模型来设计和开发。这是最优方案
2. 在NodeJs使用worker，在Python使用multiprocess调用嵌入的运行时环境单独执行脚本。此方案远不如方案1好用，因为单独的环境无法调用任何LL api。仅适合用于部分计算密集型需求。
3. 再携带一个独立的运行时环境，使用各自语言的multiprocess，或者LLSE的进程API启动进行调用。这是性能最差的方案，不过隔离性最好，对各种第三方包也有最佳的支持

按需使用

**Comment by lgc2333** [comment]
感谢解惑
