### ISSUE TITLE
LLSE中"onNpcCmd"报错

### ISSUE THREAD

**Issue by FBQingYi** [LiteLDev/LiteLoader#1158]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2019

### LiteLoader 版本

 2.12.0

### BDS 版本

1.19.72.01

### 发生了什么?

![V64I@3}YP@G9Z$24ZH%~F%X](https://user-images.githubusercontent.com/82281127/227665696-934b84ab-c709-4ed0-baac-401d9d5f2577.png)

### 复现此问题的步骤

mc.listen("onNpcCmd",(npc,pl,cmd)=>{})
然后让npc执行一个指令

**Comment by OEOTYAN** [comment]
https://github.com/LiteLDev/LiteLoaderBDS/actions/runs/4518083077 大概是修了

**Comment by yqs112358** [comment]
@FBQingYi 麻烦大佬可以下上面的github actions结果运行测试
