### ISSUE TITLE
Can not load Python Engine on Wine

### ISSUE THREAD

**Issue by sovieti9308** [LiteLDev/LiteLoader#1160]
### 异常模块

LiteLoader (本体)

### 操作系统

GNU/Linux with wine

### LiteLoader 版本

2.12.0

### BDS 版本

1.19.72

### 发生了什么?

Fatal Python error: _Py_HashRandomization_Init: failed to get random numbers to
initialize Python
Python runtime state: preinitialized

### 复现此问题的步骤

开服时出现，卡住不动，也不能正常关闭服务器，只能强制停止

![屏幕截图 2023-03-25 160249](https://user-images.githubusercontent.com/114805547/227705389-915e9f7c-18a2-4474-afcc-5659b5991e9c.jpg)

### 有关的日志/输出

```raw
Fatal Python error: _Py_HashRandomization_Init: failed to get random numbers to
initialize Python
Python runtime state: preinitialized
```

### 插件列表

```raw
无
```

**Comment by yqs112358** [comment]
CPython的问题。绷，CPython写的是真烂
等会看看怎么修

**Comment by ShrBox** [comment]
lololololololol

**Comment by WangYneos** [comment]
@ShrBox test message to check if github alive

**Comment by yqs112358** [comment]
<img width="787" alt="image" src="https://user-images.githubusercontent.com/37969157/228595399-6ac860dc-bc5f-4c7a-83f7-bf721242d8df.png">
我这里使用Ubuntu 20.04.4 LTS安装Wine8.0工作完全正常，无法复现问题。
你使用的服务商的wine版本是否过旧？可以尝试自行安装wine8

**Comment by yqs112358** [comment]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/37969157/228597959-68184dd8-6d76-455d-830c-58566e8f42bd.png">
刚刚忘记开LLSE了，不过开了之后也是一切正常

**Comment by yqs112358** [comment]
![image](https://user-images.githubusercontent.com/37969157/228598052-f7963976-9e9a-483b-a758-2d2724ea4e43.png)
游戏正常

**Comment by yqs112358** [comment]
可能是服务商系统内置的wine过旧。你可以安装Wine8来解决此问题
具体详见https://wiki.winehq.org/Download_zhcn
