### ISSUE TITLE
LLSE NBT.parseBinaryNbt()函数报错

### ISSUE THREAD

**Issue by Hurry1027** [LiteLDev/LiteLoader#1163]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows 10

### LiteLoader 版本

2.12.0

### BDS 版本

1.19.72

### 发生了什么?

我做的一个生物搬运的quickjs插件报错
NBT.parseBinaryNbt()函数解析保存实体的二进制NBT数据时报错，在上个版本(1.19.63)测试不会发生此问题。
jsdebug日志见附图。

**Comment by Hurry1027** [comment]
![parseBinaryNbt](https://user-images.githubusercontent.com/81138587/227722274-9de86dd5-0ff6-4ed0-a1ca-ec5e1f52a138.jpg)

这是一头牛的数据，nbt数据转为二进制再转码base64
[t.txt](https://github.com/LiteLDev/LiteLoaderBDS/files/11069086/t.txt)

**Comment by OEOTYAN** [comment]
确有其事

**Comment by KawaiiNahida** [comment]
已修复，麻烦测试一下

**Comment by yqs112358** [comment]
![image](https://user-images.githubusercontent.com/37969157/227755537-f0ae4df1-d589-4642-93af-09fd36616509.png)
简单测了一下无问题了
