### ISSUE TITLE
使用MCSManager开服出现问题

### ISSUE THREAD

**Issue by FBQingYi** [LiteLDev/LiteLoader#1164]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows Server 2019

### LiteLoader 版本

 2.12.0

### BDS 版本

1.19.72.01

### 发生了什么?

使用MCSManager开服后台输入指令会乱码
我输入的help，以下是输出
22:43:18 ERROR [Server] Unknown command: 敨灬. Please check that the command exists and that you have permission to use it.
并且出错后再次输入会没有响应。
经过测试原版是正常的，加载ll后会出现这个问题。

### 复现此问题的步骤

1，使用MCSManager开服并加载上ll
2，后台随便输入指令
![M$%CZ@88D3QPD` SK0(XF`N](https://user-images.githubusercontent.com/82281127/227724646-736e463b-1130-480d-ba8c-a42dc8373b3a.png)

### 有关的日志/输出

```raw
22:43:18 ERROR [Server] Unknown command: 敨灬. Please check that the command exists and that you have permission to use it.
```

**Comment by ShrBox** [comment]
请尝试在MCSM设置中将控制台输入编码更改为utf-8

**Comment by FBQingYi** [comment]
> 请尝试在MCSM设置中将控制台输入编码更改为utf-8
已经是utf-8，以前一直在用，更新后出现的。
![U0X`8DI7BNSI3TY1V$INICY](https://user-images.githubusercontent.com/82281127/227724796-4c30fca5-959f-42ab-a120-59ed1f7bd6f1.png)

**Comment by ShrBox** [comment]
检查`./plugins/LiteLoader/LiteLoader.json`中`ForceUtf8Input`是否启用，若未启用则请将其启用，若已启用请尝试禁用

**Comment by FBQingYi** [comment]
> 检查中是否启用，若未启用则请将其启用，若已启用请尝试禁用`./plugins/LiteLoader/LiteLoader.json``ForceUtf8Input`
默认是false，改成true后正常

**Comment by ShrBox** [comment]
Fixed in ef432bf02504c950c7dd7ad35bb8cc173ebbd077
