### ISSUE TITLE
Enum class StructureFeatureType is Incomplete

### ISSUE THREAD

**Issue by KobeBryant114514** [LiteLDev/LiteLoader#1174]
### 您的建议是否与现存的某个问题相关?请描述问题?

enum class StructureFeatureType
并没有给出具体值
只知道存在enum class StructureFeatureType，但是想进一步使用没有具体值。

### 您认为还缺少什么?如何解决您的问题?

将enum class StructureFeatureType下的具体值还原

**Comment by KawaiiNahida** [comment]
added in commit 398268ca933d1e58d2cea0aaba35a8651a81ad03

**Comment by KawaiiNahida** [comment]
此类建议数驱或命令（这里是/locate）入手

**Comment by KobeBryant114514** [comment]
Thanks
