### ISSUE TITLE
struct ActorLink is not defined

### ISSUE THREAD

**Issue by KobeBryant114514** [LiteLDev/LiteLoader#1176]
### 您的建议是否与现存的某个问题相关?请描述问题?

struct ActorLink 并没有被任何头文件定义
想使用此API，但是无法正常使用。

### 您认为还缺少什么?如何解决您的问题?

增加对 struct ActorLink 的定义

**Comment by KawaiiNahida** [comment]
struct ActorLink
{
  char type;
  ActorUniqueID first;
  ActorUniqueID second;
  bool unk;
  bool unk;
};
