### ISSUE TITLE
Enum class VanillaBiomeTypes is not defined

### ISSUE THREAD

**Issue by KobeBryant114514** [LiteLDev/LiteLoader#1178]
### 您的建议是否与现存的某个问题相关?请描述问题?

Enum class VanillaBiomeTypes没有完整的列出具体值。

### 您认为还缺少什么?如何解决您的问题?

补充 enum class VanillaBiomeTypes 的具体值

**Comment by KawaiiNahida** [comment]
https://github.com/LiteLDev/LiteLoaderBDS/commit/53886bfb621969f1623fcc2984983d9c3082138a
