### ISSUE TITLE
Python engine can't run on Wine

### ISSUE THREAD

**Issue by jeff87218** [LiteLDev/LiteLoader#1180]
### 异常模块

LiteLoader (本体)

### 操作系统

GNU/Linux with docker

### LiteLoader 版本

2.12.3

### BDS 版本

1.19.73.02

### 发生了什么?

只要有放任何的插件LiteLoader就會崩潰
![1680460487988](https://user-images.githubusercontent.com/29706585/229372507-eb78b4c4-763c-44e7-994e-b7fd8ff5e8a5.jpg)
把插件全刪掉了之後，手動加載插件一樣會報錯
![1680460705096](https://user-images.githubusercontent.com/29706585/229372569-0a0a08da-dec3-42f6-b9d6-385b442f4f98.jpg)

註:使用的是LiteLoader官方鏡像

**Comment by Yushu2606** [comment]
#1160

**Comment by yqs112358** [comment]
@ShrBox 🍗酱康康

**Comment by yqs112358** [comment]
见 #1160
我这里加载插件工作正常

**Comment by yqs112358** [comment]
我有空处理一下。是CPython的bug

**Comment by ShrBox** [comment]
update: 经测试在Wine 8.0 on Linux Mint 21.1没有此问题

**Comment by ShrBox** [comment]
已找到问题，已在最新的镜像中修复
