### ISSUE TITLE
Enum class GameRule::Type is not defined

### ISSUE THREAD

**Issue by KobeBryant114514** [LiteLDev/LiteLoader#1182]
### 您的建议是否与现存的某个问题相关?请描述问题?

enum class GameRule::Type 未定义

### 您认为还缺少什么?如何解决您的问题?

新增对enum class GameRule::Type的定义

**Comment by dreamguxiang** [comment]
@Tsubasa6848 你知道枚举值的话直接pr吧，不然可能得晚上了

**Comment by KawaiiNahida** [comment]
https://github.com/LiteLDev/LiteLoaderBDS/commit/9e9ae3cc257f117475bc7237f6ace8b27e032b86
