### ISSUE TITLE
Player interact on entity event

### ISSUE THREAD

**Issue by HeliosPe** [LiteLDev/LiteLoader#1190]
### Is your feature request related to a problem? Please describe.

In LLSE api, there is only onUseItemOn event which has only parameters relative to blocks. Meanwhile for entities there is only hit entity event i.e. LMB. 

### Describe the solution you'd like

Please add a RMB interact event on entities for LLSE. As a separate event, or as a parameter "entity" for onUseItemOn.

**Comment by OEOTYAN** [comment]
You can use onUseItem with getEntityFromViewVector

**Comment by HeliosPe** [comment]
onUseItem with getEntityFromViewVector did not work. So I do not agree that the issue should be closed.
