### ISSUE TITLE
如何获取掉落物是从哪个实体掉落的?

### ISSUE THREAD

**Issue by smr1987** [LiteLDev/LiteLoader#1192]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows 11

### LiteLoader 版本

1.19.73

### BDS 版本

1.19.73.02

### 发生了什么?

想实现堆肥箱掉落泥土，思路是玩家拾取的时候，判断是堆肥箱掉落的骨粉，然后删除骨粉，给玩家物品栏或者背包添加一个泥土。

**Comment by ShrBox** [comment]
issue不是论坛，如果你想要询问关于插件开发的问题请前往[官方论坛](https://www.litebds.com/)、我们的discord服务器或telegram群组

**Comment by smr1987** [comment]
> issue不是论坛，如果你想要询问关于插件开发的问题请前往[官方论坛](https://www.litebds.com/)、我们的discord服务器或telegram群组

官方论坛激活邮件 邮箱一直收不到 发不了帖子

**Comment by ShrBox** [comment]
> > issue不是论坛，如果你想要询问关于插件开发的问题请前往[官方论坛](https://www.litebds.com/)、我们的discord服务器或telegram群组
> 
> 官方论坛激活邮件 邮箱一直收不到 发不了帖子

已修复
