### ISSUE TITLE
真命令数据类型更新

### ISSUE THREAD

**Issue by timiya233** [LiteLDev/LiteLoader#1193]
### 您认为还缺少什么?如何解决您的问题?

mc在1.19.70移除了titleData,更新详情:
命令格式
/clone、/execute、/fill、/setblock和/testforblock
移除了数据参数（tileData: int、data: int或dataValue: int）。
例如：/setblock ~ ~ ~ minecraft:wool 1现在需要改写为/setblock ~ ~ ~ minecraft:wool ["color":"orange"]。
这里的第五个命令参数可能是一个新的命令参数类型？
所以我请求加入这个类型

**Comment by superx101** [comment]
#1146

**Comment by timiya233** [comment]
抱歉，没看见
