### ISSUE TITLE
添加死亡消息事件

### ISSUE THREAD

**Issue by FtyLollipop** [LiteLDev/LiteLoader#1195]
### 您的建议是否与现存的某个问题相关?请描述问题?

目前的onMobDie事件所能提供的信息过少，不能精确判断玩家或生物的死亡原因等，无法与游戏内广播的死亡消息关联。

### 您认为还缺少什么?如何解决您的问题?

希望添加新的死亡消息事件，可以提供基岩版内未翻译的原始死亡消息（如"death.attack.generic"），翻译时用到的参数字符串(一个包含死者名字，击杀者名字和击杀物品名称的数组)，以及死者实体对象和击杀者实体对象，如有其他可提供的相关信息也可一并提供。

**Comment by KawaiiNahida** [comment]
ev.cause => enum class ActorDamageCause 即为原因
souce和mob分别为造成伤害的Entity和被伤害的Mob
cpp中ActorDamageCause包含原因及造成伤害的实体

击杀不一定掉落物品，请自行监听drop事件或者在物品掉落时遍历背包获取信息

**Comment by KobeBryant114514** [comment]
> ev.cause => enum class ActorDamageCause 即为原因 souce和mob分别为造成伤害的Entity和被伤害的Mob cpp中ActorDamageCause包含原因及造成伤害的实体
> 
> 击杀不一定掉落物品，请自行监听drop事件或者在物品掉落时遍历背包获取信息

原始死亡信息发送是一个独立的东西
struct std::pair<std::string, std::vector<std::string>>

这个可以被单独提出来，稍后PR

自行判断得不到原始死亡信息，他这里要的是原始信息，也就是死亡时那条死亡信息（只有玩家和驯服生物才有）
他要的不是ActorDamageCause里面的原因，而是那条死亡信息

**Comment by KawaiiNahida** [comment]
那条死亡消息是客户端翻译的(((  我记得bds有个接口可以DamageSource转翻译key `ActorDamageSource::lookupCauseName(ev.mDamageSource->getCause());`

**Comment by KobeBryant114514** [comment]
> 那条死亡消息是客户端翻译的((( 我记得bds有个接口可以DamageSource转翻译key `ActorDamageSource::lookupCauseName(ev.mDamageSource->getCause());`

我知道是客户端翻译的，他之前和我私聊过，要的是原始字符串

**Comment by KobeBryant114514** [comment]
> 那条死亡消息是客户端翻译的((( 我记得bds有个接口可以DamageSource转翻译key `ActorDamageSource::lookupCauseName(ev.mDamageSource->getCause());`

要强行翻译那条信息的话，可以用BDS资源包的I18n::get()
不过这已经是后续处理的问题了，事件底层不应该提供翻译
