### ISSUE TITLE
Add RaidMobSpawn Event

### ISSUE THREAD

**Issue by QimleyGero** [LiteLDev/LiteLoader#1198]
### 您的建议是否与现存的某个问题相关?请描述问题?

增加监听API-袭击事件生物生成

### 您认为还缺少什么?如何解决您的问题?

我想要一个新的监听事件——袭击事件。
目前已有"onMobTrySpawn"和"onMobTrySpawned"两个监听生物生成的API，但是它们只能监听自然生成的生物。袭击事件的生物生成无法被检测。
增加袭击事件的检测有利于生电玩家探索MCBE各版本的袭击机制，并据此设计高效的机械（例如绿宝石机）。
谢谢！

**Comment by quizhizhe** [comment]
是添加到LLSE吗？
是否是使用js插件？

**Comment by QimleyGero** [comment]
是的

**Comment by QimleyGero** [comment]
袭击事件监听能包含“尝试生成”和“完成生成”两个事件吗？

**Comment by quizhizhe** [comment]
> 袭击事件监听能包含“尝试生成”和“完成生成”两个事件吗？

我想说不能，懒。
