### ISSUE TITLE
enum class ContainerType is not defined

### ISSUE THREAD

**Issue by KobeBryant114514** [LiteLDev/LiteLoader#1199]
### 您的建议是否与现存的某个问题相关?请描述问题?

enum class ContainerType未定义枚举项

### 您认为还缺少什么?如何解决您的问题?

新增enum class ContainerType的枚举项

**Comment by KobeBryant114514** [comment]
还有 struct ItemStackRequestSlotInfo 的定义、struct GameRuleId 的定义
以及 enum class ItemStackNetResult 的枚举项

**Comment by KawaiiNahida** [comment]
enum class ContainerType : int8_t {
  None = 247,
  Inventory = 255,
  Container = 0,
  Workbench = 1,
  Furnace = 2,
  Enchantment = 3,
  BrewingStand = 4,
  Anvil = 5,
  Dispenser = 6,
  Dropper = 7,
  Hopper = 8,
  Cauldron = 9,
  MinecartChest = 10,
  MinecartHopper = 11,
  Horse = 12,
  Beacon = 13,
  StructureEditor = 14,
  Trade = 15,
  CommandBlock = 16,
  Jukebox = 17,
  Armor = 18,
  Hand = 19,
  CompoundCreator = 20,
  ElementConstructor = 21,
  MaterialReducer = 22,
  LabTable = 23,
  Loom = 24,
  Lectern = 25,
  Grindstone = 26,
  BlastFurnace = 27,
  Smoker = 28,
  Stonecutter = 29,
  Cartography = 30,
  __unk = 31,
  JigsawEditor = 32,
  SmithingTable = 33,
  BoatChest = 34,
};

**Comment by KawaiiNahida** [comment]
struct GameRuleId{int val}

**Comment by KawaiiNahida** [comment]
struct ItemStackRequestSlotInfo{
  ContainerEnumName mId;
  uint8_t mSlot;
  ItemStackNetIdVariant mType;
};
