### ISSUE TITLE
Use another name for decorator in BaseLib.py

### ISSUE THREAD

**Issue by callstackexceed** [LiteLDev/LiteLoader#1200]
### Is your feature request related to a problem? Please describe.

Currently, a decorator is named `@listener` in BaseLib.py, which is strange,
because decorator in Python is commonly named as a verb.

### Describe the solution you'd like

I suggest use `@handle` instead of `@listener`.
Since the name is just in develop branch and haven't been released,
I think it is possible to change name now.

**Comment by yqs112358** [comment]
我个人感觉这个不算什么大问题。
麻烦 @lgc2333 大佬看看捏

**Comment by lgc2333** [comment]
approve
