### ISSUE TITLE
LLSE新增玩家收到消息事件

### ISSUE THREAD

**Issue by FBQingYi** [LiteLDev/LiteLoader#1208]
### 您的建议是否与现存的某个问题相关?请描述问题?

目前无法拦截系统发出的提示消息，导致玩家体验感不是很好，希望新增一个api用于处理这个情况。

### 您认为还缺少什么?如何解决您的问题?

希望新增一个api用于拦截玩家收到的所有消息
比如：其他玩家死亡，上下线等事件，也包括聊天消息和指令发送的消息.

**Comment by Milvona** [comment]
去hook ?handle@ServerNetworkHandler@@UEAAXAEBVNetworkIdentifier@@AEBVTextPacket@@@Z 偏移88

**Comment by KawaiiNahida** [comment]
此类事件更接近数据包处理，请直接监听数据包
