### ISSUE TITLE
增加书与笔/告示牌编辑完成事件

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#1211]
### 您的建议是否与现存的某个问题相关?请描述问题?

缺少书与笔/告示牌编辑完成事件

### 您认为还缺少什么?如何解决您的问题?

增加书与笔/告示牌编辑完成事件

**Comment by KawaiiNahida** [comment]
非大量使用的事件建议自行hook

**Comment by Yushu2606** [comment]
need to close this as not planned
