### ISSUE TITLE
请求帮助构析PlayerSkinPacket/SerializedSkin/SkinData

### ISSUE THREAD

**Issue by Milvona** [LiteLDev/LiteLoader#1217]
### 您的建议是否与现存的某个问题相关?请描述问题?

起始:尝试抄PMMP的协议库对PlayerSkinPacket进行头文件补充，
涉及PlayerSkinPacket.hpp,SerializedSkin.hpp,SkinData.hpp
```
class PlayerSkinPacket : public Packet {
mce::UUID mUUID;
    std::string mNewSkinName, mOldSkinName;
    SkinData mSkinData;
...
```
查询ida对SkinData结构体尝试补完
```
    int mVariant;
    bool mHasVariant;
    int mMarkVariant;
    bool mHasMarkVariant;
```
hookPlayerSkinPacket相关，
能够在控制台log出以上补完参数，
但之后尝试构造PlayerSkinPacket的MCAPI造成崩服。

注意到mOldSkinName并不输出值
将其注释掉，之后仍然能够输出以上补完参数，但依旧会崩服。

猜测可能还需要char filler[?]进行补完，
之后将SerializedSkin转化为std::string进行log输出，
发现SerializedSkin可能包含PlayerSkinPacket的UUID部分和std::string内容。

但是仍然有很多不确定之处，能做到读，但是做不到修改，和包构造。
请求有经验的大佬指出一下补全方法。

### 您认为还缺少什么?如何解决您的问题?

请求帮助补充类类型PlayerSkinPacket，SerializedSkin
结构体类型SkinData

**Comment by quizhizhe** [comment]
崩不一定是补全的结构不对的原因，能给出崩的log文件最好

**Comment by Milvona** [comment]
[Crashed!]
-- Unhandled Exception in -> ucrtbase.dll
-- Exception Code: 0xC0000409
-- Minidump generated in Directory ./logs/Crash

[StackTrace] Function invoke_watson at 0x7FFA00A0DF10  [ucrtbase.dll<6.2.22621.608>]
[StackTrace] Function invalid_parameter_noinfo_noreturn at 0x7FFA00A0DEE0  [ucrtbase.dll<6.2.22621.608>]
[StackTrace] Function std::_Hash<std::_Umap_traits<BlockPos,PathfinderNode,std::_Uhash_compare<BlockPos,std::hash<BlockPos>,std::equal_to<BlockPos> >,std::allocator<std::pair<BlockPos const ,PathfinderNode> >,0> >::~_Hash<std::_Umap_traits<BlockPos,PathfinderNode,std::_Uhash_compare<BlockPos,std::hash<BlockPos>,std::equal_to<BlockPos> >,std::allocator<std::pair<BlockPos const ,PathfinderNode> >,0> > at 0x7FF61272CA30  [bedrock_server_mod.exe<1.19.73.02>]
[StackTrace] Function SerializedSkin::~SerializedSkin at 0x7FF61272F0E0  [bedrock_server_mod.exe<1.19.73.02>]
[StackTrace] Function std::_Func_impl_no_alloc<`PluginInit'::`2'::<lambda_1>,bool,Event::PlayerChatEvent>::_Do_call at 0x7FF995DD50B0  [plugin.dll]
-- At File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\functional : Line 833

**Comment by Milvona** [comment]
Event::PlayerChatEvent::subscribe([](const Event::PlayerChatEvent& ev) {
         auto pl = ev.mPlayer;
         auto pkt = PlayerSkinPacket();//?
         return true;
         });
