### ISSUE TITLE
LLSE`item.setAux()`失效

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#1218]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.12.4

### BDS 版本

1.19.73.02

### 发生了什么?

`setAux`函数失效

### 复现此问题的步骤

![图片](https://user-images.githubusercontent.com/100036558/234272990-278a812d-7a5d-436e-a1b4-63581909c548.png)
（log / 1应是云杉原木）

Close https://github.com/StarsDream00/LiteLoaderScriptPlugins/issues/3

**Comment by quizhizhe** [comment]
设置其他数字也无效吗？，因为1是不显示数字的，我检查了LL和LLSE，看起来是没有问题的

**Comment by wcdfilll** [comment]
need reference from this plugin, I'm still using the author's shop, because this plugin is attached to my server =))
Link: https://www.minebbs.com/resources/ashop-llmoney.3582/

**Comment by StarsDream00** [comment]
> need reference from this plugin, I'm still using the author's shop, because this plugin is attached to my server =))
> Link: https://www.minebbs.com/resources/ashop-llmoney.3582/

this plugin may not be open source

**Comment by wcdfilll** [comment]
> > need reference from this plugin, I'm still using the author's shop, because this plugin is attached to my server =))
> > Link: https://www.minebbs.com/resources/ashop-llmoney.3582/
> 
> this plugin may not be open source
[Ashop.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/11356782/Ashop.zip)

**Comment by KobeBryant114514** [comment]
1.19.81中不是已将log拆分为对应的ID了吗

**Comment by Yushu2606** [comment]
> 1.19.81中不是已将log拆分为对应的ID了吗

问题版本是1.19.73
以及不只log需要用数据值

**Comment by OEOTYAN** [comment]
方块物品实际不由 Aux掌控，这是mojang代码问题，请从NBT构造
