### ISSUE TITLE
增加“玩家吸取经验”事件

### ISSUE THREAD

**Issue by FtyLollipop** [LiteLDev/LiteLoader#1222]
### 您的建议是否与现存的某个问题相关?请描述问题?

当前玩家吸取的经验若被经验修补附魔使用，则无法触发获得经验事件

### 您认为还缺少什么?如何解决您的问题?

增加一个“玩家吸取经验”事件，以弥补经验修补造成的偏差

**Comment by KobeBryant114514** [comment]
玩家获得经验的事件是玩家经验条增加才会触发。

但是玩家接触到经验球的时候，如果经验球被经验修补吃了玩家本来就不会获得经验。

**Comment by FtyLollipop** [comment]
那是否可以增加一个触发经验修补的事件呢
