### ISSUE TITLE
LLSE中.hurt()增加实体源

### ISSUE THREAD

**Issue by FBQingYi** [LiteLDev/LiteLoader#1224]
### 您认为还缺少什么?如何解决您的问题?

pl.hurt()和entity.hurt()中加入实体源，以便定位伤害来源。

**Comment by KobeBryant114514** [comment]
目前player.hurt()和entity.hurt()均无法设置该伤害来源于哪一个实体。
而MC原版命令/damage可以实现这一功能。

实体死亡时伤害来源会直接决定战利品表使用等信息，在强化武器等插件中，如果附加伤害不能设置伤害来源，会导致系统认定生物不是被玩家杀死，会影响战利品。
而如果使用/damage命令实现会导致插件性能大打折扣。
