### ISSUE TITLE
LLSE中增加为实体设置buff的api

### ISSUE THREAD

**Issue by FBQingYi** [LiteLDev/LiteLoader#1225]
### 您认为还缺少什么?如何解决您的问题?

就像目前给玩家对象设置buff一样，为实体对象添加上那三个api
en.addEffect()
en.removeEffect()
en.getAllEffects()

**Comment by quizhizhe** [comment]
其实可以使用指令（mc.runcmdEx）做到一样的效果，我的意见是，能原版实现一样效果的，优先使用原版功能
