### ISSUE TITLE
`useItemOn`内部实例化`ItemInstance`空指针

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#1227]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.13.0 Actions#3337 371dd0c

### BDS 版本

1.19.81.01

### 发生了什么?

触发UseItemOnEvent时崩溃
会导致BDS的`ItemStackBase`在赋值时空指针

### 复现此问题的步骤

触发该事件

### 有关的日志/输出
[trace_2023-04-29_14-51-27.log](https://github.com/LiteLDev/LiteLoaderBDS/files/11358612/trace_2023-04-29_14-51-27.log)
[minidump_2023-04-29_14-51-27.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/11358613/minidump_2023-04-29_14-51-27.zip)

**Comment by Yushu2606** [comment]
可以考虑给issue加一个prerelease/indevelopment的tag

**Comment by dreamguxiang** [comment]
未适配完成，等1.19.80分支合并进develop

**Comment by StarsDream00** [comment]
尝试修复后崩溃变成了这个
[trace_2023-04-30_18-40-56.log](https://github.com/LiteLDev/LiteLoaderBDS/files/11361114/trace_2023-04-30_18-40-56.log)
[minidump_2023-04-30_18-40-56.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/11361116/minidump_2023-04-30_18-40-56.zip)
```cpp
TInstanceHook(ItemInstance&, "??4ItemStackBase@@IEAAAEAV0@AEBV0@@Z", ItemInstance, class ItemInstance const& a2) {
    if (&a2 == nullptr)
        return *this;
    return original(this, a2);
}
```

**Comment by StarsDream00** [comment]
> 未适配完成，等1.19.80分支合并进develop

合并了（
