### ISSUE TITLE
应在完成解压并执行成功npm命令后就移除.llpiugin包

### ISSUE THREAD

**Issue by harry-xi** [LiteLDev/LiteLoader#1231]
### 您的建议是否与现存的某个问题相关?请描述问题?

即便插件在正确完成安装步骤（完成解压并执行成功npm命令）后未正确运行，插件包仍应被删除，因为插件已经被正确安放到指定目录了。

### 您认为还缺少什么?如何解决您的问题?

如题

**Comment by lgc2333** [comment]
建议上调优先级

**Comment by OEOTYAN** [comment]
哈哈 好像ll3修了，那close了
