### ISSUE TITLE
增加喂动物事件

### ISSUE THREAD

**Issue by FtyLollipop** [LiteLDev/LiteLoader#1242]
### 您认为还缺少什么?如何解决您的问题?

增加一个喂动物事件，参数为：玩家，喂食的实体，喂食的物品

**Comment by OEOTYAN** [comment]
不加

**Comment by FtyLollipop** [comment]
> 不加

我的评价是：斜门

**Comment by OEOTYAN** [comment]
> 

ll3会新增用户自定义事件系统，等其他人以插件形式发布事件吧

**Comment by FtyLollipop** [comment]
> > 
> 
> ll3会新增用户自定义事件系统，等其他人以插件形式发布事件吧

那原有的事件是否也会相应的删除掉一大部分，并以插件的形式独立发布呢

**Comment by OEOTYAN** [comment]
> > > 
> 
> > 
> 
> > ll3会新增用户自定义事件系统，等其他人以插件形式发布事件吧
> 
> 
> 
> 那原有的事件是否也会相应的删除掉一大部分，并以插件的形式独立发布呢

是的，现有的很多事件都是某些人PR上来的，但人家PR完就跑了，丢给我们维护，越丢越多，很多事件到最后根本修不了，这是无法接受的。
