### ISSUE TITLE
注册指令失败

### ISSUE THREAD

**Issue by ye111566** [LiteLDev/LiteLoader#1243]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.13.0-dev.0+adbcc9e

### BDS 版本

1.19.81

### 发生了什么?

启动时候报错：11:32:57 ERROR [PreLoader] Could not find function in memory: ?id@?1???$type_id@VCommandRegistry@@VCommandItem@@@@YA?AV?$typeid_t@VCommandRegistry@@@@XZ@4V1@A
11:32:57 ERROR [PreLoader] Plugin: LiteLoader.dll
11:32:57 ERROR [LiteLoader] Uncaught SEH Exception Detected!
11:32:57 ERROR [LiteLoader] Error: Code [-1073741819] SEH_UNKNOW_ERROR
11:32:57 ERROR [LiteLoader] In Function (DynamicCommand::_setup - clearbag)
11:32:57 ERROR [LiteLoader] In Plugin <ScriptEngine-QuickJs>
11:32:57 WARN [LiteLoader] Registering command "" failed

### 复现此问题的步骤

开始启动
启动过程的全部文本：
11:32:50 INFO [PreLoader] Loading symbols from pdb...
11:32:51 INFO [PreLoader] Fast Dlsym Loaded <507863>
11:32:51 INFO [PreLoader] LiteLoader.dll Injected.                                                                                            11:32:52 INFO [LiteLoader] 正在解包LiteLoaderBDS运行时资源，请耐心等待...                                                                     11:32:52 INFO [LiteLoader] 解包完毕。                                                                                                                                                               

          _     _ _       _                    _
         | |   (_) |_ ___| |    ___   __ _  __| | ___ _ __
         | |   | | __/ _ \ |   / _ \ / _` |/ _` |/ _ \ '__|
         | |___| | ||  __/ |__| (_) | (_| | (_| |  __/ |
         |_____|_|\__\___|_____\___/ \__,_|\__,_|\___|_|

       --------   Light-Weight BDS Plugin Loader   ----------

    
11:32:52 INFO [LiteLoader] 加载原生插件...
11:32:52 INFO [LiteLoader] 原生插件 <MovingLight.dll> 已加载
11:32:52 WARN [LiteLoader] NodeJs运行库文件夹未找到，已自动创建
11:32:52 INFO [LiteLoader] * Js 脚本引擎已加载
11:32:52 INFO [LiteLoader] * Lua 脚本引擎已加载
11:32:52 INFO [LiteLoader] * NodeJs 脚本引擎已加载
11:32:52 INFO [LiteLoader] * Python 脚本引擎已加载
11:32:52 INFO [LiteLoader] ScriptEngine initializing...
11:32:52 WARN [EconomicSystem] 未找到LLMoney.dll，脚本引擎经济系统将无法工作
11:32:52 INFO [LiteLoader] 依赖项 BaseLib.js 已加载。
11:32:52 INFO [LiteLoader] 加载 Js 插件...
11:32:52 INFO [LiteLoader] Js 插件 <Advertising_1_2> 已加载。
11:32:52 INFO [LiteLoader] Js 插件 <Bazaar> 已加载。
11:32:52 INFO [CMENU] 加载完成！版本：0.2.5
11:32:52 INFO [CMENU] 插件作者: 提米吖
11:32:52 INFO [LiteLoader] Js 插件 <CMENU.js> 已加载。
11:32:52 INFO [LiteLoader] Js 插件 <CustomCmd> 已加载。
11:32:52 INFO [Fly] Fly加载成功
11:32:52 INFO [LiteLoader] Js 插件 <Fly> 已加载。
11:32:52 INFO [LiteLoader] Js 插件 <HelloAndGoodbyePlayer> 已加载。
11:32:52 INFO [LiteLoader] Js 插件 <jf> 已加载。
11:32:52 INFO [LiteLoader] Js 插件 <LF_Music> 已加载。
11:32:52 INFO [OPTools] Loading...
                  ____  _____    _______          _
                 / __ \|  __ \  |__   __|        | |
                | |  | | |__) |    | | ___   ___ | |___
                | |  | |  ___/     | |/ _ \ / _ \| / __|
                | |__| | |         | | (_) | (_) | \__ \
                 \____/|_|         |_|\___/ \___/|_|___/
    ---- https://www.minebbs.com/resources/op-tools-op-gui.4836/ ----
                        By: PPOUI   Version: 2.5.2

11:32:52 INFO [OPTools] The language file was loaded successfully <zh_CN>
11:32:52 INFO [LiteLoader] Js 插件 <OPTools> 已加载。
11:32:52 INFO [orgEX] 已载入配置文件
11:32:52 INFO [orgEX] 连接数据库...
11:32:52 INFO [orgEX] 连接数据库成功
11:32:52 INFO [orgEX] 注册指令
11:32:52 INFO [LiteLoader] Js 插件 <orgEX> 已加载。
11:32:52 INFO [SimpleTeam] SimpleTeam 1.0.0 已加载，开发者：yqs112358
11:32:52 INFO [SimpleTeam] 简单的组队插件，有编队名字变色、队内伤害阻止、队内聊天等特性
11:32:52 INFO [SimpleTeam] 用法： /team create <名字>  创建队伍
11:32:52 INFO [SimpleTeam]        /team delete         解散队伍
11:32:52 INFO [SimpleTeam]        /team add <玩家>     邀请玩家加入队伍
11:32:52 INFO [SimpleTeam]        /team remove <玩家>  将玩家移出队伍
11:32:52 INFO [SimpleTeam]        /team removeall      将当前队伍中所有其他人移出
11:32:52 INFO [SimpleTeam]        /team list           显示当前队伍中所有玩家
11:32:52 INFO [SimpleTeam]        /team showall        显示当前所有的队伍
11:32:52 INFO [SimpleTeam]        [注] 涉及到更改队伍和队伍成员的命令仅OP玩家可用
11:32:52 INFO [LiteLoader] Js 插件 <SimpleTeam> 已加载。
11:32:52 INFO [LiteLoader] Js 插件 <背包整理> 已加载。
11:32:52 INFO [Timiessencial] Loading...
11:32:52 INFO [TMEssential]
     ________  _________                     __  _       __
    /_  __/  |/  / ____/____________  ____  / /_(_)___ _/ /
     / / / /|_/ / __/ / ___/ ___/ _ \/ __ \/ __/ / __ '/ / 
    / / / /  / / /___(__  |__  )  __/ / / / /_/ / /_/ / /  
   /_/ /_/  /_/_____/____/____/\___/_/ /_/\__/_/\__,_/_/   

  ===TMEssential is distributed under the GPLv3 License===
    =====Running in LiteLoader-ScriptEngine2.13.0=====
11:32:52 INFO [TMEssential] TMEssential is running in QuickJs environment
11:32:52 INFO [TMEssential] Save new operation...
11:32:52 INFO [TMEssential] LangPack Name: zh_CN
11:32:52 INFO [TMEssential] LangPack Author: 提米吖
11:32:52 INFO [TMEssential] LangPack Description: 这是一个默认中文语言包
11:32:52 INFO [TMEssential] Standard LangPack zh_CN has been read!
11:32:52 INFO [TMEssential] AutoUpdate Turned on
11:32:52 INFO [TMEssential] TMEssential loaded! author by 提米吖 version: 1.3.5
11:32:52 INFO [LiteLoader] Js 插件 <TMEssential.js> 已加载。
11:32:52 INFO [LiteLoader] Js 插件 <TitleRemarks> 已加载。
11:32:52 INFO [transfer] transfer加载成功
11:32:52 INFO [LiteLoader] Js 插件 <transfer> 已加载。
11:32:52 INFO [LiteLoader] Js 插件 <VillagerEditor> 已加载。
11:32:52 INFO [LiteLoader] 16 个 Js 插件已加载。
11:32:52 INFO [LiteLoader] 加载 Node.js 插件...
11:32:52 INFO [LiteLoader] 0 个 Node.js 插件已加载。
11:32:52 INFO [LiteLoader] 依赖项 BaseLib.lua 已加载。
11:32:52 INFO [LiteLoader] 加载 Lua 插件...
11:32:52 INFO [iLand] Powerful land plugin is loaded! Ver-2.84,
11:32:52 INFO [iLand] By: RedbeanW, License: GPLv3 with additional conditions.
11:32:52 INFO [LiteLoader] Lua 插件 <iLand> 已加载。
11:32:52 INFO [LiteLoader] 1 个 Lua 插件已加载。
11:32:52 INFO [LiteLoader] 依赖项 BaseLib.py 已加载。
11:32:52 INFO [LiteLoader] 加载 Python 插件...
11:32:52 INFO [LiteLoader] 0 个 Python 插件已加载。
11:32:52 INFO [LiteLoader] 已加载 1 个原生插件
11:32:52 INFO [bStats] bStats已启用，你可以通过编辑 plugins/bStats/config.json 来禁用它
11:32:52 INFO [Server] Starting Server
11:32:52 WARN [LiteLoader] 目前正在使用测试版
11:32:52 WARN [LiteLoader] 请勿在生产环境中使用！
11:32:52 INFO [Server] Version 1.19.81.01(ProtocolVersion 582) with LiteLoaderBDS 2.13.0-dev.0+adbcc9e
11:32:52 INFO [Server] Session ID d2ebc4aa-ad03-449f-ac8c-896b7c75d69a
11:32:52 INFO [Server] Build ID 1.19.81
11:32:52 INFO [Server] Branch r/19_u8
11:32:52 INFO [Server] Commit ID 2606f6a1a1e3ecf907cb776d138dac765c5ba3ff
11:32:52 INFO [Server] Configuration Publish
11:32:52 INFO [Server] Level Name: Bedrock leveltestb
11:32:52 INFO [Server] Game mode: 0 Survival
11:32:52 INFO [Server] Difficulty: 3 HARD
11:32:52 INFO [Server] Experiment(s) active: ddi_, biom, ucft, gtst, mola, sttc, snif
11:32:52 INFO [Server] opening worlds/Bedrock leveltestb/db
11:32:55 INFO [Server] IPv4 supported, port: 15005: Used for gameplay and LAN discovery
container@pterodactyl~ Server marked as running...
11:32:55 INFO [Server] IPv6 supported, port: 65535: Used for gameplay
11:32:56 INFO [Server] To enable Server Telemetry, add the line 'emit-server-telemetry=true' to the server.properties file in the bds directory
11:32:56 INFO [MovingLight] loaded, ver 1.9.2, author: redbeanw.
11:32:56 INFO [LiteLoader] Repository: https://github.com/LiteLDev/LiteLoaderBDS
11:32:56 INFO [LiteLoader] LiteLoader采用 LGPLv3 许可证开源
11:32:56 INFO [LiteLoader] 我们的新论坛上线了啦! -> https://litebds.com
11:32:56 INFO [LiteLoader] 帮助我们翻译&改进翻译 -> https://crowdin.com/project/liteloaderbds
11:32:56 INFO [LiteLoader] Thanks to RhyMC(rhymc.com) for the support
11:32:57 WARN [TMEssential] Failed to obtain network notice!
11:32:57 INFO [LF_Music] LF_Music 0,12,3 服务器音乐_加载成功 | by FlyLight & Wn1027
11:32:57 INFO [VillagerEditor]
 __      ___ _ _                         ______    _ _ _
 \ \    / (_) | |                       |  ____|  | (_) |
  \ \  / / _| | | __ _  __ _  ___ _ __  | |__   __| |_| |_ ___  _ __
   \ \/ / | | | |/ _` |/ _` |/ _ \ '__| |  __| / _` | | __/ _ \| '__|
    \  /  | | | | (_| | (_| |  __/ |    | |___| (_| | | || (_) | |
     \/   |_|_|_|\__,_|\__, |\___|_|    |______\__,_|_|\__\___/|_|
                        __/ |
                       |___/
                                1.2.0
                         Made by Moreallure.
                 No reproduction without permission.
---------------------------------------------------------------------

11:32:57 INFO [CustomCmd] 已成功加载 13 条自定义指令。
11:32:57 INFO [TitleRemarks] TitleRemarks称号与备注插件加载成功!-->作者:乱杖先生
11:32:57 INFO [Advertising_1_2] [定制插件|广告]作者qq:738270846,邮箱: banchen8964@gmail.com
11:32:57 INFO [iLand] 正在构建运行所需要的表...
11:32:57 ERROR [LiteLoader] C++ Uncaught Exception Detected!
11:32:57 ERROR [LiteLoader] There is already a command named land
11:32:57 ERROR [LiteLoader] [failed to get stacktrace]
11:32:57 ERROR [LiteLoader] In API: McClass::regConsoleCmd
11:32:57 ERROR [LiteLoader] In Plugin: iLand
11:32:57 WARN [iLand] 云端信息获取失败。
11:32:57 INFO [iLand] 完成，使用内存：4.18M。
11:32:57 INFO [OPTools] [Network] 欢迎使用OPTools,如果可以能给个五星好评嘛qwq
11:32:57 ERROR [PreLoader] Could not find function in memory: ?id@?1???$type_id@VCommandRegistry@@VCommandItem@@@@YA?AV?$typeid_t@VCommandRegistry@@@@XZ@4V1@A
11:32:57 ERROR [PreLoader] Plugin: LiteLoader.dll
11:32:57 ERROR [LiteLoader] Uncaught SEH Exception Detected!
11:32:57 ERROR [LiteLoader] Error: Code [-1073741819] SEH_UNKNOW_ERROR
11:32:57 ERROR [LiteLoader] In Function (DynamicCommand::_setup - clearbag)
11:32:57 ERROR [LiteLoader] In Plugin <ScriptEngine-QuickJs>
11:32:57 WARN [LiteLoader] Registering command "" failed
11:33:02 ERROR [LF_Music] 请将资源包放到./development_resource_packs/serverMusicRE/

### 有关的日志/输出

```raw
11:32:57 ERROR [PreLoader] Could not find function in memory: ?id@?1???$type_id@VCommandRegistry@@VCommandItem@@@@YA?AV?$typeid_t@VCommandRegistry@@@@XZ@4V1@A
11:32:57 ERROR [PreLoader] Plugin: LiteLoader.dll
11:32:57 ERROR [LiteLoader] Uncaught SEH Exception Detected!
11:32:57 ERROR [LiteLoader] Error: Code [-1073741819] SEH_UNKNOW_ERROR
11:32:57 ERROR [LiteLoader] In Function (DynamicCommand::_setup - clearbag)
11:32:57 ERROR [LiteLoader] In Plugin <ScriptEngine-QuickJs>
11:32:57 WARN [LiteLoader] Registering command "" failed
```

### 插件列表

```raw
11:37:34 INFO [Server] 插件列表 [23]
11:37:34 INFO [Server] - CMENU.js [v0.2.5] (CMENU.js)
11:37:34 INFO [Server]   自定义菜单
11:37:34 INFO [Server] - VillagerEditor [v1.2.0] (VillagerEditor.js)
11:37:34 INFO [Server]   编辑村民交易。
11:37:34 INFO [Server] - transfer [v0.0.3] (transfer.lxl.js)
11:37:34 INFO [Server]   传送到另一个服务器吧
11:37:34 INFO [Server] - PermissionAPI [v2.9.0] (PermissionAPI.dll)
11:37:34 INFO [Server]   Builtin & Powerful permission API for LiteLoaderBDS
11:37:34 INFO [Server] - Bazaar [v2.0.5] (Bazaar.js)
11:37:34 INFO [Server]   集市
11:37:34 INFO [Server] - MovingLight [v1.9.2] (MovingLight.dll)
11:37:34 INFO [Server]   The moving light.
11:37:34 INFO [Server] - ScriptEngine-QuickJs [v2.13.0] (LiteLoader.Js.dll)
11:37:34 INFO [Server]   Javascript ScriptEngine for LiteLoaderBDS
11:37:34 INFO [Server] - Advertising_1_2 [v1.0.0] (Advertising_1_2.llse(5).js)
11:37:34 INFO [Server]   Advertising_1_2
11:37:34 INFO [Server] - CustomCmd [v1.2.0] (CustomCmd.js)
11:37:34 INFO [Server]   添加自定义命令。
11:37:34 INFO [Server] - SimpleTeam [v1.0.0] (SimpleTeam.js)
11:37:34 INFO [Server]   SimpleTeam
11:37:34 INFO [Server] - Fly [v1.0.0] (Fly.js)
11:37:34 INFO [Server]   纯小白开发的一个飞行插件
11:37:34 INFO [Server] - HelloAndGoodbyePlayer [v1.0.0] (HelloAndGoodbyePlayer.js)
11:37:34 INFO [Server]   HelloAndGoodbyePlayer
11:37:34 INFO [Server] - jf [v1.0.0] (jf.js)
11:37:34 INFO [Server]   jf
11:37:34 INFO [Server] - LF_Music [v0.12.3] (LF_Music.js)
11:37:34 INFO [Server]   在服务器里播放音乐
11:37:34 INFO [Server] - OPTools [v2.5.2] (OPTools.js)
11:37:34 INFO [Server]   OPTools
11:37:34 INFO [Server] - orgEX [v2.0.4] (orgEX.lxl.js)
11:37:34 INFO [Server]   一个综合的组织管理插件
11:37:34 INFO [Server] - 背包整理 [v0.0.1] (Sprite‘sCleanUpBag.js)
11:37:34 INFO [Server]   整理背包或其他容器
11:37:34 INFO [Server] - TMEssential.js [v1.3.5] (Timiessencial.js)
11:37:34 INFO [Server]   新时代多功能基础插件
11:37:34 INFO [Server] - TitleRemarks [v1.0.4] (TitleRemarks.lls_1.0.4.js)
11:37:34 INFO [Server]   聊天称号与备注系统
11:37:34 INFO [Server] - ScriptEngine-NodeJs [v2.13.0] (LiteLoader.NodeJs.dll)
11:37:34 INFO [Server]   Node.js ScriptEngine for LiteLoaderBDS
11:37:34 INFO [Server] - ScriptEngine-Lua [v2.13.0] (LiteLoader.Lua.dll)
11:37:34 INFO [Server]   Lua ScriptEngine for LiteLoaderBDS
11:37:34 INFO [Server] - iLand [v2.8.4] (iland-core.lua)
11:37:34 INFO [Server]   Powerful land plugin.
11:37:34 INFO [Server] - ScriptEngine-Python [v2.13.0] (LiteLoader.Python.dll)
11:37:34 INFO [Server]   Python ScriptEngine for LiteLoaderBDS
11:37:34 INFO [Server]
11:37:34 INFO [Server]
11:37:34 INFO [Server] * 使用命令“ll list <Plugin Name>”来获取更多信息
```

**Comment by ShrBox** [comment]
Fixed in 87fa1d2c7bd27f7aadd9b86384ff81b55649d46b
