### ISSUE TITLE
RaidMobSpawnEvent 异常

### ISSUE THREAD

**Issue by KobeBryant114514** [LiteLDev/LiteLoader#1251]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows Server 2022

### LiteLoader 版本

LL 2.13.0-beta1

### BDS 版本

1.19.81

### 发生了什么?

在LLSE中，RaidMobSpawnEvent的pos.dimid永远为-1（无效的坐标）
RaidMobSpawnEvent 无法被拦截

原因是在LL层的RaidMobSpawnEvent并没有提供DimensionId相关参数，无法获取准确坐标

**Comment by KobeBryant114514** [comment]
另外根据Issue #1198 的内容，由于"onMobTrySpawn"和"onMobTrySpawned"两个监听生物生成的API无法监听袭击，因此袭击生成API最好也拆成生成前（方便拦截）和生成后（方便获取生成的实体）

**Comment by quizhizhe** [comment]
啊这。。。LLSE的pos还带有dimension的？好吧

**Comment by KobeBryant114514** [comment]
> 啊这。。。LLSE的pos还带有dimension的？好吧

你Hook的点位我以前用过，可以拦截的。
如果拦截此函数，这个函数应该是会尝试执行5次之后结束（不会一直触发）。

另外袭击生成的时候，这个函数也可能执行多次。
（如果袭击生成坐标在地下，他会重新再执行这个函数）

**Comment by quizhizhe** [comment]
> > 啊这。。。LLSE的pos还带有dimension的？好吧
> 
> 你Hook的点位我以前用过，可以拦截的。 如果拦截此函数，这个函数应该是会尝试执行5次之后结束（不会一直触发）。
> 
> 另外袭击生成的时候，这个函数也可能执行多次。 （如果袭击生成坐标在地下，他会重新再执行这个函数）

soga，这样的话，最后那个改成提供实体UUID吧，而不是提供数量，这样也方便获取生成的实体，原来也是说明可以拦截的，但为了获取数量就直接设置成不可拦截了

**Comment by KobeBryant114514** [comment]
> > > 啊这。。。LLSE的pos还带有dimension的？好吧
> > 
> > 
> > 你Hook的点位我以前用过，可以拦截的。 如果拦截此函数，这个函数应该是会尝试执行5次之后结束（不会一直触发）。
> > 另外袭击生成的时候，这个函数也可能执行多次。 （如果袭击生成坐标在地下，他会重新再执行这个函数）
> 
> soga，这样的话，最后那个改成提供实体UUID吧，而不是提供数量，这样也方便获取生成的实体，原来也是说明可以拦截的，但为了获取数量就直接设置成不可拦截了

我认为，大概可以做成在original之前，提供实体的ActorUniqueID，original之后，通过ActorUniqueId获取并提供Actor指针。分成前后两个事件（就像"onMobTrySpawn"和"onMobTrySpawned"一样）

另外由于之前也提到了，另外袭击生成的时候，这个函数也可能执行多次，就是说可能生成失败。
所以说如果original之后，通过ActorUniqueId获取到的是nullptr，则不回调这个监听。

当初MobSpawnEvent之所以拆分也是因为亮度、半砖等原因导致无法刷怪，也会反复触发MobSpawnEvent，但是并没有生成任何生物。

**Comment by quizhizhe** [comment]
是打算这样写，nullptr的问题不用担心，如果没有成功生成，是不会有actorID，至少理论的是

**Comment by OEOTYAN** [comment]
以后ll3里写成用户自定义事件以插件形式发布，这个事件回头删掉
