### ISSUE TITLE
增加繁殖事件

### ISSUE THREAD

**Issue by FtyLollipop** [LiteLDev/LiteLoader#1262]
### 您的建议是否与现存的某个问题相关?请描述问题?

无法监听繁殖

### 您认为还缺少什么?如何解决您的问题?

增加一个繁殖事件，参数为：参与繁殖的实体1，参与繁殖的实体2，生成的新实体，掉落的经验数（若是村民则为0）

**Comment by dreamguxiang** [comment]
ll2.0不再接受新事件添加，统一归档至3.0，如有需要自行hook

**Comment by OEOTYAN** [comment]
不加
