### ISSUE TITLE
增加玩家与方块的实际交互事件

### ISSUE THREAD

**Issue by FtyLollipop** [LiteLDev/LiteLoader#1263]
### 您的建议是否与现存的某个问题相关?请描述问题?

目前只有onBlockInteracted事件可以监听到玩家与方块交互（打开GUI），无法监听到实际做了什么

### 您认为还缺少什么?如何解决您的问题?

增加一个或一系列事件以监听玩家：在工作台合成了物品（使用的物品，合成的物品），附魔台附魔（附魔前的物品，使用的选项，附魔后的物品），使用铁砧（消耗的物品，命名，获得的物品），等可以进行交互的方块

**Comment by KobeBryant114514** [comment]
建议自行Hook handle就行了

**Comment by OEOTYAN** [comment]
不加
