### ISSUE TITLE
LLSE "onNpcCmd"监听失效

### ISSUE THREAD

**Issue by FBQingYi** [LiteLDev/LiteLoader#1267]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows Server 2019

### LiteLoader 版本

2.13.0

### BDS 版本

1.19.80.02

### 发生了什么?

npc执行指令监听无反应

### 复现此问题的步骤

mc.listen("onNpcCmd", (npc, player, cmd) => {
    log(cmd)
})

### 有关的日志/输出

```raw
无
```

**Comment by Futureganteng** [comment]
i have the same issue too, thank you for opening the issue.

**Comment by OEOTYAN** [comment]
你在何种情况下使用此事件？

**Comment by OEOTYAN** [comment]
此事件会被移除，因为其不合比例的维护成本，请等待 LL3 的用户自定义事件系统。
This event will be removed due to its disproportionate maintenance cost, please wait for LL3's user-defined event system.
