### ISSUE TITLE
LLSE 2.13.0 onDestroyBlock事件仍然不会被触发

### ISSUE THREAD

**Issue by siori0714** [LiteLDev/LiteLoader#1268]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows 10

### LiteLoader 版本

2.13.0

### BDS 版本

1.19.81

### 发生了什么?

https://github.com/LiteLDev/LiteLoaderBDS/issues/1249 标记已完成，但在2.13.0监听onDestroyBlock事件时仍有无法触发的问题

### 复现此问题的步骤

1.
```
注册onDestroyBlock监听事件
mc.listen("onDestroyBlock", () => {
    log(`test`)
})
```

2.破坏任意方块

3.预期后台输出"test"，实际无任何输出

註：有成功触发过一段期间，之后热重载插件或重新加入伺服皆无正确触发

**Comment by ShrBox** [comment]
无法复现，请确认`server.properties`中`server-authoritative-movement`是否设置为`server-auth`
