### ISSUE TITLE
LLSE新增一个获取方块运行id的api

### ISSUE THREAD

**Issue by FBQingYi** [LiteLDev/LiteLoader#1271]
### 您认为还缺少什么?如何解决您的问题?

方便js发包时更方便获取到方块的运行id
block.getRuntimeId();

**Comment by quizhizhe** [comment]
@FBQingYi 我的建议是，没怎么用到的不必加。强烈推荐使用c++写，更加自由

**Comment by FBQingYi** [comment]
> @FBQingYi 我的建议是，没怎么用到的不必加。强烈推荐使用c++写，更加自由

不会c++，并且也想插件不怎么需要维护。

**Comment by quizhizhe** [comment]
@FBQingYi 方块运行id会在玩家加入服务器时发送给玩家，可以从这拿到

**Comment by FBQingYi** [comment]
> @FBQingYi 方块运行id会在玩家加入服务器时发送给玩家，可以从这拿到

但是js没办法😂
