### ISSUE TITLE
在LLSE添加药水效果ID的枚举

### ISSUE THREAD

**Issue by harry-xi** [LiteLDev/LiteLoader#1272]

**Comment by KobeBryant114514** [comment]
这东西是不是应该放文档站？
另外cpp源码里面有对应的枚举项。

**Comment by dreamguxiang** [comment]
@Tsubasa6848 我的建议看wiki

**Comment by harry-xi** [comment]
> 这东西是不是应该放文档站？ 另外cpp源码里面有对应的枚举项。

文档站里当然有，我从wiki复制过来的。不过就像llse里的DamageCause一样，它能为脚本编写带来便利。

**Comment by KawaiiNahida** [comment]
枚举经常变，没动力一直更新，一些wiki没有的内部过程（例如ActorDamageCause）枚举才会考虑放进来
