### ISSUE TITLE
资源包加密出现问题

### ISSUE THREAD

**Issue by yumo135** [LiteLDev/LiteLoader#1274]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.13.1

### BDS 版本

1.19.81

### 发生了什么?

使用第三方加密pack-essentials时出现开服后包会自动把加密后的包恢复，进服之后材质不显示，似乎未适配这个加密
项目链接https://github.com/hax0r31337/pack-essentials

### 复现此问题的步骤

1.使用pack-essentials进行加密
2.以"uuid" : "key"填入
3.开服
4.加密后的包后自动解密，并且客户端下载到的包也是解密的

### 有关的日志/输出

```raw
无输出日志
```

### 插件列表

```raw
无插件，ll+bds纯净端
```

**Comment by ShrBox** [comment]
请尝试使用 https://encryptmypack.com/

**Comment by dreamguxiang** [comment]
与ll无关
