### ISSUE TITLE
xbox下onDestroyBlock事件不触发

### ISSUE THREAD

**Issue by snowie2000** [LiteLDev/LiteLoader#1275]
### 异常模块

LiteLoader (本体)

### 操作系统

GNU/Linux with docker

### LiteLoader 版本

2.13.1

### BDS 版本

1.19.81

### 发生了什么?

在xbox中创造模式，攻击一个方块，无法触发onDestroyBlock事件，但在pc或移动设备上则可以触发。

### 复现此问题的步骤

mc.listen("onDestroyBlock", ()=>logger.info("destroyed"))

xbox中此代码完全不执行，pc中打破方块可以触发

**Comment by ShrBox** [comment]
请尝试actions的最新构建

**Comment by snowie2000** [comment]
好的

**Comment by snowie2000** [comment]
经过测试，依然不触发。

**Comment by snowie2000** [comment]
在最新的版本中，所有平台都无法正确触发onDestroyBlock了

**Comment by ShrBox** [comment]
待构建完后尝试 b37a22f29d6eb7ae457eb4a2bf166c8144ed2ac3 谢谢

**Comment by snowie2000** [comment]
![QQ截图20230616165655](https://github.com/LiteLDev/LiteLoaderBDS/assets/11767189/ec982155-6e7b-4f29-9a30-5b68654a62a4)
是我什么地方的操作有问题吗？完全不能触发此事件。

使用最新的1.20版本干净的环境。完全删除了plugin文件夹，只在里面放了一个没有实际意义的js文件来打开jsdebug功能。现在pc平台也是无法触发此事件的。

另外onAttackBlock是可以触发的，但是不能拦截，并且在创造模式下block总是air

**Comment by ShrBox** [comment]
确保`server.properties`中的`server-authoritative-block-breaking`为启用状态，否则LL将无法监听到破坏方块事件

**Comment by snowie2000** [comment]
确实，现在可以触发了，我还未在xbox下测试，但pc下可以触发了。

但现在出现了另外的两个问题：
1. onAttackBlock不会触发了
2. onDestroyBlock虽然可以触发，但无法拦截

**Comment by snowie2000** [comment]
> 确保`server.properties`中的`server-authoritative-block-breaking`为启用状态，否则LL将无法监听到破坏方块事件

经过xbox测试，可以完美处理onDestroyBlock事件，并且可以拦截。同时在pc上却完全不能拦截，和之前的正好相反……

**Comment by Dofes** [comment]
dev分支下,更新了玩家破坏方块的点位(自测Win端可以不打开server-authoritative-block-breaking的情况下正常拦截),暂时不确定and和xbox是否有bug

**Comment by snowie2000** [comment]
> dev分支下,更新了玩家破坏方块的点位(自测Win端可以不打开server-authoritative-block-breaking的情况下正常拦截),暂时不确定and和xbox是否有bug

经过测试已经全部恢复正常了，不开server-authoritative-block-breaking的情况下pc，xbox均能正确触发并拦截，onAttackBlock也能触发了
