### ISSUE TITLE
玩家人數設定

### ISSUE THREAD

**Issue by ghost** [LiteLDev/LiteLoader#1276]
### 您的建议是否与现存的某个问题相关?请描述问题?

關於遊戲人數設定方面能解鎖官方限制

### 您认为还缺少什么?如何解决您的问题?

控制台 setmaxplayers 可以設定超過40人

**Comment by KobeBryant114514** [comment]
改server.properties即可

**Comment by Yushu2606** [comment]
https://github.com/SourceLandDev/FixMaxPlayers
非加载器功能或不严重漏洞不要反馈给LiteLoaderBDS
