### ISSUE TITLE
数据库操作fetchAll()失效

### ISSUE THREAD

**Issue by KINGANDWL** [LiteLDev/LiteLoader#1277]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows 11

### LiteLoader 版本

2.13.1

### BDS 版本

1.19.83

### 发生了什么?

直接执行
result = stmt.reset().fetchAll();
会报错“[LiteLoader] Event Callback Failed!”

但是换成
result = stmt.reset().fetchAll((_result)=>{
    console.log(_result)
});
能正常执行

在开发文档了说stmt.reset().fetchAll();返回的应该是any[][]，不知道是这个接口删掉了，还是说就是存在这个问题

**Comment by harry-xi** [comment]
相关API存在，
建议提供更完整的错误日志输出。
