### ISSUE TITLE
XUID数据库查询操作name2xuid失败

### ISSUE THREAD

**Issue by DanielToyama** [LiteLDev/LiteLoader#1278]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.13

### BDS 版本

1.19.81

### 发生了什么?

XUID数据库查询操作name2xuid失败

### 复现此问题的步骤

执行代码
data.name2xuid(xboxid)
的时候，控制台抛出异常
TypeError: data.name2xuid is not a function

### 有关的日志/输出

```raw
TypeError: data.name2xuid is not a function
```

**Comment by ShrBox** [comment]
无法复现

**Comment by Yushu2606** [comment]
你是不是自己定义了个data……

**Comment by DanielToyama** [comment]
> 你是不是自己定义了个data……

经过检查是这样...抱歉打扰了
