### ISSUE TITLE
发包函数或者数据包存在的不稳定因素（PlayerSkinPacket）

### ISSUE THREAD

**Issue by Milvona** [LiteLDev/LiteLoader#1279]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows Server 2022

### LiteLoader 版本

LiteLoaderBDS 2.13.1+13d598e

### BDS 版本

Version 1.19.81.01(ProtocolVersion 582)

### 发生了什么?

数据包PlayerSkinPacket在通过LoopbackPacketSender全局发送有1/20的几率会被客户端识别为InvalidPacket而断联，但是同一个数据包多次尝试也有1/17的大致几率断联

### 复现此问题的步骤

```
void sendSkinPacket(string name) {
    LoopbackPacketSender* pktSender = (LoopbackPacketSender*)Global<Level>->getPacketSender();
    auto pkt = PlayerSkinPacket();
    auto pl = getPlayer(name);
    for (auto us : users) {
        if (us.user == name) {
            pkt.mSerializedSkin = us.skin;//这是从玩家中getSkin()
        }
    }
    pkt.mUUID = getUUIDfromname(name);//这是单独写的函数获取一某个假人的uuid
    pkt.mNewName = "TEST";
    pkt.mOldName = "";
    pktSender->send(pkt);
}
```
这个函数在多次使用后发现不稳定的现象，有概率出问题，但是大部分情况下不出问题。

### 有关的日志/输出

```raw
无输出，客户端断联
```

### 插件列表

```raw
无内容
```

**Comment by dreamguxiang** [comment]
自用npc插件未发现此问题

**Comment by yufengya0420** [comment]
![{@_ACNYJITI 0RWN4( WV~C](https://github.com/LiteLDev/LiteLoaderBDS/assets/99462074/94be3c0a-cd59-4c61-aa13-09bdd13835be)

**Comment by dreamguxiang** [comment]
> ![{@_ACNYJITI 0RWN4( WV~C](https://user-images.githubusercontent.com/99462074/248670779-94be3c0a-cd59-4c61-aa13-09bdd13835be.png)

主要我们这里没办法复现，llac与移动光源都是频繁发包的

**Comment by dreamguxiang** [comment]
建议检测packet结构与大小是否正确，且发包函数都是基于BDS的，炸了和LL关系也不大
