### ISSUE TITLE
[LLSE] "onDestroyBlock" bug

### ISSUE THREAD

**Issue by AlphaMSq** [LiteLDev/LiteLoader#1280]
### Exceptions module

ScriptEngine

### Operating System

Windows 10

### LiteLoader version

2.13.1+13d598e

### BDS version

1.19.81.01

### What happened?

When a sign breaks and the "onDestroyBlock" event is intercepted (return false), the text disappears.

https://github.com/LiteLDev/LiteLoaderBDS/assets/124319298/09112455-b61f-4c57-953f-d2feed2037d2

### Steps to reproduce?

1. Use mc.listen("onDestroyBlock", (pl, bl) => { return false })
2. Break sign with text

**Comment by ShrBox** [comment]
#1113
