### ISSUE TITLE
在有部分插件的情况下往未加载的区块中丢出物品会导致bds崩溃

### ISSUE THREAD

**Issue by timiya233** [LiteLDev/LiteLoader#1281]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows 10

### LiteLoader 版本

2.13.1

### BDS 版本

1.19.81

### 发生了什么?

在有部分插件的情况下往未加载的区块中丢出物品会导致bds崩溃

使用LL监听器可解决此问题：
``` C/C++
#define let auto
bool onPlayerDropEV(Event::PlayerDropItemEvent ev)
{
    let pl = ev.mPlayer;
    let &bs = *pl->getLevel().getBlockSource(pl->getDimensionId());
    return pl->_isChunkSourceLoaded(pl->getPosition(), bs);
}

void Plugin_DLL_PROCESS_ATTACH() {//DllMain ul_reason_for_call
    Event::PlayerDropItemEvent::subscribe(onPlayerDropEV);
}
```

### 复现此问题的步骤

1.输入指令tp
2.丢出物品

**Comment by Yushu2606** [comment]
原版端试了下，只会吞物品不会崩
所以是插件问题？

以及发代码请用Markdown

**Comment by yufengya0420** [comment]
![MUTX)RNI62RA8} 4BCE4Y)X](https://github.com/LiteLDev/LiteLoaderBDS/assets/99462074/955a131d-b37f-466e-b390-37b0e8f27d73)

**Comment by yufengya0420** [comment]
![插件列表](https://github.com/LiteLDev/LiteLoaderBDS/assets/99462074/b019c1e4-bff5-4e17-b359-c19d2bea1c7c)

**Comment by Yushu2606** [comment]
> ![MUTX)RNI62RA8} 4BCE4Y)X](https://user-images.githubusercontent.com/99462074/242340942-955a131d-b37f-466e-b390-37b0e8f27d73.png)

转储和堆栈呢

**Comment by yufengya0420** [comment]
> > ![MUTX)RNI62RA8} 4BCE4Y)X](https://user-images.githubusercontent.com/99462074/242340942-955a131d-b37f-466e-b390-37b0e8f27d73.png)
> 
> 转储和堆栈呢
[crash.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/11620796/crash.zip)

**Comment by Yushu2606** [comment]
> > > ![MUTX)RNI62RA8} 4BCE4Y)X](https://user-images.githubusercontent.com/99462074/242340942-955a131d-b37f-466e-b390-37b0e8f27d73.png)
> > 
> > 
> > 转储和堆栈呢
> > [crash.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/11620796/crash.zip)

堆栈呢……

**Comment by yufengya0420** [comment]
> > > > ![MUTX)RNI62RA8} 4BCE4Y)X](https://user-images.githubusercontent.com/99462074/242340942-955a131d-b37f-466e-b390-37b0e8f27d73.png)
> > > 
> > > 
> > > 转储和堆栈呢
> > > [crash.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/11620796/crash.zip)
> 
> 堆栈呢……

没生成，输出到这就卡住了，只能结束进程，不然要等一年

**Comment by yufengya0420** [comment]
![P47%BBTI5FVSSRU{Z~ S4JT](https://github.com/LiteLDev/LiteLoaderBDS/assets/99462074/cd6aecc6-a5be-4245-b89b-b6cd0a1e686d)
![{2M}G8854$E~L{$D0E @9IE](https://github.com/LiteLDev/LiteLoaderBDS/assets/99462074/c6ab6919-d197-4df4-811e-3f700e4f940b)

**Comment by yufengya0420** [comment]
> > > > ![MUTX)RNI62RA8} 4BCE4Y)X](https://user-images.githubusercontent.com/99462074/242340942-955a131d-b37f-466e-b390-37b0e8f27d73.png)
> > > 
> > > 
> > > 转储和堆栈呢
> > > [crash.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/11620796/crash.zip)
> 
> 堆栈呢……

你等等我再复现一下看看能不能等到它加载完成

**Comment by yufengya0420** [comment]
[crash.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/11620936/crash.zip)

**Comment by yufengya0420** [comment]
> [crash.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/11620936/crash.zip)

这是堆栈和转储

**Comment by timiya233** [comment]
> 原版端试了下，只会吞物品不会崩 所以是插件问题？
> 
> 以及发代码请用Markdown

有没有一种可能，是LL调用了那个有问题的物品对象导致崩溃呢

**Comment by timiya233** [comment]
因为我的机子实在复现不出来，所以找的别人测试的

**Comment by Yushu2606** [comment]
> > 原版端试了下，只会吞物品不会崩 所以是插件问题？
> > 以及发代码请用Markdown
> 
> 有没有一种可能，是LL调用了那个有问题的物品对象导致崩溃呢

我觉得是BDS把物品吞掉后插件调用被释放的物品对象导致的访问冲突

**Comment by timiya233** [comment]
> 

可能吧，啥时候修复一下

**Comment by dreamguxiang** [comment]
你们要是会修就直接pr吧，都在考试周和高考估计没人看
（顺便提一嘴ll2.0到1.20适配完成，就不再维护了，如果3.0没在1.20.10前完成可能就无限咕咕在1.20.0一阵子了（:

**Comment by Yushu2606** [comment]
> 你们要是会修就直接pr吧，都在考试周和高考估计没人看 （顺便提一嘴ll2.0到1.20适配完成，就不再维护了，如果3.0没在1.20.10前完成可能就无限咕咕了（:

加油啊😂，祝成功

**Comment by dreamguxiang** [comment]
> > > 原版端试了下，只会吞物品不会崩 所以是插件问题？
> > > 以及发代码请用Markdown
> > 
> > 
> > 有没有一种可能，是LL调用了那个有问题的物品对象导致崩溃呢
> 
> 我觉得是BDS把物品吞掉后插件调用被释放的物品对象导致的访问冲突

正解，我觉得应该是插件自己来判断

**Comment by Yushu2606** [comment]
> 可能吧，啥时候修复一下

最好还是让插件修，咱也不知道究竟用了哪些API（
在事件之前拦截也不是不行，但是总感觉不优雅（（

**Comment by dreamguxiang** [comment]
> > 可能吧，啥时候修复一下
> 
> 最好还是让插件修，咱也不知道究竟用了哪些API（

api挺明显，gettypename（

**Comment by Yushu2606** [comment]
> > > 可能吧，啥时候修复一下
> > 
> > 
> > 最好还是让插件修，咱也不知道究竟用了哪些API（
> 
> api挺明显，gettypename（

但是不知道后续操作（（

**Comment by timiya233** [comment]
> 你们要是会修就直接pr吧，都在考试周和高考估计没人看 （顺便提一嘴ll2.0到1.20适配完成，就不再维护了，如果3.0没在1.20.10前完成可能就无限咕咕在1.20.0一阵子了（:

嗐，但是我不会编译ll啊

**Comment by dreamguxiang** [comment]
> > > > 可能吧，啥时候修复一下
> > > 
> > > 
> > > 最好还是让插件修，咱也不知道究竟用了哪些API（
> > 
> > 
> > api挺明显，gettypename（
> 
> 但是不知道后续操作（（

![image](https://github.com/LiteLDev/LiteLoaderBDS/assets/62042544/687a1a95-6966-46c4-a2ba-5c48dfe3d775)
感觉没啥修的，建议找DespawnLags的插件作者看看吧（让他判断一下空指针就行

**Comment by Yushu2606** [comment]
> > 你们要是会修就直接pr吧，都在考试周和高考估计没人看 （顺便提一嘴ll2.0到1.20适配完成，就不再维护了，如果3.0没在1.20.10前完成可能就无限咕咕在1.20.0一阵子了（:
> 
> 嗐，但是我不会编译ll啊

fork下仓库再启用Actions就行了

**Comment by timiya233** [comment]
> > > 你们要是会修就直接pr吧，都在考试周和高考估计没人看 （顺便提一嘴ll2.0到1.20适配完成，就不再维护了，如果3.0没在1.20.10前完成可能就无限咕咕在1.20.0一阵子了（:
> > 
> > 
> > 嗐，但是我不会编译ll啊
> 
> fork下仓库再启用Actions就行了

好的，我试试

**Comment by ShrBox** [comment]
插件未判断指针是否有效导致的问题就没必要在LiteLoader里面拦截了，拦截还可能导致插件出现一些意外的情况
