### ISSUE TITLE
Laggy movements

### ISSUE THREAD

**Issue by ubanning** [LiteLDev/LiteLoader#1283]
### Is your feature request related to a problem? Please describe.

Minecraft Bedrock has very laggy movements, this is not a LiteLoaderBDS problem, but I believe that this functionality could be added to make the movement more fluid, as well as large servers like HiveMC. For PvP game modes, this lag movement interferes with gameplay
Laggy movement can be observed when you view another player on the server. You can't tell playing alone, just looking at another player's movement.
The problem is not on the server, nor on the connection, but on Minecraft Bedrock itself, I tested it on LAN, Minecraft Dedicated Server and LiteBDS and they all have this problem.

### Describe the solution you'd like

I would like fluid movements like HiveMC and other big servers.
Thanks!

**Comment by ubanning** [comment]
Hello, I believe the problem is in the Minecraft Bedrock movement packets, BSDX made an example plugin with the name: `net-halfmove` . Could you give me an example of a packet handling plugin so I can do the same thing as BSDX but in LiteLoaderBDS? Thank you!
```/**
 * This example is just skip half of movement packets.
 *
 * CAUTION: this example is only works for two players. need to implement it more
 */

import { NetworkIdentifier } from "bdsx/bds/networkidentifier";
import { MinecraftPacketIds } from "bdsx/bds/packetids";
import { CANCEL } from "bdsx/common";
import { events } from "bdsx/event";

interface Counter {
    counter: number;
}
const map = new WeakMap<NetworkIdentifier, Counter>();
events.packetSendRaw(MinecraftPacketIds.MovePlayer).on((packet, size, ni) => {
    let field = map.get(ni);
    if (field === undefined) map.set(ni, (field = { counter: 0 }));

    field.counter++;
    if (field.counter >= 2) {
        field.counter = 0;
        return CANCEL;
    }
```

**Comment by Yushu2606** [comment]
it is not the responsibility of ll
