### ISSUE TITLE
isSimulatedPlayer not working with onPlayerDie's player object

### ISSUE THREAD

**Issue by FtyLollipop** [LiteLDev/LiteLoader#1285]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.13.1

### BDS 版本

1.19.83.01

### 发生了什么?

假人触发onPlayerDie事件获取到的玩家对象调用isSimulatedPlayer()结果为false，其他事件获取到的假人玩家对象调用均正常为true

### 复现此问题的步骤

同上

**Comment by OEOTYAN** [comment]
https://github.com/LiteLDev/LiteLoaderBDS/commit/41691bf921f5581c99e6bb4020826c750d1a1994 修了
