### ISSUE TITLE
控制台输入任何的指令，指令执行成功的反馈以报错方法刷屏

### ISSUE THREAD

**Issue by ye111566** [LiteLDev/LiteLoader#1290]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.14.0

### BDS 版本

1.20.0

### 发生了什么?

控制台循环刷屏执行的指令的回馈
而且是用报错方法循环输出
比如输入/title @a title
控制台循环刷屏[Error]指令title执行成功

### 复现此问题的步骤

1.启动后，控制台输入任意一个指令
比如scoreboard objectives add a dummy
接着就会循环刷屏了

### 有关的日志/输出

```raw
循环
[Error]指令tellraw执行成功。
```

### 插件列表

```raw
控制台循环刷屏，截不到ll list输出
```

**Comment by ye111566** [comment]
如图

**Comment by ye111566** [comment]
![Screenshot_20230608_182829_com huawei browser](https://github.com/LiteLDev/LiteLoaderBDS/assets/131894598/2289ec9d-5420-4e31-b47f-b6cdebbf116a)

**Comment by ENIACJushi** [comment]
https://github.com/LiteLDev/LiteLoaderBDS/pull/1286#issuecomment-1581949815
用的是最新构建吗，这个bug今天下午修过

**Comment by dreamguxiang** [comment]
最新未能复现
