### ISSUE TITLE
对于 ParticleAPI 的功能建议

### ISSUE THREAD

**Issue by ImYoyoData** [LiteLDev/LiteLoader#1297]
### 您的建议是否与现存的某个问题相关?请描述问题?

ParticleAPI 目前有一个渲染数字的  支持 0-16  或者字符串 A-F
我觉得这个极大限制了 ParticleAPI 的发展
建议增加 支持渲染 字符串的 (汉字,字母,符号呀等) 希望长度不要限制得这么小

还有

![image](https://github.com/LiteLDev/LiteLoaderBDS/assets/16756946/b7f72588-7d14-4047-9f86-d2713bb6f654)
渲染立方体会有极大可能缺失  或者 直接渲染不出来! 这个测试了很多次了

如果 粒子显示时间 可以直接设置更加好  目前是默认2秒 消失

**Comment by OEOTYAN** [comment]
首先你讲的做不了，其次立方体不会缺失，把你的完整测试代码放上来
