### ISSUE TITLE
pl.addEffect(id, tick, level, showParticles)成员函数无效

### ISSUE THREAD

**Issue by QAQLemon233** [LiteLDev/LiteLoader#1298]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2016

### LiteLoader 版本

2.14.0

### BDS 版本

1.20.0

### 发生了什么?

使用python编写的插件中用mc.runcmd(f"effect {pl.name} absorption 999 2 true")无法为玩家设置药水效果，使用时已经确保获取到玩家pl，并且pl.name是在线玩家的id。

此外使用pl.addEffect(11,999,0,False)也无法为玩家设置药水效果，并且无任何报错。

### 复现此问题的步骤

以下为插件中的代码
def buff(pl):
        pl.addEffect(11,999,0,False)
        pl.addEffect(22,999,2,False)
        mc.runcmd(f"effect {pl.name} absorption 999 2 true")
mc.listen("onRespawn",buff)

### 有关的日志/输出

```raw
[Server] No targets matched selector
```

**Comment by ShrBox** [comment]
无法复现
经测试，addEffect函数工作正常
```
pydebug
17:30:09 INFO [LiteLoader] Debug mode begins
>>> pl = mc.getPlayer('testplayer')
>>> pl.addEffect(14, 2000, 1, True)
True
```
