### ISSUE TITLE
Proposal: To-dos

### ISSUE THREAD

**Issue by futrime** [LiteLDev/LiteLoader#1302]
To-dos for LiteLoaderBDS 3.

- [ ] **事件分离**: 将事件分离出Liteloader本体,单独集成在一个模块
- [ ] **还原继承关系**：通过安卓发行版获取RTTI，还原继承关系（虚多继承需要修复内存布局）
- [ ] **类型大小自动推测**：推测类型大小进行填充（asm/ast分析？）
- [ ] **XMake迁移**：迁移到XMake工程
- [ ] **头文件生成**：生成头进行格式化
- [ ] **依赖头文件自动导入**：自动导入部分依赖头
- [ ] **嵌套命名空间适配**：适配嵌套命名空间
- [ ] **注释优化**：优化注释方案
- [ ] **生成优化**：优化生成方案

**Comment by Futrime** [comment]
- [ ] Test
