### ISSUE TITLE
LINUX SUPPORT

### ISSUE THREAD

**Issue by xAffan** [LiteLDev/LiteLoader#1309]
### Is your feature request related to a problem? Please describe.

Can't use this software on any minecraft server hosts because they run linux but do not allow wine to be installed.

### Describe the solution you'd like

It should support the linux version of BDS. It is way more in demand because of the server hosts that run linux, not windows.

**Comment by ShrBox** [comment]
Supporting Linux is equivalent to writing code from scratch.

**Comment by dreamguxiang** [comment]
#1442
