### ISSUE TITLE
"onBlockExploded" event does not cover "respawn blocks" explosion.

### ISSUE THREAD

**Issue by HeliosPe** [LiteLDev/LiteLoader#1310]
### Exceptions module

ScriptEngine

### Operating System

Windows 11

### LiteLoader version

2.14.0

### BDS version

1.20.0.01

### What happened?

I have encouraged the problem in a coreprotect ported to LLSE. Omitting the details, I finally tried to trigger the "onBlockExploded" event by blowing up the minecraft:respawn_anchor in overworld and the minecraft:bed in nether, outputting something to the chat using the function mc.broadcast();

While tnt, creeper explosion and others have successfully run the function, from the "respawn blocks" I had no result.

### Plugin list

```raw
15:10:45 INFO [Server] Список плагинов [7]
15:10:45 INFO [Server] - LLMoney [v2.14.0] (LLMoney.dll)
15:10:45 INFO [Server]   EconomyCore for LiteLoaderBDS
15:10:45 INFO [Server] - ScriptEngine-Lua [v2.14.1] (LiteLoader.Lua.dll)
15:10:45 INFO [Server]   Lua ScriptEngine for LiteLoaderBDS
15:10:45 INFO [Server] - PermissionAPI [v2.9.0] (PermissionAPI.dll)
15:10:45 INFO [Server]   Builtin & Powerful permission API for LiteLoaderBDS
15:10:45 INFO [Server] - ScriptEngine-QuickJs [v2.14.1] (LiteLoader.Js.dll)
15:10:45 INFO [Server]   Javascript ScriptEngine for LiteLoaderBDS
15:10:45 INFO [Server] - ScriptEngine-Python [v2.14.1] (LiteLoader.Python.dll)
15:10:45 INFO [Server]   Python ScriptEngine for LiteLoaderBDS
15:10:45 INFO [Server] - ScriptEngine-NodeJs [v2.14.1] (LiteLoader.NodeJs.dll)
15:10:45 INFO [Server]   Node.js ScriptEngine for LiteLoaderBDS
15:10:45 INFO [Server] - CoreProtectMini [v1.0.0] (CoreProtectMini-main)
15:10:45 INFO [Server]   Stripped down version of CoreProtect
15:10:45 INFO [Server]
15:10:45 INFO [Server]
15:10:45 INFO [Server] * Напишите в командной строке "ll list <Plugin Name>" для получения дополнительной информации
```

**Comment by ShrBox** [comment]
https://docs.litebds.com/en/#/LLSEPluginDevelopment/EventAPI/BlockEvents?id=quotonrespawnanchorexplodequot-respawn-anchor-explosion-event
Respawn anchor has its own event

**Comment by HeliosPe** [comment]
> https://docs.litebds.com/en/#/LLSEPluginDevelopment/EventAPI/BlockEvents?id=quotonrespawnanchorexplodequot-respawn-anchor-explosion-event
> Respawn anchor has its own event

1) The bed still not.
2) The event is about the respawn anchor, while I was talking about the blocks distructed by the explosion of respawning blocks.
