### ISSUE TITLE
Component block Cauldron LLSE

### ISSUE THREAD

**Issue by BuslnwTH** [LiteLDev/LiteLoader#1311]
### Is your feature request related to a problem? Please describe.

I'm try to fix the color of the water in the cauldron, which can't be edited in Component minecraft:waterContainer

minecraft scriptAPI: 
https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/minecraft/server/block#getcomponent
https://learn.microsoft.com/en-us/minecraft/creator/scriptapi/minecraft/server/blockwatercontainercomponent#getcustomcolor

### Describe the solution you'd like

add getCompoent setComponent or other etc...

**Comment by OEOTYAN** [comment]
getBlockEntity -> getNbt -> edit nbt -> setNbt
