### ISSUE TITLE
不开作弊时，自动补全工作不正常

### ISSUE THREAD

**Issue by snowie2000** [LiteLDev/LiteLoader#1313]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows 10

### LiteLoader 版本

2.14.1

### BDS 版本

1.20.1

### 发生了什么?

LiteLoaderBDS可以让mc在不开启作弊的情况下也能使用指令，包括插件自定义指令，但这些指令的自动补全功能在不开作弊时却存在问题。

例如在不开作弊时，这两条命令的提示是这样的：
![s1](https://github.com/LiteLDev/LiteLoaderBDS/assets/11767189/cae39cc8-d6a0-4e80-bb8e-5333018241a6)
![p1](https://github.com/LiteLDev/LiteLoaderBDS/assets/11767189/289f6e08-fc8e-4cf1-a0b2-55ee82784b45)

开启作弊后，命令的提示是这样的：
![s2](https://github.com/LiteLDev/LiteLoaderBDS/assets/11767189/16f43074-e4c2-465a-91b5-434ce8d59c51)
![p2](https://github.com/LiteLDev/LiteLoaderBDS/assets/11767189/ec0d55f3-079b-47b8-8562-d89c51ad746b)

很明显不开作弊时的提示是不完整的。不知道这个问题是否可以解决。

**Comment by ShrBox** [comment]
客户端限制
