### ISSUE TITLE
停止发包后破坏方块无法触发PlayerDestroyEvent

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#1317]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.14.1

### BDS 版本

1.20.1.02

### 发生了什么?

停止发包后破坏方块无法触发PlayerDestroyEvent

### 复现此问题的步骤

1. 停止发包
2. 破坏方块
3. 恢复连接

**Comment by Dofes** [comment]
什么停止发包
?

**Comment by Hosiyume** [comment]
> 什么停止发包 ?

什么什么停止发包

**Comment by PA733** [comment]
您如何实现的“停止发包”（您在“复现此问题的步骤”提到）？
破坏方块后是否有恢复发包？
重进服务器后，方块是否确实在 没有触发 PlayerDestroyEvent 的情况下被破坏/消失？
