### ISSUE TITLE
onPlaceBlock问题

### ISSUE THREAD

**Issue by KINGANDWL** [LiteLDev/LiteLoader#1321]
### Exceptions module

ScriptEngine

### Operating System

Windows 11

### LiteLoader version

2.13.1

### BDS version

1.19.83

### What happened?

我看到已经有人汇报过onPlaceBlock这个问题了，但是我还是再提供一下问题的新发现，就是使用剑、木棍或者其他非方块物品时点击地面的方块时也会触发这个事件，希望有所帮助（手机基岩版）

**Comment by ShrBox** [comment]
我们不会维护旧版本
