### ISSUE TITLE
不再能在ServerStartedEvent中注册命令

### ISSUE THREAD

**Issue by Milvona** [LiteLDev/LiteLoader#1325]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows 11

### LiteLoader 版本

LiteLoaderBDS 2.15.0-dev.0+60c6b39

### BDS 版本

Version: 1.20.11.01(ProtocolVersion 594) with

### 发生了什么?

不再能在ServerStartedEvent中注册命令,注册则崩服，而在RegCmdEvent中无此现象

### 复现此问题的步骤

无

### 有关的日志/输出

```raw
无相关内容
```

### 插件列表

```raw
无干扰
```

**Comment by Yushu2606** [comment]
#1324

**Comment by ShrBox** [comment]
此问题讨论转至#1326

**Comment by dreamguxiang** [comment]
fixed #1327
