### ISSUE TITLE
不能在onServerStarted事件回调函数中调用setup()方法

### ISSUE THREAD

**Issue by minimouse0** [LiteLDev/LiteLoader#1326]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2022

### LiteLoader 版本

#3499

### BDS 版本

1.20.11

### 发生了什么?

```
mc.listen("onServerStarted", ()=>{
    const cmd = mc.newCommand("regcmdcrash", "此指令注册过程中将发生意外退出", PermType.Any);
    cmd.overload([]);
    cmd.setCallback(()=>{})
    //此处setup()方法造成意外退出
    cmd.setup()
})
```
运行这段代码服务端程序立即中止，没有任何异常输出
在我测试的50个插件中，造成异常退出的五个LLSE插件（`FreePvp`、`landEX`、`LLSECheckBag`、`Ranking`、旧版`PlayerSleepingPercentage`）中除了闭源被混淆的`PlayerSleepingPercentage`外，其他插件经查验均存在在onServerStarted事件回调函数中调用setup方法的情况。
此问题很可能与#1324 #1325有关

### 复现此问题的步骤

使用LLSE执行代码
```
mc.listen("onServerStarted", ()=>{
    const cmd = mc.newCommand("regcmdcrash", "此指令注册过程中将发生意外退出", PermType.Any);
    cmd.overload([]);
    cmd.setCallback(()=>{})
    //此处setup()方法造成意外退出
    cmd.setup()
})
```

### 有关的日志/输出

```raw
异常退出，没有任何输出程序便中止
```

**Comment by minimouse0** [comment]
#1325

**Comment by ShrBox** [comment]
其实本来就不应该在ServerStartedEvent中注册指令，DynamicCommand会自动在合适的时刻注册指令，猜测是1.20.11.01 Mojang对指令系统的改动让指令注册不能在ServerStartedEvent中进行了

**Comment by dreamguxiang** [comment]
fixed #1327
