### ISSUE TITLE
在未加载对应语言插件时，开启对应引擎的debug出现Unknown command

### ISSUE THREAD

**Issue by engsr6982** [LiteLDev/LiteLoader#1330]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2016

### LiteLoader 版本

2.15.0-beta.0+c96a2d8

### BDS 版本

1.20.11

### 发生了什么?

我在1.20.11想测试一个接口时输入jsdebug 出现未知命令

当然
jsdebug
luadebug
pydebug
都是Unknown command

LiteloaderBds版本是 预发布beta2

### 复现此问题的步骤

上述

### 有关的日志/输出

```raw
#
```

### 插件列表

```raw
#
```

**Comment by engsr6982** [comment]
如果未加载任何对应类型的插件，输入对应引擎的debug就会出现Unknown command

**Comment by ShrBox** [comment]
在未安装任何脚本语言插件时LLSE不会启动
