### ISSUE TITLE
受到的伤害在玩家穿戴防具时可能与实际值不一致

### ISSUE THREAD

**Issue by xinchenxpc** [LiteLDev/LiteLoader#1338]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows 10

### LiteLoader 版本

2.15.0

### BDS 版本

1.20.11.01

### 发生了什么?

在监听实体受伤事件时当玩家穿戴盔甲时出现了玩家受到的伤害与实际值不同

### 复现此问题的步骤

玩家穿戴盔甲
以穿戴有摔落保护的鞋子为例

摔落

监听
mc.listen("onMobHurt", (mob, _s, damage, _c) => {
    if (mob.isPlayer()) {
        let pl = mob.toPlayer();
        pl.tell("当前生命值"+pl.healthl);
        pl.tell("受到的伤害"+damage)
    }
});

**Comment by KobeBryant114514** [comment]
这玩意监听的本来就是初始伤害，不算任何伤害减免
