### ISSUE TITLE
ResourcePackRepository::setCustomResourcePackPath 无效

### ISSUE THREAD

**Issue by KobeBryant114514** [LiteLDev/LiteLoader#1354]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows Server 2022

### LiteLoader 版本

LL 2.16.1

### BDS 版本

1.20.30

### 发生了什么?

使用 LIAPI ResourcePackRepository::setCustomResourcePackPath 无效，无法正常加载资源包

### 复现此问题的步骤

1. 将任意资源包放入任意路径，使用 ResourcePackRepository::setCustomResourcePackPath 加载。
2. 正常编译插件。
3. 插件正常加载不报错，但是资源包未被正常加载。
4. 在LL 2.15.0使用同样方法编写插件并加载资源包，不会出现此问题。

### 有关的日志/输出

```raw
无日志，此bug无任何报错，但是功能不正常
```

**Comment by dreamguxiang** [comment]
fixed
