### ISSUE TITLE
NativeFunction hook异常

### ISSUE THREAD

**Issue by timiya233** [LiteLDev/LiteLoader#1365]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.16.2+d07a9ca

### BDS 版本

1.20.30.02

### 发生了什么?

Hook tick后如果卸载插件服务器会爆炸

![image](https://github.com/LiteLDev/LiteLoaderBDS/assets/70333491/30e1a84f-495c-4be0-9841-0972c7d47cb7)

### 复现此问题的步骤

代码:

![image](https://github.com/LiteLDev/LiteLoaderBDS/assets/70333491/db73944a-86b3-48c7-9568-6d050fabd2bf)

### 有关的日志/输出

![image](https://github.com/LiteLDev/LiteLoaderBDS/assets/70333491/95014091-5f05-403a-a926-784b6a4e42b5)

[trace_2023-10-07_15-33-48.log](https://github.com/LiteLDev/LiteLoaderBDS/files/12837091/trace_2023-10-07_15-33-48.log)

### 插件列表

![image](https://github.com/LiteLDev/LiteLoaderBDS/assets/70333491/035807be-c8cc-4fe0-9793-71ae10ce4240)

**Comment by ShrBox** [comment]
插件被卸载前应该unhook，但是LL2并没有卸载前事件与unhook功能，在LL3会得到解决

**Comment by timiya233** [comment]
> 插件被卸载前应该unhook，但是LL2并没有卸载前事件与unhook功能，在LL3会得到解决

好的，我建议在卸载插件的时候ll会自动unhook没有unhook的hook(狗头)
