### ISSUE TITLE
Function tr() does not format string

### ISSUE THREAD

**Issue by ScarletRedMan** [LiteLDev/LiteLoader#137]
**Describe the bug**
Function `tr()` does not format string from file. 

**To Reproduce**
Use function `tr()` and get message from file with formatting.
```cpp
tr("test.a", "sample string");
```
messages.json
```json
{
  "test.a": "This is a {0}."
}
```
Result: `This is a {0}.`

**Expected behavior**
Result: `This is a sample string.`

**Screenshots or log**
My code where I use it:
![My code](https://user-images.githubusercontent.com/54776640/147273254-9fdb2385-b88f-4c4c-9da0-71f3820b60d2.png)
File `messages.json`:
![messages.json](https://user-images.githubusercontent.com/54776640/147273370-a4c4593a-1982-495a-bb61-76b489d2e82c.png)
Result:
![Result](https://user-images.githubusercontent.com/54776640/147273528-be7cee44-c228-4b6c-862d-135d7697b491.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 (using Wine 5.0)
 - Version 2.0.3

**Additional context**
It did work in version 2.0.2-pre3, but in 2.0.3 doesn't work. Just recompiled project with new SDK.

**Comment by dreamguxiang** [comment]
Confirmed issue，Waiting to be repaired

**Comment by dreamguxiang** [comment]
![image](https://user-images.githubusercontent.com/62042544/147337954-25db2836-2bd6-4d65-86e6-b97da1f9a26c.png)
You can Comment here to temporarily solve

**Comment by yqs112358** [comment]
fixed
