### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by OEOTYAN** [LiteLDev/LiteLoader#1374]
- [x] 搬运大部分enums
- [x] 搬运大部分结构
- [x] 搬运大部分LLAPI
- [x] 可编译
- [x] 搬运 CompoundTag API
- [x] 重写 SNBT API
- [x] 重写 Command API
- [x] 重写 计分板 API
- [x] 重写 Player API
- [x] 重写 logger API
- [x] 重写 Event API
- [x] 重写 Schedule API
- [x] 增加 Config API
- [x] 重写 plugin manager
- [x] 搬运 剩下的event
- [x] 重写 playerdb
- [x] 增加 service
- [x] 重写 静态/动态命令注册
- [x] 重构 custom dimension manager - 必须自己写继承 + 发包替换tp
- [x] 重构 file action event - how?
- [x] 重构 form - 增加图片功能? 缩减冗余代码 优化性能
- [x] 重构 i18n logger - 增加编译期检测
- [x] 新的crowdin
- [x] 重写 ll插件管理指令
- [ ] 统计需要维护的头文件

以下虽然不是ll的功能，但是ll正式版发布前也要做好，否则用户体验不佳：
- [ ] LAC基本完成
- [ ] lip和lipui的安装包做好

**Comment by OEOTYAN** [comment]
勾选需要保留的event

- [ ] ArmorStandChangeEvent

- [ ] BlockChangedEvent
- [ ] BlockExplodedEvent
- [ ] BlockExplodeEvent
- [ ] BlockInteractedEvent
- [ ] BlockPlacedByPlayerEvent

- [ ] CmdBlockExecuteEvent

- [ ] ConsoleCmdEvent
- [ ] ConsoleOutputEvent

- [ ] ContainerChangeEvent

- [ ] EntityExplodeEvent
- [ ] EntityRideEvent
- [ ] EntityStepOnPressurePlateEvent
- [ ] EntityTransformEvent

- [ ] FarmLandDecayEvent

- [ ] FireSpreadEvent

- [ ] FormResponsePacketEvent

- [ ] MobDieEvent
- [ ] MobHurtEvent
- [ ] MobSpawnedEvent
- [ ] MobTrySpawnEvent

- [ ] PlayerAteEvent
- [ ] PlayerAttackBlockEvent
- [ ] PlayerAttackEvent
- [ ] PlayerBedEnterEvent
- [ ] PlayerChangeDimEvent
- [ ] PlayerChatEvent
- [ ] PlayerCloseContainerEvent
- [ ] PlayerCmdEvent
- [ ] PlayerConsumeTotemEvent
- [ ] PlayerDestroyBlockEvent
- [ ] PlayerDieEvent
- [ ] PlayerDropItemEvent
- [ ] PlayerEatEvent
- [ ] PlayerEffectChangedEvent
- [ ] PlayerExperienceAddEvent
- [ ] PlayerInteractEntityEvent
- [ ] PlayerInventoryChangeEvent
- [ ] PlayerJoinEvent
- [ ] PlayerJumpEvent
- [ ] PlayerLeftEvent
- [ ] PlayerOpenContainerEvent
- [ ] PlayerOpenContainerScreenEvent
- [ ] PlayerOpenInventoryEvent
- [ ] PlayerPickupItemEvent
- [ ] PlayerPlaceBlockEvent
- [ ] PlayerPreJoinEvent
- [ ] PlayerPullFishingHookEvent
- [ ] PlayerRespawnEvent
- [ ] PlayerScoreChangedEvent
- [ ] PlayerSetArmorEvent
- [ ] PlayerSneakEvent
- [ ] PlayerSprintEvent
- [ ] PlayerStartDestroyBlockEvent
- [ ] PlayerSwingEvent
- [ ] PlayerUseBucketEvent
- [ ] PlayerUseFrameBlockEvent
- [ ] PlayerUseItemEvent
- [ ] PlayerUseItemOnEvent
- [ ] PlayerUseRespawnAnchorEvent

- [ ] PostInitEvent

- [ ] ProjectileCreatedEvent
- [ ] ProjectileHitBlockEvent
- [ ] ProjectileHitEntityEvent
- [ ] ProjectileSpawnEvent

- [ ] RedStoneUpdateEvent

- [ ] HopperPushOutEvent
- [ ] HopperSearchItemEvent

- [ ] LiquidSpreadEvent

- [ ] PistonPushEvent
- [ ] PistonTryPushEvent

- [ ] RegCmdEvent

- [ ] ResourcePackInitEvent

- [ ] ScriptPluginManagerEvent

- [ ] ServerStartedEvent
- [ ] ServerStoppedEvent

- [ ] WitherBossDestroyEvent

**Comment by superwfox** [comment]
加油哇🌹

**Comment by RimuruChan** [comment]
看起来只剩命令了
