### ISSUE TITLE
[Feature]: Create a separate Linux version

### ISSUE THREAD

**Issue by zangxixi2012** [LiteLDev/LiteLoader#1387]
### Is your feature request related to a problem? Please describe.

I use emulators every time, which is very annoying. I want to have a formal Linux version

### Describe the solution you'd like

I want developers to independently create a Linux version

**Comment by ShrBox** [comment]
Right now we are short of developers, and even the Windows version is moving very slowly, so we have no plans to develop a Linux version.

**Comment by dreamguxiang** [comment]
#1442
