### ISSUE TITLE
make terminal can complete command and high-light

### ISSUE THREAD

**Issue by FTS427** [LiteLDev/LiteLoader#1388]
### Is your feature request related to a problem? Please describe.

When I'm typing command , it takes me more time to do.

### Describe the solution you'd like

I wonder that LL3 can complete commands and high-light commands like the PowerNukkitXServer

**Comment by OEOTYAN** [comment]
你可以试试写一个pr上来

**Comment by FTS427** [comment]
I have no time to make it these days, but I think this function is very useful for the server owners

How about completing this after LeviLamina is done?
