### ISSUE TITLE
update[Feature]: 

### ISSUE THREAD

**Issue by crowdedplus** [LiteLDev/LiteLoader#1389]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

there have been one month since last update, the new version has released for at least  2 weeks , hoping you guys update soon.

**Comment by crowdedplus** [comment]
lite loader BDS for 1.20.40 needed .

**Comment by yufengya0420** [comment]
LL已归档，不再更新，请等待LL3发布

**Comment by ShrBox** [comment]
https://bbs.liteldev.com/resources/glacie.96/
