### ISSUE TITLE
[Bug]: Missing field in DisconnectPacket

### ISSUE THREAD

**Issue by Intoprelised** [LiteLDev/LiteLoader#1391]
### Describe the bug

As of 1.20.40 the disconnect packet has gotten a new field added to it, I do not see it in the class

### To Reproduce

N/A

### Expected behavior

N/A

### Screenshots

N/A

### Additional context

The field is most likely a Connection::DisconnectFailReason, and there is a chance that your enum is outdated (could be wrong on that)

**Comment by dreamguxiang** [comment]
fixed
