### ISSUE TITLE
[Feature]: Custom world generator

### ISSUE THREAD

**Issue by MCBEPluginModer** [LiteLDev/LiteLoader#1396]
### Is your feature request related to a problem? Please describe.

Please add to LeviLamina custom world generator sample for new custom dimensions for base on WorldGenearte BDS class.

### Describe the solution you'd like

Please add to LeviLamina custom world generator sample for new custom dimensions for base on WorldGenearte BDS class.

**Comment by quizhizhe** [comment]
Do you mean to use the Vanilla Overworld, Nether and TheEnd generators? Receiving seed parameters?
I'm currently working on a custom dimension API that will be implemented in the future

**Comment by quizhizhe** [comment]
I'm currently working on a custom dimension API that will be implemented in the future

**Comment by quizhizhe** [comment]
Also, if you have an idea, please describe the requirements more clearly rather than posting other people's projects, I can't take the time to understand the detailed implementation of these projects

**Comment by MCBEPluginModer** [comment]
I am edit my issue.

**Comment by MCBEPluginModer** [comment]
> Also, if you have an idea, please describe the requirements more clearly rather than posting other people's projects, I can't take the time to understand the detailed implementation of these projects

i am edit issue

**Comment by MCBEPluginModer** [comment]
> Also, if you have an idea, please describe the requirements more clearly rather than posting other people's projects, I can't take the time to understand the detailed implementation of these projects

I mean writing a world generator from 0 based on the WorldGenerator class. If you give me your telegram, I can provide the code that needs to be finalized.
Can you please refine the code to remove the error of infinite world generation screen after calling TestDimension::_wrapStorageForVersionCompatibility?

**Comment by quizhizhe** [comment]
> > Also, if you have an idea, please describe the requirements more clearly rather than posting other people's projects, I can't take the time to understand the detailed implementation of these projects
> 
> I mean writing a world generator from 0 based on the WorldGenerator class. If you give me your telegram, I can provide the code that needs to be finalized. Can you please refine the code to remove the error of infinite world generation screen after calling TestDimension::_wrapStorageForVersionCompatibility?

The moreDimension in test is just a rough dimension registration process, and I have ignored many details, which is why it is flat type of world, because this is the simplest. However, for the complex world type of the original type Overworld, it is recommended to look at the build process of the BDS

BDS based WordGenerator I'm working on.

**Comment by MCBEPluginModer** [comment]
> The moreDimension in test is just a rough dimension registration process, and I have ignored many details, which is why it is flat type of world, because this is the simplest. However, for the complex world type of the original type Overworld, it is recommended to look at the build process of the BDS
> 
> BDS based WordGenerator I'm working on.

So the test measurement class is still in development? Is that why my generator won't allow me to generate a world?

**Comment by quizhizhe** [comment]
> > The moreDimension in test is just a rough dimension registration process, and I have ignored many details, which is why it is flat type of world, because this is the simplest. However, for the complex world type of the original type Overworld, it is recommended to look at the build process of the BDS
> > BDS based WordGenerator I'm working on.
> 
> So the test measurement class is still in development? Is that why my generator won't allow me to generate a world?

Yes, only the dimension creation part has been done, the generator has not been improved, and I will improve the virtual table of the generator in the future, but the custom generator API part is not considered at present.

**Comment by MCBEPluginModer** [comment]
> > > The moreDimension in test is just a rough dimension registration process, and I have ignored many details, which is why it is flat type of world, because this is the simplest. However, for the complex world type of the original type Overworld, it is recommended to look at the build process of the BDS
> > > BDS based WordGenerator I'm working on.
> > 
> > 
> > So the test measurement class is still in development? Is that why my generator won't allow me to generate a world?
> 
> Yes, only the dimension creation part has been done, the generator has not been improved, and I will improve the virtual table of the generator in the future, but the custom generator API part is not considered at present.

And when approximately to expect a custom generator?

**Comment by quizhizhe** [comment]
No this plan. Only the vanilla generator is available. I'll finish the generator's virtual table. You can inherit from the generator to customize the generator, but we don't provide an API

**Comment by MCBEPluginModer** [comment]
> No this plan. Only the vanilla generator is available. I'll finish the generator's virtual table. You can inherit from the generator to customize the generator, but we don't provide an API

Will I be able to use WorldGenerator in the future to write a custom world generator and use it for dimension?
