### ISSUE TITLE
[Feature]: 表单改善建议

### ISSUE THREAD

**Issue by Milvona** [LiteLDev/LiteLoader#1400]
### Is your feature request related to a problem? Please describe.

1.表单的图片加载需要对客户端发一个attribute等级数据包
2.CustomForm有图片项，需要单独拿出来
3.ServerSetting的的CustomForm表单变体
4.ServerSetting只有一个，需要并表
5.改善这个判断字符串来选择表单图片的方案

### Describe the solution you'd like

None

### Describe alternatives you've considered

None

### Additional context

None

**Comment by banchen19** [comment]
支持

**Comment by OEOTYAN** [comment]
大家的反馈是没太看懂你讲的，能不能再详细些呢？

**Comment by Milvona** [comment]
> 大家的反馈是没太看懂你讲的，能不能再详细些呢？

1.表单url图片加载瞬间，需要补充一个UpdateAttributesPacket,内容为玩家等级,发给客户端让他加载
2.CustomForm的json不完整，里面没有Icon的图片信息
3.ServerSettingsResponsePacket是一种表单数据包，也应该补充到表单中，但是只有一个，这个接口需要可叠加性
4.不要使用字符串判断来选择表单里是否有资源包图片(现有的判断方案)

**Comment by OEOTYAN** [comment]
没人搞，你pr吗，不pr就关了
