### ISSUE TITLE
[Bug]: Hangs when teleporting to a registered new dimension

### ISSUE THREAD

**Issue by MCBEPluginModer** [LiteLDev/LiteLoader#1406]
### Describe the bug

Hangs when teleporting to a registered new dimension after registration.

### To Reproduce

Hangs when teleporting to a registered new dimension after registration.

### Expected behavior

Hangs when teleporting to a registered new dimension after registration.

### Screenshots

![image](https://github.com/LiteLDev/LeviLamina/assets/86790039/c79d1f2e-d876-4ffc-a2bb-428b99507220)

### Platform

Windows 10

### Version

feature/customdim

**Comment by MCBEPluginModer** [comment]
Not work this code:
![image](https://github.com/LiteLDev/LeviLamina/assets/86790039/1d8624a4-0649-40a6-878b-c907547cfe83)
This function not called!

**Comment by MCBEPluginModer** [comment]
Not called getDimensionFactory

**Comment by quizhizhe** [comment]
Thank you for submitting the issue, but please do not test on unfinished features.
