### ISSUE TITLE
[Bug]: 使用lip获取失败，提示不是一个有效的ZipFile。

### ISSUE THREAD

**Issue by Akanyi** [LiteLDev/LiteLoader#1407]
### Describe the bug

下载牙齿和解决依赖关系。
下载github.com/tooth-hub/levilamina@1.0.
错误：解析和下载说明符字符串列表失败：安装说明符失败：创建存档失败：打开存档失败：zip：不是一个有效的zip文件

### To Reproduce

使用lipUI/Lip下载levilamina。

### Expected behavior

我不清楚是lip的问题，还是lamina这边的问题，希望可以解决。

### Platform

Windows10 专业版

**Comment by OEOTYAN** [comment]
我们没有发过1.0
