### ISSUE TITLE
[Bug]: SerializedSkin & mce::Image structures outdated

### ISSUE THREAD

**Issue by Intoprelised** [LiteLDev/LiteLoader#1409]
### Describe the bug

The fields for SerializedSkin (probably due to mce::image changing) and mce::Image have been updated from 1.20.40-1.20.50. It is possible that the changed in SerializedSkin just result from the changes in mce::Image. One more thing I would like to add is, to properly configure entt it is good to also set the packed page size

### To Reproduce

N/A

### Expected behavior

N/A

### Screenshots

N/A

**Comment by OEOTYAN** [comment]
The page size is set in EntityId.h. For mce::Image we should fix it later. We're currently short-staffed, though, and some of us are busy exporting function parameter names, so if you could submit a PR that would be great!

**Comment by Intoprelised** [comment]
https://github.com/LiteLDev/LeviLamina/pull/1411

**Comment by ZeroMemes** [comment]
> The page size is set in EntityId.h. For mce::Image we should fix it later. We're currently short-staffed, though, and some of us are busy exporting function parameter names, so if you could submit a PR that would be great!

I've opened a separate issue that documents the specifics of the page_size issue @Intoprelised is referring to (#1412)
