### ISSUE TITLE
[Bug]: mce::Image is not updated to 1.20.5x

### ISSUE THREAD

**Issue by FloppyDolphin57** [LiteLDev/LiteLoader#1410]
### Describe the bug

Title

### To Reproduce

.

### Expected behavior

.

**Comment by OEOTYAN** [comment]
Thanks for the report, but this issue is a duplicate of #1409 .

**Comment by FloppyDolphin57** [comment]
> Thanks for the report, but this issue is a duplicate of #1409 .

Is there some place I can get in contact with you? Such as discord or telegram.

**Comment by Intoprelised** [comment]
me too

**Comment by OEOTYAN** [comment]
Theoretically, you could @OEOTYAN in LL's discord server, but I probably won't be checking that information very often, and it's probably better to communicate with the other main maintainers.
