### ISSUE TITLE
[Bug]: Levilamina run

### ISSUE THREAD

**Issue by elemen1069** [LiteLDev/LiteLoader#1414]
### Describe the bug

I ran the lip install github.com/tooth-hub/levilamina command in an empty file and ran bedrockservermod.exe, but levilamina does not run.
18:05:23 ERROR [PreLoader] Can't load LeviLamina.dll !
18:05:23 ERROR [PreLoader] Error code: 127 !
18:05:23 ERROR [PreLoader] The specified procedure could not be found.

### To Reproduce

Run this command lip install github.com/tooth-hub/levilamina in an empty file and run bedrock_server_mod.exe

### Expected behavior

none

### Screenshots

none

### Platform

windows 11 pro

### Version

0.2.0

### Additional context

none

**Comment by futrime** [comment]
Fixed with version 0.2.1
