### ISSUE TITLE
[Bug]: Can't load LiteLoader.dll

### ISSUE THREAD

**Issue by xu-haozhe** [LiteLDev/LiteLoader#1416]
### Describe the bug

运行服务器时出现
`16:38:39 ERROR [PreLoader] Can't load LiteLoader.dll !
16:38:39 ERROR [PreLoader] Error code: 127 !
16:38:39 ERROR [PreLoader] 找不到指定的程序。

16:38:39 INFO [PreLoader] PreLoader is running as DLL Loader...
16:38:39 ERROR [PreLoader] Fail to load plugin [LLMoney.dll]
16:38:39 ERROR [PreLoader] Error: Code[127]`

并且无法加载插件

### To Reproduce

安装bedrock-server-1.20.51.01和ll
以管理员身份运行PeEditor.exe
以管理员身份运行bedrock_server_mod.exe
出现错误

### Expected behavior

- 成功加载 LiteLoader.dll
- 加载其他插件

### Platform

Windows 11 专业工作站版

### Version

LiteLoaderBDSv2 2.16.2

### Additional context

设备名称	DESKTOP-6T6FP9U
处理器	12th Gen Intel(R) Core(TM) i5-1240P   1.70 GHz
机带 RAM	32.0 GB (31.8 GB 可用)
设备 ID	6D7A8B75-09C1-4BDA-B3FD-FFEFCCF53E5F
产品 ID	00391-70000-00000-AA260
系统类型	64 位操作系统, 基于 x64 的处理器

 版本	Windows 11 专业工作站版
版本	23H2
安装日期	‎2023/‎12/‎17
操作系统版本	22631.2861
体验	Windows Feature Experience Pack 1000.22681.1000.0

**Comment by CoolLoong** [comment]
你需要运行`PeEditor.exe -m -n`

**Comment by ShrBox** [comment]
本仓库为LeviLamina仓库，不再接受来自LiteLoaderBDS的反馈
顺带一提，LiteLoaderBDS支持的最新BDS版本为1.20.31
