### ISSUE TITLE
[Bug]: Wine: Call from 00006FFFFFC63D47 to unimplemented function msvcp140_atomic_wait.dll.__std_calloc_crt, aborting

### ISSUE THREAD

**Issue by ihsanharh** [LiteLDev/LiteLoader#1417]
### Describe the bug

trying to run the docker version on Ubuntu server 22.04, but it throws error, executing script from the docs https://levilamina.liteldev.com/install/install_docker/

### To Reproduce

1. execute ` docker run -d -it -e EULA=TRUE -p 19132:19132/udp -v levilamina-server-data:/data ghcr.io/liteldev/levilamina-server `
2. will throw ` wine: Call from 00006FFFFFC63D47 to unimplemented function msvcp140_atomic_wait.dll.__std_calloc_crt, aborting `

### Expected behavior

docker run successfully

### Screenshots

![IMG_20240102_133650](https://github.com/LiteLDev/LeviLamina/assets/75160414/977c1241-60ae-4f93-994b-d60bd5b677cc)

### Platform

Ubuntu 22.04

### Version

latest

### Additional context

wine --version:  `wine-8.0.2`

**Comment by anchogin** [comment]
+1，也遇到这个问题

**Comment by KawaiiNahida** [comment]
workaround has been pushed
related issue: [Microsoft/STL#2446](https://github.com/microsoft/STL/issues/2446)

**Comment by pierr3** [comment]
@KawaiiNahida Facing the same issue in an unrelated software, could I ask what workaround you ended up adopting?
