### ISSUE TITLE
[Bug]: 配置文件配置端口失效

### ISSUE THREAD

**Issue by maluyaotop** [LiteLDev/LiteLoader#1418]
### Describe the bug

我将bds自带的server.properties修改为
server-port=19100和
server-portv6=19101
之后，启动之后日志是这样的：
19:57:23.606 INFO [Server] IPv4 supported, port: 19100: Used for gameplay
19:57:23.606 INFO [Server] IPv6 supported, port: 19101: Used for gameplay
19:57:23.646 INFO [Server] Server started in (1.5s)! For help, type "help" or "?"
19:57:23.646 INFO [Server] ================ TELEMETRY MESSAGE ===================
19:57:23.646 INFO [Server] Server Telemetry is currently not enabled.
19:57:23.646 INFO [Server] Enabling this telemetry helps us improve the game.
19:57:23.646 INFO [Server]
19:57:23.646 INFO [Server] To enable this feature, add the line 'emit-server-telemetry=true'
19:57:23.647 INFO [Server] to the server.properties file in the handheld/src-server directory
19:57:23.647 INFO [Server] ======================================================
19:57:23.732 INFO [Server] IPv4 supported, port: 19132 used for LAN discovery
19:57:23.732 INFO [Server] IPv6 supported, port: 19133
不知道这是特意为之还是遗留的啥
然后端口冲突的话，服务器会直接闪退，没有任何提示

### To Reproduce

首先`lip install github.com/tooth-hub/levilamina`
然后开一个原版服务器占用19132端口
然后启动`bedrock_server_mod.exe`
发现服务器直接闪退，修改配置文件也没用

### Expected behavior

服务器闪退

### Screenshots

<img width="1280" alt="Snipaste_2024-01-02_20-17-04" src="https://github.com/LiteLDev/LeviLamina/assets/128664105/f1c0b8d0-0699-46e1-a3a1-77dbb3edddfb">

**Comment by ShrBox** [comment]
这是BDS自带的特性，与LeviLamina无关

**Comment by MLuYao** [comment]
不是把

**Comment by MLuYao** [comment]
原版没问题啊

**Comment by maluyaotop** [comment]
我的问题
