### ISSUE TITLE
[Feature]: 补全mc/enums中SignTextSide与Side的枚举类型

### ISSUE THREAD

**Issue by lostDeers** [LiteLDev/LiteLoader#1426]
### Is your feature request related to a problem? Please describe.

补全mc/enums中SignTextSide与Side的枚举类型，使得其能在相关的API（如SignBlockActor）中能够正常方便地使用。

### Describe the solution you'd like

将`mc/enums/SignTextSide.h`与`mc/enums/Side.h`中缺失的枚举值补全。

**Comment by ShrBox** [comment]
Added in 2225ecff5a48c2db1690e256ac653984d63c4905
