### ISSUE TITLE
Plugin that uses RegCommandAPI doesn't work.

### ISSUE THREAD

**Issue by KocTu4eK** [LiteLDev/LiteLoader#143]
I tried to #include in the project different headers related to commands, but nothing helped.

Error:
![image](https://user-images.githubusercontent.com/84087988/147575475-31850606-29bd-47b9-97ec-be6b1388fdcc.png)

Plugin.cpp & pch.h & dllmain.cpp:
![image](https://user-images.githubusercontent.com/84087988/147573855-f32c373f-1e9f-4058-867f-277c1dbff165.png)
![image](https://user-images.githubusercontent.com/84087988/147573888-c1b2710a-9462-4fb4-bbaa-3dde5a81880f.png)
![image](https://user-images.githubusercontent.com/84087988/147575647-26c70ce8-3844-4a98-b7c7-5080b51ea47c.png)

My project properties:
![image](https://user-images.githubusercontent.com/84087988/147574986-305bda0b-4142-4dec-b07e-a7c7950bbc30.png)
![image](https://user-images.githubusercontent.com/84087988/147575011-181b5527-c6da-42f7-a06c-ecdf5b40e7fe.png)
![image](https://user-images.githubusercontent.com/84087988/147575036-44ae8065-8550-43f9-bd5c-fff484b1a182.png)
![image](https://user-images.githubusercontent.com/84087988/147575082-062c17dc-f7e2-4d3d-abd9-b1a2a9518c83.png)

 - OS: [Windows 10]
 - LiteLoader: [2.0.3]
 - BDS: [1.18.2.03]

If I load some plugin of my friend that using RegCommandAPI, then it works. But if I compile the same plugin of my friend on my PC, the plugin stops loading.

**Comment by dreamguxiang** [comment]
![image](https://user-images.githubusercontent.com/62042544/147576767-380bf0cd-8af6-45f6-a836-2592be9bbd04.png)Did you do this step

**Comment by dreamguxiang** [comment]
![image](https://user-images.githubusercontent.com/62042544/147576897-905293c7-1d68-46f5-934a-4aa51eefa608.png)

**Comment by KocTu4eK** [comment]
I don't know where to get this dll...
or is it enough to just write it there?

**Comment by dreamguxiang** [comment]
Just write there

**Comment by KocTu4eK** [comment]
and it worked. thx!

**Comment by dreamguxiang** [comment]
This is a fake dll
