### ISSUE TITLE
[Bug]: 😲 Plugin does not load 😲

### ISSUE THREAD

**Issue by elemen1069** [LiteLDev/LiteLoader#1437]
### Describe the bug

If you create a plugin and apply the plugin and then run the server, an error will appear saying the plugin has not been applied.

### To Reproduce

After updating the server to 0.5.0, when I create a plugin, run xmake, apply it, and run the server, it says the plugin has not been loaded.

### Expected behavior

Um... I'm not sure..

### Screenshots

![image](https://github.com/LiteLDev/LeviLamina/assets/124027876/52095a22-a3ac-4959-ab09-3ab25337b58e)
![image](https://github.com/LiteLDev/LeviLamina/assets/124027876/44f23ba2-1736-42ab-89da-573bcdc9bc7e)
![image](https://github.com/LiteLDev/LeviLamina/assets/124027876/66caf8f8-da6a-48af-8c55-6a89ab96b7b4)
![image](https://github.com/LiteLDev/LeviLamina/assets/124027876/ced1ff77-76e5-4510-ba55-d66787c475f6)
![image](https://github.com/LiteLDev/LeviLamina/assets/124027876/b7ce4ab0-9b68-4f9b-a642-67256997ff59)

### Platform

windows 11 pro

### Version

0.5.0

### Additional context

**I hope it gets resolved quickly... Thank you for your hard work!!**  ❤️❤️

**Comment by OEOTYAN** [comment]
your server is 0.4.0

**Comment by Dofes** [comment]
please update your server's ll version

**Comment by elemen1069** [comment]
![image](https://github.com/LiteLDev/LeviLamina/assets/124027876/703582ec-aa9f-48a5-8b73-94f38aa2f0bf)

I already update..
