### ISSUE TITLE
[Bug]: LeviLamina failed to parse CustomForm result

### ISSUE THREAD

**Issue by lostDeers** [LiteLDev/LiteLoader#1441]
### Describe the bug

I try to send a CustomForm to player in an event.
When I run LeviLamina with the plugin and trigger this event, I got an error.
```
ERROR [LeviLamina] Failed to parse CustomForm result
```

### To Reproduce

test code:
```
auto form = ll::form::CustomForm("form");
form.appendInput("item_name", "Item Name", ".", "");
form.appendInput("item_detail", "Item Detail");
form.sendTo(player,...callback);
```

### Expected behavior

Parse the correct result and send it to callback function.

**Comment by Dofes** [comment]
can it still be reproduced in the latest version?

**Comment by lostDeers** [comment]
It has been fixed.
