### ISSUE TITLE
[Bug]: 在控制台的help指令使服务器崩溃

### ISSUE THREAD

**Issue by DJRsiri** [LiteLDev/LiteLoader#1449]
### Describe the bug

当“server.properties”（即服务器配置文件）里添加op-permission-level=4（或者是1到3）后，在服务器控制台中输入help （或 ? ）导致服务器崩溃。

该bug在玩家上的测试：无。

### To Reproduce

1. 打开 server.properties
2. 添加 op-permission-level=4 在新的一行
3. 启动 bedrock_server_mod.exe
4. 输入 help
5. 输出 BDS Crashed! （服务器崩溃）

### Expected behavior

修复此bug

### Screenshots

dmp file：
[minidump_2024-01-29_23-57-46.dmp](https://github.com/LiteLDev/LeviLamina/files/14086928/minidump_2024-01-29_23-57-46.dmp)
Screenshots：
![20240130001953](https://github.com/LiteLDev/LeviLamina/assets/147926791/77e19a44-ceaf-4f83-bfdd-59ae8bb26926)

### Platform

Windows 10 专业版 22H2 19045.3324

### Version

Server Version: 1.20.51.01(ProtocolVersion 630) with LeviLamina-0.4.2+8e8c429

**Comment by ShrBox** [comment]
0.4.2过于久远，请尝试在0.6.2上复现

**Comment by DJRsiri** [comment]
> 0.4.2过于久远，请尝试在0.6.2上复现

16:12:03.835 INFO [Server] Version: 1.20.51.01(ProtocolVersion 630) with LeviLamina-0.6.2+dbbb01e05
仍然导致服务器崩溃

**Comment by xianyubb** [comment]
`help ll` 这个命令也会崩

**Comment by quizhizhe** [comment]
已定位问题，由于此位置被注释
https://github.com/LiteLDev/LeviLamina/blob/ef28f8b94553413b0e6686adb9b4bf33b18e714c/src/ll/core/tweak/BuiltinCommands.cpp#L390
导致下面使用的枚举
https://github.com/LiteLDev/LeviLamina/blob/8db100a2d21b33589f161e05c1da8cb32a0c9e0a/src/ll/core/tweak/BuiltinCommands.cpp#L487
无法获取导致崩溃
