### ISSUE TITLE
When I use 'help' command in console,BDS crashed.

### ISSUE THREAD

**Issue by BensonChen2456** [LiteLDev/LiteLoader#1452]
### Describe the bug

When I use 'help' command in console,bds crashed.
LeviLamina Version:0.6.3
bds Version :1.20.50.01

### To Reproduce

>help
BDS Crashed!

### Expected behavior

LeviLamina will run 'help' command in a correct way,but not crash the server.

### Platform

Windows 11

### Version

BDS1.20.51.01 with LeviLamina0.6.3

### Additional context

Nothing anymore

**Comment by TukangM** [comment]
i so have this probem on 0.4.0. 1.20.51. i have test if execute `help` command after server afk 2 days then crashed if type `help`

**Comment by TukangM** [comment]
![image](https://github.com/LiteLDev/LeviLamina/assets/91467886/562d57ef-c066-43ed-9dea-980d9df46d48)
i'm wanna update to 0.7.0 but i seeing new update so i'm waiting git action done

**Comment by zCN24** [comment]
This Bug has been fixed, you just need to update LeviLamina to version 0.7.2
