### ISSUE TITLE
[Feature]: Add support to Minecraft BDS preview/beta Edition

### ISSUE THREAD

**Issue by MLCraftKaiKai** [LiteLDev/LiteLoader#1453]
### Is your feature request related to a problem? Please describe.

Add support to Minecraft BDS preview/beta Edition，So that players can experience the beta game content as soon as possible.

### Describe the solution you'd like

Create a new LeviLamina Beta project that supports the latest beta protocol, all other code remains unchanged

**Comment by BensonChen2456** [comment]
Support you

**Comment by Dofes** [comment]
That's hard for both lldev and other plugin devs
if u really wanna mod the preview edition, u can use preloader to launch ur server.
