### ISSUE TITLE
Adapt to 1.20.60

### ISSUE THREAD

**Issue by xiaoheiCat** [LiteLDev/LiteLoader#1455]
### Describe the bug

1.20.60 is now released but LeviLamina does not support

### To Reproduce

Run 1.20.60 bds server but PreLoader throw an error

### Expected behavior

Run 1.20.60 bds server with LeviLamina normally

### Platform

Windows 10

### Version

BDS 1.20.61 / latest LeviLamina when post this issue

**Comment by xiaoheiCat** [comment]
Finally I finished build of my server with LeviLamina but mojang soon updated that I cannot play it because my Apple App Store updated my Mineraft to version of 1.20.60 :I

**Comment by futrime** [comment]
Not adapted to BDS 1.20.60 yet. Please wait patiently.

**Comment by RimuruChan** [comment]
We are currently upgrading our toolchain to reduce unk functions.

**Comment by RainoutOvO** [comment]
Waiting as well, Microsoft Store has also updated my MC version automatically.

**Comment by Intoprelised** [comment]
> We are currently upgrading our toolchain to reduce unk functions.

id assume u guys know this but for vtables the linux server gives functions that don't exist/got replaced in the windows one

**Comment by RimuruChan** [comment]
@Intoprelised Yeah, we knew that. We are currently working on this.
