### ISSUE TITLE
[Feature]: Please create an npm module for LegacyScriptEngine

### ISSUE THREAD

**Issue by elemen1069** [LiteLDev/LiteLoader#1456]
### Is your feature request related to a problem? Please describe.

I create a plug-in with Quick-js while using the visual studio code program, but it is very inconvenient because auto-completion is not performed when creating the plug-in.
To make it a little easier, please create an npm module and make it auto-complete.

### Describe the solution you'd like

Please create an autocomplete npm module.

### Describe alternatives you've considered

Or, use the Visual Studio code extension to create an autocompletion function for the Lagasy script engine.

**Comment by futrime** [comment]
See https://github.com/LiteLDev/LiteLoaderSE-Aids
