### ISSUE TITLE
[Feature]:  AutoSync Release to LiteLDev/xmake-repo

### ISSUE THREAD

**Issue by Hopeeia** [LiteLDev/LiteLoader#1464]
### Is your feature request related to a problem? Please describe.

it's too slow to wait the dev update version in [xmake.lua](https://github.com/LiteLDev/xmake-repo/blob/main/packages/l/levilamina/xmake.lua). Is there any way to sync over github action/workflow ?

### Describe the solution you'd like

Maybe Github Action

**Comment by futrime** [comment]
Yes, we will make that in GitHub Actions later.

**Comment by RimuruChan** [comment]
We are sorry, but due to multiple factors, it's hard to make it full automated.
We will update as quickly as possible.
If you want to use latest develop version of LeviLamina, you can use
```lua
add_requires("bdslibrary <coresponding version>")
add_requires("levilamina develop")
```
and add them to your project.
