### ISSUE TITLE
[Proposal]: Add support Protocol in every release

### ISSUE THREAD

**Issue by LiteZero** [LiteLDev/LiteLoader#1467]
I hope you will include the protocol number supported by that version in the introductory file of each build, like LiteLoaderBDS v2, which will help some automated deployers to get the BDS version number supported by that version and help the users. tks :)

**Comment by harry-xi** [comment]
You can try to get this information from `tooth.json`
Check the version of the dependency `github.com/LiteLDev/bds` in the `dependencies` field.
In fact, we have a package manager that can be used to automate the installation of LeviLamina and its dependencies, and its github repository is https://github.com/lippkg/lip

**Comment by LiteZero** [comment]
OK.Thanks 👍
