### ISSUE TITLE
[Bug]: I cannot get bedrock_server_mod.exe

### ISSUE THREAD

**Issue by LucGamesYT** [LiteLDev/LiteLoader#1468]
### Describe the bug

I have installed and executed everything as described in the description and only get the normal server without the bedrock_server_mod.exe

### To Reproduce

Install the project step by step from the readme.md

### Expected behavior

Creating a bedrock_server_mod.exe

### Screenshots

![image](https://github.com/LiteLDev/LeviLamina/assets/19286296/d4cfc76c-04a4-43b5-be82-4e7dd1a464d4)

### Platform

Windows 11

### Version

0.8.1

**Comment by Dofes** [comment]
where is the peeditor.exe?
Please read the document of how to install the Levilamina, or use the lip to install.
https://levilamina.liteldev.com/install/
https://levilamina.liteldev.com/install/#install-via-lip
