### ISSUE TITLE
Is it possible to add a similar overload for the command?

### ISSUE THREAD

**Issue by KocTu4eK** [LiteLDev/LiteLoader#147]
Is it possible to add an argument like this "add" and "stop" to the command overload?
![image](https://user-images.githubusercontent.com/84087988/147819147-36d15b85-0bce-4b4c-a0ec-6144407e26a2.png)

**Comment by Jaciezyt** [comment]
Certainly you can add an enum argument

**Comment by Jaciezyt** [comment]
Maybe #115 can help you

**Comment by KocTu4eK** [comment]
No, you misunderstood me. I meant no <name: type> argument, just text like "add" and "stop".

**Comment by Jaciezyt** [comment]
argument <op: string>?

**Comment by KocTu4eK** [comment]
for example, the camerashake command has two overloads: the first "add" and the second "stop".
"add" and "stop" do not have <op: string>, they are just text without <> and [].
![image](https://user-images.githubusercontent.com/84087988/147820162-44e9a887-2156-4cf1-8357-06d91cba2c07.png)

**Comment by dreamguxiang** [comment]
This may not be possible

**Comment by dreamguxiang** [comment]
For example, MC's /gametest is the same,
![image](https://user-images.githubusercontent.com/62042544/147822026-2daff749-9fb5-4b63-8446-27248330e088.png)

**Comment by KocTu4eK** [comment]
I hope there is a way, because without this it is impossible to beautifully implement different functionality for one team.

**Comment by dreamguxiang** [comment]
![image](https://user-images.githubusercontent.com/62042544/147822921-47130167-9d9a-4d3c-951f-bcae26f33c37.png)
this?
![image](https://user-images.githubusercontent.com/62042544/147822934-ac9518fe-8591-4d8b-8380-1836acfda668.png)

**Comment by dreamguxiang** [comment]
![image](https://user-images.githubusercontent.com/62042544/147823593-a7f1bfde-d110-448f-a6ef-3f635da98ab1.png)
You can refer to this paragraph

**Comment by KocTu4eK** [comment]
yes, thanks! I'll try it now

**Comment by KocTu4eK** [comment]
seems to work, but very strange.

here is my command:
![image](https://user-images.githubusercontent.com/84087988/147827894-b3fc0123-8b99-4cda-bc72-2dec2e2bc06b.png)
![image](https://user-images.githubusercontent.com/84087988/147828264-ffcf1481-0152-4acf-b40c-50dd6e77de74.png)

and whatever I enter, the parser throws me on the inspect overload:
![image](https://user-images.githubusercontent.com/84087988/147828202-6cf43103-f883-4d51-ae40-075084b9c4eb.png)
![image](https://user-images.githubusercontent.com/84087988/147828240-97aa30fd-655b-4970-af7c-aa4e4024be9f.png)

Upd: I guess the parser has priority for short commands ...

**Comment by dreamguxiang** [comment]
With two String, BDS can't tell if it's the first or the second. This is no longer part of the LL discussion.

**Comment by dreamguxiang** [comment]
Please use back to enum, this may also be the reason why BDS uses that method internally

Sorry I couldn't help you.

**Comment by KocTu4eK** [comment]
thanks for trying to help.

I hope that soon it will be possible to add something like "names" to overloads, like add & stop in camerashake, etc.

**Comment by xiaoqch** [comment]
> No, you misunderstood me. I meant no <name: type> argument, just text like "add" and "stop".

you should call CommandParameterData::addOptions() 
for example:
![image](https://user-images.githubusercontent.com/37901097/147830494-0a896ab4-c245-4e45-85c2-f23bcd15c349.png)

**Comment by KocTu4eK** [comment]
I'll now try it

**Comment by KocTu4eK** [comment]
what is the CommandParameterOption? what heading is it in?

**Comment by dreamguxiang** [comment]
add enum CommandParameterOption in your code

**Comment by KocTu4eK** [comment]
ok, but it doesn't solve my current parsing problem.
or am I missing something?

**Comment by KawaiiNahida** [comment]
- [ ] [TODO] BDS CommandRegistery API Docs

**Comment by KocTu4eK** [comment]
Sorry i didn't get the gist of addOptions() yesterday.
Today I figured out what you advised me, and everything works, thanks!
I think the question can be closed (but the documentation for the CommandRegistry API will still be useful).

![image](https://user-images.githubusercontent.com/84087988/147882011-b873e72f-cc86-4ba3-8012-008d685c7a93.png)

**Comment by dreamguxiang** [comment]
Thank you for your reply. Documentation will be available as soon as possible

**Comment by MCBEPluginModer** [comment]
> Thank you for your reply. Documentation will be available as soon as possible

How to make the parser work adequately with different arguments in 2 overloads?
For example:
/cmd <string>
/cmd enum
And if I enter /cmd enum, then it would choose enum, and not the first overload option?
