### ISSUE TITLE
关于resourcePackEncryptionMap

### ISSUE THREAD

**Issue by panjj95** [LiteLDev/LiteLoader#1471]
已加密的资源包，在LeviLamina的config文件上填写正确的，uuid和密钥，进入游戏内发现不能正常显示，就像没解密一样，换上没密的资源包，则正常显示

**Comment by ShrBox** [comment]
该功能尚未实现，并且在未来也不会在LeviLamina中实现
该功能在未来会由单独的插件提供

**Comment by ShrBox** [comment]
已经做成单独的插件了
https://lippkg.com/ShrBox/ResourcePackEncryption/0.1.0
