### ISSUE TITLE
[Bug]: v0.8.4无法使用

### ISSUE THREAD

**Issue by FishCMD** [LiteLDev/LiteLoader#1474]
### Describe the bug

levilamina0.8.4版本无法使用，服务器启动失败
相同目录将LeviLamina.dll换成0.8.3版本就可以正常启动

### To Reproduce

运行bds levilamina0.8.4

### Expected behavior

服务器正常启动

### Screenshots

报错截图：
![79223ec3ac4bfd8943101ba2030f2626](https://github.com/LiteLDev/LeviLamina/assets/54362633/035920e4-59f6-44f6-8568-5de8d3e8c9b3)

其他插件版本：
![image](https://github.com/LiteLDev/LeviLamina/assets/54362633/b98e521f-55db-40a5-8007-edb82306d993)

### Platform

Windows 10

### Version

0.8.4

**Comment by ShrBox** [comment]
请尝试删除`plugins\LeviLamina\config\config.json`

**Comment by FishCMD** [comment]
> 请尝试删除`plugins\LeviLamina\config\config.json`

还是不行

**Comment by ShrBox** [comment]
尝试安装最新的Microsoft Visual C++ Redistributable？
https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by futrime** [comment]
Cannot reproduce.
![image](https://github.com/LiteLDev/LeviLamina/assets/35801754/1cfe646d-57d4-4ca2-a50a-add441f15c22)

**Comment by FishCMD** [comment]
> 尝试安装最新的Microsoft Visual C++ Redistributable？ https://aka.ms/vs/17/release/vc_redist.x64.exe

解决了，感谢
