### ISSUE TITLE
wine Startup failure reported an error.

### ISSUE THREAD

**Issue by kabaka9527** [LiteLDev/LiteLoader#1475]
### Describe the bug

wine bedrock_server_mod.exe
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
008c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
008c:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
008c:err:systray:initialize_systray Could not create tray window
13:01:59.712 INFO [PreLoader]
 Loading symbols from pdb...                                                    13:02:09.093 INFO [PreLoa
der] Loaded 597772 symbols                                                      13:02:09.095 INFO [PreLoa
der] Loading Reverse Lookup Table                                               13:02:09.310 ERROR [PreLoader] Can'
t load LeviLamina.dll                                                           13:02:09.311 ERROR [PreLoader] Erro
r code: 998                                                                     13:02:09.313 ERROR [PreLoader] 无 法 访 问
内 存 位 置 。                                                                       13:02:09.314 ERROR [PreLoader] Fail
 to load LeviLamina. Exiting...

### To Reproduce

wine-9.0
Use lip to download the package and start error reporting.

### Expected behavior

Successfully started

### Platform

Debian12，wine-9.0

### Version

0.9.0

**Comment by CsVeryLoveXieWenLi** [comment]
**自己手动安装试试？不用LIP，我是没问题的，Debian11。**

**Comment by kabaka9527** [comment]
> **自己手动安装试试？不用LIP，我是没问题的，Debian11。**

还是这样

**Comment by futrime** [comment]
Can you provide all logs including those generated during installing?

**Comment by kabaka9527** [comment]
> Can you provide all logs including those generated during installing?

Refers to the log that generated the mod core?

**Comment by kabaka9527** [comment]
> **自己手动安装试试？不用LIP，我是没问题的，Debian11。**

谢谢你，可以了

**Comment by kabaka9527** [comment]
> **自己手动安装试试？不用LIP，我是没问题的，Debian11。**

谢谢你，Debian11可以，就是有点卡控制台
![Screenshot_2024-02-27-18-29-49-453_com.server.auditor.ssh.client-edit.jpg](https://github.com/LiteLDev/LeviLamina/assets/142149737/7a7cae2d-6f3c-495b-aa13-3f4c13363cf5)

**Comment by kabaka9527** [comment]
貌似实测Debian11用lip也可以用，就是还是卡控制台

**Comment by futrime** [comment]
On Linux we recommend getting started with our official Docker image. See docker-levilamina-server repo

**Comment by kabaka9527** [comment]
> On Linux we recommend getting started with our official Docker image. See docker-levilamina-server repo

Yes, I followed the wine part of the docker tutorial, but the console still can't input instructions, no matter what instructions.
![Screenshot_2024-02-28-21-06-49-762_com.server.auditor.ssh.client-edit.jpg](https://github.com/LiteLDev/LeviLamina/assets/142149737/547b1fe7-c566-4656-a214-5551223c74bb)

**Comment by kabaka9527** [comment]
> > On Linux we recommend getting started with our official Docker image. See docker-levilamina-server repo
> 
> Yes, I followed the wine part of the docker tutorial, but the console still can't input instructions, no matter what instructions.
> ![Screenshot_2024-02-28-21-06-49-762_com.server.auditor.ssh.client-edit.jpg](https://github.com/LiteLDev/LeviLamina/assets/142149737/547b1fe7-c566-4656-a214-5551223c74bb)
> 
> 

Console input help no feedback, input? The feedback is as follows
```
024c:err:msvcrt:read_i got odd number of bytes in UTF16 mode
```

```
```

**Comment by kabaka9527** [comment]
Is this a wine feature?

**Comment by Yushu2606** [comment]
> > **自己手动安装试试？不用LIP，我是没问题的，Debian11。**
> 
> 谢谢你，Debian11可以，就是有点卡控制台 ![Screenshot_2024-02-27-18-29-49-453_com.server.auditor.ssh.client-edit.jpg](https://private-user-images.githubusercontent.com/142149737/308131636-7a7cae2d-6f3c-495b-aa13-3f4c13363cf5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzODE2OTcsIm5iZiI6MTcwOTM4MTM5NywicGF0aCI6Ii8xNDIxNDk3MzcvMzA4MTMxNjM2LTdhN2NhZTJkLTZmM2MtNDk1Yi1hYTEzLTNmNGMxMzM2M2NmNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQxMjA5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmMyMDA3YmNkZGEyMmUzODczNzRjNTAwMDJiMTVmM2NmMTQ5Mzg0YTZjNDUzNDRjNGQ2Mzc0NmExNTk2ZWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mMn-vALmdST1XdvIFrsjQDAdpirG6c_BNgFWTvQIgD8)

This is a problem with the original BDS.

**Comment by kabaka9527** [comment]
> > > **自己手动安装试试？不用LIP，我是没问题的，Debian11。**
> > 
> > 谢谢你，Debian11可以，就是有点卡控制台 ![Screenshot_2024-02-27-18-29-49-453_com.server.auditor.ssh.client-edit.jpg](https://private-user-images.githubusercontent.com/142149737/308131636-7a7cae2d-6f3c-495b-aa13-3f4c13363cf5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzODE2OTcsIm5iZiI6MTcwOTM4MTM5NywicGF0aCI6Ii8xNDIxNDk3MzcvMzA4MTMxNjM2LTdhN2NhZTJkLTZmM2MtNDk1Yi1hYTEzLTNmNGMxMzM2M2NmNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQxMjA5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmMyMDA3YmNkZGEyMmUzODczNzRjNTAwMDJiMTVmM2NmMTQ5Mzg0YTZjNDUzNDRjNGQ2Mzc0NmExNTk2ZWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mMn-vALmdST1XdvIFrsjQDAdpirG6c_BNgFWTvQIgD8)
> 
> This is a problem with the original BDS.

Ok, thank you very much.
