### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by facredit** [LiteLDev/LiteLoader#1478]
### Describe the bug

Can't load LeviLamina.dll

### To Reproduce

.

### Expected behavior

.

### Screenshots

![image](https://github.com/LiteLDev/LeviLamina/assets/157518377/c1b1cd53-b86b-41e8-8fda-d8785083d3b9)

### Platform

Windows 10

### Version

.

### Additional context

Microsoft Windows [Version 10.0.19045.4046]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Administrative\Desktop\ok>bedrock_server_mod.exe
13:10:40.841 INFO [PreLoader] Loading symbols from pdb...
13:10:43.366 INFO [PreLoader] Loaded 597772 symbols
13:10:43.376 INFO [PreLoader] Loading Reverse Lookup Table
13:10:43.502 ERROR [PreLoader] Can't load LeviLamina.dll
13:10:43.502 ERROR [PreLoader] Error code: 1114
13:10:43.503 ERROR [PreLoader] A dynamic link library (DLL) initialization routine failed.
13:10:43.503 ERROR [PreLoader] Fail to load LeviLamina. Exiting...

C:\Users\Administrative\Desktop\ok>

**Comment by FTS427** [comment]
Runtime is wrong, please install this to solve:

https://aka.ms/vs/17/release/vc_redist.x64.exe
