### ISSUE TITLE
LeviLamina启动不了

### ISSUE THREAD

**Issue by liuyuhang9066** [LiteLDev/LiteLoader#1485]
11:51:05.708 INFO [PreLoader] Loading symbols from pdb...
11:51:17.126 INFO [PreLoader] Loaded 597772 symbols
11:51:17.153 INFO [PreLoader] Loading Reverse Lookup Table
11:51:17.719 ERROR [PreLoader] Can't load LeviLamina.dll
11:51:17.719 ERROR [PreLoader] Error code: 1114
11:51:17.719 ERROR [PreLoader] 动态链接库(DLL)初始化例程失败。
11:51:17.720 ERROR [PreLoader] Fail to load LeviLamina. Exiting...

**Comment by liuyuhang9066** [comment]
有可能发错地方了，嘶。。

**Comment by ShrBox** [comment]
#1474
