### ISSUE TITLE
[bug] LeviLamina will crash when server is fixing ldb missing

### ISSUE THREAD

**Issue by FTS427** [LiteLDev/LiteLoader#1487]
### Describe the bug

Just like the title said, LeviLamina will crash suddenly when server is trying fixing leveldb missing 

### To Reproduce

Remove some .ldb files under /world/`worldname`/db/

Then restart server

It will happen

### Expected behavior

/

### Platform

Windows Server2022

### Version

0.9.4

**Comment by ShrBox** [comment]
I can't reproduce it.

**Comment by OEOTYAN** [comment]
ll不会修改任何原版特性，如果你发现了非api的bug，那么只有两个可能，你的使用的插件造成了问题，或原版本身就有问题。

**Comment by FTS427** [comment]
> I can't reproduce it.

Try to remove more to reproduce, this problem is still happened

**Comment by FTS427** [comment]
I'll upload the logs next weekend

**Comment by FTS427** [comment]
> ll不会修改任何原版特性，如果你发现了非api的bug，那么只有两个可能，你的使用的插件造成了问题，或原版本身就有问题。

This problem has been disappeared
