### ISSUE TITLE
[Bug]:  Fail to load LeviLamina. Exiting...

### ISSUE THREAD

**Issue by a54343** [LiteLDev/LiteLoader#1488]
### Describe the bug

03:48:39.387 ERROR [PreLoader] Can't load LeviLamina.dll
03:48:39.387 ERROR [PreLoader] Error code: 1114
03:48:39.397 ERROR [PreLoader] 动态链接库(DLL)初始化例程失败。
03:48:39.397 ERROR [PreLoader] Fail to load LeviLamina. Exiting...

### To Reproduce

win10 powershell 运行lip install -y github.com/LiteLDev/LeviLamina 后发生

### Expected behavior

= =

**Comment by RimuruChan** [comment]
安装最新的微软vc库
