### ISSUE TITLE
[Feature]: Will there have LegacyHelper???

### ISSUE THREAD

**Issue by BensonChen2456** [LiteLDev/LiteLoader#1489]
### Is your feature request related to a problem? Please describe.

All we know, there is a plugin named LLHelper in LiteLoaderBDSv2.But now, it doesn't adapt to LeviLamina.Will it adapt to LeviLamina???
This plugin is useful.I don't want it unsupported.
Crash player's client is quite funny, right?

### Describe the solution you'd like

Nothing. Just keep the normal usage.

**Comment by Yuisyuu** [comment]
wrong repo for this issue
