### ISSUE TITLE
[Feature]: Adapt to BDS 1.20.71,PLEASEEEEEEEEEEEEEE

### ISSUE THREAD

**Issue by BensonChen2456** [LiteLDev/LiteLoader#1490]
### Is your feature request related to a problem? Please describe.

THE BDS WAS UPDATED THE RELEASE VERSION ON MAR.12TH.
AND TODAY IS MAR.18TH.
HOW LONG SHOULD WE NEED TO WAIT????

### Describe the solution you'd like

ADAPT TO BDS 1.20.71, PROTOCOL VERSION 662

**Comment by RimuruChan** [comment]
We are working on this.
