### ISSUE TITLE
[Feature]: 希望加回LL2的控制台命令显示

### ISSUE THREAD

**Issue by BensonChen2456** [LiteLDev/LiteLoader#1494]
### Is your feature request related to a problem? Please describe.

希望加回LL2的控制台命令显示

### Describe the solution you'd like

希望加回LL2的控制台命令显示

### Describe alternatives you've considered

希望加回LL2的控制台命令显示

### Additional context

希望加回LL2的控制台命令显示

**Comment by ShrBox** [comment]
？

**Comment by yufengya0420** [comment]
这又是什么东西
