### ISSUE TITLE
[Bug]: crash with error 136

### ISSUE THREAD

**Issue by royaljacques** [LiteLDev/LiteLoader#1495]
### Describe the bug

I made the command in the readme, and when I click on bedrock_server_mod.exe, cmd opens and closes

### To Reproduce

just dl with readme explain 

### Expected behavior

 .

### Screenshots

![image](https://github.com/LiteLDev/LeviLamina/assets/63215754/632fd996-3bdb-4f86-a6b8-cde17016e049)
![image](https://github.com/LiteLDev/LeviLamina/assets/63215754/5a154e02-f081-40d3-bf09-511ed38d5cf1)

### Platform

windows &&

**Comment by ShrBox** [comment]
Just waiting for depency analysis, it will output what library you lack.
