### ISSUE TITLE
[Bug]: mce::Blob::Blob Causing Compiler Error without cpp23

### ISSUE THREAD

**Issue by HuQisQwQ** [LiteLDev/LiteLoader#1511]
### Describe the bug

Levilamina SDK headers bug.
Yesterday I builded my plugin, but in compiling, MSVC reported a bug: 
constexpr 函数“mce::Blob::Blob”不能生成常量表达式
note: 请参见“std::unique_ptr<mce::Blob::value_type [],mce::Blob::Deleter>::operator =”的用法
error C3615: constexpr 函数“mce::Blob::data”不能生成常量表达式
note: 对未定义的函数或为未声明为“constexpr”的函数的调用导致了故障
These error from header Blob.h

### To Reproduce

![QQ截图20240424063852](https://github.com/LiteLDev/LeviLamina/assets/127600545/eb83d9ee-7ca6-4ea0-80fd-27bb34889e80)
My code.

### Expected behavior

Is this the reason for my code or the header file
If this's for header file, please fix it plssssssssssssssssssssssssssssssssss

### Platform

Windows10

### Version

0.11.1

**Comment by HuQisQwQ** [comment]
![Uploading QQ截图20240424063852.png…]()

**Comment by OEOTYAN** [comment]
0.12修复 不要在中文中混杂英文
