### ISSUE TITLE
[Bug]: Error when installing Levilamina using LIP

### ISSUE THREAD

**Issue by Futureganteng** [LiteLDev/LiteLoader#1512]
### Describe the bug

Apr 25 09:48:08.540 [ERRO]
        failed to install tooth archive root/.lip/cache/https%3A%2F%2Fgoproxy.io%2Fgithub.com%2F%21lite%21l%21dev%2Fbdsdown%2F%40v%2Fv1.0.1.zip
        failed to attach asset archive root/.lip/cache/https%3A%2F%2Fgithub.com%2FLiteLDev%2Fbdsdown%2Freleases%2Fdownload%2Fv1.0.1%2Fbdsdown-linux-amd64.tar.gz
        failed to open zip reader root/.lip/cache/https%3A%2F%2Fgithub.com%2FLiteLDev%2Fbdsdown%2Freleases%2Fdownload%2Fv1.0.1%2Fbdsdown-linux-amd64.tar.gz
        zip: not a valid zip file

### To Reproduce

use the lip-amd64, extract the file, chmod 777 lip, ./lip install github.com/LiteLDev/LeviLamina

### Expected behavior

![Screenshot 2024-04-25 165513](https://github.com/LiteLDev/LeviLamina/assets/47469885/4ad96028-683b-417f-a8ec-c1bbf4ba2b35)

### Screenshots

![Screenshot 2024-04-25 165159](https://github.com/LiteLDev/LeviLamina/assets/47469885/b0a9bb24-9736-4d6e-adf6-c16366d3e1d6)

### Platform

Ubuntu Server 22.04

### Version

Lip 0.22.0

**Comment by ShrBox** [comment]
It's Lip's bug
https://github.com/lippkg/lip/issues/129
