### ISSUE TITLE
[Feature]: 添加 材质包加密 支持

### ISSUE THREAD

**Issue by CloudStarOwO** [LiteLDev/LiteLoader#1523]
### Is your feature request related to a problem? Please describe.

添加 加密材质包 支持

### Describe the solution you'd like

与LL相同,可在./plugins/LeviLamina/config/config.json中ResourcePackEncryption填写Key:uuid使用加密材质包

**Comment by ShrBox** [comment]
https://github.com/ShrBox/ResourcePackEncryption
