### ISSUE TITLE
[Bug]: 无法安装liteloaderBDS

### ISSUE THREAD

**Issue by crowdedplus** [LiteLDev/LiteLoader#1527]
### Describe the bug

按照文档运行了lip install github.com/LiteLDev/LeviLamina指令，但是报错，Installing tooth github.com/liteldev/levilamina...
'.\PeEditor.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

### To Reproduce

![image](https://github.com/LiteLDev/LeviLamina/assets/112145371/b4c578e2-4b43-4b6e-afbf-a3176ebc10bf)

### Expected behavior

安装成功

**Comment by ShrBox** [comment]
所使用的Lip版本？

**Comment by crowdedplus** [comment]
0.15.2在本地，服务器那边也装不上，在服务器的lip加了环境变量还是没法查看版本，放第一个也没用


修罗
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiteLDev/LeviLamina"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月4日(星期六) 晚上6:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiteLDev/LeviLamina] [Bug]: 无法安装liteloaderBDS (Issue #1527)





 
所使用的Lip版本？

**Comment by ShrBox** [comment]
> 0.15.2在本地，服务器那边也装不上，在服务器的lip加了环境变量还是没法查看版本，放第一个也没用 修罗 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "LiteLDev/LeviLamina" ***@***.***&gt;; 发送时间:&nbsp;2024年5月4日(星期六) 晚上6:38 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [LiteLDev/LeviLamina] [Bug]: 无法安装liteloaderBDS (Issue #1527) 所使用的Lip版本？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

太老了
