### ISSUE TITLE
[Bug]: Installing dependencies

### ISSUE THREAD

**Issue by LordBombardir** [LiteLDev/LiteLoader#1533]
### Describe the bug

Incorrect installation of LeviLamina dependencies using xmake.

### To Reproduce

1. I cloned the template https://github.com/LiteLDev/levilamina-plugin-template to my repository.
2. Changed some files according to https://levilamina.liteldev.com/tutorials/create_your_first_plugin/.
3. Opened the terminal and entered the "xmake" command to install the necessary dependencies for developing my own plugins.

### Expected behavior

Correct installation of LeviLamina dependencies and further work with them in VS/VS Code

### Screenshots

![image](https://github.com/LiteLDev/LeviLamina/assets/60620262/42e3abf1-f932-4c0d-b0cb-b90cbbe3a370)
![image](https://github.com/LiteLDev/LeviLamina/assets/60620262/15cce2c2-b2ce-48b8-b760-31f172f3e908)

### Platform

Windows 11

### Version

0.12.3

**Comment by ShrBox** [comment]
It's your network issue, maybe your isp is hijacking Github.
