### ISSUE TITLE
[Feature]: Addition PlayerMoveEvent

### ISSUE THREAD

**Issue by LordBombardir** [LiteLDev/LiteLoader#1537]
### Is your feature request related to a problem? Please describe.

I'm making a player authorization system on my server. Until a player auth/registers, they should not be able to move in any way. But, unfortunately, with the current API, in my opinion, this is impossible to do. By adding a player movement event with the ability to cancel it, I can solve my problem.

### Describe the solution you'd like

I would like to be able to listen to the player's movement event and also cancel it.

### Describe alternatives you've considered

I tried to hook various packets, but in vain.

### Additional context

If something is unclear, then forgive me, because my native language is Russian.

**Comment by OEOTYAN** [comment]
Because there is no way to cancel player move, move is client-side behavior. Perhaps you could try teleporting the player back when player movement is detected.

**Comment by LordBombardir** [comment]
> Because there is no way to cancel player move, move is client-side behavior. Perhaps you could try teleporting the player back when player movement is detected.

Oh, if only I knew how to do this. After all, with the MovePlayerPacket hook, the reference to the player is constant, and I cannot use the method teleportTo.

**Comment by OEOTYAN** [comment]
> > Because there is no way to cancel player move, move is client-side behavior. Perhaps you could try teleporting the player back when player movement is detected.
> 
> 
> 
> Oh, if only I knew how to do this. After all, with the MovePlayerPacket hook, the reference to the player is constant, and I cannot use the method teleportTo.

Usually there are some ids and you should be able to look up the player from level or something else.
