### ISSUE TITLE
[Bug]: build failed

### ISSUE THREAD

**Issue by killcerr** [LiteLDev/LiteLoader#1543]
### Describe the bug

build failed

### To Reproduce

use Github Action build LeviLamina

### Expected behavior

build successfully

### Screenshots

![image](https://github.com/LiteLDev/LeviLamina/assets/93478098/286bc6ef-a164-46fb-a7eb-20ae033e0f67)

### Additional context

https://github.com/xmake-io/xmake/issues/4965

**Comment by OEOTYAN** [comment]
你还是看看别的吧 这游戏都寄了

**Comment by OEOTYAN** [comment]
刚才的提交构建成功了，无法复现
