### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by QuintenQVD0** [LiteLDev/LiteLoader#1544]
I am trying to build this project myself with the provided workflow file in this repo on the develop branch and it always fails even tho when the workflow runs here it works just fine.

Workflow: https://github.com/QuintenQVD0/LeviLamina/actions/runs/9428781498

Fix the workflow or the code that you can build this yourself

**Comment by OEOTYAN** [comment]
This project has ended on June 6, 2024, as mojang is no longer providing debug symbols.
