### ISSUE TITLE
[Bug]: plugin cannot be compiled

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#1547]
### Describe the bug

```
include/ll/api/base/Concepts.h(108): error C2760: syntax error: '||' was unexpected here; expected 'expression'
```

### To Reproduce

None

### Expected behavior

Build pass

### Additional context

https://github.com/LiteLDev/LeviLamina/blob/6ed404f06f3d00b0c9e47250807caae43f73b959/src/ll/api/base/Concepts.h#L108

**Comment by ShrBox** [comment]
Try add `"_HAS_CXX23=1` in add_defines?
