### ISSUE TITLE
[Bug]: #1499再现

### ISSUE THREAD

**Issue by Milvona** [LiteLDev/LiteLoader#1550]
### Describe the bug

BlockSource::getDimensionId returns nullptr
https://github.com/LiteLDev/LeviLamina/issues/1499

### To Reproduce

```
    eventBus.emplaceListener<ll::event::BlockChangedEvent>([](ll::event::BlockChangedEvent& ev) {
        logger.info("Block Changed Pos: {} Dimension: {}", ev.pos().toString(), ev.blockSource().getDimensionId().id);
    });
```

### Expected behavior

![image](https://github.com/LiteLDev/LeviLamina/assets/121496151/b81230d3-f345-41b3-8736-6d45235390b0)

### Screenshots

/

### Platform

Win

### Version

Version: 1.21.0.03(ProtocolVersion 685) with LeviLamina-0.13.1+123135e8e

### Additional context

/

**Comment by OEOTYAN** [comment]
你能不能用debug版看看堆栈
