### ISSUE TITLE
[Proposal]: Rename Plugin to Mod

### ISSUE THREAD

**Issue by OEOTYAN** [LiteLDev/LiteLoader#1551]
### Is your feature request related to a problem? Please describe.

Apparently, "plugin" is a historical problem and should be changed as soon as possible before an official version is released.

### Describe the solution you'd like

Rename Plugin to Mod

**Comment by S3v3Nice** [comment]
I think calling the Plugin a Mod will confuse a lot of people. Modifications that are performed only on the server side have long been called plugins, and mods are modifications on the client side. For some reason on JE players haven't stopped calling plugins plugins, so why should they on Bedrock? I realize that on Bedrock there are no mods in the usual sense, but nevertheless.

**Comment by OEOTYAN** [comment]
> I think calling the Plugin a Mod will confuse a lot of people. Modifications that are performed only on the server side have long been called plugins, and mods are modifications on the client side. For some reason on JE players haven't stopped calling plugins plugins, so why should they on Bedrock? I realize that on Bedrock there are no mods in the usual sense, but nevertheless.

We've actually reached a level of modification close to that of fabric on JE so far.

**Comment by S3v3Nice** [comment]
> We've actually reached a level of modification close to that of fabric on JE so far.

Yes, but people primarily associate "mods" with content that you can add yourself to a single-player game, not just a server. That's why even addons are called mods by a lot of people (most of the players who don't bother to look into how things work). I think even if you rename Plugin to Mod, people will continue to call it plugins because it's easier to get the point across to most players that it's a server-side modification.

**Comment by OEOTYAN** [comment]
> > We've actually reached a level of modification close to that of fabric on JE so far.
> 
> Yes, but people primarily associate "mods" with content that you can add yourself to a single-player game, not just a server. That's why even addons are called mods by a lot of people (most of the players who don't bother to look into how things work). I think even if you rename Plugin to Mod, people will continue to call it plugins because it's easier to get the point across to most players that it's a server-side modification.

![image](https://github.com/LiteLDev/LeviLamina/assets/58554322/0a2e2ef9-80e0-42c6-9ad2-d8c964a3d4eb)
You are right, so I tested it, and our current framework can run well on the client, and it is very simple to adapt to UWP, but other platforms will take some time (probably longer than Linux). So I think I can change the name now.

**Comment by MCBEPluginModer** [comment]
> > > We've actually reached a level of modification close to that of fabric on JE so far.
> > 
> > 
> > Yes, but people primarily associate "mods" with content that you can add yourself to a single-player game, not just a server. That's why even addons are called mods by a lot of people (most of the players who don't bother to look into how things work). I think even if you rename Plugin to Mod, people will continue to call it plugins because it's easier to get the point across to most players that it's a server-side modification.
> 
> ![image](https://private-user-images.githubusercontent.com/58554322/344239948-0a2e2ef9-80e0-42c6-9ad2-d8c964a3d4eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1OTIyNTcsIm5iZiI6MTcxOTU5MTk1NywicGF0aCI6Ii81ODU1NDMyMi8zNDQyMzk5NDgtMGEyZTJlZjktODBlMC00MmM2LTlhZDItZDhjOTY0YTNkNGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDE2MjU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZTNiNWU3MTJlYmM5ZmMxNTk1YTE0ZGJmOThhYzhlY2I4OTQxZmUyOGYyYmFjNjhhN2E5YmZmOGY1OTlmZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LbVhmYQ9XyfDRbqAEMcl_JX271qlu_ErNBYh020soAc) You are right, so I tested it, and our current framework can run well on the client, and it is very simple to adapt to UWP, but other platforms will take some time (probably longer than Linux). So I think I can change the name now.

Are you writing a .dll mod loader for UWP/Andoid?

**Comment by MCBEPluginModer** [comment]
> > > We've actually reached a level of modification close to that of fabric on JE so far.
> > 
> > 
> > Yes, but people primarily associate "mods" with content that you can add yourself to a single-player game, not just a server. That's why even addons are called mods by a lot of people (most of the players who don't bother to look into how things work). I think even if you rename Plugin to Mod, people will continue to call it plugins because it's easier to get the point across to most players that it's a server-side modification.
> 
> ![image](https://private-user-images.githubusercontent.com/58554322/344239948-0a2e2ef9-80e0-42c6-9ad2-d8c964a3d4eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNTE2MDMsIm5iZiI6MTcyMDI1MTMwMywicGF0aCI6Ii81ODU1NDMyMi8zNDQyMzk5NDgtMGEyZTJlZjktODBlMC00MmM2LTlhZDItZDhjOTY0YTNkNGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDA3MzUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMmM5MzRkYzgyOGM4NjIxZDgyODE2MDg1ZTk5YTU4OWJmMjRhOThmNWQxOWE5YzliY2FiYjk0YmJkNjE2ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4VNN9U8tNwQqcCu46z8wyCwJ7ybtgjTkMPvpDIScODM) You are right, so I tested it, and our current framework can run well on the client, and it is very simple to adapt to UWP, but other platforms will take some time (probably longer than Linux). So I think I can change the name now.

how to write mods on UWP?
