### ISSUE TITLE
请适配1.21.3.01

### ISSUE THREAD

**Issue by BensonChen2456** [LiteLDev/LiteLoader#1556]
### Is your feature request related to a problem? Please describe.

1.21.3.01的服务器包有pdb文件 请及时适配 谢谢

### Describe the solution you'd like

1.21.3.01的服务器包有pdb文件 请及时适配 谢谢

### Describe alternatives you've considered

各位LeviLamina Developers辛苦了

### Additional context

各位LeviLamina Developers辛苦了

**Comment by BensonChen2456** [comment]
![Screenshot_2024-07-20-19-01-11-212_bin mt plus](https://github.com/user-attachments/assets/4e02635a-65ae-4931-8f5c-4d8e74c6276d)

**Comment by BensonChen2456** [comment]
是出现问题了吗？怎么一个小时前的Action撤回了

**Comment by BensonChen2456** [comment]
@Lovelylavender4

**Comment by ShrBox** [comment]
这需要适配？就改个协议号的事
不更新也能正常跑
