### ISSUE TITLE
[Bug]: 重载插件时出现问题

### ISSUE THREAD

**Issue by SCFY233** [LiteLDev/LiteLoader#1557]
### Describe the bug

在第一次重载js插件时报错，手动加载插件后，恢复正常，重载插件也不再出现问题

### To Reproduce

打开服务端，第一次重载任意插件就会出现问题

### Expected behavior

正常重载插件

### Screenshots

![1](https://github.com/user-attachments/assets/30009647-db00-43bc-99a7-0a5f59f84cd1)

### Platform

Windows11 x64 

### Version

BDS Version: 1.21.0.03(ProtocolVersion 685) with LeviLamina-0.13.0+cafc1d601

**Comment by SCFY233** [comment]
经过测试，普通js插件也会出现问题
![image](https://github.com/user-attachments/assets/0eaa945a-b972-4621-80f6-53bed4b4d56f)

**Comment by OEOTYAN** [comment]
更新ll

**Comment by SCFY233** [comment]
确实好了a.e
