### ISSUE TITLE
[Bug]: 启动时间异常

### ISSUE THREAD

**Issue by p1145p** [LiteLDev/LiteLoader#1562]
### Describe the bug

启动服务器时
[Server] [Packs] [SERVER] Pack Stack
等待时间过长
最长可达15分钟

### To Reproduce

正常启动服务器

### Expected behavior

启动速度较快

### Platform

Windows10

### Version

LeviLamina-0.13.4+740e75ff4

### Additional context

存档大小约100m左右
DBS版本1.21.3.01

**Comment by ShrBox** [comment]
https://bugs.mojang.com/
