### ISSUE TITLE
[Bug]: 运行时显示Error Code 1114 动态链接库(DLL)初始化例程失败

### ISSUE THREAD

**Issue by Moxuan6** [LiteLDev/LiteLoader#1564]
### Describe the bug

使用lip 安装捆绑了 Minecraft Bedrock Server 的 LeviLamina然后启动，它就显示动态链接库(DLL)初始化例程失败

### To Reproduce

1. "lip install github.com/LiteLDev/LeviLamina"
2. "./bedrock_server_mod.exe"

### Expected behavior

想问一下这是什么原因怎么解决？

### Screenshots

![QQ_1723277839625](https://github.com/user-attachments/assets/1420e001-43f7-46dd-b393-29ccc1595b72)

### Platform

windows11

### Version

1.21.3.01

**Comment by ShrBox** [comment]
Vcredist版本太老。更新[vcredist](https://learn.microsoft.com/cpp/windows/latest-supported-vc-redist?view=msvc-170)以解决此错误。
> From: https://levilamina.liteldev.com/zh/faq/#1114
