### ISSUE TITLE
[Feature]: 建议内置云黑＆封禁功能

### ISSUE THREAD

**Issue by BensonChen2456** [LiteLDev/LiteLoader#1565]
### Is your feature request related to a problem? Please describe.

建议内置云黑＆封禁功能

### Describe the solution you'd like

建议内置云黑＆封禁功能

### Describe alternatives you've considered

建议内置云黑＆封禁功能

### Additional context

建议内置云黑＆封禁功能

**Comment by Yushu2606** [comment]
https://github.com/LiteLDev/LeviAntiCheat
