### ISSUE TITLE
[Bug]: 热卸载dll插件后其他所有插件注册的指令失效

### ISSUE THREAD

**Issue by Atrium4641** [LiteLDev/LiteLoader#1574]
### Describe the bug

BDS1.21.3，LL0.13.5，热卸载dll插件后其他所有插件注册的指令失效，提示未启用作弊，但是通过player.runcmd("command")用正常执行

### To Reproduce

热卸载dll插件后执行其他插件注册的指令

### Expected behavior

热卸载dll插件后其他所有插件注册的指令正常执行

### Platform

Win10

### Version

0.13.5

**Comment by OEOTYAN** [comment]
讲清楚

**Comment by Atrium4641** [comment]
> 讲清楚

就是控制台ll unload 一个dll插件 然后其他所有插件注册的指令就都不能用 重启服务器后恢复正常

**Comment by OEOTYAN** [comment]
说明有问题的插件和使用的插件列表

**Comment by Atrium4641** [comment]
> 说明有问题的插件和使用的插件列表

正常来讲你随便搞个dll插件热卸载都会导致其他所有插件指令失效

**Comment by quizhizhe** [comment]
> > 说明有问题的插件和使用的插件列表
> 
> 
> 
> 正常来讲你随便搞个dll插件热卸载都会导致其他所有插件指令失效

建议还是提供下文件，这样也好复现问题，而不是含糊其词来描述

**Comment by Atrium4641** [comment]
![image](https://github.com/user-attachments/assets/b337d772-46f2-4eb4-9ef4-f910b32936d4)

有问题的插件：LeviTPSystem，热卸载该插件后其余所有插件注册的指令失效，显示该世界未开启无敌模式

**Comment by Atrium4641** [comment]
插件文件夹压缩后290MB，无法上传

**Comment by Atrium4641** [comment]
这是有问题的插件的链接：https://www.minebbs.com/resources/levitpsystem.5755/
