### ISSUE TITLE
[Bug]: 18:15:17.892 ERROR [Server] [Scripting] Unhandled promise rejection: CommandError: Syntax error: Unexpected "[": at "damage @a»[«r=7] 15" 18:15:17.892 ERROR [Server]

### ISSUE THREAD

**Issue by DarkWorldserver** [LiteLDev/LiteLoader#1576]
### Describe the bug

пропали атриуты на сервере на ядре LeviLamina

### To Reproduce

я просто запустил сервер

### Expected behavior

пропали атрибуты

### Platform

Win 11

### Version

1.21.3

**Comment by OEOTYAN** [comment]
When the output is titled [Server], it means that this is a BDS error.
