### ISSUE TITLE
[Feature]: request to add log output filtering

### ISSUE THREAD

**Issue by zimuya4153** [LiteLDev/LiteLoader#1582]
### Is your feature request related to a problem? Please describe.

me want to filter some specified log content

### Describe the solution you'd like

achieve this function

**Comment by OEOTYAN** [comment]
没听懂 哪个log

**Comment by zimuya4153** [comment]
就是，希望能过滤一些日志输出，提供一个数组，填入想过滤的关键词

**Comment by zimuya4153** [comment]
就跟LL2的OutputFilter一样

**Comment by OEOTYAN** [comment]
你要过滤自己的插件还是什么

**Comment by zimuya4153** [comment]
过滤一些其他插件的内容，比如刷屏内容什么的
