### ISSUE TITLE
[Bug]: stop关服崩服

### ISSUE THREAD

**Issue by Atrium4641** [LiteLDev/LiteLoader#1583]
### Describe the bug

[crash.zip](https://github.com/user-attachments/files/17567606/crash.zip)

stop关服崩服

### To Reproduce

BDS版本1.21.3
LL版本0.13.5

stop关服崩服，崩服日志dump文件不知道为什么无法成功生成

### Expected behavior

stop不崩服

### Screenshots

![image](https://github.com/user-attachments/assets/e5ad20b8-379d-4ded-922f-5085814839d8)

### Platform

Win10

### Version

0.13.5

**Comment by OEOTYAN** [comment]
这个已经修了，只是没有发新版，以后更新了会好的

**Comment by Atrium4641** [comment]
> 这个已经修了，只是没有发新版，以后更新了会好的

ok
