### ISSUE TITLE
[Feature]: plugin unload error

### ISSUE THREAD

**Issue by Atrium4641** [LiteLDev/LiteLoader#1603]
### Is your feature request related to a problem? Please describe.

得搞个关服先关掉依赖插件,再关掉被依赖插件的办法

### Describe the solution you'd like

得搞个关服先关掉依赖插件,再关掉被依赖插件的办法

### Describe alternatives you've considered

得搞个关服先关掉依赖插件,再关掉被依赖插件的办法

### Additional context

得搞个关服先关掉依赖插件,再关掉被依赖插件的办法

**Comment by Atrium4641** [comment]
![a1ae9911b66d94838ee2c2c720309162](https://github.com/user-attachments/assets/5367b3a0-0453-45db-bcef-8c49e688c70b)


卸载顺序问题

**Comment by OEOTYAN** [comment]
本来就是倒序禁用 这是插件问题
