### ISSUE TITLE
No drops when using Level::breakBlockNaturally(bs, pos, item);

### ISSUE THREAD

**Issue by BotProMax** [LiteLDev/LiteLoader#165]
There are no drops when I use `Level::breakBlockNaturally(bs, pos, item)`, but `Level::breakBlockNaturally(bs, pos)`.
"item" cames from
`ItemStack* item = (ItemStack*)&pl->getCarriedItem();`

**Comment by Jaciezyt** [comment]
maybe the item can't destroy the block?

**Comment by dreamguxiang** [comment]
I tested it and it is work

**Comment by BotProMax** [comment]
> maybe the item can't destroy the block?

I've tried different ores with different pickaxes and logs with different axes, but never came drops.

**Comment by dreamguxiang** [comment]
> > maybe the item can't destroy the block?
> 
> I've tried different ores with different pickaxes and logs with different axes, but never came drops.

There is indeed a problem, I tried to fix it

**Comment by BotProMax** [comment]
> > > maybe the item can't destroy the block?
> > 
> > 
> > I've tried different ores with different pickaxes and logs with different axes, but never came drops.
> 
> There is indeed a problem, I tried to fix it

Thanks!

**Comment by yqs112358** [comment]
fixed
