### ISSUE TITLE
这个项目能支持 Ubuntu 20.14吗(Can this program support Ubuntu 21.04)

### ISSUE THREAD

**Issue by Onlyacat233** [LiteLDev/LiteLoader#166]
Can this program support Ubuntu 21.04?
这个项目能支持 Ubuntu 20.14吗，我希望这个项目能支持Ubuntu 21.04(受不了windows的奇妙占用了)

**Comment by RimuruChan** [comment]
本项目目前不会支持linux，如果您想在linux上使用BDS和LL，请参考 README 中的docker教程，或者自行配置wine。
