### ISSUE TITLE
Cmd Parser

### ISSUE THREAD

**Issue by MCBEPluginModer** [LiteLDev/LiteLoader#167]
How to make the parser work adequately with different arguments in 2 overloads?
For example:
/cmd <string>
/cmd enum
And if I enter /cmd enum, then it would choose enum, and not the first overload option?

**Comment by xiaoqch** [comment]
You can set the fourth parameter of makeMandatory and use it to judge whether the enum is set in execute
for example:
![image](https://user-images.githubusercontent.com/37901097/150276257-b4888c53-511e-4899-aaf0-0c65cf3bb234.png)

**Comment by MCBEPluginModer** [comment]
> You can set the fourth parameter of makeMandatory and use it to judge whether the enum is set in execute for example: ![image](https://user-images.githubusercontent.com/37901097/150276257-b4888c53-511e-4899-aaf0-0c65cf3bb234.png)

Thank you, but there's no other way? I implemented it by passing the unique name of the argument (op val, etc.) and jumping to the label via goto.

**Comment by MCBEPluginModer** [comment]
> You can set the fourth parameter of makeMandatory and use it to judge whether the enum is set in execute for example: ![image](https://user-images.githubusercontent.com/37901097/150276257-b4888c53-511e-4899-aaf0-0c65cf3bb234.png)

Yes,this is method is work!

**Comment by MCBEPluginModer** [comment]
Thanks for your job! I am waiting LiteLoader 2.0.7 ;)
