### ISSUE TITLE
Docker & Linux Support for LiteLoaderBDS

### ISSUE THREAD

**Issue by Atten007** [LiteLDev/LiteLoader#169]
**Is your feature request related to a problem? Please describe.**
No, it's currently not a problem because this is a feature request for this very, very nice MCPE project.

**Describe the solution you'd like**
I have a Synology NAS with two Docker Minecraft Servers on it and on my Docker MCPE Server I want to install the "LiteLoaderBDS". But currently I can't because there's 1. no docker file in the repo and 2. the startup file of this MCPE project is a .exe file that's only executable on Windows...

**Describe alternatives you've considered**
I considered nothing because I found no alternatives here on GitHub for this project...

**Additional context**
It may be really, really nice for me when you can add Linux support and docker support for this project. I need this very urgently for my bedrock dedicated server e.g. to make mini games for it that my server will be future a featured MCPE server. And also sorry for my bad English, I'm German.

Sincerely yours,

Atten007😊

**Comment by ShrBox** [comment]
Synology NAS uses ARM-based processor, so Bedrock Dedicated Server cannot be started
I suggest you to ask this question to mojang
