### ISSUE TITLE
Throwable items.

### ISSUE THREAD

**Issue by MCBEPluginModer** [LiteLDev/LiteLoader#176]
How to disable throwable for snowball,experience potion and e.t.c?

**Comment by Jaciezyt** [comment]
onUseItem?

**Comment by MCBEPluginModer** [comment]
No, my goal is to ban throwing a snowball, experience bubble, ender pearls, etc.

**Comment by Jaciezyt** [comment]
you can try listening onUseItem, because throwing a snowball is theoretically using an item

**Comment by MCBEPluginModer** [comment]
onUseItem function not found!

**Comment by MCBEPluginModer** [comment]
i will try using PlayerUseItemOnEvent event

**Comment by Jaciezyt** [comment]
`Event::PlayerUseItemEvent::subscribe`

**Comment by MCBEPluginModer** [comment]
Not work!

**Comment by Jaciezyt** [comment]
Why?
Not UseItemOn
`PlayerUseItem`

**Comment by MCBEPluginModer** [comment]
![image](https://user-images.githubusercontent.com/86790039/150674167-1490b54f-5862-45e5-96ee-f92966637ebc.png)
Snowball throwable!

**Comment by MCBEPluginModer** [comment]
Thans,PlayerUseItemEvent work!

**Comment by Jaciezyt** [comment]
By the way,you can also try this event `ProjectileSpawnEvent`

**Comment by MCBEPluginModer** [comment]
Okay,thans for help!
