### ISSUE TITLE
Interacted blocks.

### ISSUE THREAD

**Issue by MCBEPluginModer** [LiteLDev/LiteLoader#177]
Is it possible to prevent interaction with buttons/doors etc with a single function?

**Comment by ambiennt** [comment]
I'd say the simplest way is to just give the player the doors and switches ability set to false. but if you want to do it serverside you can check the block type(s) in BlockEventCoordinator::sendBlockInteractedWith(Player &, BlockPos const &), cancel the function and send a BlockUpdatePacket back to the client in order to restore the unpressed/unopened blockstate.

**Comment by Jasonzyt** [comment]
I think `Event::PlayerUseItemOnEvent` might work

**Comment by ambiennt** [comment]
oh yeah, it seems like the client sends an InventoryTransactionPacket AND a PlayerActionPacket when interacting with a button or door. Thats 2 different places you need to account for at least.

**Comment by MCBEPluginModer** [comment]
> oh yeah, it seems like the client sends an InventoryTransactionPacket AND a PlayerActionPacket when interacting with a button or door. Thats 2 different places you need to account for at least.

No

**Comment by MCBEPluginModer** [comment]
> BlockEventCoordinator::sendBlockInteractedWith

not work

**Comment by ambiennt** [comment]
Did you try canceling the inventory transaction packet as well?

**Comment by MCBEPluginModer** [comment]
> Did you try canceling the inventory transaction packet as well?

No

**Comment by MCBEPluginModer** [comment]
> Did you try canceling the inventory transaction packet as well?

I have no idea how to cancel packages

**Comment by MCBEPluginModer** [comment]
> Did you try canceling the inventory transaction packet as well?

Via ServerNetworkHandler?

**Comment by MCBEPluginModer** [comment]
Event::PlayerUseItemOnEvent not worked for open/closen door,but worked for button/levers and e.t.c interact blocks!

**Comment by MCBEPluginModer** [comment]
> Did you try canceling the inventory transaction packet as well?

Cancelling and not worked!

**Comment by MCBEPluginModer** [comment]
Help please
