### ISSUE TITLE
BlockInteractedEvent not worked for door!

### ISSUE THREAD

**Issue by MCBEPluginModer** [LiteLDev/LiteLoader#179]
I'm return 0 in BlockInteractedEvent and this work for button,levers and e.t.c,but not work for doors! How to fix it!?

**Comment by ShrBox** [comment]
It cannot be intercepted because opening the door is a client-side behavior and is not controlled by the server.

**Comment by MCBEPluginModer** [comment]
> It cannot be intercepted because opening the door is a client-side behavior and is not controlled by the server.

but on poketmine and nukkit it can be controlled on the server side...

**Comment by MCBEPluginModer** [comment]
> It cannot be intercepted because opening the door is a client-side behavior and is not controlled by the server.

Is it physically possible to implement something like this on the server side?

**Comment by ambiennt** [comment]
> It cannot be intercepted because opening the door is a client-side behavior and is not controlled by the server.

If the player lacks the doorsandswitches ability, its possible to disable clientside. Even without it, if the event is canceled serverside, the blockstate won't change and the levelsoundevent will not be broadcast.

**Comment by MCBEPluginModer** [comment]
> Referenc

This option does not suit me, since the ban will be dynamic and individual for each.

**Comment by ambiennt** [comment]
> > Referenc
> 
> 
> 
> This option does not suit me, since the ban will be dynamic and individual for each.

- What? You just update the ability serverside, then send an adventuresettings packet to the specific player. Make sure to save to the permissions file (symcall permissionsfile::persistplayerpermissionstodisk) so it saves on server restart as well.

**Comment by MCBEPluginModer** [comment]
> * What? You just update the ability serverside, then send an adventuresettings packet to the specific player. Make sure to save to the permissions file (symcall permissionsfile::persistplayerpermissionstodisk) so it saves on server restart as well.

Can I have a code example please? And I have this purely individually for each player. The player has the right - we do nothing, no - we forbid opening and closing the door

**Comment by ambiennt** [comment]
> > * What? You just update the ability serverside, then send an adventuresettings packet to the specific player. Make sure to save to the permissions file (symcall permissionsfile::persistplayerpermissionstodisk) so it saves on server restart as well.
> 
> Can I have a code example please? And I have this purely individually for each player. The player has the right - we do nothing, no - we forbid opening and closing the door

I did it in a mod for an old modloading software [here](https://github.com/ambiennt/Abilities), but now its deprecated in 1.18. It should be basically the same principle though.

**Comment by MCBEPluginModer** [comment]
> > > * What? You just update the ability serverside, then send an adventuresettings packet to the specific player. Make sure to save to the permissions file (symcall permissionsfile::persistplayerpermissionstodisk) so it saves on server restart as well.
> > 
> > 
> > Can I have a code example please? And I have this purely individually for each player. The player has the right - we do nothing, no - we forbid opening and closing the door
> 
> I did it in a mod for an old modloading software [here](https://github.com/ambiennt/Abilities), but now its deprecated in 1.18. It should be basically the same principle though.

Technically not suitable!

**Comment by ambiennt** [comment]
> Technically not suitable!

It is though. The principle is exactly the same but you will have to reimplement some class structures if they dont exist in LL. Btw, a raw pointer to class PermissionsFile exists at ServerNetworkHandler + 0x78 in 1.18.2

**Comment by MCBEPluginModer** [comment]
> Technically not suitable!

Technically not suitable!

**Comment by MCBEPluginModer** [comment]
> > Technically not suitable!
> 
> It is though. The principle is exactly the same but you will have to reimplement some class structures if they dont exist in LL. Btw, a raw pointer to class PermissionsFile exists at ServerNetworkHandler + 0x78 in 1.18.2

Abilities object crash server!
