### ISSUE TITLE
Pickup item.

### ISSUE THREAD

**Issue by MCBEPluginModer** [LiteLDev/LiteLoader#184]
How to check pickup item? I'm hooked ?handle@ComplexInventoryTransaction@@UEBA?AW4InventoryTransactionError@@AEAVPlayer@@_N@Z,but it reacts only to throwing objects, and nothing happens when you raise it. I also output (int)*((char*)&i.first + 8), but the output was triggered only when throwing an object!
How to check PickupItem actions?

**Comment by ambiennt** [comment]
picking up items is serverside, so trace when the server sends a takeitemactor packet

**Comment by ambiennt** [comment]
Player::take

**Comment by KawaiiNahida** [comment]
@MCBEPluginModer I think you should ask such questions on telegram or discord instead of github issue. Also when it comes to reverse engineering, I suggest you to guess and test what Mojang made, this will make you understand how BDS work better

**Comment by MCBEPluginModer** [comment]
> take

thanks

**Comment by MCBEPluginModer** [comment]
> @MCBEPluginModer I think you should ask such questions on telegram or discord instead of github issue. Also when it comes to reverse engineering, I suggest you to guess and test what Mojang made, this will make you understand how BDS work better

Player::take is not suitable, I do not need to check exactly the action of the player - in my case picking up the item!

**Comment by MCBEPluginModer** [comment]
> Player::take

Player::take is not suitable, I do not need to check exactly the action of the player - in my case picking up the item!

**Comment by MCBEPluginModer** [comment]
> @MCBEPluginModer I think you should ask such questions on telegram or discord instead of github issue. Also when it comes to reverse engineering, I suggest you to guess and test what Mojang made, this will make you understand how BDS work better

i'm checked vanillia mc function

**Comment by MCBEPluginModer** [comment]
ambient asked!
