### ISSUE TITLE
pl.blockPos获取到的坐标值与实际值有出入

### ISSUE THREAD

**Issue by Asurin219** [LiteLDev/LiteLoader#203]
# 问题
LLSE：通过API``pl.blockPos``获取到的坐标值与实际值有出入：``pl.blockPos.y``值比实际y轴坐标值大了2格

# 复现
1. 加载``MyPosition.lxl.js``插件，在游戏内输入here返回玩家脚下方块的坐标。插件代码如下：

```javascript
//LiteXLoader Dev Helper
/// <reference path="c:\Users\Administrator\.vscode-server\extensions\moxicat.lxldevhelper-0.1.8/Library/JS/Api.js" /> 

var _ver = '1.0'
mc.regPlayerCmd("here","发送我的坐标",(pl)=>{
    mc.broadcast(`§b玩家 §r${pl.realName} §b当前正位于 §e${pl.pos.dim}§b 的 §a(${pl.blockPos.x} , ${pl.blockPos.y} , ${pl.blockPos.z})`)
})
```

# 屏幕截图
![U97~R@0R4B_UH44BZ1WG2FJ](https://user-images.githubusercontent.com/77911856/153692633-c008aa89-0080-4e07-9dcb-4d11b0348320.jpg)

# 环境
 - OS: [Windows Server 2022]
 - LiteLoader Version [2.1.0]

**Comment by Asurin219** [comment]
使用pl.pos暂未发现上述问题

**Comment by dreamguxiang** [comment]
需要哪种，y与pos一致还是和游戏一致，两者一个指头一个指脚

**Comment by Asurin219** [comment]
blockPos.y的话 应该与游戏一致吧（指脚
