### ISSUE TITLE
Door can't be placed

### ISSUE THREAD

**Issue by ShrBox** [LiteLDev/LiteLoader#204]
**Describe the bug**
When I installed iland, i can't place door in my server

**To Reproduce**
1. Install iland
2. Try to place door

**Environment (please complete the following information):**
 - OS: Windows Server 2016
 - LiteLoader Version 2.1.0

**Comment by dreamguxiang** [comment]
fixed 68ff93b03cb8b5660f07e2e67a46753d10745c56
