### ISSUE TITLE
Centos7+wine7.2下崩溃

### ISSUE THREAD

**Issue by assidence** [LiteLDev/LiteLoader#207]
**Describe the bug**
Centos7，3.10内核，wine7.2环境下崩溃

**To Reproduce**
启动即崩溃

**Expected behavior**
正常启动

**Screenshots or log**
https://gist.github.com/assidence/aea8e67bb3e324eb76e3fbce5a1280c3

**Environment (please complete the following information):**
 - OS: Centos7
 - LiteLoader Version 2.1.0

**Comment by ShrBox** [comment]
存档有点问题

**Comment by assidence** [comment]
我是现在才架设的服务器，刚下载了官网的程序与ll，编译的是32位与64位共存的wine。

**Comment by PA733** [comment]
请尝试使用原版服务端启动服务器，以排查问题。

**Comment by dreamguxiang** [comment]
ubuntu20.04+wine7.0正常
![image](https://user-images.githubusercontent.com/62042544/153701533-cbd05bc2-7296-4c8c-b196-bf99761bdbfd.png)

**Comment by assidence** [comment]
https://gist.github.com/assidence/cf56b4fb8ff8942ce1d19d64a87d8be9
好像原版也是起不来

**Comment by PA733** [comment]
那么您反馈错地方了。
这里是LiteLoaderBDS的issue区。
[请移步](https://bugs.mojang.com//)

**Comment by dreamguxiang** [comment]
如果不会配置环境，请使用ll docker

**Comment by PA733** [comment]
另外，对于原版端缺少chakra的问题，[这个可能对您有帮助](https://github.com/chakra-core/ChakraCore)。
