### ISSUE TITLE
自定义表单“Dropdown”顺序错误

### ISSUE THREAD

**Issue by timiya233** [LiteLDev/LiteLoader#209]
**Describe the bug**
自定义表单Dropdown
选择回调不正确

**To Reproduce**
使用”Dropdown“
Steps to reproduce the behavior

**Expected behavior**
修复它

**Screenshots or log**
你逝逝就知道了（战术去世
If applicable, add screenshots or log to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. Windows Server 2019]
 - LiteLoader Version [e.g. 1.1.1]

**Additional content**
.
Add any other content about the problem here.

**Comment by yqs112358** [comment]
已修复，请尝试最新beta
