### ISSUE TITLE
在控制台输入allowlist list、permission list会导致服务端崩溃

### ISSUE THREAD

**Issue by Asurin219** [LiteLDev/LiteLoader#211]
# 问题
在控制台输入``allowlist list``、``permission list``会导致服务端崩溃

# 问题复现
在控制台输入指令``allowlist list``、``permission list``

# 控制台截图
![image](https://user-images.githubusercontent.com/77911856/153704072-3e9062f3-e91b-46b4-81f4-54d698903822.png)

# 环境
 - OS: [e.g. Windows Server 2022]
 - LiteLoader Version [e.g. 2.1.0]

**Comment by dreamguxiang** [comment]
Fixed 68738315f1eb6a455d82727afb3f37ce49adcf4c
