### ISSUE TITLE
无法运行SymDB2.exe

### ISSUE THREAD

**Issue by zyy82** [LiteLDev/LiteLoader#212]
> 
**Describe the bug**
当我把最新构建，解压到bds，尝试双击运行SymDB2.exe时，没有任何效果，没有弹出cmd，这在我之前安装ll历史版本时，没有出现这种情况

**To Reproduce**
在这里描述如何复现问题。
运行SymDB2.exe

**Expected behavior**
在这里描述你希望看到的现象。
应该弹出cmd

**Screenshots or log**
无

**Environment (please complete the following information):**
系统是 Windows Server 2019
LiteLoader 版本2.1.0

**Comment by Jaciezyt** [comment]
使用命令行运行SymDB2，看看有没有输出

**Comment by zyy82** [comment]
当我使用命令行打开SymDB2.exe，它成功被打开了

**Comment by zyy82** [comment]
但双击无效

**Comment by Jaciezyt** [comment]
> 当我使用命令行打开SymDB2.exe，它成功被打开了

结果如何

**Comment by zyy82** [comment]
> > 当我使用命令行打开SymDB2.exe，它成功被打开了
> 
> 结果如何

正常运行，并安装，没有什么异常
但双击无法运行

**Comment by Jaciezyt** [comment]
所以现在运行成功了对吧

**Comment by Jaciezyt** [comment]
可能是win的玄学bug

**Comment by zyy82** [comment]
> 所以现在运行成功了对吧

是的
