### ISSUE TITLE
新版11安装后，所以插件的UI都出现一个问题，所有插件目标选择器均为为第1个（不好描述）,例子:我是玩家A,像玩家B转帐，在选择玩家时，玩家A为列表第1个，提交转账申请后，却成为自己向自己转，

### ISSUE THREAD

**Issue by Herobrine96024** [LiteLDev/LiteLoader#213]
> **NOTICE**
> 1. 请勿反馈非加载器问题。   Feedback issues should belong to LiteLoader.
> 2. 请勿在这里反馈具有严重影响的游戏漏洞，相关问题请在聊天软件内私聊项目开发者并向及时向Mojang反馈。   Please do not report destructive Minecraft Bugs, please send a private message to the project developer in IM, and give feedback to Mojang in time.
> 3. 问题反馈格式必须遵循模板，否则可能被直接close。   Template feedback must be followed, otherwise the issue may be closed directly.
> 4. 请控制你的情绪（如果有），因为这于事无补。   Please keep your emotions in check as it won't solve the problem.
> 5. 请删除相关说明文字（包括本Notice），以免使版面混乱。   Please delete the relevant description text (including this Notice) before sending to avoid cluttering the layout.

**Describe the bug**
以简明清晰的语言描述问题。

**To Reproduce**
在这里描述如何复现问题。
Steps to reproduce the behavior

**Expected behavior**
在这里描述你希望看到的现象。

**Screenshots or log**
请提供一些屏幕截图，或者相关日志（这很必要）。
If applicable, add screenshots or log to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. Windows Server 2019]
 - LiteLoader Version [e.g. 1.1.1]

**Additional content**
附加信息
Add any other content about the problem here.

**Comment by dreamguxiang** [comment]
#209
