### ISSUE TITLE
关于一个反复崩服且日志一样的崩服事件

### ISSUE THREAD

**Issue by fengzi6** [LiteLDev/LiteLoader#214]
**Describe the bug**
今天下午突然服务器多次假死，机器人重启多次后无果最终崩服，在崩服发生时，服务器内只有两个假人。我手动开服后，再次过了30分钟后左右服务器再次发生崩服，崩服时服务器内同样没有真人，且经过比对，两份崩服日志一样。

**To Reproduce**
启动服务器等待即可

**Expected behavior**
当然是不会再次发生同样原因的崩服

**Screenshots or log**
![image](https://user-images.githubusercontent.com/99534515/153707793-289de767-2e9e-4596-8d61-bcf253ef107f.png)
![image](https://user-images.githubusercontent.com/99534515/153707495-924613ae-4f75-43f6-aaa0-cfee6c624043.png)

**Environment (please complete the following information):**
 - OS: [Windows 10 专业工作站版]
 - LiteLoader Version [2.1.0]

**Additional content**
附加信息
Add any other content about the problem here.

**Comment by Jaciezyt** [comment]
自行排查插件

**Comment by fengzi6** [comment]
> 自行排查插件

我就俩插件，behavior和backup没问题

**Comment by dreamguxiang** [comment]
等新版，看有没有修复

**Comment by ShrBox** [comment]
#211
