### ISSUE TITLE
/tpdim指令中枚举值对应字符串错误

### ISSUE THREAD

**Issue by wyf7685** [LiteLDev/LiteLoader#215]
**Describe the bug**
/tpdim指令中枚举值对应字符串错误
在 registry->addEnum 中将`DimensionType::OverWorld`误注册为`"overload"`(应为`"overworld"`)

**To Reproduce**
翻阅源码`/LiteLoader/Main/BuiltinCommands.cpp`第143行

**Expected behavior**
修复该错误

**Screenshots or log**
源码图片
![源码图片](https://user-images.githubusercontent.com/69091901/153707983-63a22ac9-907c-4b96-ae34-ec7955ec27c2.png)
控制台操作示例
![控制台操作示例](https://user-images.githubusercontent.com/69091901/153707996-252f5966-1384-494a-8b69-6e460e378ef6.png)

**Environment (please complete the following information):**
 - OS: Any
 - LiteLoader Version 2.1.0

**Additional content**
暂无

**Comment by Jaciezyt** [comment]
Fixed
