### ISSUE TITLE
菜单出现图片内容后服务器假死，此问题概率性触发

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [LiteLDev/LiteLoader#216]
![9F` R2B%9 FM HU$_{Z2(ZH](https://user-images.githubusercontent.com/99535761/153708173-9aa1b24b-3137-46c2-989d-d3b9bf55bc82.png)
后台无报错，服务器直接假死
且频繁进入服务器也会导致假死

**Comment by dreamguxiang** [comment]
假死后，导出dmp

**Comment by Jaciezyt** [comment]
什么图片内容

**Comment by dreamguxiang** [comment]
#221
