### ISSUE TITLE
`ll`热重载指令多余报错问题

### ISSUE THREAD

**Issue by Redbeanw44602** [LiteLDev/LiteLoader#219]
**Describe the bug**
当使用热重载指令（`load`）且包含`/`（或`\\`）符号时，会出现多余报错，加上双引号也会有。

**To Reproduce**
 - 加载一个插件，并自行指定路径

**Expected behavior**
不应当出现多余报错

**Screenshots or log**
```
> ll load "Project/iLand/iland-core.lua"
18:58:20 INFO [Server] Syntax error: Unexpected ".FiniShed.lua": at "-core.lua">>.FiniShed.lua<<"
```

**Environment (please complete the following information):**
 - OS: Windows 11
 - LiteLoader 2.1.0

**Comment by Jasonzyt** [comment]
这个看起来是mojang解析的问题（？）

**Comment by dreamguxiang** [comment]
#222

**Comment by yufengya0420** [comment]
![指令输出报错白色](https://user-images.githubusercontent.com/99462074/153739919-eb0e7258-d6a1-465e-adb0-e491bfa4a0d9.png)

**Comment by yufengya0420** [comment]
ll热加载指令依然存在问题

**Comment by xiaoqch** [comment]
已修复，如有问题请重新打开
