### ISSUE TITLE
LLSE makes console's command output abnormal

### ISSUE THREAD

**Issue by ShrBox** [LiteLDev/LiteLoader#222]
**Describe the bug**
When LLSE is turned on, console's command output abnormal

**To Reproduce**
1. Enable LLSE
2. Press enter key without typing anything

**Expected behavior**
Server output `unknown command`

**Screenshots or log**
![image](https://user-images.githubusercontent.com/53301243/153712412-bdab77a7-d990-4a90-a20c-a70a765eea62.png)

**Environment (please complete the following information):**
 - OS: Windows 11
 - LiteLoader Version: 2.1.0

**Comment by KawaiiNahida** [comment]
#219
