### ISSUE TITLE
Addon Installer 在遇到中文名addon包的时候会抛出异常

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LiteLoader#223]
临时解决方案：报错不安装
后续再看如何解决
目测是本地化编码问题，filesystem抛出异常 
{_What=0x000001a7403c6df0 "在多字节的目标代码页中，没有此 Unicode 字符可以映射到的字符。" _DoFree=true }

**Comment by Lition802** [comment]
![LM8VK%6~JRVNFCAOPYW`42B](https://user-images.githubusercontent.com/79248548/153800640-9acea282-6fe0-4543-88c2-1f84360749fb.png)
不光是中文包名，中文名的内部文件也会抛异常。
虽然维护版权是好的(
![7NY9U1N}AHUYBSO60ODI7@2](https://user-images.githubusercontent.com/79248548/153800729-563d73c9-17ea-4d3e-b628-b078b17eb423.png)
![D($SZ} CZ}Y7)RTJ~KD5$)U](https://user-images.githubusercontent.com/79248548/153800736-2bf1bd89-9e54-435a-b4e5-f2472f24654a.png)

**Comment by yqs112358** [comment]
这其实是一个更广泛问题的表现：
部分exception的.what()为本地化ASCII编码，需要通过宽字符中转转换成utf8方可输出，否则会在catch中抛出异常，导致crash
filesystem如为本地化编码，结果与utf8字符串拼接时同样会发生问题

**Comment by yqs112358** [comment]
欢迎大家提供更多相关信息，目前正在测试使用字符串编码检测库配合C API进行转换

**Comment by xiaoqch** [comment]
最新构建已修复，如仍有问题请重写打开此issue
