### ISSUE TITLE
脚本引擎的log函数功能

### ISSUE THREAD

**Issue by harry-xi** [LiteLDev/LiteLoader#226]
**Describe the bug**
以简明清晰的语言描述问题。

log函数输出多行文本时报错

**To Reproduce**
在这里描述如何复现问题。

使用一个log函数输出多行文本

**Expected behavior**
在这里描述你希望看到的现象。

使得其能够输出多行文本（或你们认为没必要请告诉我）

**Screenshots or log**
请提供一些屏幕截图，或者相关日志（这很必要）。
If applicable, add screenshots or log to help explain your problem.

```
21:26:33 ERROR [LiteLoader] C++ Uncaught Exception Detected!
21:26:33 ERROR [LiteLoader] invalid format string
21:26:33 ERROR [LiteLoader] In API: Log
```

**Comment by yqs112358** [comment]
多行文本实测不存在问题
能否给出复现代码

**Comment by xiaoqch** [comment]
应该是输出包含花括号的问题，等更新 #211

**Comment by harry-xi** [comment]
> 应该是输出包含花括号的问题，等更新 #211

是的，您说对了

**Comment by dreamguxiang** [comment]
#211
