### ISSUE TITLE
局域网端口bug

### ISSUE THREAD

**Issue by NomiyaAzusa** [LiteLDev/LiteLoader#227]
关闭fixlistenport
正常输出局域网端口
但是游戏里面监听不到

**Comment by dreamguxiang** [comment]
![image](https://user-images.githubusercontent.com/62042544/153713894-a0dd7686-f017-4ff9-a17d-dc1e293d7517.png)

这个也关闭

**Comment by NomiyaAzusa** [comment]
19132那个关了

**Comment by dreamguxiang** [comment]
![}9L$1P 52{ZS3)IROP`Q)NV](https://user-images.githubusercontent.com/62042544/153714428-cf68baf3-ef0b-41a8-9742-3c1996d8b9fb.jpg)
![image](https://user-images.githubusercontent.com/62042544/153714432-8a36144b-7c93-4d99-bcfc-8e4ca62af669.png)
![image](https://user-images.githubusercontent.com/62042544/153714438-9f506a91-fdef-4473-b298-5f1b8072017f.png)
我这正常
