### ISSUE TITLE
我认为LLMoney作为一个插件，不应该不装就爆红WARN，计分板党看者难受...可以做个开关嘛，默认打开不装LLMoney才爆红

### ISSUE THREAD

**Issue by MengYang8481** [LiteLDev/LiteLoader#232]
**Is your feature request related to a problem? Please describe.**
您认为现在存在什么问题？
A clear and concise description of what the problem is. Ex. I'm always frustrated when ...

**Describe the solution you'd like**
您认为还缺少什么？请用简短的语言说明。

**Describe alternatives you've considered**
您是否对此考虑过一些解决方案？请与我们分享。

**Additional context**
附加信息

**Comment by yqs112358** [comment]
llmoney是ll脚本引擎 经济系统API的必须组件，报错是提醒用户插件可能不按预期工作

**Comment by Jaciezyt** [comment]
下次请不要把内容全部堆在标题里奥

**Comment by MengYang8481** [comment]
> llmoney是ll脚本引擎 经济系统API的必须组件，报错是提醒用户插件可能不按预期工作

原来如此，我以为是个插件，thx

**Comment by yufengya0420** [comment]
> > llmoney是ll脚本引擎 经济系统API的必须组件，报错是提醒用户插件可能不按预期工作
> 
> 原来如此，我以为是个插件，thx

本来就是一个插件（经济组件），而且不应该是报黄吗，为什么是爆红
