### ISSUE TITLE
console command parse invalid

### ISSUE THREAD

**Issue by Sbaoor-fly** [LiteLDev/LiteLoader#236]
# Exceptions module 异常模块

Core 核心

|Q|A|
|:-:|:-:|
|OS|Windows Server 2019|
|LiteLoader version|2.1.1|
|BDS version|1.18.11|

# 复现此问题的步骤

输入一个控制台不存在的命令

## before 

``` shell
>> 114514
Unknown command: 114514. Please check that the command exists and that you have permission to use it.
```
## now

``` shell
>> 114514
 [Server] Syntax error: Unexpected "114514": at ">>114514<<"
```

![捕获](https://user-images.githubusercontent.com/70316422/153743441-0d87334f-d9ff-4cac-8a05-f99f329f1dfa.PNG)

**Comment by Jaciezyt** [comment]
#219 
#222 
和这俩挺像的

**Comment by yqs112358** [comment]
和#222是同一个问题

**Comment by dreamguxiang** [comment]
与 #222 重复，关闭
