### ISSUE TITLE
jsdebug error

### ISSUE THREAD

**Issue by Sbaoor-fly** [LiteLDev/LiteLoader#237]
# Exceptions module 异常模块

ScriptEngine 脚本引擎

|Q|A|
|:-:|:-:|
|OS|Windows Server 2019|
|LiteLoader version|2.1.0|
|BDS version|1.18.11|

## 发生了什么?请描述你的问题

使用jsdebug时，字符串被当作变量处理

## 复现此问题的步骤
```
>> jsdebug
>> mc.runcmd('list')
```

## 有关的日志/输出

```shell
shell
> mc.runcmd('list')
15:35:22 ERROR [LiteLoader] Uncaught ReferenceError: list is not defined
    at <anonymous>:1:1
    at <anonymous>:1:4

```
![捕获](https://user-images.githubusercontent.com/70316422/153743881-7f0b4f28-9c7d-4edf-9c57-77d28aaf58bd.PNG)

**Comment by xiaoqch** [comment]
这是jsdebug里调用控制台指令相关API的bug，其他api的字符串没有问题

**Comment by yqs112358** [comment]
感觉这个不太好处理，影响不大，先待办吧
