### ISSUE TITLE
v8 StackTraceBack会引起崩溃

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LiteLoader#238]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows Server 2019

### LiteLoader version 版本

2.x

### BDS version  BDS版本

1.18.x

### What happened? Please describe your problem. 发生了什么?请描述你的问题

如题，此问题偶尔触发，无法稳定复现

### Steps to reproduce? 复现此问题的步骤

偶发性问题

**Comment by yqs112358** [comment]
新情报: mc.crash()可以稳定复现

**Comment by dreamguxiang** [comment]
> 新情报: mc.crash()可以稳定复现

这是crash玩家那个？

**Comment by yqs112358** [comment]
不是，mc.crash()是崩服
写坏堆栈
![-64fc04b795bb5e72.jpg](https://user-images.githubusercontent.com/37969157/154096184-65ef15e8-f1a3-444d-a80b-11769e8866c8.jpg)

**Comment by yqs112358** [comment]
todo：检查erase_if是否正常工作
顺带处理一下timetask的enter enginescope with a destroyed engine

**Comment by yqs112358** [comment]
目前开始怀疑是因为崩溃时指令指针不在主线程，导致抓取堆栈时抓错线程，实际崩溃原因可能并非因为V8

**Comment by yqs112358** [comment]
目测为V8内部断点问题，已通过CrashLogger调试器修复
