### ISSUE TITLE
活塞事件失效

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LiteLoader#239]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows Server 2019

### LiteLoader version 版本

2.1.1

### BDS version  BDS版本

1.18.11

### What happened? Please describe your problem. 发生了什么?请描述你的问题

onPistonPush和onPistonTryPush两个活塞事件失效，可能是点位或者偏移变化了
- KING的报告

**Comment by ShrBox** [comment]
我检查了一下THook，是正常的，理论上`PistonTryPushEvent`和`PistonPushEvent`都是正常的（它们使用了相同的点位）

**Comment by ShrBox** [comment]
我写了个插件测试了下，也是正常的
