### ISSUE TITLE
自动安装addon报错

### ISSUE THREAD

**Issue by FBQingYi** [LiteLDev/LiteLoader#241]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows Server 2019

### LiteLoader version 版本

#1507

### BDS version  BDS版本

1.18.11

### What happened? Please describe your problem. 发生了什么?请描述你的问题

将addon放入AddonsHelper文件夹后运行bedrock_server_mod.exe出现报错。并不能正确安装addon

### Steps to reproduce? 复现此问题的步骤

1，将addon放入AddonsHelper文件夹
2，运行bedrock_server_mod.exe

### Relevant log output 有关的日志/输出

```shell
11:27:21 WARN [AddonHelper] 1 new addon(s) found to install. Working...
11:27:21 WARN [AddonHelper] Installing addon <Arkcraft 2.1.2.zip>...
11:27:27 ERROR [AddonHelper] Fail to uncompress addon Arkcraft 2.1.2.zip!
11:27:27 ERROR [AddonHelper] Exit Code: 2
11:27:27 ERROR [AddonHelper] Program Output:

11:27:27 ERROR [AddonHelper] * Install progress aborted!
11:27:27 ERROR [AddonHelper] No addon was installed.
```

**Comment by yufengya0420** [comment]
1507是什么版本不是最新2.1.1吗

**Comment by FBQingYi** [comment]
> 1507是什么版本不是最新2.1.1吗

Actions 里面目前最新的一个版本，2.1.1也存在这个问题

**Comment by yqs112358** [comment]
已修复，请等待下一个版本更新
