### ISSUE TITLE
Autoupdate cannot update multiple plugins at once

### ISSUE THREAD

**Issue by dreamguxiang** [LiteLDev/LiteLoader#242]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows 10

### LiteLoader version 版本

2.1.1

### BDS version  BDS版本

1.18.11

### What happened? Please describe your problem. 发生了什么?请描述你的问题

Cannot update multiple plugins at once

### Steps to reproduce? 复现此问题的步骤

null

### Relevant log output 有关的日志/输出

```shell
null
```

**Comment by yqs112358** [comment]
等待pluginMgr完工
