### ISSUE TITLE
事件"onRespawn"在满足触发条件时及游戏规则"立即重生"打开时多次触发

### ISSUE THREAD

**Issue by PosiedChoss** [LiteLDev/LiteLoader#243]
当游戏规则为"立即重生"时运行:
`
mc.listen("onRespawn",function(pl){
        log("玩家重生")
}
`
在玩家重生时,产生了7次的执行

而运行"onPlayerDie"时没有这种现象

```
02:46:51 INFO [RottenTimber] 玩家死亡
02:46:51 INFO [RottenTimber] 玩家重生
02:46:51 INFO [RottenTimber] 玩家重生
02:46:51 INFO [RottenTimber] 玩家重生
02:46:51 INFO [RottenTimber] 玩家重生
02:46:51 INFO [RottenTimber] 玩家重生
02:46:51 INFO [RottenTimber] 玩家重生
```

#### 复现

监听事件满足游戏规则并执行其相关监听内容

#### 预期的现象

只执行1次

#### 实际现象

若游戏规则为"立即重生",重生时"onRespawn"多次执行,测试为7次

#### 问题频率

每次

#### 版本及相关选项选择
- LiteXLoader: `0.2.1`

**Comment by dreamguxiang** [comment]
已修复，等待更新
