### ISSUE TITLE
“命令接口”的描述应该要和原版命令一样有两种描述

### ISSUE THREAD

**Issue by leoweyr** [LiteLDev/LiteLoader#245]
<img width="890" alt="image" src="https://user-images.githubusercontent.com/58080150/148343142-05691c1b-0f58-4a70-a82f-7bc21129445b.png">
如图上方的是”命令解释“描述，下方的是”命令补全“描述
而LXL目前只支持“命令解释”描述
<img width="454" alt="image" src="https://user-images.githubusercontent.com/58080150/148343276-902feb97-fd5f-4c1d-97e0-448a6881c41f.png">

**Comment by leoweyr** [comment]
命令补全描述输入到那时还会有“补全选择性提示”

**Comment by Redbeanw44602** [comment]
现在是假指令注册，这个等以后如果能实现真指令自然会有。

**Comment by ShrBox** [comment]
等寒假

**Comment by yqs112358** [comment]
大佬们已经有在尝试真指令系统，可以期待一下

**Comment by yqs112358** [comment]
已经更新了真指令接口，请试用
