### ISSUE TITLE
Cant found sym ??0MovePlayerPacket@@QEAA@AEAVPlayer@@AEBVVec3@@@Z

### ISSUE THREAD

**Issue by VoryWork** [LiteLDev/LiteLoader#252]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows 10

### LiteLoader version 版本

2.1.2

### BDS version  BDS版本

1.18.11

### What happened? Please describe your problem. 发生了什么?请描述你的问题

11:22:28 INFO [Command] <HitoMiao> /savepos1
11:22:51 INFO [Command] <HitoMiao> /fill 1963 194 2352 ~~~ stone 0 replace air
11:22:51 INFO [Command] <HitoMiao> /fill ~ 991 ~ ~~~ stone 0 replace air
11:22:51 ERROR [Chakra] Could not find function in memory: ??0MovePlayerPacket@@QEAA@AEAVPlayer@@AEBVVec3@@@Z
11:22:51 ERROR [Chakra] Cannot find symbol in SymDB: ??0MovePlayerPacket@@QEAA@AEAVPlayer@@AEBVVec3@@@Z
Cant found sym ??0MovePlayerPacket@@QEAA@AEAVPlayer@@AEBVVec3@@@Z

### Steps to reproduce? 复现此问题的步骤

随机出现，一分钟一次

**Comment by Jaciezyt** [comment]
插件列表？

**Comment by VoryWork** [comment]
AntiCheats-1.18.11.0210.dll

**Comment by VoryWork** [comment]
AntiCheats-1.18.11.0214.dll
LLHelper.dll
LLMoney.dll
All plugins had updated to latest version
