### ISSUE TITLE
Script Language Request

### ISSUE THREAD

**Issue by notacoderr** [LiteLDev/LiteLoader#254]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

Nope

### Describe the solution you'd like 您认为还缺少什么?

I would like to request to have 2 languages for the plugins
1) PHP
3) CoffeeScript

**Comment by ipad54** [comment]
I think that PHP support should be implemented soon, this will allow many PocketMine-MP users to switch to LiteLoader

**Comment by Jaciezyt** [comment]
> I think that PHP support should be implemented soon, this will allow many PocketMine-MP users to switch to LiteLoader

i don't think so unless someone create a pull request to https://github.com/Tencent/ScriptX for PHP support xD
going here https://github.com/Tencent/ScriptX/issues and creating a feature request is better

**Comment by yqs112358** [comment]
To be honest I am actually interested in your idea. 
But since LiteLoaderBDS's script engine is based on ScriptX Project, if ScriptX will support PHP in the future，and then our project will support too.
ScriptX project is open-sourced too on GitHub https://github.com/Tencent/ScriptX
