### ISSUE TITLE
突然崩溃

### ISSUE THREAD

**Issue by Nico6719** [LiteLDev/LiteLoader#258]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.1.2

### BDS version   BDS版本

1.18.11

### What happened? 发生了什么问题?

就突然崩溃

### Steps to reproduce? 复现此问题的步骤

1.开服
2.等待（这时我在恢复数据）
3.崩溃

### Relevant log output 有关的日志/输出

```shell
[Crashed!]
-- Unhandled Exception in -> ntdll.dll
-- Exception Code: 0xC0000374
-- Minidump generated in Directory ./logs/Crash
[TrackBack] Function RtlIsNonEmptyDirectoryReparsePointAllowed at 0x7FF8160DA890  [ntdll.dll]
[TrackBack] Function RtlIsNonEmptyDirectoryReparsePointAllowed at 0x7FF8160DA890  [ntdll.dll]
[TrackBack] Function RtlpNtMakeTemporaryKey at 0x7FF8160E2D30  [ntdll.dll]
[TrackBack] Function RtlpNtMakeTemporaryKey at 0x7FF8160E2D30  [ntdll.dll]
[TrackBack] Function RtlRaiseStatus at 0x7FF81607EDF0  [ntdll.dll]
[TrackBack] Function memset at 0x7FF816086800  [ntdll.dll]
[TrackBack] Function free_base at 0x7FF81304B370  [ucrtbase.dll]
[TrackBack] Function ColorFormat::transferMcColorToConsole at 0x7FFFEFFD9C90  [LiteLoader.dll]
[TrackBack] Function std::basic_streambuf<char,std::char_traits<char> >::xsputn at 0x7FFFF70896D0  [MSVCP140.dll]
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function onPostInit at 0x7FFFEE4A8100  [LiteLoader.Js.dll]
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function onPostInit at 0x7FFFEE4A8100  [LiteLoader.Js.dll]
[TrackBack] Function onPostInit at 0x7FFFEE4A8100  [LiteLoader.Js.dll]
[TrackBack] Function onPostInit at 0x7FFFEE4A8100  [LiteLoader.Js.dll]
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function o_exp at 0x7FF813062630  [ucrtbase.dll]
[TrackBack] Function BaseThreadInitThunk at 0x7FF813227960  [KERNEL32.DLL]
[TrackBack] Function RtlUserThreadStart at 0x7FF81603A2D0  [ntdll.dll]
```

### Plugin list 插件列表

22:15:58 INFO [Server] Plugin Lists [27]
22:15:58 INFO [Server]
22:15:58 INFO [Server] - LiteLoaderBDS [v2.1.2] (LiteLoader.dll)
22:15:58 INFO [Server]   Strong plugin loader for Bedrock Dedicated Server
22:15:58 INFO [Server]
22:15:58 INFO [Server] - AntiToolbox [v2.0.0] (AntiToolbox.dll)
22:15:58 INFO [Server]   Stop toolbox player from joining your server
22:15:58 INFO [Server]
22:15:58 INFO [Server] - LLtpa [v2.1.1] (LLTpa.dll)
22:15:58 INFO [Server]   A part of LLEssentials, provides teleport function
22:15:58 INFO [Server]
22:15:58 INFO [Server] - PFEssentials [v0.1.8080] (PFEssentials.LL.dll)
22:15:58 INFO [Server]   PF基础插件 v0.1.8080.10702
22:15:58 INFO [Server]
22:15:58 INFO [Server] - ScheduleCmd [v1.1.0] (ScheduleCmd.dll)
22:15:58 INFO [Server]   Schedule your command execute in language of crontab
22:15:58 INFO [Server]
22:15:58 INFO [Server] - ScriptEngine-Js [v2.1.2] (LiteLoader.Js.dll)
22:15:58 INFO [Server]   Javascript ScriptEngine For LiteLoaderBDS
22:15:58 INFO [Server]
22:15:58 INFO [Server] - BackupHelper [v2.0.5] (BackupHelper.dll)
22:15:58 INFO [Server]   One command to backup your level
22:15:58 INFO [Server]
22:15:58 INFO [Server] - Achievement.lxl.js [v1.0.0] (Achievement.lxl.js)
22:15:58 INFO [Server]   Achievement.lxl.js
22:15:58 INFO [Server]
22:15:58 INFO [Server] - AntiCreativeDestroy.lxl.js [v1.0.0] (AntiCreativeDestroy.lxl.js)
22:15:58 INFO [Server]   AntiCreativeDestroy.lxl.js
22:15:58 INFO [Server]
22:15:58 INFO [Server] - Tsidebar (2).js [v1.0.0] (Tsidebar (2).js)
22:15:58 INFO [Server]   Tsidebar (2).js
22:15:58 INFO [Server]
22:15:58 INFO [Server] - ChainGather (1).js [v1.0.0] (ChainGather (1).js)
22:15:58 INFO [Server]   ChainGather (1).js
22:15:58 INFO [Server]
22:15:58 INFO [Server] - Economic_core.js [v1.0.0] (Economic_core.js)
22:15:58 INFO [Server]   Economic_core.js
22:15:58 INFO [Server]
22:15:58 INFO [Server] - EntryAgreement.lxl.js [v1.0.0] (EntryAgreement.lxl.js)
22:15:58 INFO [Server]   EntryAgreement.lxl.js
22:15:58 INFO [Server]
22:15:58 INFO [Server] - FantasyMenu.js [v1.0.0] (FantasyMenu.js)
22:15:58 INFO [Server]   FantasyMenu.js
22:15:58 INFO [Server]
22:15:58 INFO [Server] - Start_and_Stop.js [v1.0.0] (Start_and_Stop.js)
22:15:58 INFO [Server]   Start_and_Stop.js
22:15:58 INFO [Server]
22:15:58 INFO [Server] - FMHunter.js [v1.0.0] (FMHunter.js)
22:15:58 INFO [Server]   FMHunter.js
22:15:58 INFO [Server]
22:15:58 INFO [Server] - WLHelper.js [v1.0.0] (WLHelper.js)
22:15:58 INFO [Server]   WLHelper.js
22:15:58 INFO [Server]
22:15:58 INFO [Server] - login.js [v1.0.0] (login.js)
22:15:58 INFO [Server]   login.js
22:15:58 INFO [Server]
22:15:58 INFO [Server] - LxlBlackBe.lxl.js [v1.0.0] (LxlBlackBe.lxl.js)
22:15:58 INFO [Server]   LxlBlackBe.lxl.js
22:15:58 INFO [Server]
22:15:58 INFO [Server] - LxlCheckBag.lxl.js [v1.0.0] (LxlCheckBag.lxl.js)
22:15:58 INFO [Server]   LxlCheckBag.lxl.js
22:15:58 INFO [Server]
22:15:58 INFO [Server] - mbdie.js [v1.0.0] (mbdie.js)
22:15:58 INFO [Server]   mbdie.js
22:15:58 INFO [Server]
22:15:58 INFO [Server] - OpManageYoyo.lxl.js [v1.0.0] (OpManageYoyo.lxl.js)
22:15:58 INFO [Server]   OpManageYoyo.lxl.js
22:15:58 INFO [Server]
22:15:58 INFO [Server] - origin_motd.lxl.js [v1.0.0] (origin_motd.lxl.js)
22:15:58 INFO [Server]   origin_motd.lxl.js
22:15:58 INFO [Server]
22:15:58 INFO [Server] - PIM.js [v1.0.0] (PIM.js)
22:15:58 INFO [Server]   PIM.js
22:15:58 INFO [Server]
22:15:58 INFO [Server] - ScriptEngine-Lua [v2.1.2] (LiteLoader.Lua.dll)
22:15:58 INFO [Server]   Lua ScriptEngine For LiteLoaderBDS
22:15:58 INFO [Server]
22:15:58 INFO [Server] - iland-core.lua [v1.0.0] (iland-core.lua)
22:15:58 INFO [Server]   iland-core.lua
22:15:58 INFO [Server]
22:15:58 INFO [Server] - LXLShop.lxl.lua [v1.0.0] (LXLShop.lxl.lua)
22:15:58 INFO [Server]   LXLShop.lxl.lua
22:15:58 INFO [Server]

**Comment by Nico6719** [comment]
[两次了.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/8070202/default.zip)

**Comment by dreamguxiang** [comment]
如何触发、
输入了什么质量

**Comment by yqs112358** [comment]
可能是颜色代码相关问题，等待修复

**Comment by dreamguxiang** [comment]
等待新版本
