### ISSUE TITLE
在wine7.0环境中运行失败

### ISSUE THREAD

**Issue by X-Funny** [LiteLDev/LiteLoader#260]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Linux(Ubuntu/CentOS/...) with wine

### LiteLoader version   LiteLoader版本

LiteLoaderBDS 2.1.0

### BDS version   BDS版本

1.18.11.01

### What happened? 发生了什么问题?

我于上周六配置了上述版本的BDS和liteloader，能正常运行，但今天忽然就不行了。(期间未进行任何修改)
系统 Debian11  amd64
wine version 7.0

0104:err:sync:RtlpWaitForCriticalSection section 0000000170065600 "dlls/ntdll/loader.c: loader_section" wait timed out in thread 0104, blocked by 0118, retrying (60 sec)
0118:err:sync:RtlpWaitForCriticalSection section 00000001423C3010 "?" wait timed out in thread 0118, blocked by 0000, retrying (60 sec)

### Steps to reproduce? 复现此问题的步骤

root@iZtdmgdupgbdx9Z:~# cd /mcserver/test2
root@iZtdmgdupgbdx9Z:/mcserver/test2# wine bedrock_server_mod.exe
0088:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0088:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0088:err:systray:initialize_systray Could not create tray window
[38;2;173;216;230m12:44:36[0m[38;2;032;178;170m INFO [0m[37m[C
hakra] LLAutoUpdate.dll Injected.
[0m0104:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F3F0 1 C) semi-stub
0104:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F3E0 1 C) semi-stub
[38;2;173;216;230m12:44:36[0m[38;2;032;178;170m INFO [0m[3
7m[Chakra] [SymDB] Loading symbols...
[0m[38;2;173;216;230m12:44:39[0m[38;2;032;178;170m INFO [0m[3
7m[Chakra] [SymDB] FastDlsymInited <244304>
[0m[38;2;173;216;230m12:44:39[0m[38;2;032;178;170m INFO [0m[3
7m[Chakra] LiteLoader.dll Injected.
[0m0104:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0104:err:sync:RtlpWaitForCriticalSection section 0000000170065600 "dlls/ntdll/loader.c: loader_section" wait timed out in thread 0104, blocked by 0118, retrying (60 sec)
0118:err:sync:RtlpWaitForCriticalSection section 00000001423C3010 "?" wait timed out in thread 0118, blocked by 0000, retrying (60 sec)

### Relevant log output 有关的日志/输出

```shell
0104:err:sync:RtlpWaitForCriticalSection section 0000000170065600 "dlls/ntdll/loader.c: loader_section" wait timed out in thread 0104, blocked by 0118, retrying (60 sec)
0118:err:sync:RtlpWaitForCriticalSection section 00000001423C3010 "?" wait timed out in thread 0118, blocked by 0000, retrying (60 sec)
```

### Plugin list 插件列表

![Screenshot_2022-02-16-12-46-16-225_com mixplorer](https://user-images.githubusercontent.com/79325059/154197957-b7db9d8b-ab11-458a-bb00-9c51fa8b510c.jpg)

**Comment by X-Funny** [comment]
莫名其妙的又可以使用了

**Comment by yqs112358** [comment]
阿哲，行
如果有问题再报告

**Comment by yqs112358** [comment]
还有，你可以去配置文件关闭颜色代码，这样看起来舒服很多

**Comment by X-Funny** [comment]
切换了最新版本只成功运行了一次，重启服务器后再次运行出现上述问题

**Comment by dreamguxiang** [comment]
wine未知原因，暂时没法修复，遇到只能强制重启

**Comment by X-Funny** [comment]
> wine 原因，暂时无法修复，发生只能重新开始

但是重启后再次开服还是存在该问题

**Comment by dreamguxiang** [comment]
wine64 bedrock_server_mod.ex
e | tee -a bds.log

**Comment by X-Funny** [comment]
19:26:51 INFO [37m[Chakra] LLAutoUpdate.dll Injected.
[0m19:26:51 INFO [37m[Chakra] [SymDB] Loading symbols...
[0m19:26:54 INFO [37m[Chakra] [SymDB] FastDlsymInited <244304>
[0m

**Comment by X-Funny** [comment]
我将 LLAutoUpdate.dll删除后可以正常启动

**Comment by X-Funny** [comment]
使用wine运行该版本liteloader需要删除LLAutoUpdate.dll并清空preload.conf,否则只能启动一次。
