### ISSUE TITLE
Console Output Event for ScriptEngine

### ISSUE THREAD

**Issue by n0madxx** [LiteLDev/LiteLoader#261]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

Nope

### Describe the solution you'd like 您认为还缺少什么?

往LXL新增控制台输出事件

**Comment by Yushu2606** [comment]
https://docs.litebds.com/zh_CN/Development/EventAPI/OtherEvents.html#onconsoleoutput-%E6%8E%A7%E5%88%B6%E5%8F%B0%E4%BA%A7%E7%94%9F%E5%91%BD%E4%BB%A4%E8%BE%93%E5%87%BA

**Comment by Yushu2606** [comment]
need to close
