### ISSUE TITLE
item.clone()的结果为nulll

### ISSUE THREAD

**Issue by KINGANDWL** [LiteLDev/LiteLoader#262]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows 10

### LiteLoader version   LiteLoader版本

2.1.2

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

item.clone()的结果为nulll

### Steps to reproduce? 复现此问题的步骤

`onUseItem(player,item){
            this.printObject(this.NBTHelper.getJsObjNbt(item.getNbt()))
            this.print(item==null) //false
            let item_temp = mc.newItem(item.getNbt());
            this.print(item_temp==null) //true
}`

### Plugin list 插件列表

ll list
19:09:07 INFO [Server] Plugin Lists [24]
19:09:07 INFO [Server]
19:09:07 INFO [Server] - MovingLight [v1.7.3] (MovingLight.dll)
19:09:07 INFO [Server]   The moving light.
19:09:07 INFO [Server]
19:09:07 INFO [Server] - LiteLoaderBDS [v2.1.2] (LiteLoader.dll)
19:09:07 INFO [Server]   Strong plugin loader for Bedrock Dedicated Server
19:09:07 INFO [Server]
19:09:07 INFO [Server] - FakeSeed [v1.0.5] (FakeSeed.dll)
19:09:07 INFO [Server]   Hide Map seed
19:09:07 INFO [Server]
19:09:07 INFO [Server] - mytest.js [v1.0.0] (mytest.js)
19:09:07 INFO [Server]   mytest.js
19:09:07 INFO [Server]
19:09:07 INFO [Server] - AntiToolbox [v2.0.0] (AntiToolbox.dll)
19:09:07 INFO [Server]   Stop toolbox player from joining your server
19:09:07 INFO [Server]
19:09:07 INFO [Server] - FuckDiscount-NoDiscount.dll [v1.0.0] (FuckDiscount-NoDiscount.dll)
19:09:07 INFO [Server]   FuckDiscount-NoDiscount.dll
19:09:07 INFO [Server]
19:09:07 INFO [Server] - ScriptEngine-Js [v2.1.2] (LiteLoader.Js.dll)
19:09:07 INFO [Server]   Javascript ScriptEngine For LiteLoaderBDS
19:09:07 INFO [Server]
19:09:07 INFO [Server] - LLAntiCheat_pr23_fix2.dll [v1.0.0] (LLAntiCheat_pr23_fix2.dll)
19:09:07 INFO [Server]   LLAntiCheat_pr23_fix2.dll
19:09:07 INFO [Server]
19:09:07 INFO [Server] - LLMoney [v2.1.1] (LLMoney.dll)
19:09:07 INFO [Server]   EconomyCore for LiteLoaderBDS
19:09:07 INFO [Server]
19:09:07 INFO [Server] - Sweeper.lxl.js [v1.0.0] (Sweeper.lxl.js)
19:09:07 INFO [Server]   Sweeper.lxl.js
19:09:07 INFO [Server]
19:09:07 INFO [Server] - BackupHelper [v2.0.6] (BackupHelper.dll)
19:09:07 INFO [Server]   One command to backup your level
19:09:07 INFO [Server]
19:09:07 INFO [Server] - OutputFilter.dll [v1.0.0] (OutputFilter.dll)
19:09:07 INFO [Server]   OutputFilter.dll
19:09:07 INFO [Server]
19:09:07 INFO [Server] - BanExplosion [v1.5.7] (BanExplosion.dll)
19:09:07 INFO [Server]   Customize your explosion destroy rule!
19:09:07 INFO [Server]
19:09:07 INFO [Server] - AdminUI.lxl.js [v1.0.0] (AdminUI.lxl.js)
19:09:07 INFO [Server]   AdminUI.lxl.js
19:09:07 INFO [Server]
19:09:07 INFO [Server] - BehaviorLog.lxl.js [v1.0.0] (BehaviorLog.lxl.js)
19:09:07 INFO [Server]   BehaviorLog.lxl.js
19:09:07 INFO [Server]
19:09:07 INFO [Server] - BorderLimit.lxl.js [v1.0.0] (BorderLimit.lxl.js)
19:09:07 INFO [Server]   BorderLimit.lxl.js
19:09:07 INFO [Server]
19:09:07 INFO [Server] - EditSign.lxl.js [v1.0.0] (EditSign.lxl.js)
19:09:07 INFO [Server]   EditSign.lxl.js
19:09:07 INFO [Server]
19:09:07 INFO [Server] - LockYourChest.lxl.js [v1.0.0] (LockYourChest.lxl.js)
19:09:07 INFO [Server]   LockYourChest.lxl.js
19:09:07 INFO [Server]
19:09:07 INFO [Server] - LxlBlackBe.lxl.js [v1.0.0] (LxlBlackBe.lxl.js)
19:09:07 INFO [Server]   LxlBlackBe.lxl.js
19:09:07 INFO [Server]
19:09:07 INFO [Server] - LxlCheckBag.lxl.js [v1.0.0] (LxlCheckBag.lxl.js)
19:09:07 INFO [Server]   LxlCheckBag.lxl.js
19:09:07 INFO [Server]
19:09:07 INFO [Server] - VersionCheck.lxl.js [v1.0.0] (VersionCheck.lxl.js)
19:09:07 INFO [Server]   VersionCheck.lxl.js
19:09:07 INFO [Server]
19:09:07 INFO [Server] - ScheduleCmd [v1.1.0] (ScheduleCmd.dll)
19:09:07 INFO [Server]   Schedule your command execute in language of crontab
19:09:07 INFO [Server]
19:09:07 INFO [Server] - ScriptEngine-Lua [v2.1.2] (LiteLoader.Lua.dll)
19:09:07 INFO [Server]   Lua ScriptEngine For LiteLoaderBDS
19:09:07 INFO [Server]
19:09:07 INFO [Server] - DoAsVue.lxl.js [v1.0.0] (DoAsVue.lxl.js)
19:09:07 INFO [Server]   DoAsVue.lxl.js
19:09:07 INFO [Server]
19:09:07 INFO [Server] * Send command "ll list <Plugin Name>" for more information

**Comment by Jaciezyt** [comment]
@xiaoqch fixed
