### ISSUE TITLE
setTimeout可能不运行

### ISSUE THREAD

**Issue by timiya233** [LiteLDev/LiteLoader#264]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows 10

### LiteLoader version   LiteLoader版本

2.1.2

### BDS version   BDS版本

1.18.11

### What happened? 发生了什么问题?

setTimeout可能不会运行

### Steps to reproduce? 复现此问题的步骤

1.创建test.js文件
2.写入：setTimeout(()=>{
    log("Suc")
},50);
3.重载尝试多次，总会遇到的...

### Relevant log output 有关的日志/输出

```shell
let a = false;
function aaa() {
    log(JSON.stringify(a);
    if (!a) {
        a = true;
        setTimeout(()=>{a=false},50);
    }
}//多次触发aaa函数

21:23:17 INFO [TMEssential] false
21:23:20 INFO [TMEssential] true
21:23:24 INFO [TMEssential] true
```

### Plugin list 插件列表

无关

**Comment by timiya233** [comment]
![$UYXAG55YL~$6FF1SG0)_2E](https://user-images.githubusercontent.com/70333491/154696537-0a316f60-c96d-429e-8d59-dfede98fbca6.jpg)

**Comment by yqs112358** [comment]
<img width="223" alt="image" src="https://user-images.githubusercontent.com/37969157/155866869-5dfef280-ae68-40f2-88ad-9d6a68916a35.png">
不要滥用重载，重载仅供调试插件使用

正常开服后周期调用无法复现

**Comment by yqs112358** [comment]
我觉得是你异步使用savetask变量的问题。。。

**Comment by yqs112358** [comment]
一直无法复现，请给出复现方法

**Comment by xiaoqch** [comment]
reload与setTimeout相关的问题已修复，请确认问题是否仍然存在
