### ISSUE TITLE
ll.require和ll.registerPlugin

### ISSUE THREAD

**Issue by timiya233** [LiteLDev/LiteLoader#270]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows 10

### LiteLoader version   LiteLoader版本

2.1.2

### BDS version   BDS版本

1.18.11

### What happened? 发生了什么问题?

ll.require会让用了ll.registerPlugin的llse插件重复加载....

### Steps to reproduce? 复现此问题的步骤

1.写一个test.js和test1.js
2.分别写入：
test:
ll.registerPlugin(xxxxxxxxx);

test1:
ll.require("test.js")//重复加载
3.成功复现

### Relevant log output 有关的日志/输出

```shell
无
```

### Plugin list 插件列表

无关紧要

**Comment by yqs112358** [comment]
最新BETA已修复
