### ISSUE TITLE
运行时插件执行热管理命令造成问题

### ISSUE THREAD

**Issue by Redbeanw44602** [LiteLDev/LiteLoader#271]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows 11

### LiteLoader version   LiteLoader版本

2.1.2

### BDS version   BDS版本

1.18.11

### What happened? 发生了什么问题?

远程函数在调用时出现假死。

### Steps to reproduce? 复现此问题的步骤

1. [插件A] 导出函数A
2. [插件B] 导入并调用函数A
3. 似乎只能在开服后（也就是使用ll load+路径）加载的插件才会有这个问题，100%出现

### Relevant log output 有关的日志/输出

```shell
/
```

### Plugin list 插件列表

/

**Comment by yqs112358** [comment]
<img width="602" alt="image" src="https://user-images.githubusercontent.com/37969157/155864548-2cca9b30-6f34-4764-bfb4-8b9551de570e.png">
<img width="881" alt="image" src="https://user-images.githubusercontent.com/37969157/155864550-ea350ee2-e51b-40f9-8b3a-bda17fb10589.png">
无法复现，能否给出更详细的复现方法说明

**Comment by yqs112358** [comment]
无法复现，暂时关闭

**Comment by Redbeanw44602** [comment]
在插件内使用 `ll load` 在 `onServerStarted` 时加载TestImport插件，可以稳定复现问题。

**Comment by yqs112358** [comment]
仍然无法复现
还有，在代码内使用ll load命令是不规范的行为，热加载系统仅供调试使用，不保证生产环境运行稳定性
正确的做法是在插件开头使用ll.require加载依赖库

**Comment by yqs112358** [comment]
已复现，将尽量修复
考虑更换热管理命令内部实现

**Comment by xiaoqch** [comment]
> 在插件内使用 `ll load` 在 `onServerStarted` 时加载TestImport插件，可以稳定复现问题。

最新构建中已无法复现，此issue关闭，如问题仍存在，请重新打开此issue

**Comment by Redbeanw44602** [comment]
经测试，此问题已解决。
