### ISSUE TITLE
关于插件BehaviorLog出现问题！

### ISSUE THREAD

**Issue by CNDogc** [LiteLDev/LiteLoader#272]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows 10

### LiteLoader version   LiteLoader版本

v2.1.2

### BDS version   BDS版本

1.18.11

### What happened? 发生了什么问题?

<img width="714" alt="屏幕截图 2022-02-20 013304" src="https://user-images.githubusercontent.com/92175245/154812160-9c29afe4-4d2c-4501-897f-621cb7078b25.png">

在使用插件BehaviorLog时偶然发现监控内容从中文变成了英文

<img width="668" alt="屏幕截图 2022-02-20 012802" src="https://user-images.githubusercontent.com/92175245/154812093-0a0f9416-364b-4528-b544-807b2920597a.png">

### Steps to reproduce? 复现此问题的步骤

安装ll之后加入BehaviorLog运行即可

### Plugin list 插件列表

[38;2;173;216;230m01:19:35[0m [38;2;032;178;170mINFO[0m [37m[Server][0m [37m[0m
[38;2;173;216;230m01:19:35[0m [38;2;032;178;170mINFO[0m [37m[Server][0m [37m- ScriptEngine-Lua [v2.1.2] (LiteLoader.Lua.dll)[0m
[38;2;173;216;230m01:19:35[0m [38;2;032;178;170mINFO[0m [37m[Server][0m [37m  Lua ScriptEngine For LiteLoaderBDS[0m
[38;2;173;216;230m01:19:35[0m [38;2;032;178;170mINFO[0m [37m[Server][0m [37m[0m
[38;2;173;216;230m01:19:35[0m [38;2;032;178;170mINFO[0m [37m[Server][0m [37m- iland-core.lua [v1.0.0] (iland-core.lua)[0m
[38;2;173;216;230m01:19:35[0m [38;2;032;178;170mINFO[0m [37m[Server][0m [37m  iland-core.lua[0m
[38;2;173;216;230m01:19:35[0m [38;2;032;178;170mINFO[0m [37m[Server][0m [37m[0m
[38;2;173;216;230m01:19:35[0m [38;2;032;178;170mINFO[0m [37m[Server][0m [37m- LXLShop.lxl.lua [v1.0.0] (LXLShop.lxl.lua)[0m
[38;2;173;216;230m01:19:35[0m [38;2;032;178;170mINFO[0m [37m[Server][0m [37m  LXLShop.lxl.lua[0m
[38;2;173;216;230m01:19:35[0m [38;2;032;178;170mINFO[0m [37m[Server][0m [37m[0m
[38;2;173;216;230m01:19:35[0m [38;2;032;178;170mINFO[0m [37m[Server][0m [37m- RandomEnchant.lxl.lua [v1.0.0] (RandomEnchant.lxl.lua)[0m
[38;2;173;216;230m01:19:35[0m [38;2;032;178;170mINFO[0m [37m[Server][0m [37m  RandomEnchant.lxl.lua[0m
[38;2;173;216;230m01:19:35[0m [38;2;032;178;170mINFO[0m [37m[Server][0m [37m[0m
[38;2;173;216;230m01:19:35[0m [38;2;032;178;170mINFO[0m [37m[Server][0m [37m- XLore.lxl.lua [v1.0.0] (XLore.lxl.lua)[0m
[38;2;173;216;230m01:19:35[0m [38;2;032;178;170mINFO[0m [37m[Server][0m [37m  XLore.lxl.lua[0m
[38;2;173;216;230m01:19:35[0m [38;2;032;178;170mINFO[0m [37m[Server][0m [37m[0m
[38;2;173;216;230m01:19:35[0m [38;2;032;178;170mINFO[0m [37m[Server][0m [37m* Send command "ll list <Plugin Name>" for more information[0m
[38;2;173;216;230m01:19:35[0m [38;2;032;178;170mINFO[0m [37m[Server][0m [37m[0m

**Comment by ShrBox** [comment]
插件问题不应该在此处反馈

**Comment by CNDogc** [comment]
> 插件问题不应该在此处反馈

yq让我往这里投欸...

**Comment by CNDogc** [comment]
> 插件问题不应该在此处反馈

说是有可能是加载器导致的这个问题

**Comment by yufengya0420** [comment]
吧ll配置文件改成中文语言包
