### ISSUE TITLE
item.setNbt()之后item.count未同步

### ISSUE THREAD

**Issue by KINGANDWL** [LiteLDev/LiteLoader#274]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows 10

### LiteLoader version   LiteLoader版本

2.1.2

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

`item.setNbt(currentItem_JN.getNbt()); //将剩下的量给玩家
                                    this.print(item_temp.getNbt().toSNBT());
                                    this.print(item_temp.count);`

### Steps to reproduce? 复现此问题的步骤

1、修改一个item的nbt的Count数量属性
2、item.setNbt(修改Count之后的新的Nbt)
3、查看该item.getNbt().toSNBT()确认数量已经改变
4、打印item.count发现数据未同步

**Comment by yqs112358** [comment]
xiaoqch has fixed this problem
Wait for new version upgrade
