### ISSUE TITLE
ServerCrash in EntitySystems::tick

### ISSUE THREAD

**Issue by Chlna6666** [LiteLDev/LiteLoader#278]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.12

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

不管玩家多少
就是崩 #258 
不是攻击

### Relevant log output 有关的日志/输出

```shell
[Crashed!]
-- Unhandled Exception in -> bedrock_server_mod.exe
-- Exception Code: 0xC0000005
-- C++ STL Exception detected!

[TrackBack] Function BreakDoorAnnotationComponent::_shouldBreakDoor at 0x7FF798CCC2C0  [bedrock_server_mod.exe]
-- At File (null) : Line -1619200912 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function BreakDoorAnnotationComponent::obstructionCheck at 0x7FF798CD89F0  [bedrock_server_mod.exe]
-- At File (null) : Line -1619200912 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function BreakDoorAnnotationSystemCpp::_tick at 0x7FF798C3CC20  [bedrock_server_mod.exe]
-- At File (null) : Line -1619200912 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ??$iterate@P6AXAEAV?$ViewedEntityContextT@VEntityContext@@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@VBehaviorComponent@@@@@ZV?$basic_view@VEntityId@@U?$get_t@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@VBehaviorComponent@@@entt@@U?$exclude_t@$$V@3@X@entt@@V23@$$V@?$View@$00VEntityContext@@VEntityRegistry@@U?$exclude_t@$$V@entt@@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@VBehaviorComponent@@@EntityRegistryBase@@AEAAXP6AXAEAV?$ViewedEntityContextT@VEntityContext@@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@VBehaviorComponent@@@@@ZAEBV?$basic_view@VEntityId@@U?$get_t@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@VBehaviorComponent@@@entt@@U?$exclude_t@$$V@3@X@entt@@2@Z at 0x7FF798C38E40  [bedrock_server_mod.exe]
-- At File (null) : Line -1619200912 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function BreakDoorAnnotationSystem::tick at 0x7FF798C41A70  [bedrock_server_mod.exe]
-- At File (null) : Line -1619200912 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function std::_Func_impl_no_alloc<<lambda_402054a1cc8ac232f46e648b3b6daed6>,void,ITickingSystem &>::_Do_call at 0x7FF798C51700  [bedrock_server_mod.exe]
-- At File (null) : Line -1619200912 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function `anonymous namespace'::DefaultEntitySystemsCollection::foreachTickingSystem at 0x7FF798EEDB80  [bedrock_server_mod.exe]
-- At File (null) : Line -1619200912 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function EntitySystems::tick at 0x7FF798C554B0  [bedrock_server_mod.exe]
-- At File (null) : Line -1619200912 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function Level::tickEntitySystems at 0x7FF79953D490  [bedrock_server_mod.exe]
-- At File (null) : Line -1619200912 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function Level::tick at 0x7FF79953C140  [bedrock_server_mod.exe]
-- At File (null) : Line -1619200912 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ServerLevel::tick at 0x7FF798BDB3C0  [bedrock_server_mod.exe]
-- At File (null) : Line -1619200912 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function Schedule::nextTick at 0x7FFFDAE7D2F0  [LiteLoader.dll]
-- At File (null) : Line -1619200912 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function Minecraft::update at 0x7FF7990E0830  [bedrock_server_mod.exe]
-- At File (null) : Line -1619200912 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ServerInstance::_update at 0x7FF798BB5610  [bedrock_server_mod.exe]
-- At File (null) : Line -1619200912 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function <lambda_5d63f534eeadf9e385a3ddce5663beb8>::operator() at 0x7FF798BAD5F0  [bedrock_server_mod.exe]
-- At File (null) : Line -1619200912 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function std::thread::_Invoke<std::tuple<<lambda_5d63f534eeadf9e385a3ddce5663beb8> >,0> at 0x7FF798B92240  [bedrock_server_mod.exe]
-- At File (null) : Line -1619200912 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function o_exp at 0x7FFFF7E60360  [ucrtbase.dll]
-- At File (null) : Line -1619200912 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function BaseThreadInitThunk at 0x7FFFFAA87E80  [KERNEL32.DLL]
-- At File (null) : Line -1619200912 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function RtlUserThreadStart at 0x7FFFFB687AB0  [ntdll.dll]
-- At File (null) : Line -1619200912 
[TrackBack] Function ???????? at 0x????????
```

### Plugin list 插件列表

07:02:35 INFO [Server] Plugin Lists [21]
07:02:35 INFO [Server]
07:02:35 INFO [Server] - LiteLoaderBDS [v2.1.2] (LiteLoaderBDS閺佹潙鎮庨崠鍖糒iteLoader.dll)
07:02:35 INFO [Server]   Strong plugin loader for Bedrock Dedicated Server
07:02:35 INFO [Server]
07:02:35 INFO [Server] - BackupHelper [v2.0.6] (BackupHelper.dll)
07:02:35 INFO [Server]   One command to backup your level
07:02:35 INFO [Server]
07:02:35 INFO [Server] - BDSLM [v0.3.0] (BDSLM.dll)
07:02:35 INFO [Server]   Satellite Map for Bedrock Dedicated Server
07:02:35 INFO [Server]
07:02:35 INFO [Server] - LLAntiCheat_pr23_fix4.dll [v1.0.0] (LLAntiCheat_pr23_fix4.dll)
07:02:35 INFO [Server]   LLAntiCheat_pr23_fix4.dll
07:02:35 INFO [Server]
07:02:35 INFO [Server] - Achievement.lxl.js [v1.0.0] (Achievement.lxl.js)
07:02:35 INFO [Server]   Achievement.lxl.js
07:02:35 INFO [Server]
07:02:35 INFO [Server] - BetterStop [v2.0.2] (BetterStop.dll)
07:02:35 INFO [Server]   Have a better and safer "stop" command.
07:02:35 INFO [Server]
07:02:35 INFO [Server] - AlwaysBroadcast [v1.0.4] (AlwaysBroadcast.dll)
07:02:35 INFO [Server]   Fix an broadcast bug in bds.
07:02:35 INFO [Server]
07:02:35 INFO [Server] - Operation Agent [v1.2.1] (OperationAgent.dll)
07:02:35 INFO [Server]   Operation Agent
07:02:35 INFO [Server]
07:02:35 INFO [Server] - BanExplosion [v1.5.7] (BanExplosion.dll)
07:02:35 INFO [Server]   Customize your explosion destroy rule!
07:02:35 INFO [Server]
07:02:35 INFO [Server] - ScheduleCmd [v1.1.1] (ScheduleCmd.dll)
07:02:35 INFO [Server]   Schedule your command execute in language of crontab
07:02:35 INFO [Server]
07:02:35 INFO [Server] - LXLRobot.lxl.js [v1.0.0] (LXLRobot.lxl.js)
07:02:35 INFO [Server]   LXLRobot.lxl.js
07:02:35 INFO [Server]
07:02:35 INFO [Server] - ScriptEngine-Js [v2.1.2] (LiteLoader.Js.dll)
07:02:35 INFO [Server]   Javascript ScriptEngine For LiteLoaderBDS
07:02:35 INFO [Server]
07:02:35 INFO [Server] - BehaviorLog.lxl.js [v1.0.0] (BehaviorLog.lxl.js)
07:02:35 INFO [Server]   BehaviorLog.lxl.js
07:02:35 INFO [Server]
07:02:35 INFO [Server] - PVP.js [v1.0.0] (PVP.js)
07:02:35 INFO [Server]   PVP.js
07:02:35 INFO [Server]
07:02:35 INFO [Server] - EntryAgreement.lxl.js [v1.0.0] (EntryAgreement.lxl.js)
07:02:35 INFO [Server]   EntryAgreement.lxl.js
07:02:35 INFO [Server]
07:02:35 INFO [Server] - GPS.js [v1.0.0] (GPS.js)
07:02:35 INFO [Server]   GPS.js
07:02:35 INFO [Server]
07:02:35 INFO [Server] - HealthBar.lxl.js [v1.0.0] (HealthBar.lxl.js)
07:02:35 INFO [Server]   HealthBar.lxl.js
07:02:35 INFO [Server]
07:02:35 INFO [Server] - LxlBlackBe.lxl.js [v1.0.0] (LxlBlackBe.lxl.js)
07:02:35 INFO [Server]   LxlBlackBe.lxl.js
07:02:35 INFO [Server]
07:02:35 INFO [Server] - ProtectionFarmLand.lxl.js [v1.0.0] (ProtectionFarmLand.lxl.js)
07:02:35 INFO [Server]   ProtectionFarmLand.lxl.js
07:02:35 INFO [Server]
07:02:35 INFO [Server] - ranking.lxl.js [v1.0.0] (ranking.lxl.js)
07:02:35 INFO [Server]   ranking.lxl.js
07:02:35 INFO [Server]
07:02:35 INFO [Server] - ScriptEngine-Lua [v2.1.2] (LiteLoader.Lua.dll)
07:02:35 INFO [Server]   Lua ScriptEngine For LiteLoaderBDS
07:02:35 INFO [Server]

**Comment by PA733** [comment]
是否有复现方法

**Comment by xiaoqch** [comment]
疑似BDS的bug，看一下行为日志，服务器崩溃的时候是否有玩家在切换维度？

**Comment by yqs112358** [comment]
#290
