### ISSUE TITLE
The latest beta version occured an Uncaught Error in Leveldb

### ISSUE THREAD

**Issue by VoryWork** [LiteLDev/LiteLoader#280]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

Commit ba5607d pushed by xiaoqch

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

21:56:14 ERROR [LiteLoader] Uncaught Exception Detected!
21:56:14 ERROR [LiteLoader] In API: DbClass::set
21:56:14 ERROR [LiteLoader] In Plugin: bag.js

### Steps to reproduce? 复现此问题的步骤

随意开一个KV数据库，执行Set操作

### Relevant log output 有关的日志/输出

```shell
21:56:14 ERROR [LiteLoader] Uncaught Exception Detected!
21:56:14 ERROR [LiteLoader] In API: DbClass::set
21:56:14 ERROR [LiteLoader] In Plugin: bag.js
```

**Comment by xiaoqch** [comment]
无法复现，测试代码，请确认是否是插件问题，或提供可复现问题的具体代码，
测试代码：
```javascript
let db = data.openDB("./plugins/EnchantUtil/enchants.db");
db.set("enchant", "test");
logger.warn(db.get("enchant"));
db.close();
```

**Comment by VoryWork** [comment]
var ldb = new KVDatabase("./plugins/js_data/bag-tools/db/");
var gameTeamScore = "statTeam";
mc.listen("onServerStarted", function () {
    if (mc.getScoreObjective(gameTeamScore) == null) {
        log("[背包工具]战队记分板不存在，自动创建");
        mc.newScoreObjective(gameTeamScore, "游玩队伍")

    }
})
function saveBags(player, clear = true) {
    var nbt = player.getNbt()
    save = new NbtCompound({
        "Armor": nbt.getTag("Armor"),
        "Inventory": nbt.getTag("Inventory"),
        "Mainhand": nbt.getTag("Mainhand"),
        "Offhand": nbt.getTag("Offhand"),
    })
    if (clear) {
        player.getHand().setNull();
        player.getOffHand().setNull();
        player.getInventory().removeAllItems()
        player.getArmor().removeAllItems()
        player.refreshItems()
    }
    return save.toSNBT()
}
function restoreBags(player, snbt) {
    var playernbt = player.getNbt();
    var anbt = NBT.parseSNBT(snbt);
    playernbt.setTag("Armor", anbt.getTag("Armor"),);
    playernbt.setTag("Inventory", anbt.getTag("Inventory"),)
    playernbt.setTag("Mainhand", anbt.getTag("Mainhand"),)
    playernbt.setTag("Offhand", anbt.getTag("Offhand"),)
    player.setNbt(playernbt);
    player.refreshItems()
}
mc.listen("onJoin", function (player) {
    if (player.getScore(gameTeamScore)) {
        player.tell("[背包工具]§c注意：您正在使用临时背包进行服内游戏。");
        return;
    }
    var tmpBag = ldb.get(player.xuid + "tempBag");
    if (tmpBag != null) {
        restoreBags(player, tmpBag);
        player.tell("[背包工具]§a检测到您离开时使用的是临时背包，已切换回普通背包");
        ldb.delete(player.xuid + "tempBag");
    }
})
mc.regPlayerCmd("bag-tools", "多背包工具箱", function (player, args) {
    var fm = mc.newSimpleForm();
    var tmpBag = ldb.get(player.xuid + "tempBag");
    ldb.close();
    if (tmpBag == null) {
        fm.addButton("切换至临时背包\n§7可用于玩需要清包的游戏", "textures/items/apple_golden")
    } else {
        fm.addButton("销毁临时背包\n§7销毁临时背包并切换回正常背包", "textures/items/apple")
    }

    fm.addButton("备份背包\n万一出现异常方便管理修复", "textures/items/slimeball");
    fm.addButton("多背包系统\n§7购买更多的随身空间", "textures/items/experience_bottle");
    fm.addButton("协管查包\n§7克隆其他用户的背包至临时背包", "textures/items/hopper");
    player.sendForm(fm, (pl, dt) => {
        if (dt == null) {
            return;
        }
        switch (dt) {
            case 0:
                if (pl.getScore(gameTeamScore)) {
                    pl.tell("[背包工具]§c您正在进行游戏，无法切换。");
                    return;
                }
                if (tmpBag == null) {
                    var snbt = saveBags(pl);
                    pl.tell("[背包工具]§a已切换到临时背包");
                    ldb.set(pl.xuid + "tempBag", snbt);
                } else {
                    restoreBags(pl, tmpBag);
                    pl.tell("[背包工具]§a已切换回普通背包");
                    ldb.delete(pl.xuid + "tempBag");
                }
                break;
            case 1:
                var snbt = saveBags(pl, false);
                pl.tell("[背包工具]§a备份成功！感谢您的支持！");
                ldb.set(pl.xuid + "backupBag", snbt);
                break;
            default:
                pl.tell("[背包工具]§a敬请期待！");
                break;
        }
    })
});

**Comment by VoryWork** [comment]
```
var ldb = new KVDatabase("./plugins/js_data/bag-tools/db/");
var gameTeamScore = "statTeam";
mc.listen("onServerStarted", function () {
    if (mc.getScoreObjective(gameTeamScore) == null) {
        log("[背包工具]战队记分板不存在，自动创建");
        mc.newScoreObjective(gameTeamScore, "游玩队伍")

    }
})
function saveBags(player, clear = true) {
    var nbt = player.getNbt()
    save = new NbtCompound({
        "Armor": nbt.getTag("Armor"),
        "Inventory": nbt.getTag("Inventory"),
        "Mainhand": nbt.getTag("Mainhand"),
        "Offhand": nbt.getTag("Offhand"),
    })
    if (clear) {
        player.getHand().setNull();
        player.getOffHand().setNull();
        player.getInventory().removeAllItems()
        player.getArmor().removeAllItems()
        player.refreshItems()
    }
    return save.toSNBT()
}
function restoreBags(player, snbt) {
    var playernbt = player.getNbt();
    var anbt = NBT.parseSNBT(snbt);
    playernbt.setTag("Armor", anbt.getTag("Armor"),);
    playernbt.setTag("Inventory", anbt.getTag("Inventory"),)
    playernbt.setTag("Mainhand", anbt.getTag("Mainhand"),)
    playernbt.setTag("Offhand", anbt.getTag("Offhand"),)
    player.setNbt(playernbt);
    player.refreshItems()
}
mc.listen("onJoin", function (player) {
    if (player.getScore(gameTeamScore)) {
        player.tell("[背包工具]§c注意：您正在使用临时背包进行服内游戏。");
        return;
    }
    var tmpBag = ldb.get(player.xuid + "tempBag");
    if (tmpBag != null) {
        restoreBags(player, tmpBag);
        player.tell("[背包工具]§a检测到您离开时使用的是临时背包，已切换回普通背包");
        ldb.delete(player.xuid + "tempBag");
    }
})
mc.regPlayerCmd("bag-tools", "多背包工具箱", function (player, args) {
    var fm = mc.newSimpleForm();
    var tmpBag = ldb.get(player.xuid + "tempBag");
    ldb.close();
    if (tmpBag == null) {
        fm.addButton("切换至临时背包\n§7可用于玩需要清包的游戏", "textures/items/apple_golden")
    } else {
        fm.addButton("销毁临时背包\n§7销毁临时背包并切换回正常背包", "textures/items/apple")
    }

    fm.addButton("备份背包\n万一出现异常方便管理修复", "textures/items/slimeball");
    fm.addButton("多背包系统\n§7购买更多的随身空间", "textures/items/experience_bottle");
    fm.addButton("协管查包\n§7克隆其他用户的背包至临时背包", "textures/items/hopper");
    player.sendForm(fm, (pl, dt) => {
        if (dt == null) {
            return;
        }
        switch (dt) {
            case 0:
                if (pl.getScore(gameTeamScore)) {
                    pl.tell("[背包工具]§c您正在进行游戏，无法切换。");
                    return;
                }
                if (tmpBag == null) {
                    var snbt = saveBags(pl);
                    pl.tell("[背包工具]§a已切换到临时背包");
                    ldb.set(pl.xuid + "tempBag", snbt);
                } else {
                    restoreBags(pl, tmpBag);
                    pl.tell("[背包工具]§a已切换回普通背包");
                    ldb.delete(pl.xuid + "tempBag");
                }
                break;
            case 1:
                var snbt = saveBags(pl, false);
                pl.tell("[背包工具]§a备份成功！感谢您的支持！");
                ldb.set(pl.xuid + "backupBag", snbt);
                break;
            default:
                pl.tell("[背包工具]§a敬请期待！");
                break;
        }
    })
});
```

**Comment by VoryWork** [comment]
已通过重配服务端解决
