### ISSUE TITLE
onEat无法检测使用药水、牛奶（可能还有别的）

### ISSUE THREAD

**Issue by KINGANDWL** [LiteLDev/LiteLoader#281]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows 10

### LiteLoader version   LiteLoader版本

2.1.2

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

onEat无法检测使用药水，水瓶，牛奶等

### Steps to reproduce? 复现此问题的步骤

监听onEat
喝水瓶、牛奶等

**Comment by yqs112358** [comment]
LL事件系统需要检查

**Comment by Redbeanw44602** [comment]
onEat顾名思义，是吃的行为。若BDS不将物品判断为Food就不会触发事件。之前包括药水、牛奶是错误的。

**Comment by yqs112358** [comment]
@Redbeanw44602 呃不是啊，事件系统里面本来就是把这些处理成onEat的
肯定是因为点位变了之类的原因

**Comment by yqs112358** [comment]
你看EventAPI.cpp

**Comment by Redbeanw44602** [comment]
> @Redbeanw44602 呃不是啊，事件系统里面本来就是把这些处理成onEat的 肯定是因为点位变了之类的原因

呃，这个事件是我修的，以前的点位拦截不了。如果要把使用药水、牛奶加上的话，那就要再找新点位了。

**Comment by dreamguxiang** [comment]
Fixed
