### ISSUE TITLE
测试

### ISSUE THREAD

**Issue by RimuruChan** [LiteLDev/LiteLoader#284]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

a

### BDS version   BDS版本

a

### What happened? 发生了什么问题?

a

### Steps to reproduce? 复现此问题的步骤

a

### Relevant log output 有关的日志/输出

```shell
a
```

### Plugin list 插件列表

a

**Comment by ShrBox** [comment]
114514

**Comment by Redbeanw44602** [comment]
寄

**Comment by RimuruChan** [comment]
seems good
