### ISSUE TITLE
EntitySystems::tick 内部发生崩溃

### ISSUE THREAD

**Issue by xinge4088** [LiteLDev/LiteLoader#287]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows 10

### LiteLoader version   LiteLoader版本

2.1.2

### BDS version   BDS版本

1.18.10

### What happened? 发生了什么问题?

服务器一直崩溃，并且crash的内容一直都是一样的

### Steps to reproduce? 复现此问题的步骤

服务器于生产环境运行时导致的，目前无法定位问题。

### Relevant log output 有关的日志/输出

```shell
[Crashed!]
-- Unhandled Exception in -> bedrock_server_mod.exe
-- Exception Code: 0xC0000005
-- C++ STL Exception detected!

[TrackBack] Function KnockbackRoarGoal::tick at 0x7FF7A2254BE0  [bedrock_server_mod.exe]
-- At File (null) : Line -282069712 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function GoalSelectorUtility::tickGoals at 0x7FF7A2566BC0  [bedrock_server_mod.exe]
-- At File (null) : Line -282069712 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ??$iterate@P6AXAEAV?$ViewedEntityContextT@VEntityContext@@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@V?$ActorFlagComponent@UBurnsInDaylightFlag@@@@@@@ZV?$basic_view@VEntityId@@U?$get_t@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@V?$ActorFlagComponent@UBurnsInDaylightFlag@@@@@entt@@U?$exclude_t@V?$FlagComponent@UActorInvalidRegionFlag@@@@@3@X@entt@@V?$basic_view@VEntityId@@U?$get_t@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@V?$ActorFlagComponent@UBurnsInDaylightFlag@@@@@entt@@U?$exclude_t@$$V@3@X@3@$$V@?$View@$00VEntityContext@@VEntityRegistry@@U?$exclude_t@V?$FlagComponent@UActorInvalidRegionFlag@@@@@entt@@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@V?$ActorFlagComponent@UBurnsInDaylightFlag@@@@@EntityRegistryBase@@AEAAXP6AXAEAV?$ViewedEntityContextT@VEntityContext@@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@V?$ActorFlagComponent@UBurnsInDaylightFlag@@@@@@@ZAEBV?$basic_view@VEntityId@@U?$get_t@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@V?$ActorFlagComponent@UBurnsInDaylightFlag@@@@@entt@@U?$exclude_t@V?$FlagComponent@UActorInvalidRegionFlag@@@@@3@X@entt@@AEBV?$basic_view@VEntityId@@U?$get_t@V?$FlagComponent@UActorTickedFlag@@@@V?$FlagComponent@UActorFlag@@@@V?$ActorFlagComponent@UBurnsInDaylightFlag@@@@@entt@@U?$exclude_t@$$V@3@X@4@@Z at 0x7FF7A20E0A80  [bedrock_server_mod.exe]
-- At File (null) : Line -282069712 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function GoalSelectorSystem::tick at 0x7FF7A2565500  [bedrock_server_mod.exe]
-- At File (null) : Line -282069712 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function std::_Func_impl_no_alloc<<lambda_402054a1cc8ac232f46e648b3b6daed6>,void,ITickingSystem &>::_Do_call at 0x7FF7A25611A0  [bedrock_server_mod.exe]
-- At File (null) : Line -282069712 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function `anonymous namespace'::DefaultEntitySystemsCollection::foreachTickingSystem at 0x7FF7A27FD620  [bedrock_server_mod.exe]
-- At File (null) : Line -282069712 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function EntitySystems::tick at 0x7FF7A2564F50  [bedrock_server_mod.exe]
-- At File (null) : Line -282069712 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function Level::tickEntitySystems at 0x7FF7A2E4CF30  [bedrock_server_mod.exe]
-- At File (null) : Line -282069712 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function Level::tick at 0x7FF7A2E4BBE0  [bedrock_server_mod.exe]
-- At File (null) : Line -282069712 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ServerLevel::tick at 0x7FF7A24EB3C0  [bedrock_server_mod.exe]
-- At File (null) : Line -282069712 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function Schedule::nextTick at 0x7FFF137CD2F0  [LiteLoader.dll]
-- At File (null) : Line -282069712 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function Minecraft::update at 0x7FF7A29F02D0  [bedrock_server_mod.exe]
-- At File (null) : Line -282069712 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ServerInstance::_update at 0x7FF7A24C5610  [bedrock_server_mod.exe]
-- At File (null) : Line -282069712 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ???????? at 0x????????
```

### Plugin list 插件列表

14:54:47 INFO [Server] Plugin Lists [39]
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - Wooden_axe.js [v1.0.0] (Wooden_axe.js)
14:54:47 INFO [Server]   Wooden_axe.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - LiteLoaderBDS [v2.1.2] (LiteLoader.dll)
14:54:47 INFO [Server]   Strong plugin loader for Bedrock Dedicated Server
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - Banuse.lxl.js [v1.0.0] (Banuse.lxl.js)
14:54:47 INFO [Server]   Banuse.lxl.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - AntiToolbox [v2.0.1] (AntiToolbox.dll)
14:54:47 INFO [Server]   Stop toolbox player from joining your server
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - MAGICALCHEST_common__220220_1.18.11.dll [v1.0.0] (MAGICALCHEST_common__220220_1.18.11.dll)
14:54:47 INFO [Server]   MAGICALCHEST_common__220220_1.18.11.dll
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - LLAntiCheat_pr23_fix4.dll [v1.0.0] (LLAntiCheat_pr23_fix4.dll)
14:54:47 INFO [Server]   LLAntiCheat_pr23_fix4.dll
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - VipUse.lxl.js [v1.0.0] (VipUse.lxl.js)
14:54:47 INFO [Server]   VipUse.lxl.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - flyfix.js [v1.0.0] (flyfix.js)
14:54:47 INFO [Server]   flyfix.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - PFEssentials [v0.1.8082] (PFEssentials.ll.dll)
14:54:47 INFO [Server]   PF基础插件 v0.1.8082.4984 
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - LLMoney [v2.1.1] (LLMoney.dll)
14:54:47 INFO [Server]   EconomyCore for LiteLoaderBDS
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - LLWebsocketR.dll [v1.0.0] (LLWebsocketR.dll)
14:54:47 INFO [Server]   LLWebsocketR.dll
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - OutputFilter.dll [v1.0.0] (OutputFilter.dll)
14:54:47 INFO [Server]   OutputFilter.dll
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - BackupHelper [v2.0.5] (BackupHelper.dll)
14:54:47 INFO [Server]   One command to backup your level
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - BanExplosion [v1.5.7] (BanExplosion.dll)
14:54:47 INFO [Server]   Customize your explosion destroy rule!
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - ScriptEngine-Js [v2.1.2] (LiteLoader.Js.dll)
14:54:47 INFO [Server]   Javascript ScriptEngine For LiteLoaderBDS
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - BehaviorLog.lxl.js [v1.0.0] (BehaviorLog.lxl.js)
14:54:47 INFO [Server]   BehaviorLog.lxl.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - BetterSidebar.lxl.js [v1.0.0] (BetterSidebar.lxl.js)
14:54:47 INFO [Server]   BetterSidebar.lxl.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - StatusView.lxl.lua [v1.0.0] (StatusView.lxl.lua)
14:54:47 INFO [Server]   StatusView.lxl.lua
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - BetterStop.lxl.js [v1.0.0] (BetterStop.lxl.js)
14:54:47 INFO [Server]   BetterStop.lxl.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - JoinTips.lxl.js [v1.0.0] (JoinTips.lxl.js)
14:54:47 INFO [Server]   JoinTips.lxl.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - BorderLimit.lxl.js [v1.0.0] (BorderLimit.lxl.js)
14:54:47 INFO [Server]   BorderLimit.lxl.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - clock.js [v1.0.0] (clock.js)
14:54:47 INFO [Server]   clock.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - LxlBlackBe.lxl.js [v1.0.0] (LxlBlackBe.lxl.js)
14:54:47 INFO [Server]   LxlBlackBe.lxl.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - cmd.js [v1.0.0] (cmd.js)
14:54:47 INFO [Server]   cmd.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - NewTitleYoyo.lxl.js [v1.0.0] (NewTitleYoyo.lxl.js)
14:54:47 INFO [Server]   NewTitleYoyo.lxl.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - EditSign.lxl.js [v1.0.0] (EditSign.lxl.js)
14:54:47 INFO [Server]   EditSign.lxl.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - Give_LXL.js [v1.0.0] (Give_LXL.js)
14:54:47 INFO [Server]   Give_LXL.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - info.js [v1.0.0] (info.js)
14:54:47 INFO [Server]   info.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - LxlCheckBag.lxl.js [v1.0.0] (LxlCheckBag.lxl.js)
14:54:47 INFO [Server]   LxlCheckBag.lxl.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - OnlineRewardsYoyo.lxl.js [v1.0.0] (OnlineRewardsYoyo.lxl.js)
14:54:47 INFO [Server]   OnlineRewardsYoyo.lxl.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - OnlineTimer.lxl.js [v1.0.0] (OnlineTimer.lxl.js)
14:54:47 INFO [Server]   OnlineTimer.lxl.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - PlayerInfo.js [v1.0.0] (PlayerInfo.js)
14:54:47 INFO [Server]   PlayerInfo.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - qh.lxl.js [v1.0.0] (qh.lxl.js)
14:54:47 INFO [Server]   qh.lxl.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - rankingListYoyo.lxl.js [v1.0.0] (rankingListYoyo.lxl.js)
14:54:47 INFO [Server]   rankingListYoyo.lxl.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - suicide.js [v1.0.0] (suicide.js)
14:54:47 INFO [Server]   suicide.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - SweepHelper.js [v1.0.0] (SweepHelper.js)
14:54:47 INFO [Server]   SweepHelper.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - VIP.lxl.js [v1.0.0] (VIP.lxl.js)
14:54:47 INFO [Server]   VIP.lxl.js
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - ScriptEngine-Lua [v2.1.2] (LiteLoader.Lua.dll)
14:54:47 INFO [Server]   Lua ScriptEngine For LiteLoaderBDS
14:54:47 INFO [Server] 
14:54:47 INFO [Server] - XLore.lxl.lua [v1.0.0] (XLore.lxl.lua)
14:54:47 INFO [Server]   XLore.lxl.lua
14:54:47 INFO [Server] 
14:54:47 INFO [Server] * Send command "ll list <Plugin Name>" for more information
14:54:47 INFO [Server]

**Comment by xiaoqch** [comment]
原版无addon成功复现，
![{6N(1VYWP$PZQQUSKQ2BWO3](https://user-images.githubusercontent.com/37901097/168034673-dfdca432-7f84-48c2-ad3a-a84deab8501d.png)
具体是使用挂机池主世界和下界来回切换维度，附近一个区块刷沙机

**Comment by RimuruChan** [comment]
长时间无回复，有问题重新打开。
