### ISSUE TITLE
onLiquidFlow(from,to)数据不准确

### ISSUE THREAD

**Issue by KINGANDWL** [LiteLDev/LiteLoader#289]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows 10

### LiteLoader version   LiteLoader版本

2.1.2

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

onLiquidFlow(from,to) 
1、from.demid==null 
2、to.dimid==-1
这两个的坐标维度不准确

### Steps to reproduce? 复现此问题的步骤

监听onLiquidFlow(from,to)
打印from与to

**Comment by KINGANDWL** [comment]
不好意思，from没问题，是to的dimid为-1不准确（虽然他的dimid和from.pos.dimid相同，但是。。。我还是汇报一下）

**Comment by xiaoqch** [comment]
最新构建已修复，如有仍有问题请重新打开
