### ISSUE TITLE
输入斜杠ll list + 插件名 查看插件具体信息时 ， 名字显示错误

### ISSUE THREAD

**Issue by Arnolwutong** [LiteLDev/LiteLoader#294]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows 10

### LiteLoader version   LiteLoader版本

2.1.3

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

输入斜杠ll list + 插件名 查看插件具体信息时 ， 名字显示错误

### Steps to reproduce? 复现此问题的步骤

输入 ll list + 插件名

### Relevant log output 有关的日志/输出

```shell
ll plugins EnchantUtil
10:59:51 INFO [Server] Plugin <EnchantUtil>
10:59:51 INFO [Server] 
10:59:51 INFO [Server] - Name:  EnchantUtil8232EnchantUtil.ll.js)
10:59:51 INFO [Server] - Introduction:  LLSE 真指令示例插件
10:59:51 INFO [Server] - Version:  v1.0.0
10:59:51 INFO [Server] - Type:  Script Plugin
10:59:51 INFO [Server] - File Path:  plugins\EnchantUtil.ll.js
10:59:51 INFO [Server] - Author:  xiaoqch
```

### Plugin list 插件列表

ll list
11:04:50 INFO [Server] Plugin Lists [6]
11:04:50 INFO [Server] - LLMoney [v2.1.1] (LLMoney.dll)
11:04:50 INFO [Server]   EconomyCore for LiteLoaderBDS
11:04:50 INFO [Server] - ScriptEngine-Lua [v2.1.3] (LiteLoader.Lua.dll)
11:04:50 INFO [Server]   Lua ScriptEngine for LiteLoaderBDS
11:04:50 INFO [Server] - ScriptEngine-Js [v2.1.3] (LiteLoader.Js.dll)
11:04:50 INFO [Server]   Javascript ScriptEngine for LiteLoaderBDS
11:04:50 INFO [Server] - Antistacking [v0.1.3] (Antistacking.js)
11:04:50 INFO [Server]   用来清理堆叠实体的插件
11:04:50 INFO [Server] - EnchantUtil [v1.0.0] (EnchantUtil.ll.js)
11:04:50 INFO [Server]   LLSE 真指令示例插件
11:04:50 INFO [Server] - GiveClock [v1.0.0] (GiveClock.lxl.js)
11:04:50 INFO [Server]   LLSE 进服自动给个钟 [输入 ll plugins GiveClock 查看具体信息]
11:04:50 INFO [Server]
11:04:50 INFO [Server] * Send command "ll list <Plugin Name>" for more information

**Comment by Arnolwutong** [comment]
中间显示个8232
![输入斜杠ll list + 插件名 查看插件具体信息时 ， 名字显示错误](https://user-images.githubusercontent.com/95761056/156489086-5b415304-9ac8-4794-a94b-ff5882beec24.png)

**Comment by yqs112358** [comment]
小问题，符号打错了
已修复
