### ISSUE TITLE
ll settings 命令

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LiteLoader#296]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

修改配置需要在配置文件修改，相对麻烦

### Describe the solution you'd like 您认为还缺少什么?

增加 ll settings 系列命令，功能类似gamerule，提供运行时实时修改配置功能，提供 ll settings reload功能

**Comment by RimuruChan** [comment]
cdadff70b232cd9fb51bb5be77a8d24a0d14fde9
