### ISSUE TITLE
更换文档工具

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LiteLoader#297]
docsify写久了之后发现众多问题
1. 大量功能靠插件支持，本体功能不足，插件较多导致性能不佳
2. 部分必要功能缺失（自动目录，内容隐藏等），也没有类似插件

推荐可选工具：[Docusaurus](https://docusaurus.io/zh-CN/docs)、[VuePress](https://vuepress.vuejs.org/zh/guide/)

**Comment by Redbeanw44602** [comment]
like LiteLDev/docs#15
