### ISSUE TITLE
LiteLoader.json清空

### ISSUE THREAD

**Issue by LatosProject** [LiteLDev/LiteLoader#300]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.1.3

### BDS version   BDS版本

2.1.3

### What happened? 发生了什么问题?

疑似BDS强制关闭后，/plugins/LiteLoader/LiteLoader.json会自动清空文件，以至于重启后无法启动脚本引擎
![Screenshot_20220306_120720](https://user-images.githubusercontent.com/89125260/156908816-357d113a-1715-461a-ae3f-78ecb580feb3.jpg)
![Screenshot_20220306_120558](https://user-images.githubusercontent.com/89125260/156908803-6fb203ce-b88a-433c-adbe-d69f344286f2.jpg)

### Steps to reproduce? 复现此问题的步骤

1.非正常关闭

**Comment by yufengya0420** [comment]
你家bds版本神特么2.1.3

**Comment by yufengya0420** [comment]
人才，宁是穿越了吗

**Comment by ShrBox** [comment]
删除LiteLoader.json
