### ISSUE TITLE
注册真指令时概率性崩服

### ISSUE THREAD

**Issue by VoryWork** [LiteLDev/LiteLoader#304]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.1.3

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

[Crashed!]
-- Unhandled Exception in -> ntdll.dll
-- Exception Code: 0xC0000374
-- Minidump generated in Directory ./logs/Crash

[TrackBack] Function RtlIsZeroMemory at 0x7FFAEEEAF080  [ntdll.dll]
[TrackBack] Function RtlIsZeroMemory at 0x7FFAEEEAF080  [ntdll.dll]
[TrackBack] Function RtlpNtSetValueKey at 0x7FFAEEEB7A30  [ntdll.dll]
[TrackBack] Function RtlpNtSetValueKey at 0x7FFAEEEB7A30  [ntdll.dll]
[TrackBack] Function RtlpNtSetValueKey at 0x7FFAEEEB7A30  [ntdll.dll]
[TrackBack] Function RtlGetCurrentServiceSessionId at 0x7FFAEEDD4850  [ntdll.dll]
[TrackBack] Function RtlFreeHeap at 0x7FFAEEDD4760  [ntdll.dll]
[TrackBack] Function free_base at 0x7FFAEC59F040  [ucrtbase.dll]
[TrackBack] Function operator delete at 0x7FF7795EFC30  [bedrock_server_mod.exe]
[TrackBack] Function std::_Tree_val<std::_Tree_simple_types<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > >,void * __ptr64> > > at 0x7FF7787C13A0  [bedrock_server_mod.exe]
[TrackBack] Function std::_Tree_val<std::_Tree_simple_types<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > >,void * __ptr64> > > at 0x7FF7787C13A0  [bedrock_server_mod.exe]
[TrackBack] Function std::_Tree_val<std::_Tree_simple_types<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > >,void * __ptr64> > > at 0x7FF7787C13A0  [bedrock_server_mod.exe]
[TrackBack] Function std::_Tree_val<std::_Tree_simple_types<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > >,void * __ptr64> > > at 0x7FF7787C13A0  [bedrock_server_mod.exe]
[TrackBack] Function std::_Tree_val<std::_Tree_simple_types<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > >,void * __ptr64> > > at 0x7FF7787C13A0  [bedrock_server_mod.exe]
[TrackBack] Function CommandRegistry::ParseTable::~ParseTable at 0x7FF7787DBE80  [bedrock_server_mod.exe]
[TrackBack] Function CommandRegistry::addRule at 0x7FF7787E7180  [bedrock_server_mod.exe]
[TrackBack] Function CommandRegistry::addSoftEnum at 0x7FF7787E7440  [bedrock_server_mod.exe]
[TrackBack] Function DynamicCommandInstance::setSoftEnum at 0x7FFAB76E1FB0  [LiteLoader.dll]
[TrackBack] Function DynamicCommandInstance::initCommandBuilder at 0x7FFAB76E2410  [LiteLoader.dll]
[TrackBack] Function DynamicCommandInstance::initCommandBuilder at 0x7FFAB76E2410  [LiteLoader.dll]
[TrackBack] Function DedicatedServer::start at 0x7FF7783782B0  [bedrock_server_mod.exe]
[TrackBack] Function main at 0x7FF7783A2300  [bedrock_server_mod.exe]
[TrackBack] Function __scrt_common_main_seh at 0x7FF7797F26D4  [bedrock_server_mod.exe]
[TrackBack] Function BaseThreadInitThunk at 0x7FFAEDC27020  [KERNEL32.DLL]
[TrackBack] Function RtlUserThreadStart at 0x7FFAEEE02630  [ntdll.dll]

### Steps to reproduce? 复现此问题的步骤

1.反复重启服务器

### Relevant log output 有关的日志/输出

```shell
[Crashed!]
-- Unhandled Exception in -> ntdll.dll
-- Exception Code: 0xC0000374
-- Minidump generated in Directory ./logs/Crash

[TrackBack] Function RtlIsZeroMemory at 0x7FFAEEEAF080  [ntdll.dll]
[TrackBack] Function RtlIsZeroMemory at 0x7FFAEEEAF080  [ntdll.dll]
[TrackBack] Function RtlpNtSetValueKey at 0x7FFAEEEB7A30  [ntdll.dll]
[TrackBack] Function RtlpNtSetValueKey at 0x7FFAEEEB7A30  [ntdll.dll]
[TrackBack] Function RtlpNtSetValueKey at 0x7FFAEEEB7A30  [ntdll.dll]
[TrackBack] Function RtlGetCurrentServiceSessionId at 0x7FFAEEDD4850  [ntdll.dll]
[TrackBack] Function RtlFreeHeap at 0x7FFAEEDD4760  [ntdll.dll]
[TrackBack] Function free_base at 0x7FFAEC59F040  [ucrtbase.dll]
[TrackBack] Function operator delete at 0x7FF7795EFC30  [bedrock_server_mod.exe]
[TrackBack] Function std::_Tree_val<std::_Tree_simple_types<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > >,void * __ptr64> > > at 0x7FF7787C13A0  [bedrock_server_mod.exe]
[TrackBack] Function std::_Tree_val<std::_Tree_simple_types<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > >,void * __ptr64> > > at 0x7FF7787C13A0  [bedrock_server_mod.exe]
[TrackBack] Function std::_Tree_val<std::_Tree_simple_types<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > >,void * __ptr64> > > at 0x7FF7787C13A0  [bedrock_server_mod.exe]
[TrackBack] Function std::_Tree_val<std::_Tree_simple_types<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > >,void * __ptr64> > > at 0x7FF7787C13A0  [bedrock_server_mod.exe]
[TrackBack] Function std::_Tree_val<std::_Tree_simple_types<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > > > >::_Erase_tree<std::allocator<std::_Tree_node<std::pair<typeid_t<CommandRegistry> const ,std::vector<int,std::allocator<int> > >,void * __ptr64> > > at 0x7FF7787C13A0  [bedrock_server_mod.exe]
[TrackBack] Function CommandRegistry::ParseTable::~ParseTable at 0x7FF7787DBE80  [bedrock_server_mod.exe]
[TrackBack] Function CommandRegistry::addRule at 0x7FF7787E7180  [bedrock_server_mod.exe]
[TrackBack] Function CommandRegistry::addSoftEnum at 0x7FF7787E7440  [bedrock_server_mod.exe]
[TrackBack] Function DynamicCommandInstance::setSoftEnum at 0x7FFAB76E1FB0  [LiteLoader.dll]
[TrackBack] Function DynamicCommandInstance::initCommandBuilder at 0x7FFAB76E2410  [LiteLoader.dll]
[TrackBack] Function DynamicCommandInstance::initCommandBuilder at 0x7FFAB76E2410  [LiteLoader.dll]
[TrackBack] Function DedicatedServer::start at 0x7FF7783782B0  [bedrock_server_mod.exe]
[TrackBack] Function main at 0x7FF7783A2300  [bedrock_server_mod.exe]
[TrackBack] Function __scrt_common_main_seh at 0x7FF7797F26D4  [bedrock_server_mod.exe]
[TrackBack] Function BaseThreadInitThunk at 0x7FFAEDC27020  [KERNEL32.DLL]
[TrackBack] Function RtlUserThreadStart at 0x7FFAEEE02630  [ntdll.dll]
```

**Comment by xiaoqch** [comment]
堆栈信息有点奇怪，是不是pdb和ll版本没有对应？

**Comment by xiaoqch** [comment]
最新构建重启一个小时，每次注册10个指令无复现

**Comment by xiaoqch** [comment]
发现常规的指令在RegCmdEvent外注册崩服，考虑将指令注册自动延迟到RegCmdEvent里执行，但是如果插件在该事件后执行的注册或者热加载插件暂时没有找到好的防止崩服的办法

**Comment by VoryWork** [comment]
考虑注册指令时机有问题，在服务器未初始化状态下注册崩服。

**Comment by Jaciezyt** [comment]
LLSE的动态真命令可以在onServerStarted事件setup，LL的真命令要在RegCmdEvent执行setup

**Comment by xiaoqch** [comment]
> LLSE的动态真命令可以在onServerStarted事件setup，LL的真命令要在RegCmdEvent执行setup

最新构建已经可以（而且推荐）在插件加载时注册，会自动延迟到RegCmdEvent里注册，onServerStarted事件是在RegCmdEvent后的，目前发现貌似是在RegCmdEvent外注册插件均有小概率出问题，动态指令和常规指令注册都出现过

**Comment by xiaoqch** [comment]
> 考虑注册指令时机有问题，在服务器未初始化状态下注册崩服。

目前仅actions构建版本支持自动延迟注册指令

**Comment by xiaoqch** [comment]
此问题已于commit #[56a012d](https://github.com/LiteLDev/LiteLoaderBDS/commit/56a012d90176c35995dfc71f05868c7de6482873) 修复，如仍有问题请重新打开此issue
