### ISSUE TITLE
Client in limbo when trying to download resource packs

### ISSUE THREAD

**Issue by ambiennt** [LiteLDev/LiteLoader#306]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

There exists a bug with vanilla BDS that prevents the server from sending a resource pack over the network if the server has been idle for a few hours or more. Unfortunately, it is a bit tedious to reproduce and test this bug due to the time you need to wait in order for it to occur. If I restart the server, clients are able to download the resource packs just fine, but over some time, the bug will reoccur. It is not desirable to have to restart the server each time this happens

![Untitled](https://user-images.githubusercontent.com/63216972/157099463-76ef26ac-5dfd-4aee-b3f8-5f871e263635.png)
 
 I have a resource pack applied on my server, and the "Co-Resource pack" setting enabled (but enabling this likely isnt the reason why the bug occurs). I tried logging the packets when this bug occurs, and I found that the client will send a **ResourcePackClientResponsePacket** saying it needs the packs to be sent over the network. However, the server doesn't send any response after that. the BDS console still shows that the client has joined.

### Describe the solution you'd like 您认为还缺少什么?

I would like to see the LL team implement a fix for this in the original bug switch. Currently, it is not possible for me to use a resource pack on my server because I cannot afford to keep restarting the server each time that this happens. I believe that fixing this bug is important and will allow better usage of server resource packs for all BDS servers.

**Comment by ambiennt** [comment]
so is that a no for trying to fix?

**Comment by dreamguxiang** [comment]
Has your world ever been opened in  client？

**Comment by dreamguxiang** [comment]
try
```c++
THook(bool, "?getLANBroadcast@LevelData@@QEBA_NXZ",
	LevelData* _this)
{
	return true;
}

THook(bool, "?getLANBroadcastIntent@LevelData@@QEBA_NXZ",
	LevelData* _this)
{
	return true;
}
```
