### ISSUE TITLE
Command registration does not work for LL-JS

### ISSUE THREAD

**Issue by shizotoaster** [LiteLDev/LiteLoader#308]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows 11

### LiteLoader version   LiteLoader版本

2.1.3

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

I am unable to register any command (via both fake and real command registration)

### Steps to reproduce? 复现此问题的步骤

1. Write a script that registers any command
2. Launch BDS and connect to the server
3. Connect to your server and see that there're still no custom commands :(

### Relevant log output 有关的日志/输出

```shell
None
```

### Plugin list 插件列表

![изображение](https://user-images.githubusercontent.com/51480483/158590612-e120694c-31be-4693-b378-8bb0329df6e9.png)

**Comment by Jaciezyt** [comment]
error outputs and your code plz

**Comment by shizotoaster** [comment]
> error outputs and your code plz

There're no error outputs, it just seems to do nothing

**Comment by shizotoaster** [comment]
Have also tried that on latest 2.1.4 beta, LL says that cmd is registered but it's still not displayed in commands menu

**Comment by xiaoqch** [comment]
> Have also tried that on latest 2.1.4 beta, LL says that cmd is registered but it's still not displayed in commands menu

Did you add any overloads? Even if your command doesn't need any parameters, you need to add an overload with no parameters, like `cmd.overload()`.
