### ISSUE TITLE
`mc.runcmd`在执行`setblock`时报错,直接执行正常

### ISSUE THREAD

**Issue by dzx-dzx** [LiteLDev/LiteLoader#309]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows 11

### LiteLoader version   LiteLoader版本

2.1.3

### BDS version   BDS版本

1.18.12.01

### What happened? 发生了什么问题?

![图片](https://user-images.githubusercontent.com/31068367/158778318-31643b86-fd8c-418c-950b-1e3945237f1e.png)
如图所示,从脚本执行命令得到区块未加载的报错,但直接执行可以成功.

**Comment by Jaciezyt** [comment]
应该和ll没有关系，你setblock的时候区块还没加载就会出现世界外问题

**Comment by dzx-dzx** [comment]
> 应该和ll没有关系，你setblock的时候区块还没加载就会出现世界外问题

这两条命令执行的间隔很短。事实上它们都是在离玩家非常近的地方执行的。

**Comment by dzx-dzx** [comment]
一个更加具体的实验:
```javascript
mc.listen("onPlaceBlock", (player, block) => {
    player.runcmd("say 123")
    mc.runcmd("say 456")
    const {x,y,z}=block.pos
    player.runcmd(`setblock ${x} ${y+2} ${z} diamond_block`)
    mc.runcmd(`setblock ${x} ${y+4} ${z} diamond_block`)
    return true
})
```
放置方块时其正上方两格的钻石块始终可放置，但代表服务器命令的方块只有"第一次"触发时才能成功放置。
（这里的“第一次”似乎具体指的是进入新区块后的第一次。如果玩家tp到一个很远的地方，在这里的首次放置是可以成功的）

**Comment by xiaoqch** [comment]
已修复，如问题仍存在，请重新打开此issue
