### ISSUE TITLE
JAVA MITM

### ISSUE THREAD

**Issue by notacoderr** [LiteLDev/LiteLoader#311]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

Java players may be able to play alongside Bedrock players

### Describe the solution you'd like 您认为还缺少什么?

An integrated MITM for Java Edition

**Comment by KawaiiNahida** [comment]
Why don't you just run JE's server?

**Comment by StarsDream00** [comment]
Geyser, plz
