### ISSUE TITLE
World custom generator

### ISSUE THREAD

**Issue by ScarletRedMan** [LiteLDev/LiteLoader#312]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

I want to create custom world generator without default world generation. 
Examples: void world, skygrid, sky islands, etc. 

### Describe the solution you'd like 您认为还缺少什么?

Implement the ability to override the default world generator. Selecting the type of generator in a special config.
Default id of generator is `DEFAULT`.  If non-standard generation is selected, then automatic generation of structures is disabled. But they can be generated using a special function.

Example generator class from pmmp4 core:
https://github.com/pmmp/PocketMine-MP/blob/stable/src/world/generator/Generator.php
Where `generateChunk` is generation of landscape structure, and `populateChunk` is generation filters for chunks(trees, ores, caves, etc).

**Comment by KawaiiNahida** [comment]
You can write your own plugins to do this, the demand for this function is not large, we will not spend too much time for this
