### ISSUE TITLE
实体事件 生物受伤`"onMobHurt"`无法侦听`投掷/滞留药水/龙息`造成的伤害

### ISSUE THREAD

**Issue by ghitori** [LiteLDev/LiteLoader#313]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows 10

### LiteLoader version   LiteLoader版本

2.1.3

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

创建`“onMobHurt”`侦听器，当生物受到魔法伤害时，侦听器无响应

**Comment by dreamguxiang** [comment]
已添加至onMobHurt， 4107ce55e2edef86bbdfb650a33fa35f1bfd7a79

**Comment by ghitori** [comment]
当前最新[Beta Build](https://github.com/LiteLDev/LiteLoaderBDS/actions/runs/2033742115)的`onMobHurt`已添加`MagicDamage`，但由`MagicDamage`引起的`onMobHurt`参数`damage`为负值，其余事件引起为正值
![Damage正负不统一](https://s3.bmp.ovh/imgs/2022/03/1a6716bf4bbba64d.png "Damage正负不统一")

**Comment by dreamguxiang** [comment]
bds返回就是负值
