### ISSUE TITLE
Project build error

### ISSUE THREAD

**Issue by KocTu4eK** [LiteLDev/LiteLoader#314]
I'm trying to compile an LL **2.0.4** project on LL **2.1.3** and get this error:
![image](https://user-images.githubusercontent.com/84087988/159336365-efc295b0-c59b-4cf9-ab81-973b7ae27ec8.png)

**Comment by ShrBox** [comment]
The version of Visual Studio mismatch

**Comment by KocTu4eK** [comment]
oh, thank you
