### ISSUE TITLE
[Dev] Multi-database support for LL&LLSE

### ISSUE THREAD

**Issue by Jaciezyt** [LiteLDev/LiteLoader#317]
- [x] Core 4 LL
- [x] SQLite3 4 LL
- [x] MySQL 4 LL
- [x] LLSE APIs

**Comment by Rjlintkh** [comment]
wonder if this is necessary, why dont people add them manually when they actually need them

**Comment by Jaciezyt** [comment]
> wonder if this is necessary, why dont people add them manually when they actually need them

JavaScript&Lua need it
