### ISSUE TITLE
希望可以更新LL调用lua这个功能

### ISSUE THREAD

**Issue by CNDogc** [LiteLDev/LiteLoader#318]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

LL无法调用lua

### Describe the solution you'd like 您认为还缺少什么?

LL调用lua

**Comment by xiaoqch** [comment]
暂时可以考虑使用真指令 + runcmdEx代替

**Comment by xiaoqch** [comment]
功能已实现，目前仅在 commit [cd6b13d870fb11322c2ea91b1a13a70ee935d594](https://github.com/LiteLDev/LiteLoaderBDS/commit/cd6b13d870fb11322c2ea91b1a13a70ee935d594) 下启用 debugMode 时可用，欢迎测试
