### ISSUE TITLE
Please return logs about Registered Commands

### ISSUE THREAD

**Issue by VinkyV** [LiteLDev/LiteLoader#320]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

I need to return logs about registered commands because i don't know how many and what commands are built in LiteLoaderBDS and ScriptEngine.

### Describe the solution you'd like 您认为还缺少什么?

Return console logs about registered commands(optional in json config) or write a docs file about commands built in LiteLoaderBDS.

**Comment by dreamguxiang** [comment]
I will add it to debug mode

**Comment by dreamguxiang** [comment]
ff70c2cc620d9b4e7a6b81913bea85bced9c52d3
