### ISSUE TITLE
启动完成时提示的时长不正常

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#322]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows Server 2022

### LiteLoader version   LiteLoader版本

2.1.4

### BDS version   BDS版本

1.18.12.01

### What happened? 发生了什么问题?

启动完成时提示的时长不正常，具体表现为负数

### Steps to reproduce? 复现此问题的步骤

开启服务器

### Relevant log output 有关的日志/输出

```shell
INFO [Server] Done (-2.2s)! For help, type "help" or "?"
```

### Plugin list 插件列表

无

**Comment by StarsDream00** [comment]
2.1.5直接不提示Done了

**Comment by dreamguxiang** [comment]
已修复，等待新版
