### ISSUE TITLE
Make LLMoney optional and not being served with LL release

### ISSUE THREAD

**Issue by shizotoaster** [LiteLDev/LiteLoader#323]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

I am totally against any money systems on servers but I also understand that it can be useful for some reason. Unfortunately, every time LLBDS is updated, the dll appears in my plugins folder

### Describe the solution you'd like 您认为还缺少什么?

Do not include LLMoney.dll with default LLBDS release and change LLSE's "economic module not found" warning to a single-timed recommendation or even turn LLSE's economic api into a separate module (some kind of additional optional dll that adds some methods to LLSE)

**Comment by dreamguxiang** [comment]
Changes will be made in the next mc update

**Comment by shizotoaster** [comment]
Well, it's been a couple of mc updates but the dll is still there. Is it going to be removed?

**Comment by dreamguxiang** [comment]
add config Options
