### ISSUE TITLE
2.1.4频繁假死问题

### ISSUE THREAD

**Issue by MengYang8481** [LiteLDev/LiteLoader#324]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.1.4

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

2.1.4自动更新后频繁假死，LL2.1.3的时候稳定运行，极少崩服和无假死现象

### Steps to reproduce? 复现此问题的步骤

根据玩家描述，最后一个行为：打开高炉并放入煤炭
![Uploading image.png…]()

### Relevant log output 有关的日志/输出

```shell
暂无
```

### Plugin list 插件列表

![QQ图片20220331101002](https://user-images.githubusercontent.com/23436744/160962154-af02dcc7-efcc-4488-b606-1cf5d470a230.jpg)

**Comment by xiaoqch** [comment]
应该是有插件执行了 0tick 的 interval 或者说 repeat，因为2.1.3存在一个bug，Schedule 执行延迟或者间隔会比设置的多 1tick，0tick变成1tick，20tick变成21tick，修复该bug或 0tick 会进入无限循环，已通过限制 repeat 最低延迟为1tick的方式修复

**Comment by Ronifue** [comment]
我这边也出现了同样的情况，更新后突然假死，最终移除LLhelper后解决问题。
