### ISSUE TITLE
末影珍珠击中怪物时触发onMobHurt报错

### ISSUE THREAD

**Issue by ENIACJushi** [LiteLDev/LiteLoader#325]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows Server 2016

### LiteLoader version   LiteLoader版本

2.1.5

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

使用末影珍珠扔怪物时报错

### Steps to reproduce? 复现此问题的步骤

1. 召唤一个僵尸
2. 用末影珍珠扔它

### Relevant log output 有关的日志/输出

```shell
ERROR [LiteLoader] Event Callback Failed!
ERROR [LiteLoader] Uncaught Exception Detected!
ERROR [LiteLoader] In Event: onMobHurt
```

### Plugin list 插件列表

16:42:34 INFO [Server] - LLMoney [v2.1.1] (LLMoney.dll)
16:42:34 INFO [Server]   EconomyCore for LiteLoaderBDS
16:42:34 INFO [Server] - ScriptEngine-Lua [v2.1.5] (LiteLoader.Lua.dll)
16:42:34 INFO [Server]   Lua ScriptEngine for LiteLoaderBDS
16:42:34 INFO [Server] - TMEssential.js [v2.823.0] (TMEssential.js)
16:42:34 INFO [Server]   新时代多功能基础插件
16:42:34 INFO [Server] - ScriptEngine-Js [v2.1.5] (LiteLoader.Js.dll)
16:42:34 INFO [Server]   Javascript ScriptEngine for LiteLoaderBDS
16:42:34 INFO [Server] - MinecraftServerManager.js [v1.0.0] (MinecraftServerManager.js)
16:42:34 INFO [Server]   MinecraftServerManager.js
16:42:34 INFO [Server] - Tsidebar.js [v1.0.0] (Tsidebar.js)
16:42:34 INFO [Server]   Tsidebar.js

**Comment by dreamguxiang** [comment]
无法复现，

**Comment by xiaoqch** [comment]
已修复，如问题仍存在，请重新打开此issue
