### ISSUE TITLE
无法重载使用数据库的脚本

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#326]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows Server 2022

### LiteLoader version   LiteLoader版本

2.1.5

### BDS version   BDS版本

1.18.12.01

### What happened? 发生了什么问题?

无法重载使用数据库的脚本（互斥锁）
并且在提示卸载成功与加载失败后，该脚本仍会显示在`ll list`里，无法再次加载/卸载

### Steps to reproduce? 复现此问题的步骤

1. 在脚本里实例一个数据库对象
2. 重载该脚本

### Relevant log output 有关的日志/输出

```shell
ERROR [LevelDB] Fail to load KVDB <数据库路径>
ERROR [LevelDB] IO error: 数据库路径/LOCK: 另一个程序正在使用此文件，进程无法访问。
```

### Plugin list 插件列表

无

**Comment by xiaoqch** [comment]
已修复，如问题仍存在请重新打开此issue
