### ISSUE TITLE
Fail to attach Debugger! Error Code: 5

### ISSUE THREAD

**Issue by zyy82** [LiteLDev/LiteLoader#330]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.1.5

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

开启bds后，显示[CrashLogger][ERROR] Fail to attach Debugger! Error Code: 5
然后关闭
没加任何插件，只是迁移了自己的bds存档

### Steps to reproduce? 复现此问题的步骤

1开启bds
2然后bds关闭

### Relevant log output 有关的日志/输出

```shell
[CrashLogger][ERROR] Fail to attach Debugger! Error Code: 5
```

### Plugin list 插件列表

没有额外日志

**Comment by xiaoqch** [comment]
如果不安装LiteLoader能启动吗

**Comment by zyy82** [comment]
> ###
> 1.18.12
> 
> ### 发生了什么事？发生了什么问题?
> 开启 bds 后，显示[CrashLogger][错误] 无法附加调试器！错误代码： 5 然后关闭 没加任何插件，只是迁移了自己的bds存档
> 
> ### 重现的步骤？复现此问题的步骤
> 1开启bds 2然后bds关闭
> 
> ### 相关日志输出 有关的日志/输出
> ```shell
> [CrashLogger][ERROR] Fail to attach Debugger! Error Code: 5
> ```
> 
> ###

可以

**Comment by zyy82** [comment]
> 如果不安装LiteLoader能启动吗

可以

**Comment by xiaoqch** [comment]
等最新提交构建完后试试Actions最新构建问题是否仍然存在？
[Adjust the modules startup order](https://github.com/LiteLDev/LiteLoaderBDS/actions/runs/2084966313)

**Comment by zyy82** [comment]
> 等最新提交构建完后试试Actions最新构建问题是否仍然存在？ [Adjust the modules startup order](https://github.com/LiteLDev/LiteLoaderBDS/actions/runs/2084966313)

更新到最新快照，能正常开启bds，没有问题了

**Comment by xiaoqch** [comment]
问题已修复，请等待新版，此issue关闭
