### ISSUE TITLE
AddonsHelper 安装某些压缩工具压缩的 addon 报错

### ISSUE THREAD

**Issue by HuoHuas001** [LiteLDev/LiteLoader#332]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

LiteLoader 2.1.5

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

![image](https://user-images.githubusercontent.com/51258524/161413259-598e38a5-022e-45f4-8cc3-730a21b1cb96.png)
如图，像这样的mcaddon资源包无法被安装，具体报错如下
```
11:38:44 ERROR [AddonHelper] Fail to uncompress addon xuanfuzi.mcaddon!
11:38:44 ERROR [AddonHelper] Exit Code: 2
11:38:44 ERROR [AddonHelper] Program Output:

11:38:44 ERROR [AddonHelper] * Install progress aborted!
11:38:44 ERROR [AddonHelper] No addon was installed.
```

### Steps to reproduce? 复现此问题的步骤

1.将资源包[Link](https://www.minebbs.com/resources/3096/)下载
2.将资源包放在plugins/AddonHelper中

### Relevant log output 有关的日志/输出

```shell
11:38:44 ERROR [AddonHelper] Fail to uncompress addon xuanfuzi.mcaddon!
11:38:44 ERROR [AddonHelper] Exit Code: 2
11:38:44 ERROR [AddonHelper] Program Output:

11:38:44 ERROR [AddonHelper] * Install progress aborted!
11:38:44 ERROR [AddonHelper] No addon was installed.
```

**Comment by xiaoqch** [comment]
暂时解决方法，解压后重新压缩
