### ISSUE TITLE
添加使用桶事件

### ISSUE THREAD

**Issue by Redbeanw44602** [LiteLDev/LiteLoader#335]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

UseItem(On) 无法监听到水桶在水中取生物（生成桶装XX）行为。

### Describe the solution you'd like 您认为还缺少什么?

为使用桶添加专用的事件

`onUseBucket`

> mBucket 桶的物品对象
> mType 桶正在进行的操作 收/放
> mTarget 桶尝试拾取的方块

**Comment by VoryWork** [comment]
Maybe you can use `onInventoryChange`,`onBlockIntxxxx` and `useItem` to emit player Using Bucket

**Comment by Jaciezyt** [comment]
Completed by #746
