### ISSUE TITLE
ActorType enum does not exist

### ISSUE THREAD

**Issue by KocTu4eK** [LiteLDev/LiteLoader#336]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

![image](https://user-images.githubusercontent.com/84087988/161695352-6efc270e-8086-486d-ab82-f7b3a4a2caf8.png)
The **_Actor::fetchNearbyActorsSorted_** method takes an ActorType parameter, but I didn't find enum ActorType anywhere, even in ActorAPI.cpp.

![image](https://user-images.githubusercontent.com/84087988/161695417-86976ccb-706e-4252-a686-0267eda15c76.png)
I tried **_this (screenshot)_** and **_(ActorType)0_** but it all leads to this error.

### Describe the solution you'd like 您认为还缺少什么?

I think you need to generate an ActorType.hpp header or add an ActorType enum to Types.hpp.

**Comment by xiaoqch** [comment]
Please try to build the project first, It looks like just a intellicode error

**Comment by KocTu4eK** [comment]
I tried, it throws the same error as in the screenshot

**Comment by xiaoqch** [comment]
I tried that code and it builds successfully,
![image](https://user-images.githubusercontent.com/37901097/161892916-18855922-3a9a-46d4-9de0-43e652b58086.png)

**Comment by xiaoqch** [comment]
Or, you can try declaring "enum ActorType" in your code, like
```cpp
#include <MC/Mob.hpp>
struct DistanceSortedActor
{
    char fakeFiller[0]; //unknown size
};
enum ActorType; // <- This line
void entry()
{
    Mob* fakeMob = (Mob*)nullptr;
    fakeMob->fetchNearbyActorsSorted(fakeMob->getPos(), fakeMob->getEntityTypeId());
}
```
