### ISSUE TITLE
给某些事件添加更多的参数

### ISSUE THREAD

**Issue by HongyiMC** [LiteLDev/LiteLoader#339]
请为onMobDie添加：
- death_position （死亡坐标）
- cause （导致死亡原因）
- projectile_type （弹射物种类）

请为onMobHurt添加：
- absorbed_damage （被击打目标盔甲和药水吸收的伤害）
- hurt_position （被击打目标受伤的位置）
- cause （导致受伤的原因）
- projectile_type （弹射物种类）

**Comment by HongyiMC** [comment]
受原版MC的脚本启发
https://bedrock.dev/docs/stable/Scripting#minecraft%3Aentity_hurt

**Comment by Jaciezyt** [comment]
onMobDie:
https://github.com/LiteLDev/LiteLoaderBDS/blob/5fb61b10dc2aec2e6ac0ea03e24cfa0bafd028a7/LiteLoader/Kernel/EventAPI.cpp#L1710
可以通过`ev.mDamageSource`对象获取到伤害源类型/受伤原因, `ev.mMob->getPos()`可以获取到死亡坐标
onMobHurt也是同样的道理，absorbed_damage可以自行研究下，肯定也是可以获得的

**Comment by HongyiMC** [comment]
> onMobDie:
> 
> https://github.com/LiteLDev/LiteLoaderBDS/blob/5fb61b10dc2aec2e6ac0ea03e24cfa0bafd028a7/LiteLoader/Kernel/EventAPI.cpp#L1710
> 
> 
> 可以通过`ev.mDamageSource`对象获取到伤害源类型/受伤原因, `ev.mMob->getPos()`可以获取到死亡坐标
> onMobHurt也是同样的道理，absorbed_damage可以自行研究下，肯定也是可以获得的

这个是js脚本吗

**Comment by Yushu2606** [comment]
不关吗？
