### ISSUE TITLE
llse的colorlog无法正确输出颜色

### ISSUE THREAD

**Issue by Singl-Daemon** [LiteLDev/LiteLoader#340]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.1.6

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

当使用colorlog时无法正确输出颜色
比如colorLog("green","hello")
他只会输出白色的而不是绿色的
其他颜色如上

### Steps to reproduce? 复现此问题的步骤

1.colorLog("green","hello")
2.加载插件

### Relevant log output 有关的日志/输出

```shell
20:52:33 INFO [test] hello
//并不是绿色的
```

### Plugin list 插件列表

21:00:04 INFO [Server] Plugin Lists [4]
21:00:04 INFO [Server] - LLMoney [v2.1.5] (LLMoney.dll)
21:00:04 INFO [Server]   EconomyCore for LiteLoaderBDS
21:00:04 INFO [Server] - ScriptEngine-Lua [v2.1.6] (LiteLoader.Lua.dll)
21:00:04 INFO [Server]   Lua ScriptEngine for LiteLoaderBDS
21:00:04 INFO [Server] - ScriptEngine-Js [v2.1.6] (LiteLoader.Js.dll)
21:00:04 INFO [Server]   Javascript ScriptEngine for LiteLoaderBDS
21:00:04 INFO [Server] - test.js [v1.0.0] (test.js)
21:00:04 INFO [Server]   nmsl.js

**Comment by Singl-Daemon** [comment]
az露插件名了

**Comment by Singl-Daemon** [comment]
那个****.js就是test.js

**Comment by yufengya0420** [comment]
配置文件关了锁定颜色了么

**Comment by Singl-Daemon** [comment]
关了

**Comment by xiaoqch** [comment]
已修复，如问题仍存在，请重新打开此issue
