### ISSUE TITLE
Form disadvantage

### ISSUE THREAD

**Issue by twoone-3** [LiteLDev/LiteLoader#344]
https://github.com/LiteLDev/LiteLoaderBDS/blob/0f178f8801c0cc86ee122fb12732ad3693883eef/LiteLoader/Kernel/MC/PlayerAPI.cpp#L696
此处如果传入的buttons和images为空数组，则表单解析错误，因为for循环没有执行，buttontext为json::null，建议在声明变量buttonText时赋予其JSON数组类型

**Comment by xiaoqch** [comment]
已修复，如问题仍存在，请重新打开此issue
