### ISSUE TITLE
"onStepOnPressurePlate" events seems can not work

### ISSUE THREAD

**Issue by VoryWork** [LiteLDev/LiteLoader#350]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.1.6

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

mc.listen("onStepOnPressurePlate",(entity,block)=>{
return false;
})

### Steps to reproduce? 复现此问题的步骤

mc.listen("onStepOnPressurePlate",(entity,block)=>{
return false;
})

### Relevant log output 有关的日志/输出

```shell
.
```

**Comment by dreamguxiang** [comment]
这个事件不可拦截
