### ISSUE TITLE
LLSE: onPlayerCmd

### ISSUE THREAD

**Issue by notacoderr** [LiteLDev/LiteLoader#351]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows Server 2016

### LiteLoader version   LiteLoader版本

2.1.6

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

onPlayerCmd sometimes does not cancel the event.
specifically commands that either add tasks / brings up forms.

In my case, i have a combat logger which blocks players from using a command when in combat. But commands that has forms are intercepted but does not prevent. (meaning it verifies the condition and sends message but still shows the form)

in the images below, i ran the command /lotto while being combat logged

![Screenshot_2022-04-14-15-49-58-438_com mojang minecraftpe](https://user-images.githubusercontent.com/38270548/163339169-9672c39c-0e6c-4650-bdfa-e1fd2d46aa76.jpg)
![Screenshot_2022-04-14-15-50-14-066_com mojang minecraftpe](https://user-images.githubusercontent.com/38270548/163339215-0b705413-3a88-412c-90e7-f128aa918791.jpg)

### Steps to reproduce? 复现此问题的步骤

make a plugin that shows a Form

make a combat plugin that prevents command usage

try it

**Comment by dreamguxiang** [comment]
How did you register command, I can't reproduce

**Comment by notacoderr** [comment]
> How did you register command, I can't reproduce


via Fake Command, (LLSE: mc.regPlayerCmd function)

**Comment by dreamguxiang** [comment]
[True Command Registration](https://docs.litebds.com/#/en_US/Development/GameAPI/Command?id=command-registration-api)  use this
