### ISSUE TITLE
Can't refuse player take book of lectern

### ISSUE THREAD

**Issue by VoryWork** [LiteLDev/LiteLoader#354]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.1.7

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

无法阻止玩家从讲台上取下书
`onUseItemon`
`onAttackBlock`
均无效

**Comment by Redbeanw44602** [comment]
这个操作是客户端处理的，暂时无法解决。
