### ISSUE TITLE
tpdim位置转换应该是反了

### ISSUE THREAD

**Issue by yhzx233** [LiteLDev/LiteLoader#355]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows 10

### LiteLoader version   LiteLoader版本

2.1.7

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

从主世界/tpdim 1到地狱坐标会乘8，从地狱/tpdim 0到主世界坐标会除以8，我猜原来的意思是反着来的（

**Comment by dreamguxiang** [comment]
fix
