### ISSUE TITLE
检测到异常玩家后执行命令

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#358]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

无

### Describe the solution you'd like 您认为还缺少什么?

在检测到异常玩家（刷物/异常移动等）后执行指定命令

**Comment by ShrBox** [comment]
我的建议是，自行clone修改然后编译

**Comment by StarsDream00** [comment]
> 我的建议是，自行clone修改然后编译

好的

**Comment by xiaoqch** [comment]
关闭antiGive后自己写插件实现

**Comment by dreamguxiang** [comment]
ADD
