### ISSUE TITLE
请求在文档中添加"onMobHurt"和"onMobDie"事件受伤原因/死亡原因的对照表

### ISSUE THREAD

**Issue by FBQingYi** [LiteLDev/LiteLoader#360]

**Comment by Jaciezyt** [comment]
可以自行查阅源码：
https://github.com/LiteLDev/LiteLoaderBDS/blob/db6efc2078e0dcd1b2ead1c1d7828323b6a4280c/LiteLoader/Header/MC/Types.hpp#L754

**Comment by dreamguxiang** [comment]
14455df14ad9c6fcd9190e79b7e9aa80e350ed76
