### ISSUE TITLE
AutoUpgrade error

### ISSUE THREAD

**Issue by ShrBox** [LiteLDev/LiteLoader#361]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.1.7

### BDS version   BDS版本

1.18.12.01

### What happened? 发生了什么问题?

AutoUpgrade system output `MD5 Check failed`

### Steps to reproduce? 复现此问题的步骤

Type `ll upgrade`

### Relevant log output 有关的日志/输出

```shell
Nope
```

### Plugin list 插件列表

Nope

**Comment by KawaiiNahida** [comment]
PainText issue
