### ISSUE TITLE
Player->setName() breaks Vanilla commands

### ISSUE THREAD

**Issue by ghost** [LiteLDev/LiteLoader#362]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows 10

### LiteLoader version   LiteLoader版本

2.1.5

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

When I try to change the player's name via Player->setName(), then when I want, for example, to teleport to him, it says to me that there is no such player.

### Steps to reproduce? 复现此问题的步骤

1. Write a simple plugin that changes name of Player.
2. Try to teleport to him

**Comment by dreamguxiang** [comment]
When you change the player's nametag, it means that everywhere in the bds where the nametag is used will be changed.

**Comment by dreamguxiang** [comment]
这不是一个bug，不建议改变铭牌，这将使其他插件不能正常工作。

**Comment by dreamguxiang** [comment]
This is not a bug, and it is not recommended to change nametag, it will make other plugins not work properly

**Comment by dreamguxiang** [comment]
Or you can change it back by hook getnametag

**Comment by Yushu2606** [comment]
https://github.com/StarsDream00/FixGetName
