### ISSUE TITLE
Update 1.18.30

### ISSUE THREAD

**Issue by dreamguxiang** [LiteLDev/LiteLoader#363]
- [x] Update & Fix Headers 
- [x] replace missing function
- [x] update structures(and offsets)
- [x] stability test

**Comment by HoLyMosquito487** [comment]
when dedicated server 1.18.30 is fixed run create bedrock_server_mod update api. 
![1E7A079E-F124-4AFF-8B5F-15FAAD1B5A36](https://user-images.githubusercontent.com/104082600/164367374-f74e80a9-d235-4e26-aaf0-d09ffaef3383.png)

**Comment by muqiupika** [comment]
I‘m looking forward to your update.
Come on, author！
我盼望着你们的更新，加油，作者！

**Comment by KawaiiNahida** [comment]
> when dedicated server 1.18.30 is fixed run create bedrock_server_mod update api. ![1E7A079E-F124-4AFF-8B5F-15FAAD1B5A36](https://user-images.githubusercontent.com/104082600/164367374-f74e80a9-d235-4e26-aaf0-d09ffaef3383.png)

Use https://github.com/LiteLDev/PeEditor/actions/runs/2200172172 instead

**Comment by muqiupika** [comment]
I tried all versions, but none of them are compatible with version 1.18.30
我尝试了所有版本,但都不兼容1.18.30版本

**Comment by ShrBox** [comment]
> I tried all versions, but none of them are compatible with version 1.18.30 我尝试了所有版本,但都不兼容1.18.30版本

Download the beta version from [actions](https://github.com/LiteLDev/LiteLoaderBDS/actions)

**Comment by muqiupika** [comment]
1.18.30 there are still bugs

[Crashed!]
-- Unhandled Exception in -> ucrtbase.dll
-- Exception Code: 0xC0000409
-- Minidump generated in Directory ./logs/Crash

[TrackBack] Function invoke_watson at 0x7FFDDFB2C630  [ucrtbase.dll]
[TrackBack] Function exp2f at 0x7FFDDFB04EF0  [ucrtbase.dll]
[TrackBack] Function invalid_parameter_noinfo at 0x7FFDDFAD8670  [ucrtbase.dll]
[TrackBack] Function invalid_parameter_noinfo_noreturn at 0x7FFDDFB2C600  [ucrtbase.dll]
[TrackBack] Function std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > at 0x7FFDAE673CE0  [BETweaker.dll]
-- At File C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\include\xstring : Line 3007
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function _NLG_Return2 at 0x7FFDD6551150  [VCRUNTIME140_1.dll]
[TrackBack] Function _NLG_Return2 at 0x7FFDD6551150  [VCRUNTIME140_1.dll]
[TrackBack] Function _NLG_Return2 at 0x7FFDD6551150  [VCRUNTIME140_1.dll]
[TrackBack] Function _CxxFrameHandler4 at 0x7FFDD6554070  [VCRUNTIME140_1.dll]
[TrackBack] Function __GSHandlerCheck_EH4 at 0x7FFDAE6D192C  [BETweaker.dll]
-- At File d:\a01\_work\43\s\src\vctools\crt\vcstartup\src\gs\amd64\gshandlereh4.cpp : Line 86
[TrackBack] Function _chkstk at 0x7FFDE1F285C0  [ntdll.dll]
[TrackBack] Function RtlUnwindEx at 0x7FFDE1EB87C0  [ntdll.dll]
[TrackBack] Function _NLG_Return2 at 0x7FFDD6551150  [VCRUNTIME140_1.dll]
[TrackBack] Function _NLG_Return2 at 0x7FFDD6551150  [VCRUNTIME140_1.dll]
[TrackBack] Function _NLG_Return2 at 0x7FFDD6551150  [VCRUNTIME140_1.dll]
[TrackBack] Function _NLG_Return2 at 0x7FFDD6551150  [VCRUNTIME140_1.dll]
[TrackBack] Function _NLG_Return2 at 0x7FFDD6551150  [VCRUNTIME140_1.dll]
[TrackBack] Function _CxxFrameHandler4 at 0x7FFDD6554070  [VCRUNTIME140_1.dll]
[TrackBack] Function DB::SQLiteStmt::create at 0x7FFDA0524950  [LiteLoader.dll]
[TrackBack] Function _chkstk at 0x7FFDE1F285C0  [ntdll.dll]
[TrackBack] Function RtlRestoreContext at 0x7FFDE1EB5240  [ntdll.dll]
[TrackBack] Function KiUserExceptionDispatcher at 0x7FFDE1F276D0  [ntdll.dll]
[TrackBack] Function <lambda_7b1bd5f543fb24b269c0de424f635963>::operator() at 0x7FFDAE6C0430  [BETweaker.dll]
-- At File D:\a\BETweaker\BETweaker\BETweaker\Kernel\HUBInfo.cpp : Line 102
[TrackBack] Function Level::forEachPlayer at 0x7FF674B126B0  [bedrock_server_mod.exe]
[TrackBack] Function Level::forEachPlayer at 0x7FFDA04EC0B0  [LiteLoader.dll]
[TrackBack] Function std::_Func_impl_no_alloc<<lambda_6ffc424278fab3199a2cbeadef7ce066>,void>::_Do_call at 0x7FFDAE6C1A70  [BETweaker.dll]
-- At File C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\include\functional : Line 834
[TrackBack] Function Player::sendCustomFormPacket at 0x7FFDA04FC910  [LiteLoader.dll]
[TrackBack] Function Minecraft::update at 0x7FF6745D3140  [bedrock_server_mod.exe]
[TrackBack] Function ServerInstance::_update at 0x7FF6744DF6E0  [bedrock_server_mod.exe]
[TrackBack] Function <lambda_5fb5cb6c28312d2ba094a9a2ee0e4913>::operator() at 0x7FF6744D82D0  [bedrock_server_mod.exe]
[TrackBack] Function std::thread::_Invoke<std::tuple<<lambda_5fb5cb6c28312d2ba094a9a2ee0e4913> >,0> at 0x7FF6744BC9A0  [bedrock_server_mod.exe]
[TrackBack] Function recalloc at 0x7FFDDFAD6BB0  [ucrtbase.dll]
[TrackBack] Function BaseThreadInitThunk at 0x7FFDE0FB54D0  [KERNEL32.DLL]
[TrackBack] Function RtlUserThreadStart at 0x7FFDE1E84830  [ntdll.dll]


[已退出进程，代码为 3221226505 (0xc0000409)]

**Comment by muqiupika** [comment]
How can i do？

**Comment by dreamguxiang** [comment]
BETweaker did not release version for 1.18.30

**Comment by muqiupika** [comment]
> BETweaker did not release version for 1.18.30

Do you know when you can update1.18.30？
Please be quick QwQ

**Comment by dreamguxiang** [comment]
> Do you know when you can update1.18.30？
> Please be quick QwQ

Yesterday it was ready, you can go to the project gtihub action to download

**Comment by muqiupika** [comment]
> > Do you know when you can update1.18.30？
> > Please be quick QwQ
> 
> Yesterday it was ready, you can go to the project gtihub action to download

Where?Can you send me the connect？
Thanks
