### ISSUE TITLE
player.pos.y 返回的数据过高

### ISSUE THREAD

**Issue by HongyiMC** [LiteLDev/LiteLoader#369]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows 10

### LiteLoader version   LiteLoader版本

2.2.0

### BDS version   BDS版本

1.18.30

### What happened? 发生了什么问题?

player.pos.y 返回的数据过高
假设玩家站在y坐标正好在 64 的地方 player.pos.y 会返回 65.62001037597656
也就是说整整多出了1.62001037597656
望修复。

**Comment by xiaoqch** [comment]
这不是一个bug，直接获取的pos不管哪里都是指的是头部坐标，而你说的64是脚底坐标

**Comment by HongyiMC** [comment]
> 这不是一个bug，直接获取的pos不管哪里都是指的是头部坐标，而你说的64是脚底坐标

上一个版本pos返回的是脚部坐标

**Comment by ShrBox** [comment]
大概是由于mojang的改动导致的

**Comment by xiaoqch** [comment]
> > 这不是一个bug，直接获取的pos不管哪里都是指的是头部坐标，而你说的64是脚底坐标
> 
> 上一个版本pos返回的是脚部坐标

blockPos吧，那个有点问题，pos应该是没变的
