### ISSUE TITLE
Killing a player while logging out will only kill them after the next login.

### ISSUE THREAD

**Issue by ghost** [LiteLDev/LiteLoader#371]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.1.8

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

![image](https://user-images.githubusercontent.com/60012371/164936438-c9513727-8475-4a4b-86f9-0e7e27929071.png)
When a player exits the game when he is in "pvp mode", then after exiting he is not killed immediately.  Only after the next login.  This can be very dishonest, because after entering the player can take their resources by simply running to the coordinates where he left.

### Steps to reproduce? 复现此问题的步骤

1. Write plugin that kills player after logout

**Comment by HoLyMosquito487** [comment]
![EF705E09-66B0-4D36-B3CA-4655AAE35AF4](https://user-images.githubusercontent.com/104082600/164950749-768ddf1f-c80f-4998-88ee-3b2a234ea8a6.png)
Some players when entering the server, the server is closed

**Comment by ambiennt** [comment]
It's more than likely that some methods called within the kill method are scheduled for the next tick, and since the player has left the server, it cannot process the full function until that player has joined back

**Comment by notacoderr** [comment]
so this was a bug after all, i thought it's like that. was thinking of making a hack fix for my combat log plugin

**Comment by dreamguxiang** [comment]
I can't reproduce the above problem

**Comment by ghost** [comment]
> It's more than likely that some methods called within the kill method are scheduled for the next tick, and since the player has left the server, it cannot process the full function until that player has joined back

I thought about this.  But the Event cannot be checked for cancel or event cancelling by task, since there is no event.cancel() or event.isCancelled() method

**Comment by ghost** [comment]
> > It's more than likely that some methods called within the kill method are scheduled for the next tick, and since the player has left the server, it cannot process the full function until that player has joined back
> 
> I thought about this. But the Event cannot be checked for cancel or event cancelling by task, since there is no event.cancel() or event.isCancelled() method

At the moment, Events are arranged like this: If the function returns `true`, then the Event is not canceled, if `false`, then it is canceled.

**Comment by ghost** [comment]
> I can't reproduce the above problem

I can provide you a plugin, this error has been seen by at least 2 users.  Recheck.

**Comment by dreamguxiang** [comment]
> > It's more than likely that some methods called within the kill method are scheduled for the next tick, and since the player has left the server, it cannot process the full function until that player has joined back
> 
> I thought about this. But the Event cannot be checked for cancel or event cancelling by task, since there is no event.cancel() or event.isCancelled() method

 Event has design flaw,You can hook by yourself

**Comment by ghost** [comment]
> 

I know.  As for the plugin, where can I drop it for you?

**Comment by ghost** [comment]
> I know. As for the plugin, where can I drop it for you?

Oh.  Sorry.  I thought you were talking about my problem.

**Comment by dreamguxiang** [comment]
> > 
> 
> I know. As for the plugin, where can I drop it for you?

telegarm

**Comment by xiaoqch** [comment]
> ![EF705E09-66B0-4D36-B3CA-4655AAE35AF4](https://user-images.githubusercontent.com/104082600/164950749-768ddf1f-c80f-4998-88ee-3b2a234ea8a6.png) Some players when entering the server, the server is closed

Please update AntiToolbox plugin, [LiteLoaderPlugins](https://github.com/LiteLDev/LiteLoaderPlugins/releases/tag/2.2.1)

**Comment by ghost** [comment]
> > > 
> > 
> > 
> > I know. As for the plugin, where can I drop it for you?
> 
> telegarm

Are you saying that the player normally dying when he logout?
If I can, I'll drop you a test plugin.  My main system is linux and I need a windows server to do this.

**Comment by dreamguxiang** [comment]
update AntiToolbox plugin

**Comment by ghost** [comment]
What?  This is a really important issue, which is an imbalance!

**Comment by JustStevee** [comment]
> update AntiToolbox plugin

Update your brain. This issue is not related to AntiToolbox plugin. Read description
