### ISSUE TITLE
建议触发AntiGive时自动执行自定义指令

### ISSUE THREAD

**Issue by MengYang8481** [LiteLDev/LiteLoader#372]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

LL的反玩家刷物品很有用，毕竟100%不可能出错；但是玩个MC都开科技，这种人肯定会以其他方式进行作弊或者不良好的游戏行为.

### Describe the solution you'd like 您认为还缺少什么?

检测到作弊行为时自动执行自定义指令，如Kick或ban（具体希望能配置文件自定义）

**Comment by Yushu2606** [comment]
#358

**Comment by dreamguxiang** [comment]
ADD
