### ISSUE TITLE
在玩家进入服务器时会导致服务端崩溃

### ISSUE THREAD

**Issue by muqiupika** [LiteLDev/LiteLoader#373]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows 11

### LiteLoader version   LiteLoader版本

2.2.0

### BDS version   BDS版本

1.18.30

### What happened? 发生了什么问题?

在开服时会有报错，并且在玩家进服时，会导致服务端崩溃，如果开服后没有玩家进入，服务端依旧开启
![E9CDF55A-9544-4FEC-B304-EA2DEDD580D7](https://user-images.githubusercontent.com/83871552/164954491-388b135c-0677-477d-9197-d234017f234c.png)

![DC39D45B-DC77-4098-9346-A4BCD6819BC3](https://user-images.githubusercontent.com/83871552/164954438-c9225563-7090-4129-b8ef-ec6d56f2c6d0.png)

![846F8E6D-99F6-4983-BF46-D5EAD48BC12B](https://user-images.githubusercontent.com/83871552/164954409-382c33e2-ddf1-43db-a61b-27d89a43f63b.png)

### Relevant log output 有关的日志/输出

```shell
[Crashed!]
-- Unhandled Exception in -> LLAntiCheat_pr23_fix8.dll
-- Exception Code: 0xC0000005
-- Minidump generated in Directory ./logs/Crash

[TrackBack] Function ???????? at 0x????????
[TrackBack] Function NetworkChunkPublisher::sendQueuedChunks at 0x7FF7AFAAE210  [bedrock_server_mod.exe]
[TrackBack] Function ServerPlayer::tickWorld at 0x7FF7AFAA63D0  [bedrock_server_mod.exe]
[TrackBack] Function std::_Func_impl_no_alloc<<lambda_2d5fab2554846224c8f2245ae295cf91>,bool,Player &>::_Do_call at 0x7FF7B00A1760  [bedrock_server_mod.exe]
[TrackBack] Function Level::forEachPlayer at 0x7FF7B00B26B0  [bedrock_server_mod.exe]
[TrackBack] Function Level::tick at 0x7FF7B00C24E0  [bedrock_server_mod.exe]
[TrackBack] Function THookTemplate<-2025466159863359608,4938590944480407134>::_hook at 0x7FFD55682330  [BETweaker.dll]
-- At File D:\a\BETweaker\BETweaker\BETweaker\Main\Hook.cpp : Line 48
[TrackBack] Function ServerLevel::tick at 0x7FF7AFAA6030  [bedrock_server_mod.exe]
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function Schedule::nextTick at 0x7FFD3901E8A0  [LiteLoader.dll]
[TrackBack] Function Minecraft::update at 0x7FF7AFB73140  [bedrock_server_mod.exe]
[TrackBack] Function ServerInstance::_update at 0x7FF7AFA7F6E0  [bedrock_server_mod.exe]
[TrackBack] Function <lambda_5fb5cb6c28312d2ba094a9a2ee0e4913>::operator() at 0x7FF7AFA782D0  [bedrock_server_mod.exe]
[TrackBack] Function std::thread::_Invoke<std::tuple<<lambda_5fb5cb6c28312d2ba094a9a2ee0e4913> >,0> at 0x7FF7AFA5C9A0  [bedrock_server_mod.exe]
[TrackBack] Function recalloc at 0x7FFD88D86BB0  [ucrtbase.dll]
[TrackBack] Function BaseThreadInitThunk at 0x7FFD8A1D54D0  [KERNEL32.DLL]
[TrackBack] Function RtlUserThreadStart at 0x7FFD8B364830  [ntdll.dll]


[已退出进程，代码为 3221225477 (0xc0000005)]
```

### Plugin list 插件列表

![Uploading 8E595B0F-1ED0-4F36-A3CA-E098762A75F7.png…]()

**Comment by muqiupika** [comment]
![DBBF06CC-F84F-41EF-9F8E-CBBB968C9B5A](https://user-images.githubusercontent.com/83871552/164954518-22542a14-d4b4-4f1c-abe2-21bd78edf75a.png)

**Comment by HongyiMC** [comment]
这个是旧版 LL anticheat 导致的
更新一下就好

**Comment by wodeyouxi2008** [comment]
> 这个是旧版 LL anticheat 导致的
> 更新一下就好

但是我已经使用了[Releases]中的2.2.0版本

**Comment by wodeyouxi2008** [comment]
你能发我一下LL anticheat的下载链接吗

> > 这个是旧版 LL anticheat 导致的
> > 更新一下就好
> 
> 但是我已经使用了[Releases]中的2.2.0版本

**Comment by muqiupika** [comment]
> 这个是旧版 LL anticheat 导致的
> 更新一下就好

但是我已经在minebbs上下载了LL anticheat的最新版

**Comment by HongyiMC** [comment]
> > 这个是旧版 LL anticheat 导致的
> > 更新一下就好
> 
> 但是我已经在minebbs上下载了LL anticheat的最新版

Discord上面的才是最新
