### ISSUE TITLE
Incorrect work mc.runcmdEx()

### ISSUE THREAD

**Issue by ghost** [LiteLDev/LiteLoader#375]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows 10

### LiteLoader version   LiteLoader版本

2.2.0

### BDS version   BDS版本

1.18.30

### What happened? 发生了什么问题?

**mc.runcmdEx** does not work correctly when using intervals and LiteLoader commands `(ll help, ll reload)`

When trying to run this code:
```javascript
setInterval(() => {
    logger.info("Try to execute 'll reload'")
    logger.info("==============================================")
    var llreload = mc.runcmdEx("ll reload");
    logger.info("==============================================")
}, 1000);
```
The result of the `ll reload` command is displayed, but it should not be displayed, because there is no 
```javascript
logger.info(llreload.output);
```

Screenshot
![bedrock_server_mod_aOSLNvzYYd](https://user-images.githubusercontent.com/44939683/164980215-d17f9517-b723-46a5-91f3-2573c33d4218.png)

### Steps to reproduce? 复现此问题的步骤

1. Create script
2. Paste this code
```javascript
setInterval(() => {
    logger.info("Try to execute 'll reload'")
    logger.info("==============================================")
    var llhelp = mc.runcmdEx("ll reload");
    logger.info("==============================================")
}, 1000);
```
3. Save and run server.

### Relevant log output 有关的日志/输出

```shell
21:03:12 INFO [Automate] Try to execute 'll reload'
21:03:12 INFO [Automate] ==============================================
21:03:13 WARN [LiteLoader] Reload function of dll plugins has not been finished.
21:03:13 ERROR [LiteLoader] Fail to reload plugin LLMoney!
21:03:13 WARN [LiteLoader] Reload function of dll plugins has not been finished.
21:03:13 ERROR [LiteLoader] Fail to reload plugin ScriptEngine-Lua!
21:03:13 WARN [LiteLoader] Reload function of dll plugins has not been finished.
21:03:13 ERROR [LiteLoader] Fail to reload plugin ScriptEngine-Js!
21:03:13 INFO [LiteLoader] Automate.js unloaded.
21:03:13 INFO [LiteLoader] Automate.js loaded.
21:03:13 INFO [Automate] ==============================================
```

### Plugin list 插件列表

![bedrock_server_mod_DEcNzuUrcQ](https://user-images.githubusercontent.com/44939683/164980305-54000d62-e75a-4ef7-8f46-7969bf6408d1.png)

## ❗❗ Automate.js - this is the script that caused the error

**Comment by dreamguxiang** [comment]
These log are not Command output
