### ISSUE TITLE
Server Crashed When Shooting Player

### ISSUE THREAD

**Issue by VoryWork** [LiteLDev/LiteLoader#377]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.2.0

### BDS version   BDS版本

1.18.30

### What happened? 发生了什么问题?

Server Crashed When Shooting Player Twice

### Steps to reproduce? 复现此问题的步骤

1.找我索要一份测试地图
2.用加载LL的BDS
3.进俩玩家改生存模式
4.其中一个玩家射箭对另一个玩家造成伤害
5.第一次射击，伤害正常
6.第二次设计，服务器崩溃

### Relevant log output 有关的日志/输出

```shell
日志太长，找我索要
```

### Plugin list 插件列表

不加载任何插件也会崩溃

**Comment by dreamguxiang** [comment]
minecraft bug

**Comment by dreamguxiang** [comment]
llac已防护
