### ISSUE TITLE
Entity Event: onCreation(entity)

### ISSUE THREAD

**Issue by notacoderr** [LiteLDev/LiteLoader#379]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

This is something useful in my opinion especially if it can be intercepted.

With this we can disallow spawning on certain regions, example claimed lands, spawn, etc.
Right now, I am using command block to simply kill other entities within a certain region so that players will not experience the so-called "spawn r*pe".

### Describe the solution you'd like 您认为还缺少什么?

"onCreation", prototype function(entity)
entity: the entity that is about to spawn

intercept: return false;
//kills or despawn the entity without any drop

**Comment by dreamguxiang** [comment]
ADD
