### ISSUE TITLE
"onProjectileCreated" events seems can not work

### ISSUE THREAD

**Issue by VoryWork** [LiteLDev/LiteLoader#381]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.2.0

### BDS version   BDS版本

1.18.30

### What happened? 发生了什么问题?

onProjectileCreated
无法通过return false拦截弹射物的创建
具体安装我的领地插件就可以测试了

### Steps to reproduce? 复现此问题的步骤

onProjectileCreated
无法通过return false拦截弹射物的创建

### Relevant log output 有关的日志/输出

```shell
无输出
```

### Plugin list 插件列表

LLandEX.lxl.js

**Comment by dreamguxiang** [comment]
不可拦截事件

**Comment by dreamguxiang** [comment]
尝试onProjectileSpawn
