### ISSUE TITLE
Player::getDimensionId()

### ISSUE THREAD

**Issue by KocTu4eK** [LiteLDev/LiteLoader#382]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows 11

### LiteLoader version   LiteLoader版本

2.2.0

### BDS version   BDS版本

1.18.30

### What happened? 发生了什么问题?

Trying to do something with the return value of the Player::getDimensionId() method throws an unknown error.

### Steps to reproduce? 复现此问题的步骤

Just try this for example:
![image](https://user-images.githubusercontent.com/84087988/165366533-ccbd5b16-fda1-4b83-ad2e-d8687ae84b6e.png)

### Relevant log output 有关的日志/输出

```shell
00:20:35 ERROR [LiteLoader] Uncaught Exception Detected!
00:20:35 ERROR [LiteLoader] Error: Code [-1]
00:20:35 ERROR [LiteLoader] In Event (class Event::BlockInteractedEvent)
00:20:35 ERROR [LiteLoader] In Plugin <SimpleSleeping>
```

### Plugin list 插件列表

![image](https://user-images.githubusercontent.com/84087988/165366691-b486b3c0-ee0d-4bf4-8a44-c467d9de7eb1.png)

**Comment by dreamguxiang** [comment]
Unrecoverable

**Comment by dreamguxiang** [comment]
update your mc header

**Comment by KocTu4eK** [comment]
thx
