### ISSUE TITLE
data.toJson lost accuracy when stringfity object includes decimal 

### ISSUE THREAD

**Issue by VoryWork** [LiteLDev/LiteLoader#384]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.2.0

### BDS version   BDS版本

1.18.30

### What happened? 发生了什么问题?

data.toJson在转换小数时损失精度，直接变为整数

### Steps to reproduce? 复现此问题的步骤

```
let test={
  animal:{
    maomi:0.9,
    gougou:1
  }
}
log(data.toJson(test,4))
///{"maomi":0,"gougou":1}
```

### Relevant log output 有关的日志/输出

```shell
无
```

**Comment by dreamguxiang** [comment]
Fixed
