### ISSUE TITLE
PlayerAPI: LLSE player.getExperience()

### ISSUE THREAD

**Issue by notacoderr** [LiteLDev/LiteLoader#389]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

we have player.addExperience(); player.getLevel(); player.resetLevel(); etc.

but idk why we don't have this in LLSE

**Comment by dreamguxiang** [comment]
Since this is available through nbt, no one has suggested it before

**Comment by dreamguxiang** [comment]
next version add

**Comment by StarsDream00** [comment]
because Mojang doesn't make them into functions
