### ISSUE TITLE
命令方块[rm=1]会选择其它维度的实体

### ISSUE THREAD

**Issue by ENIACJushi** [LiteLDev/LiteLoader#390]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows Server 2012

### LiteLoader version   LiteLoader版本

2.1.5

### BDS version   BDS版本

1.18.12

### What happened? 发生了什么问题?

命令方块的选择器会选择不同维度的实体，而在原版是不会的。
最早发现于2月12日。
记忆中这个问题出现在LL加入维度选择之后，在那之前是只会选择本维度的实体的。

### Steps to reproduce? 复现此问题的步骤

1. 在主世界放置一个命令方块，循环执行“execute @a[rm=1] ~~~ say hello world”
2. /tickingarea add ~-16 ~ ~-16 ~16 ~ ~16
3. 传送到地狱或末地
4. 原版应不会继续提示消息，而装了ll会提示，说明选择器选择到了不同维度的实体

### Relevant log output 有关的日志/输出

```shell
无
```

### Plugin list 插件列表

17:05:00 INFO [Server] Plugin Lists [1]
17:05:00 INFO [Server] - LLMoney [v2.1.1] (LLMoney.dll)
17:05:00 INFO [Server]   EconomyCore for LiteLoaderBDS
17:05:00 INFO [Server]
17:05:00 INFO [Server] * Send command "ll list <Plugin Name>" for more information

**Comment by dreamguxiang** [comment]
未能复现，测试下来ll也没显示

**Comment by harry-xi** [comment]
> 未能复现，测试下来ll也没显示

尝试复现时是否保证命令方块处在被加载的区块？
显然的，有一个复现步骤是将命令方块所在位置设置为常加载区块。

**Comment by dreamguxiang** [comment]
> > 未能复现，测试下来ll也没显示
> 
> 尝试复现时是否保证命令方块处在被加载的区块？ 显然的，有一个复现步骤是将命令方块所在位置设置为常加载区块。

是啊
