### ISSUE TITLE
Whitelist/Allowlist Command in Game

### ISSUE THREAD

**Issue by BuslnwTH** [LiteLDev/LiteLoader#393]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

BDS Server Command not allowed whitelist/Allowlist in game.

### Describe the solution you'd like 您认为还缺少什么?

add command /whitelist /allowlist Command. In game.

**Comment by KawaiiNahida** [comment]
You can do it by using a plugin

**Comment by BuslnwTH** [comment]
I understand plugin can do. but want to be a feature in LLCore.

**Comment by dreamguxiang** [comment]
Please adjust the op level to the console level

**Comment by dreamguxiang** [comment]
![image](https://user-images.githubusercontent.com/62042544/166179898-66a66796-cc15-4d2b-b5eb-cc8bdbc78448.png)

**Comment by BuslnwTH** [comment]
thank you.
