### ISSUE TITLE
为llse增加玩家合成事件

### ISSUE THREAD

**Issue by zyy82** [LiteLDev/LiteLoader#394]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

llse无法获取玩家合成事件

### Describe the solution you'd like 您认为还缺少什么?

给llse增加onCrafting函数，可以监听与拦截玩家合成。可以修改合成出来的物品

**Comment by OEOTYAN** [comment]
为什么不使用行为包增删合成表？
