### ISSUE TITLE
LLSE pl.clearItem 返回值异常

### ISSUE THREAD

**Issue by hhaipaap** [LiteLDev/LiteLoader#395]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows 10

### LiteLoader version   LiteLoader版本

2.2.2

### BDS version   BDS版本

1.18.31

### What happened? 发生了什么问题?

LLse 在使用pl.clearItem(type) api时如果清理的物品小于64只返回1
大于64才会返回正确的数值 

### Steps to reproduce? 复现此问题的步骤

使用 pl.clearItem(type)

### Relevant log output 有关的日志/输出

```shell
无
```

### Plugin list 插件列表

在写插件时发现的

**Comment by dreamguxiang** [comment]
Fix
