### ISSUE TITLE
刷新XUID数据库

### ISSUE THREAD

**Issue by ImYoyoData** [LiteLDev/LiteLoader#403]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

玩家进入第一次记录xuid数据库 但是玩家修改名称后 用xuid 去查询名称 依然是旧的

### Describe the solution you'd like 您认为还缺少什么?

我觉得应该有一个刷新的,主动函数或者自动检测变更都可以

**Comment by Jaciezyt** [comment]
事实上，PlayerDB中储存的玩家名都是realName，既Xbox昵称。如果不更改Xbox昵称的话，这里的名称是不会变的。
如果您想要获取玩家的NameTag，可以用getNameTag函数获取，储存+离线读取的话也可以自己造轮子。

**Comment by ImYoyoData** [comment]
好吧,谢谢
