### ISSUE TITLE
LLSE 获取自身文件名

### ISSUE THREAD

**Issue by ImYoyoData** [LiteLDev/LiteLoader#404]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

我认为在做插件自动更新的时候,避免用户修改文件名导致的写入错误的问题!

### Describe the solution you'd like 您认为还缺少什么?

增加一个 获取 插件自身的文件名 这样方便明确的更新自身而不会因为修改文件名而发生的错误信息!

**Comment by Jaciezyt** [comment]
如果您使用C++进行插件开发的话，您可以使用LLSDK中的WinHelper.h获取当前模块所在路径，如：
```cpp
std::string path = GetModulePath(GetCurrentModule()); //  in Utils/WinHelper.h
```

**Comment by ImYoyoData** [comment]
llse可以做到吗?

**Comment by Jaciezyt** [comment]
可以，wip

**Comment by Jaciezyt** [comment]
added 6d0dd0a01
e.g.
```js
let info = ll.getPluginInfo("MyPlugin");
info.filePath;
```
