### ISSUE TITLE
放置手持方块时`onPlaceBlock`事件的`block`参数携带异常的`nbt`

### ISSUE THREAD

**Issue by dzx-dzx** [LiteLDev/LiteLoader#406]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows 11

### LiteLoader version   LiteLoader版本

2.2.3

### BDS version   BDS版本

1.18.32.02

### What happened? 发生了什么问题?

打印`onPlaceBlock`所得的`block`, 其`nbt`中`states`似乎被重置为默认值.

例如, 使用以下测试代码:
```javascript
mc.listen("onPlaceBlock", (player, block) => {
    log(block.getNbt().toString())
    return true
})
```

放置黄绿色玻璃与青色玻璃时, 其输出均为:
```
{"name":"minecraft:stained_glass","states":{"color":"white"},"version":...}
```

使用物品点击两种玻璃则没有问题:
```
{"name":"minecraft:stained_glass","states":{"color":"cyan"},"version":...}
{"name":"minecraft:stained_glass","states":{"color":"lime"},"version":...}
```

**Comment by dreamguxiang** [comment]
Fix
