### ISSUE TITLE
使用rename修改玩家name,导致命令指定玩家名失效

### ISSUE THREAD

**Issue by CoolLoong** [LiteLDev/LiteLoader#412]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows 10

### LiteLoader version   LiteLoader版本

2.2.4

### BDS version   BDS版本

1.18.32.02

### What happened? 发生了什么问题?

使用rename修改玩家name,导致命令指定玩家名失效(**在命令行中执行**)
例如op命令不能再使用realname而是使用被修改后的name
tp指令也是如此

### Steps to reproduce? 复现此问题的步骤

使用llse的rename方法修改玩家name
在命令行中测试op命令

**Comment by Yushu2606** [comment]
#362

**Comment by Jaciezyt** [comment]
THIS IS NOT A BUG

**Comment by Yushu2606** [comment]
https://github.com/StarsDream00/FixGetName
