### ISSUE TITLE
加入播放声音功能

### ISSUE THREAD

**Issue by scientificworld** [LiteLDev/LiteLoader#414]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

我想实现一个点歌插件，需要播放背景音乐，但找了一下api，似乎没有关于播放声音的

### Describe the solution you'd like 您认为还缺少什么?

有没有可能加入直接播放声音的api（PS. 找到过一个切换背景音乐的插件，但似乎要重启服务器，应该是基于资源包实现的，可不可能在无需重启的情况下直接播放）

**Comment by xiaoqch** [comment]
可能会增加播放已有背景音乐的API，但你想要的功能不适合添加到加载器，请考虑插件或addon

**Comment by Jaciezyt** [comment]
所有声音都基于资源包，不可能像你所说的点歌播放

**Comment by hhaipaap** [comment]
最好加个可以播放服务器本地音乐的api
用addon玩家进服下载太慢了

**Comment by KawaiiNahida** [comment]
技术上做不到，播放来自服务器的音频文件只能通过资源包或者addon内嵌实现
