### ISSUE TITLE
粒子(particle)和效果(effect)存在问题

### ISSUE THREAD

**Issue by kyouhimesama** [LiteLDev/LiteLoader#415]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows 10

### LiteLoader version   LiteLoader版本

2.2.5

### BDS version   BDS版本

1.18.33.02

### What happened? 发生了什么问题?

1.actor_->addEffect(MobEffect::EffectType::Poison,10000,5,false,true,true);
存在伤害动画但没有中毒粒子效果
2.Level::spawnParticleEffect("minecraft:heart_particle",*actor,actor->getPosition());
函数动态库加载报错 

### Steps to reproduce? 复现此问题的步骤

1.actor_->addEffect(MobEffect::EffectType::Poison,10000,5,false,true,true);
2.Level::spawnParticleEffect("minecraft:heart_particle",*actor,actor->getPosition());

### Relevant log output 有关的日志/输出

```shell
2.Level::spawnParticleEffect("minecraft:heart_particle",*actor,actor->getPosition());

00:07:24 INFO [YOOMEPlugin] amplifiler 0.25
00:07:24 ERROR [PreLoader] Could not find function in memory: ?spawnParticleEffect@Level@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVActor@@AEBVVec3@@@Z
00:07:24 ERROR [PreLoader] Plugin: LiteLoader.dll
```

**Comment by WangYneos** [comment]
Plz update libs and headers

**Comment by dreamguxiang** [comment]
fix next verison
