### ISSUE TITLE
解耦项目

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#421]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

1. 现在的LL将几乎所有模块都塞在主仓库里（一部分内置于主项目里），对某个模块的改动都会使整个项目重新编译，浪费时间（目前编译时长约为25分钟）。
2. 项目过于繁杂，难以分隔清楚依赖关系。
3. 用户无法在不查阅源码的情况下完全了解启用了哪些功能
4. 多余功能浪费时间和空间。

### Describe the solution you'd like 您认为还缺少什么?

尽量细分所有功能到对应模块，并将各模块分割到各自的仓库并编译发行

**Comment by Jaciezyt** [comment]
好主意

**Comment by StarsDream00** [comment]
https://github.com/LiteLDev-421

**Comment by dreamguxiang** [comment]
你要知道当初为什么要全合并在一起，就不会提出分割，

**Comment by Yushu2606** [comment]
https://github.com/LiteLDev/LLScriptEngine
这是准备做了吗？（

**Comment by Jaciezyt** [comment]
@StarsDream00 新建文件夹.jpg

**Comment by Yushu2606** [comment]
LiteLDev/ScriptEngine#26
