### ISSUE TITLE
return false doesn't work

### ISSUE THREAD

**Issue by mikhaillav** [LiteLDev/LiteLoader#423]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows 10

### LiteLoader version   LiteLoader版本

2.2.5

### BDS version   BDS版本

 1.18.33.02

### What happened? 发生了什么问题?

i wrote plugin that off all player's comands via return false in PlayerCmdEvent. it works fine in vanilla's cmd but doesn't work in plugin's cmd

### Steps to reproduce? 复现此问题的步骤

1. it's my plugin 
    Event::PlayerCmdEvent::subscribe([](const Event::PlayerCmdEvent& ev) {
        Player* player = ev.mPlayer;
        string cmd = ev.mCommand;
        player->sendText("Bruh, you can't use commands");
        return false;
    });
2. i try to do off PFEssentials tpa command and it's doesn't work

### Relevant log output 有关的日志/输出

```shell
no output just doesn't work XD
```

### Plugin list 插件列表

there is only my plugin and PFEssentials

**Comment by ShrBox** [comment]
Maybe it's `PFEssentials`'s problem

**Comment by mikhaillav** [comment]
looks like yes, thank you
