### ISSUE TITLE
新增注册 /ability 命令

### ISSUE THREAD

**Issue by hhaipaap** [LiteLDev/LiteLoader#424]
### Is your feature request related to a problem? Please describe. 您认为现在存在什么问题?

LLse已经有pl.getAbilities()获取玩家能力列表但没有修改能力列表的api

### Describe the solution you'd like 您认为还缺少什么?

在LiteLoader.json增加注册 /ability 命令的选项
或者在LLse里增加开关玩家飞行的api

**Comment by xiaoqch** [comment]
Ability的修改有客户端相关的bug，最新测试版有相关内容更新，可能会随观察者模式bug一并修复（观察者模式是基于ability的

**Comment by dreamguxiang** [comment]
暂不考虑，强开会有小问题，需要请自行打开教育玩法
