### ISSUE TITLE
setAuxValue of item invalid bug

### ISSUE THREAD

**Issue by ghost** [LiteLDev/LiteLoader#427]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows 11

### LiteLoader version   LiteLoader版本

latest(2.2.5)

### BDS version   BDS版本

1.18.33.02

### What happened? 发生了什么问题?

Whether the aux value is, I can not set the value when I call `item->setAuxValue(aux);`
So I can merely set the aux value when I call `ItemStack::create(id, aux, count);`
```
ItemStack* item = ItemStack::create(id, aux, count);
item->setAuxValue(1);// not '0', such as 1 or 2...
std::cout << "aux: " + std::to_string(item->getAux()) + ", auxValue: " + std::to_string(item->getAuxValue()) << std::endl;
```
Output: 
`aux: 0, auxValue: 0`//not '1' or other value

### Steps to reproduce? 复现此问题的步骤

1. Start a C++ plugin.
2. Input the codes.

### Relevant log output 有关的日志/输出

```shell
aux: 0, auxValue: 0
//not '1' or other value
```

### Plugin list 插件列表

empty plugin.

**Comment by ghost** [comment]
By the way, if the aux value is not '0' when I call `ItemStack::create(id, aux, count);`, it call `item->setAuxValue(0);` successful.

**Comment by KawaiiNahida** [comment]
check those two function in Decompile tools
```
__int16 __fastcall ItemStackBase::getAuxValue(ItemStackBase *this)
{
  __int64 v1; // rax

  v1 = *((_QWORD *)this + 3);
  if ( !v1 || *((_WORD *)this + 16) == 0x7FFF )
    return *((_WORD *)this + 16);
  else
    return *(_WORD *)(v1 + 8);
}
```
```
void __fastcall ItemStackBase::setAuxValue(ItemStackBase *this, __int16 a2)
{
  __int16 v2; // ax

  v2 = 0;
  if ( a2 > 0 )
    v2 = a2;
  *((_WORD *)this + 16) = v2;
}
```

**Comment by KawaiiNahida** [comment]
Skill issue
