### ISSUE TITLE
为报错提供更多信息

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#430]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.2.5

### BDS version   BDS版本

1.18.33.02

### What happened? 发生了什么问题?

有关报错没有错误位置等其他信息

### Steps to reproduce? 复现此问题的步骤

未知

### Relevant log output 有关的日志/输出

```shell
ERROR [LiteLoader] Unknown Type of Form Parameter!
```

**Comment by Jaciezyt** [comment]
确定不是插件的问题？

**Comment by Yushu2606** [comment]
> 确定不是插件的问题？

是插件调用API时触发的异常，但只有这一条日志，没有别的信息

**Comment by KawaiiNahida** [comment]
![image](https://user-images.githubusercontent.com/42824603/172030861-d0486af0-ec4f-46e2-a3a3-4b4abfed6db3.png)

**Comment by StarsDream00** [comment]
> ![image](https://user-images.githubusercontent.com/42824603/172030861-d0486af0-ec4f-46e2-a3a3-4b4abfed6db3.png)
> 
> 

？？
LiteLoader只输出了这一条消息我怎么找原因，，

**Comment by Yushu2606** [comment]
参数类型不正确时不会显示第几个参数
