### ISSUE TITLE
LLSE sp.simulateDisconnect()崩服

### ISSUE THREAD

**Issue by hhaipaap** [LiteLDev/LiteLoader#435]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.2.5

### BDS version   BDS版本

1.18.33

### What happened? 发生了什么问题?

在使用sp.simulateDisconnect()时崩服
由于安装了fishing导致没有日志输出

### Steps to reproduce? 复现此问题的步骤

使用sp.simulateDisconnect()

### Plugin list 插件列表

08:18:45 INFO [Server] Plugin Lists [38]
08:18:45 INFO [Server] - Report.js [v1.0.0] (Report.js)
08:18:45 INFO [Server]   Report.js
08:18:45 INFO [Server] - AntiCheats-1.18.30.0519.dll [v1.0.0] (AntiCheats-1.18.30.0519.dll)
08:18:45 INFO [Server]   AntiCheats-1.18.30.0519.dll
08:18:45 INFO [Server] - LLFakePlayer [v0.0.1] (LLFakePlayer.dll)
08:18:45 INFO [Server]   Fake Player plugin base on LiteLoader
08:18:45 INFO [Server] - 63hd.js [v1.0.0] (63hd.js)
08:18:45 INFO [Server]   63hd.js
08:18:45 INFO [Server] - BackupHelper [v2.0.6] (BackupHelper.dll)
08:18:45 INFO [Server]   One command to backup your level
08:18:45 INFO [Server] - tps.js [v1.0.0] (tps.js)
08:18:45 INFO [Server]   tps.js
08:18:45 INFO [Server] - ScriptEngine-Lua [v2.2.5] (LiteLoader.Lua.dll)
08:18:45 INFO [Server]   Lua ScriptEngine for LiteLoaderBDS
08:18:45 INFO [Server] - LLMoney [v2.2.5] (LLMoney.dll)
08:18:45 INFO [Server]   EconomyCore for LiteLoaderBDS
08:18:45 INFO [Server] - TrustedSkin [v1.0.0] (TrustedSkin.dll)
08:18:45 INFO [Server]   Make all skin trusted
08:18:45 INFO [Server] - AlwaysBroadcast [v1.0.5] (AlwaysBroadcast.dll)
08:18:45 INFO [Server]   Fix an broadcast bug in bds.
08:18:45 INFO [Server] - Transfer.js [v1.0.0] (Transfer.js)
08:18:45 INFO [Server]   Transfer.js
08:18:45 INFO [Server] - BanExplosion [v1.5.7] (BanExplosion.dll)
08:18:45 INFO [Server]   Customize your explosion destroy rule!
08:18:45 INFO [Server] - MovingLight [v1.7.5] (MovingLight.dll)
08:18:45 INFO [Server]   The moving light.
08:18:45 INFO [Server] - setname.js [v1.0.0] (setname.js)
08:18:45 INFO [Server]   setname.js
08:18:45 INFO [Server] - PFEssentials [v0.1.8169] (PFEssentials.LL.dll)
08:18:45 INFO [Server]   PF基础插件 v0.1.8169.38280 
08:18:45 INFO [Server] - SleepFast [v1.1.0] (SleepFast.js)
08:18:45 INFO [Server]   快速睡觉
08:18:45 INFO [Server] - ScriptEngine-Js [v2.2.5] (LiteLoader.Js.dll)
08:18:45 INFO [Server]   Javascript ScriptEngine for LiteLoaderBDS
08:18:45 INFO [Server] - backup.lxl.js [v1.0.0] (backup.lxl.js)
08:18:45 INFO [Server]   backup.lxl.js
08:18:45 INFO [Server] - bl.js [v1.0.0] (bl.js)
08:18:45 INFO [Server]   bl.js
08:18:45 INFO [Server] - cbl.js [v1.0.0] (cbl.js)
08:18:45 INFO [Server]   cbl.js
08:18:45 INFO [Server] - IKill.js [v1.0.0] (IKill.js)
08:18:45 INFO [Server]   IKill.js
08:18:45 INFO [Server] - cd.js [v1.0.0] (cd.js)
08:18:45 INFO [Server]   cd.js
08:18:45 INFO [Server] - CMENU.js [v1.0.0] (CMENU.js)
08:18:45 INFO [Server]   CMENU.js
08:18:45 INFO [Server] - DBoxShop [v1.0.0] (DBoxShop.js)
08:18:45 INFO [Server]   箱子商店
08:18:45 INFO [Server] - DSimulatePlayer [v1.0.3] (DSimulatePlayer.js)
08:18:45 INFO [Server]   模拟玩家
08:18:45 INFO [Server] - RecycleShops.js [v1.0.0] (RecycleShops.js)
08:18:45 INFO [Server]   RecycleShops.js
08:18:45 INFO [Server] - Email.js [v1.0.0] (Email.js)
08:18:45 INFO [Server]   Email.js
08:18:45 INFO [Server] - MoneyTitle.js [v1.0.0] (MoneyTitle.js)
08:18:45 INFO [Server]   MoneyTitle.js
08:18:45 INFO [Server] - giveclock.lxl.js [v1.0.0] (giveclock.lxl.js)
08:18:45 INFO [Server]   giveclock.lxl.js
08:18:45 INFO [Server] - reward.lxl.js [v1.0.0] (reward.lxl.js)
08:18:45 INFO [Server]   reward.lxl.js
08:18:45 INFO [Server] - LiteSign.js [v1.0.0] (LiteSign.js)
08:18:45 INFO [Server]   LiteSign.js
08:18:45 INFO [Server] - LxlBlackBe.lxl.js [v1.0.0] (LxlBlackBe.lxl.js)
08:18:45 INFO [Server]   LxlBlackBe.lxl.js
08:18:45 INFO [Server] - SimpleTeam [v1.1.3] (SimpleTeam1.1.3.lls.js)
08:18:45 INFO [Server]   让玩家可以互相组队 | Have players team up with each other
08:18:45 INFO [Server] - MayFly.js [v1.0.0] (MayFly.js)
08:18:45 INFO [Server]   MayFly.js
08:18:45 INFO [Server] - MoneyBill.js [v1.0.0] (MoneyBill.js)
08:18:45 INFO [Server]   MoneyBill.js
08:18:45 INFO [Server] - PlayerTitle.js [v1.0.0] (PlayerTitle.js)
08:18:45 INFO [Server]   PlayerTitle.js
08:18:45 INFO [Server] - PointVolume.js [v1.0.0] (PointVolume.js)
08:18:45 INFO [Server]   PointVolume.js
08:18:45 INFO [Server] - Sidebar.lxl.js [v1.0.0] (Sidebar.lxl.js)
08:18:45 INFO [Server]   Sidebar.lxl.js

**Comment by KawaiiNahida** [comment]
临时去掉会导致无法正常抓取崩溃日志的插件，带上log再反馈

**Comment by xiaoqch** [comment]
无法复现，可能是其他插件没适配模拟玩家，请临时去掉反作弊后提供崩服日志

**Comment by hhaipaap** [comment]
是fishing导致的无法正常抓取崩溃日志
但去掉fishingbug就没了

**Comment by xiaoqch** [comment]
> 是fishing导致的无法正常抓取崩溃日志 但去掉fishingbug就没了

请向该插件作者反馈

**Comment by dreamguxiang** [comment]
#437
