### ISSUE TITLE
使用bedrock_server_mod.exe运行出现无法加入世界

### ISSUE THREAD

**Issue by ImMello223** [LiteLDev/LiteLoader#436]
### Exceptions module 异常模块

Core 核心

### Operating System 操作系统

Windows Server 2016

### LiteLoader version   LiteLoader版本

2.2.5

### BDS version   BDS版本

1.18.33

### What happened? 发生了什么问题?

使用bedrock_server_mod.exe运行时会出现，无法加入服务器无法显示人数延迟，但服务器后台还是可以正常输入指令，没有安装插件，ip和端口都检查过
![Uploading Screenshot_20220606_230301.jpg…]()
![Uploading Screenshot_20220606_230316.jpg…]()
使用bedrock_server.exe运行服务器可以正常加入
![Uploading Screenshot_20220606_230227.jpg…]()
![Uploading Screenshot_20220606_230147.jpg…]()

**Comment by ShrBox** [comment]
检查您的服务器防火墙策略
