### ISSUE TITLE
LLSE sp.simulateDisconnect()崩服

### ISSUE THREAD

**Issue by hhaipaap** [LiteLDev/LiteLoader#437]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows Server 2019

### LiteLoader version   LiteLoader版本

2.2.5

### BDS version   BDS版本

1.18.32

### What happened? 发生了什么问题?

在使用sp.simulateDisconnect()时崩服

### Steps to reproduce? 复现此问题的步骤

使用sp.simulateDisconnect()

### Relevant log output 有关的日志/输出

```shell
[Crashed!]
-- Unhandled Exception in -> bedrock_server_mod.exe
-- Exception Code: 0xC0000005
-- C++ STL Exception detected!

[StackTrace] Function SynchedActorData::_get at 0x7FF7289AA360  [bedrock_server_mod.exe<1.18.32.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7289AA366  [bedrock_server_mod.exe<1.18.32.02>]
[StackTrace] Function SynchedActorData::set<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > at 0x7FF7282BC680  [bedrock_server_mod.exe<1.18.32.02>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF7282BC694  [bedrock_server_mod.exe<1.18.32.02>]
[StackTrace] Function ???????? at 0x19228C13E7D  []
[StackTrace] Function ???????? at 0x19254176090  []
[StackTrace] Function ???????? at 0x82B847F990  []
[StackTrace] Function ???????? at 0x82B847F9C9  []
[StackTrace] Function ???????? at 0x30  []
[StackTrace] Function ???????? at 0x1925DF1B450  []
[StackTrace] Function ???????? at 0x30  []
```

### Plugin list 插件列表

在测试服务器,没有其他插件!

**Comment by hhaipaap** [comment]
[CrashDump_20220607_11-13-25.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/8849853/CrashDump_20220607_11-13-25.zip)
这是dmp文件

**Comment by HoLyMosquito487** [comment]
![DC8F0C4C-CA1E-42B0-8908-73B058DA0C95](https://user-images.githubusercontent.com/104082600/172290488-6480d30e-a137-4a6a-8711-d17f3216441f.png)
![95208E46-B0DD-438C-9CB9-0F6F4233EC05](https://user-images.githubusercontent.com/104082600/172290510-6b41b6b4-7cef-4c86-bfdd-415fd7c3ce78.png)
1.19.10.20 beta liteloader 2.2.5 not delete bedrock_server.exe, i can add plugins to server

**Comment by dreamguxiang** [comment]
> ![DC8F0C4C-CA1E-42B0-8908-73B058DA0C95](https://user-images.githubusercontent.com/104082600/172290488-6480d30e-a137-4a6a-8711-d17f3216441f.png) ![95208E46-B0DD-438C-9CB9-0F6F4233EC05](https://user-images.githubusercontent.com/104082600/172290510-6b41b6b4-7cef-4c86-bfdd-415fd7c3ce78.png) 1.19.10.20 beta liteloader 2.2.5 not delete bedrock_server.exe, i can add plugins to server

not suppot

**Comment by dreamguxiang** [comment]
> [CrashDump_20220607_11-13-25.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/8849853/CrashDump_20220607_11-13-25.zip) 这是dmp文件

删除所有无关插件再测试

**Comment by StarsDream00** [comment]
need to close
