### ISSUE TITLE
为脚本引擎提供更换API调用的经济核心的功能

### ISSUE THREAD

**Issue by harry-xi** [LiteLDev/LiteLoader#443]
### 您的建议是否与现存的某个问题相关?请描述问题?

因为一些特殊需求无法依靠liteloader自带的LLmoney经济核心实现，手动适配了许多插件到自制的经济核心，这一过程耗费的大量的时间和精力，但主要工作仅为替换了大量接口调用语句。

### 您认为还缺少什么?如何解决您的问题?

希望能LLSE提供一种便利的形式让自己的经济核心替换LLmoney来对接到脚本引擎提供的通用的经济核心接口。

**Comment by xiaoqch** [comment]
请考虑提供一个api文件后其他插件 require对money进行替换，只要保留API相同，就不需要过多更改，LLSE是不允许插件主动更改其他插件的API的，

**Comment by harry-xi** [comment]
感谢提供解决方案
