### ISSUE TITLE
点击传送指令的命令方块，控制台爆红

### ISSUE THREAD

**Issue by Arnolwutong** [LiteLDev/LiteLoader#444]
### 异常模块

Core(核心)

### 操作系统

Windows 10

### LiteLoader版本

LiteLoaderBDS 2.2.7 - Beta

### BDS版本

Version 1.19.1.01(ProtocolVersion 527)

### 发生了什么?

点击传送指令的命令方块后，控制台爆红

### 复现此问题的步骤

1.装Version 1.19.1.01(ProtocolVersion 527)
2.装LiteLoaderBDS 2.2.7 - Beta
3.进服点带传送指令的命令方块
4.控制台爆红

### 有关的日志/输出

```shell
09:40:21 ERROR [LiteLoader] Uncaught SEH Exception Detected!
09:40:21 ERROR [LiteLoader] Error: Code [-1073741819] 内存位置访问无效。

09:40:21 ERROR [LiteLoader] In Event (class Event::PlayerJoinEvent)
```

### 插件列表

```shell
ll list
09:43:34 INFO [Server] Plugin Lists [1]
09:43:34 INFO [Server] - LLMoney [v2.2.5] (LLMoney.dll)
09:43:34 INFO [Server]   EconomyCore for LiteLoaderBDS
09:43:34 INFO [Server]
09:43:34 INFO [Server] * Send command "ll list <Plugin Name>" for more information
```

**Comment by Arnolwutong** [comment]
我装了个LLSE插件，发现无法使用，
version
10:10:25 INFO [Server] Bedrock Dedicated Server v1.19.1
10:10:25 INFO [Server] - with LiteLoaderBDS 2.2.7
10:10:25 INFO [Server] - Network Protocol: 527

10:05:53 ERROR [LiteLoader] Uncaught SEH Exception Detected!
10:05:53 ERROR [LiteLoader] Error: Code [-1073741819] 内存位置访问无效。

10:05:53 ERROR [LiteLoader] In Event (class Event::PlayerJoinEvent)
10:06:26 INFO [Command] <> /clear @s
10:06:29 INFO [Server] Player disconnected: opwutong, xuid: 2535427985579640
10:06:39 INFO [Server] Player connected: opwutong, xuid: 2535427985579640
10:06:43 ERROR [LiteLoader] Uncaught SEH Exception Detected!
10:06:43 ERROR [LiteLoader] Error: Code [-1073741819] 内存位置访问无效。

10:06:43 ERROR [LiteLoader] In Event (class Event::PlayerJoinEvent)
10:06:43 ERROR [LiteLoader] C++ Uncaught Exception Detected!
10:06:43 ERROR [LiteLoader] 内存位置访问无效。

10:06:43 ERROR [LiteLoader]     at ./plugins/GiveClock.lxl.js:81:20
10:06:43 ERROR [LiteLoader] In API: PlayerClass::giveItem
10:06:43 ERROR [LiteLoader] In Plugin: GiveClock
10:06:43 ERROR [LiteLoader] C++ Uncaught Exception Detected!
10:06:43 ERROR [LiteLoader] 内存位置访问无效。

10:06:43 ERROR [LiteLoader]     at ./plugins/GiveClock.lxl.js:82:36
10:06:43 ERROR [LiteLoader] In API: PlayerClass::getName
10:06:43 ERROR [LiteLoader] In Plugin: GiveClock
10:06:43 INFO [GiveClock] 入服自动给钟 undefined clock*1
10:07:29 INFO [Command] <> /clock
10:07:29 ERROR [LiteLoader] C++ Uncaught Exception Detected!
10:07:29 ERROR [LiteLoader] 内存位置访问无效。

10:07:29 ERROR [LiteLoader]     at ./plugins/GiveClock.lxl.js:105:39
10:07:29 ERROR [LiteLoader] In API: PlayerClass::giveItem
10:07:29 ERROR [LiteLoader] In Plugin: GiveClock
10:07:29 ERROR [LiteLoader] C++ Uncaught Exception Detected!
10:07:29 ERROR [LiteLoader] 内存位置访问无效。

10:07:29 ERROR [LiteLoader]     at ./plugins/GiveClock.lxl.js:106:53
10:07:29 ERROR [LiteLoader] In API: PlayerClass::getName
10:07:29 ERROR [LiteLoader] In Plugin: GiveClock
10:07:29 INFO [GiveClock] 指令给钟 undefined clock*1[cid:9929764f-d12e-485d-9deb-52ef91d03c6d]
________________________________
发件人: xiaoqch ***@***.***>
发送时间: 2022年6月9日 9:58
收件人: LiteLDev/LiteLoaderBDS ***@***.***>
抄送: Arnol梧桐 ***@***.***>; Author ***@***.***>
主题: Re: [LiteLDev/LiteLoaderBDS] 点击传送指令的命令方块，控制台爆红 (Issue #444)


Closed #444<https://github.com/LiteLDev/LiteLoaderBDS/issues/444> as completed.

―

**Comment by dreamguxiang** [comment]
> 我装了个LLSE插件，发现无法使用， version 10:10:25 INFO [Server] Bedrock Dedicated Server v1.19.1 10:10:25 INFO [Server] - with LiteLoaderBDS 2.2.7 10:10:25 INFO [Server] - Network Protocol: 527 10:05:53 ERROR [LiteLoader] Uncaught SEH Exception Detected! 10:05:53 ERROR [LiteLoader] Error: Code [-1073741819] 内存位置访问无效。 10:05:53 ERROR [LiteLoader] In Event (class Event::PlayerJoinEvent) 10:06:26 INFO [Command] <> /clear @s 10:06:29 INFO [Server] Player disconnected: opwutong, xuid: 2535427985579640 10:06:39 INFO [Server] Player connected: opwutong, xuid: 2535427985579640 10:06:43 ERROR [LiteLoader] Uncaught SEH Exception Detected! 10:06:43 ERROR [LiteLoader] Error: Code [-1073741819] 内存位置访问无效。 10:06:43 ERROR [LiteLoader] In Event (class Event::PlayerJoinEvent) 10:06:43 ERROR [LiteLoader] C++ Uncaught Exception Detected! 10:06:43 ERROR [LiteLoader] 内存位置访问无效。 10:06:43 ERROR [LiteLoader] at ./plugins/GiveClock.lxl.js:81:20 10:06:43 ERROR [LiteLoader] In API: PlayerClass::giveItem 10:06:43 ERROR [LiteLoader] In Plugin: GiveClock 10:06:43 ERROR [LiteLoader] C++ Uncaught Exception Detected! 10:06:43 ERROR [LiteLoader] 内存位置访问无效。 10:06:43 ERROR [LiteLoader] at ./plugins/GiveClock.lxl.js:82:36 10:06:43 ERROR [LiteLoader] In API: PlayerClass::getName 10:06:43 ERROR [LiteLoader] In Plugin: GiveClock 10:06:43 INFO [GiveClock] 入服自动给钟 undefined clock*1 10:07:29 INFO [Command] <> /clock 10:07:29 ERROR [LiteLoader] C++ Uncaught Exception Detected! 10:07:29 ERROR [LiteLoader] 内存位置访问无效。 10:07:29 ERROR [LiteLoader] at ./plugins/GiveClock.lxl.js:105:39 10:07:29 ERROR [LiteLoader] In API: PlayerClass::giveItem 10:07:29 ERROR [LiteLoader] In Plugin: GiveClock 10:07:29 ERROR [LiteLoader] C++ Uncaught Exception Detected! 10:07:29 ERROR [LiteLoader] 内存位置访问无效。 10:07:29 ERROR [LiteLoader] at ./plugins/GiveClock.lxl.js:106:53 10:07:29 ERROR [LiteLoader] In API: PlayerClass::getName 10:07:29 ERROR [LiteLoader] In Plugin: GiveClock 10:07:29 INFO [GiveClock] 指令给钟 undefined clock*1[cid:9929764f-d12e-485d-9deb-52ef91d03c6d]
> […](#)

2.2.7不支持1.19
