### ISSUE TITLE
LLSE实体事件"onMobHurt"失效

### ISSUE THREAD

**Issue by hhaipaap** [LiteLDev/LiteLoader#447]
### 异常模块

ScriptEngine(脚本引擎)

### 操作系统

Windows Server 2019

### LiteLoader版本

2.2.7

### BDS版本

1.18.33

### 发生了什么?

在模拟玩家被攻击时实体事件"onMobHurt"并未生效
但愿不是故意设计的

### 复现此问题的步骤

使用实体事件"onMobHurt"

### 有关的日志/输出

```shell
无
```

### 插件列表

```shell
在测试环境运行
```

**Comment by ShrBox** [comment]
9d43cc427c00a97dd9766dda91668895d4ee1a2c
