### ISSUE TITLE
分离控制台输入输出

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#448]
### 您的建议是否与现存的某个问题相关?请描述问题?

现在的控制台会把输入和输出混在一起，不方便编辑

### 您认为还缺少什么?如何解决您的问题?

类似于Java版的控制台输入输出分离

**Comment by KawaiiNahida** [comment]
1 conhost对此类动作的兼容性不佳
2 在Windows10以前的系统上原生实现相关功能较为繁复
3 实际需求量不大

**Comment by StarsDream00** [comment]
未计划
