### ISSUE TITLE
[BUG]伺服器後臺輸入指令不會回應

### ISSUE THREAD

**Issue by VincentX0905** [LiteLDev/LiteLoader#450]
### 异常模块

Core(核心)

### 操作系统

Linux(Ubuntu/CentOS/...) with wine

### LiteLoader版本

2.3.0

### BDS版本

1.19.1.01

### 发生了什么?

![image](https://user-images.githubusercontent.com/76867533/173011300-c7389930-3546-4dfb-988f-4a0640eeb3a0.png)
![image](https://user-images.githubusercontent.com/76867533/173011485-fefb13b2-b43e-4f66-b201-75bc75da5a9d.png)

### 复现此问题的步骤

開啟伺服器
輸入指令

**Comment by ShrBox** [comment]
已确认为BDS的问题
