### ISSUE TITLE
希望可以让llse插件输出WARN、ERROR等类型的log

### ISSUE THREAD

**Issue by lgc2333** [LiteLDev/LiteLoader#457]
### 您认为还缺少什么?如何解决您的问题?

见标题

**Comment by Yushu2606** [comment]
> ### 您的建议是否与现存的某个问题相关?请描述问题?
> 
> _No response_
> 
> ### 您认为还缺少什么?如何解决您的问题?
> 
> 见标题

https://docs.litebds.com/#/zh_CN/Development/ScriptAPI/Logger

**Comment by Jaciezyt** [comment]
> > ### 您的建议是否与现存的某个问题相关?请描述问题?
> > _No response_
> > ### 您认为还缺少什么?如何解决您的问题?
> > 见标题
> 
> https://docs.litebds.com/#/zh_CN/Development/ScriptAPI/Logger

感谢回复

**Comment by lgc2333** [comment]
不好意思 没仔细看文档……打扰你们了
