### ISSUE TITLE
LLSE 玩家移动事件不灵敏

### ISSUE THREAD

**Issue by PosiedChoss** [LiteLDev/LiteLoader#464]
### 异常模块

ScriptEngine(脚本引擎)

### 操作系统

Windows 11

### LiteLoader版本

2.3.0

### BDS版本

1.19

### 发生了什么?

玩家在走路时很难触发移动事件,跑跳能够触发/走了一段路断断续续触发

### 复现此问题的步骤

`mc.listen("onMove",(pl,pos)=>{
    log(`${pl.realName} 在走路`)
})
`
玩家在游戏内只有部分动作会触发事件(跑跳,断断续续触发)

**Comment by KawaiiNahida** [comment]
MC自身限制，此类事件无法持续触发，如果需要精确监测玩家移动请使用CPP来实现逻辑
