### ISSUE TITLE
Player skin API

### ISSUE THREAD

**Issue by shizotoaster** [LiteLDev/LiteLoader#466]
### Is your feature request related to a problem? Please describe.

LL is developed really fast and SimulatedPlayer API that was added lately brought server bots/NPCs to an absolutely new level. Sadly, all the simulated players just look like Steve and there's nothing to do with that. There're also plenty of players who might use 4D skins to crash the server. I think we need something to work with player skins

### Describe the solution you'd like

We need an API to edit, remove or copy player's skins. I suggest adding:
`onSkinChanged` cancelable event with callback `function(player, oldSkin, newSkin)` where oldSkin and newSkin are objects of Skin or PersonaSkin class

I also would like to see `player.setSkin(Skin or PersonaSkin)` that returns boolean, `player.getSkin()` that returns Skin or PersonaSkin methods

**Comment by dreamguxiang** [comment]
Related functions have been implemented and are waiting to be added
