### ISSUE TITLE
Support Linux bash runner pls

### ISSUE THREAD

**Issue by crischutu07** [LiteLDev/LiteLoader#467]
### Is your feature request related to a problem? Please describe.

No, this feature is not request a problem, but run executable file in Linux is won't work (if you use wine package, is still work, but some error when running Linux BDS)

### Describe the solution you'd like

I want LiteLoaderBDS can support Linux runner to make the server easier to run.

**Comment by crischutu07** [comment]
You can install Ubuntu to run but I did request a feature that can run all Linux bash contain popular Linux terminal like CentOS or Debian

**Comment by KawaiiNahida** [comment]
maybe Docker is a better choice to redistribute project like this
please check our Docker image to see if it match your need

**Comment by crischutu07** [comment]
It matches
