### ISSUE TITLE
FULL CodeReview

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#469]
### 您的建议是否与现存的某个问题相关?请描述问题?

类似 LiteLDev/LeviLamina#468 、 LiteLDev/LeviLamina#430 和 LiteLDev/LeviLamina#391 这样的小漏洞实在太多了，，

### 您认为还缺少什么?如何解决您的问题?

建议进行一次代码审查

**Comment by KawaiiNahida** [comment]
没人有空www，现在LL这边干活的开发者只有俩三个了，剩下的不是高三就是大三/大四，要CodeReview我们也计划过几次了，最后都因时间和人手不够没有进行

**Comment by KawaiiNahida** [comment]
包括部分ModernCpp设计的改进，以及ABI稳定的一些设计都因为各种原因没有时间没有人处理

**Comment by yqs112358** [comment]
LiteLDev/ScriptEngine#26
