### ISSUE TITLE
无法加载liteloader.dll

### ISSUE THREAD

**Issue by xq20190308** [LiteLDev/LiteLoader#471]
### 异常模块

Core(核心)

### 操作系统

Windows 10

### LiteLoader版本

2.3.0

### BDS版本

1.18.12.01

### 发生了什么?

启动bedrock_server_mod，提示无法找到入口。

### 复现此问题的步骤

![0](https://user-images.githubusercontent.com/48353202/173333664-9752eb61-118c-47af-9775-38bdb1157433.png)
自从liteloader在2.20之后都有该提示，之前正常运行。

**Comment by xiaoqch** [comment]
新版LiteLoader加载器不兼容旧版BDS，请更新你的bds版本或回退你的LiteLoader版本
