### ISSUE TITLE
完善LLSE异常处理

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#473]
例：LLSE 参数类型不正确无法获取有关信息

__最初由 @StarsDream00 在 https://github.com/LiteLDev/LiteLoaderBDS/issues/430#issuecomment-1153593942 发布__

**Comment by Jaciezyt** [comment]
未来的新API会加上这个，并且回抛到脚本中进行处理，include APIHelp之前加上#define NEW_DEFINES即可
鉴于回抛可能会导致脚本报废，而CHECK_ARG_TYPE传index需要改的地方太多，对旧API暂时不改动

**Comment by Yushu2606** [comment]
> 未来的新API会加上这个，并且回抛到脚本中进行处理，include APIHelp之前加上#define NEW_DEFINES即可
> 
> 鉴于回抛可能会导致脚本报废，而CHECK_ARG_TYPE传index需要改的地方太多，对旧API暂时不改动

但其实现在的解决方案容易导致行为不可预测，希望还是尽快完善异常处理吧

**Comment by Yushu2606** [comment]
LiteLDev/ScriptEngine#26
