### ISSUE TITLE
Unable to use volume mounts in Docker container to save data

### ISSUE THREAD

**Issue by hwittenborn** [LiteLDev/LiteLoader#475]
### Exceptions module

Core

### Operating System

Linux(Ubuntu/CentOS/...) with docker

### LiteLoader version

N/A

### BDS version

N/A

### What happened?

Whenever I try to run the Docker image with a volume mount for `/home/bds/bds` so I can save my server's runtime data, I get the following error:

![image](https://user-images.githubusercontent.com/74838472/174155249-13c274d3-5fe9-4de8-bb0c-b9c344097892.png)

Anythin I might be able to do to fix it?

### Steps to reproduce?

Run the following:

```sh
docker run -it -v "${PWD}:/home/bds/bds" shrbox/liteloaderbds
```

### Relevant log output

```shell
See above.
```

### Plugin list

```shell
N/A
```

**Comment by StarsDream00** [comment]
can't reproduce

**Comment by RimuruChan** [comment]
Close due to inactivity
