### ISSUE TITLE
真命令中output:success()等操作崩服

### ISSUE THREAD

**Issue by Redbeanw44602** [LiteLDev/LiteLoader#480]
### 异常模块

ScriptEngine

### 操作系统

Windows 10

### LiteLoader版本

2.3.0

### BDS版本

1.19.1.01

### 发生了什么?

当使用 output:success("...") 时，发生了崩溃

### 复现此问题的步骤

```
mc.listen('onServerStarted',function ()
    local cmd = mc.newCommand('test','hello crash server.',PermType.GameMasters)
    cmd:overload({})
    cmd:setCallback(function (_cmd,origin,output,results)
        output:success("take crash!")
    end)
    cmd:setup()
end)
```
然后，在游戏里执行 /test
![1](https://user-images.githubusercontent.com/29711228/174794886-18b58d2e-b25f-4274-9e76-b5ae3afa12ad.png)

[dmp.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/8954190/Crash.zip)

### 有关的日志/输出

```shell
见上（图片）
```

### 插件列表

```shell
无
```

**Comment by dreamguxiang** [comment]
未能复现
