### ISSUE TITLE
希望可以兼容更多Linux发行版(我可以提供帮助)

### ISSUE THREAD

**Issue by Onlyacat233** [LiteLDev/LiteLoader#485]
### 您的建议是否与现存的某个问题相关?请描述问题?

最近我把我的主力系统替换成了Archlinux,在开liteloader服务端时遇到了很多阻碍,所以我希望可以多兼容一些linux发行版

### 您认为还缺少什么?如何解决您的问题?

我希望可以多兼容一些linux发行版,并且我可以制作安装脚本awa

**Comment by Yushu2606** [comment]
理应兼容wine就兼容llbds

**Comment by ShrBox** [comment]
只熟悉debian系所以就只写了Ubuntu的安装脚本，你可以fork本项目并通过pull request来提交您的安装脚本
