### ISSUE TITLE
LLse增加修改玩家的 Attributes 属性功能

### ISSUE THREAD

**Issue by hhaipaap** [LiteLDev/LiteLoader#486]
### 您的建议是否与现存的某个问题相关?请描述问题?

想要编写飞行插件但没有相关api

### 您认为还缺少什么?如何解决您的问题?

增加修改玩家的 Attributes 属性功能

**Comment by xiaoqch** [comment]
新版飞行插件需要hook，而且 BETweaker 已有此功能，另外部分attribute的修改仍有bug，暂不考虑提供额外支持

**Comment by RimuruChan** [comment]
LiteLDev/ScriptEngine#16
