### ISSUE TITLE
给log添加带控制台高亮的INFO输出的功能

### ISSUE THREAD

**Issue by hhhxiao** [LiteLDev/LiteLoader#491]
### 您的建议是否与现存的某个问题相关?请描述问题?

我想要用户看到一条带控制台高亮的重要信息，但不是警告或者错误，INFO是白色的不够显眼

### 您认为还缺少什么?如何解决您的问题?

添加一个类似`logger.highlight()`或者`logger.important()`的API，功能和`logger.info()`类似但是自带控制台高亮

**Comment by StarsDream00** [comment]
不能colorlog吗

**Comment by Jaciezyt** [comment]
> 不能colorlog吗

可以
```cpp
logger.info << fmt::format(color, format, args...);
```
但这样确实有点麻烦，可以开新api自定义color输出

**Comment by StarsDream00** [comment]
> > 不能colorlog吗
> 
> 
> 
> 可以
> 
> ```cpp
> 
> logger.info << fmt::format(color, format, args...);
> 
> ```
> 
> 但这样确实有点麻烦，可以开新api自定义color输出

所以为啥不自己打包一个函数（

**Comment by dreamguxiang** [comment]
你们想到的，在提交这个issue前几个人都讨论过了，这里只是为了记录一下todo
