### ISSUE TITLE
Node.js Support

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#492]
https://github.com/LiteLDev/LiteLoaderBDS/tree/feature/nodejs

**Comment by Jaciezyt** [comment]
等后续看看能不能上nodejs吧

**Comment by dreamguxiang** [comment]
暑假

**Comment by yqs112358** [comment]
之前已经做完了nodejs backend相关的编译操作，证实相关技术的可行性，在 https://github.com/LiteLDev/LiteLoaderBDS/tree/main/Tools/ScriptX 可以看到编译好的nodejs backend支持。之前测试已经成功跑起来了基于nodejs编写的插件demo，只待后续零碎的适配工作即可完成
说明一下整体设计思路：

#### 首先，是引擎对接部分
设计思路如下：由于 nodejs = v8引擎 + libuv事件循环
因此，把两部分分开处理，v8引擎部分直接对接ScriptX的v8接口，就跟LLSE Js后端那边一模一样处理就行
libuv是一个单独的事件循环，因此直接将他放到tick中执行即可（或者其他的d比如单独开线程等等，具体设计看情况）
这样就完成了ScriptX和Nodejs的对接

#### 第二是npm
我在npm上发布了一个包 npm-js-interface 通过这个包可以在js代码中直接执行npm命令，因此npm就不再需要单独作为exe调用执行
同时，需要设计一个内置插件在bds控制台中添加npm命令，以方便用户和开发者进行npm命令的执行

#### 第三个是插件分发和部署
这边的相关工作可能稍微复杂一些，设计思路如下：
每一个Nodejs插件发布时，都将所有代码以及package.json等打包为一个zip
在加载插件时加载器负责解压zip，插件解压目录为plugins/nodejs下以压缩包名命名的子目录，同时在自动解压后npm install，完成依赖包的自动安装

#### 第四个是node_modules目录的安排
node_modules的全局目录为plugins/nodejs/node_modules
每个插件自己的node_modules的局部目录为plugins/nodejs/各自子目录中的node_modules
插件的工作目录仍然为根目录（跟C++、Js插件等保持一致）


> 补：ScriptX文档中提到的nodejs backend是将C++ dll作为nodejs的插件来实现的，跟这里需要的场景完全不同，因此不需要关注，按照上面所说的方案施工即可（

**Comment by yqs112358** [comment]
可能需要的修复（记在待办里的忘了是啥意思了，到这里记一笔，以防有用）
node编译时，预定义宏 加 using v8 shared

**Comment by yqs112358** [comment]
备忘
- [x] npm适配
- [x] 自动执行npm install
- [x] libuv植入tick
- [x] 自动创建nodejs目录
- [x] node引擎销毁处理

**Comment by RimuruChan** [comment]
#613
