### ISSUE TITLE
LLse pl.setNbt(nbt) 失效

### ISSUE THREAD

**Issue by hhaipaap** [LiteLDev/LiteLoader#493]
### 异常模块

ScriptEngine(脚本引擎)

### 操作系统

Windows 10

### LiteLoader版本

2.3.1

### BDS版本

1.19.1

### 发生了什么?

使用pl.setNbt(nbt)写入nbt后和写入前的一样

### 有关的日志/输出

```shell
无
```

### 插件列表

```shell
没有其他插件
```

**Comment by yqs112358** [comment]
请给出复现方法，谢谢
这里无法复现，其他插件开发者也未大量反馈此问题
