### ISSUE TITLE
LLSE pl.removeBossBar(uid)

### ISSUE THREAD

**Issue by mikhaillav** [LiteLDev/LiteLoader#494]
### Exceptions module

ScriptEngine

### Operating System

Windows 10

### LiteLoader version

2.3.1

### BDS version

1.19.2.02

### What happened?

So, pl.removeBossBar(uid) just doesn't work

### Steps to reproduce?

1. Created bossbar ( pl.setBossBar(228, "test",100,2) )
2. Try to remove bossbar ( pl.removeBossBar(228) )

### Relevant log output

```shell
No logs/errors but boss bar doesn't remove
```

### Plugin list

```shell
just my plugin
```

**Comment by dreamguxiang** [comment]
Failure to reproduce
