### ISSUE TITLE
PlayerMoveEvent isnt called

### ISSUE THREAD

**Issue by ghost** [LiteLDev/LiteLoader#505]
### Exceptions module

Core

### Operating System

Windows 11

### LiteLoader version

LiteLoaderBDS 2.3.1

### BDS version

1.19.2

### What happened?

Player move event isnt calling.

### Steps to reproduce?

1. Write simple plugin, that logs if Event::PlayerMoveEvent is called.
```
Event::PlayerMoveEvent::subscribe([](Event::PlayerMoveEvent& event) {
   cout << "called." << endl;
});
```
2. You will see that when the player moves, no text is written to the console.

### Relevant log output

```shell
None
```

### Plugin list

```shell
None
```

**Comment by dreamguxiang** [comment]
2.3.2 fixed
