### ISSUE TITLE
Docker container frozen on start

### ISSUE THREAD

**Issue by username100099** [LiteLDev/LiteLoader#507]
### Exceptions module

Core

### Operating System

Linux(Ubuntu/CentOS/...) with docker

### LiteLoader version

2.3.1 

### BDS version

1.19.1

### What happened?

When i start the docker container (docker container start liteloader) it crashes and when you press enter it just has a blank screen and you can't type commands. On rare occasions it comes on then shuts off due to "World corruption". The os is Ubuntu server 20.04 and there were no errors when installing docker or creating a liteloader container. I tested the exact same world on a windows pc and it worked fine.

### Plugin list

```shell
Llcheckbag
Discord.js
Antitoolbox
```

**Comment by StarsDream00** [comment]
i can't reproduce
