### ISSUE TITLE
不会加载文件名与已注册插件名称相同的插件

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#510]
### 异常模块

ScriptEngine(脚本引擎)

### 操作系统

Windows Server 2022

### LiteLoader版本

2.3.2

### BDS版本

1.19.2.02

### 发生了什么?

不会加载文件名与已注册插件名称相同的插件

### 复现此问题的步骤

1. 添加注册为test的插件
2. 添加插件test.js
3. test.js被跳过

**Comment by Jaciezyt** [comment]
原因应该是这
https://github.com/LiteLDev/LiteLoaderBDS/blob/929b78d3ea7222fb8878a0cb6229f3df817ba174/ScriptEngine/PluginManager.cpp#L87
不清楚是不是特别设计的 先放一放吧 感觉不会有特别大影响

**Comment by Yushu2606** [comment]
> 原因应该是这
> 
> https://github.com/LiteLDev/LiteLoaderBDS/blob/929b78d3ea7222fb8878a0cb6229f3df817ba174/ScriptEngine/PluginManager.cpp#L87
> 
> 
> 不清楚是不是特别设计的 先放一放吧 感觉不会有特别大影响

这里的`pluginFileName`只有文件名，但注册时会带有后缀

**Comment by Jaciezyt** [comment]
https://github.com/LiteLDev/LiteLoaderBDS/blob/df836910c6c9b4728ecae727c89dc27b7e113a50/LiteLoader/Main/PluginManager.cpp#L97
在这里

**Comment by Jasonzyt** [comment]
fixed
