### ISSUE TITLE
LLse增加“玩家能力变更”监听项

### ISSUE THREAD

**Issue by hhaipaap** [LiteLDev/LiteLoader#514]
### 您的建议是否与现存的某个问题相关?请描述问题?

想基于其他飞行插件开发插件
在玩家飞行时间结束时插件会撤销玩家的飞行能力
想监听这个行为

### 您认为还缺少什么?如何解决您的问题?

增加“玩家能力变更”监听项
做不到的话当我没说 awa

**Comment by dreamguxiang** [comment]
下版本再考虑，最近能力改动特别大，不好做事件

**Comment by hhaipaap** [comment]
> 下版本再考虑，最近能力改动特别大，不好做事件

好耶
