### ISSUE TITLE
Please Fix Server Error Automatically Stopping For No Reason 

### ISSUE THREAD

**Issue by BeeAZ-pm-pl** [LiteLDev/LiteLoader#515]
### Exceptions module

Core

### Operating System

Windows Server 2016

### LiteLoader version

Latest Version

### BDS version

1.19.2

### What happened?

The Server Is Running Normal But Stops For No Reason . I got hit five to seven times in one day

### Steps to reproduce?

No

### Relevant log output

```shell
No
```

### Plugin list

```shell
JoinUI.js 
AntiToolBox
LLHelper
LLAntiCheat
AutoClearLag.js ( Simply Run mc.runcmd("kill @e [type=item]") 
Scoreboard.js
RespawnItem.js ( When respawn there will be items )
AntiWindow.js ( I kick players who use windows 10 operating system)
AntiRedStone.js ( I block RedStoneUpdateEvent)
```

**Comment by Redbeanw44602** [comment]
Please provide crash log.

**Comment by PA733** [comment]
I can't understand what you mean, did the server crash or was it stoppedI can't understand what you mean, did the server crash or was it stopped.

**Comment by PA733** [comment]
If the server was stopped, you can see that the console will output "Quit correctly".
If the server crashed, please ti'gon the trackback file in the logs/Crash directory.
