### ISSUE TITLE
希望可以添加禁用/tpdim指令的选项，或者使其在作弊关闭时无法使用

### ISSUE THREAD

**Issue by a86296007** [LiteLDev/LiteLoader#518]
### 您的建议是否与现存的某个问题相关?请描述问题?

通常来说，关闭作弊并将LL配置文件中的UnlockCmd设为false可以阻止拥有OP权限的玩家使用绝大部分作弊指令，但/tpdim并不受此限制，这会对某些有类似特殊配置需求的服务器造成不便
![image](https://user-images.githubusercontent.com/91132489/178253239-1761123a-27f3-4308-bb2a-f8296bacaa70.png)

### 您认为还缺少什么?如何解决您的问题?

如果可以让使用者自己决定是否启用/tpdim指令的功能，或者将其划归到作弊开启才可使用的范围也许可以解决这一问题

**Comment by dreamguxiang** [comment]
已添加
