### ISSUE TITLE
schedule循环任务可能导致BDS无法正常退出

### ISSUE THREAD

**Issue by PA733** [LiteLDev/LiteLoader#521]
### 异常模块

Core(核心)

### 操作系统

Windows 10

### LiteLoader版本

2.3.2

### BDS版本

1.19.2.02(ProtocolVersion 527)

### 发生了什么?

在一个循环任务执行中退出bds，bds会卡在“Stopping server...”

### 复现此问题的步骤

启动一个循环任务，如：

```cpp
auto ptr = Schedule::repeat([]() {
    std::cout << "1" << std::endl;
    }, 20);
```

### 有关的日志/输出

```shell
1
1
1
stop
16:36:45 INFO [Server] Server stop requested.
16:36:45 INFO [Server] Stopping server...
1
# 然后就在这卡住了
```

**Comment by Jaciezyt** [comment]
没能复现
![image](https://user-images.githubusercontent.com/66063199/178474576-f3d5ce59-1c36-4296-83f7-4fae6d0aeffd.png)

**Comment by PA733** [comment]
已确认无法复现，可能是我的问题
感谢回复，打扰了
