### ISSUE TITLE
File.getFilesList(dir)函数在Wine环境下获取的文件列表为空。

### ISSUE THREAD

**Issue by Hurry1027** [LiteLDev/LiteLoader#522]
### 异常模块

ScriptEngine(脚本引擎)

### 操作系统

Linux(Ubuntu/CentOS/...) with wine

### LiteLoader版本

2.3.1

### BDS版本

最新版本

### 发生了什么?

关于我的LF_Music插件，使用Wine环境开服的服主反馈插件BUG。
**File.getFilesList(dir)函数在Wine环境下获取的文件列表为空。**

插件 LF_Music.js 在WinServer环境下一切正常，但在Wine环境下报错，获取到的文件列表为空数组。
我没有搭建Wine环境的条件，请帮忙检查下是否为api函数bug还是Wine环境下文件权限的问题。

代码样例：
    // 检查资源包是否存在
    if (File.exists(config.get("serverRES")) == false) {
        //无资源包不执行动作
	log(File.getFilesList(config.get("serverRES"))) // 获取到的列表为空
        setTimeout('logger.error(`请现在将资源包serverMusicRE文件夹放到 ./development_resource_packs/下`)', 2000)
        enable = false

    } else if (File.getFilesList(config.get("serverRES")).length < 4) {
        setTimeout('logger.error(`请检查资源包完整性`)', 2000)
        enable = false
    }
检查log输出为空数组，导致wine环境下报错。

### 复现此问题的步骤

 LF_Music.js 插件在wine环境启动会报错，在Windows环境下则正常。

### 有关的日志/输出

```shell
无
```

### 插件列表

```shell
LF_Music.js
```

**Comment by Jaciezyt** [comment]
不应该是`file.${method}()`吗

**Comment by Hurry1027** [comment]
File.getFilesList(dir)
我是按照llse文档里写的呀，这....没问题吧？

**Comment by Jaciezyt** [comment]
看你描述应该没问题 当我没说罢

**Comment by Hurry1027** [comment]
文件夹路径
"serverRES": "./development_resource_packs/serverMusicRE/",

插件MineBBS地址：[LF_Music](https://www.minebbs.com/resources/lf_music-3d.4311/)

[Uploading LF_Music.zip…]()

**Comment by PA733** [comment]
无法复现
![image](https://user-images.githubusercontent.com/67588574/178683192-a3cf43db-a9c4-4fbf-b466-37e2a8c6aef7.png)
![image](https://user-images.githubusercontent.com/67588574/178683273-63e79f7d-9e20-478a-a846-46199074d2bb.png)
arch with wine 7.12
请尝试更新您的wine版本并重试
另外，经过测试，getFilesList函数对应的cpp代码段也可以正常运作。

**Comment by Hurry1027** [comment]
@pa733 
好的，十分感谢帮助。
因为有两个人反馈wine环境插件报错我才重视一下，
据说他的wine还套了层docker，有点离谱，我再继续排查其他问题以及收集更多反馈。
