### ISSUE TITLE
wsc.connect() 无法连接至加密的wss

### ISSUE THREAD

**Issue by yanhy2000** [LiteLDev/LiteLoader#526]
### 异常模块

ScriptEngine(脚本引擎)

### 操作系统

Windows 10

### LiteLoader版本

2.3.2

### BDS版本

1.19.2

### 发生了什么?

使用wsc.connect()函数时，目标地址仅支持如"ws://127.0.0.1:2333"，如果服务端使用加密的wss，地址如"wss://127.0.0.1:2334"，将无法连接，返回false；
验证：使用WS工具`http://wstool.jackxiang.com/`时，连接本地"wss://127.0.0.1:2334"，连接正常，通讯正常

### 复现此问题的步骤

function ws_con() {
  if (wsc.connect("wss://127.0.0.1:2334") == true) {
    log("WSC连接至服务端成功！");
    wsc.send("BDS连接成功！");
  } else {
    log("WSC连接失败！");
    ws_con();
  }
}
ws_con() ;
实际输出：WSC连接失败！

### 有关的日志/输出

```shell
输出同上述
```

### 插件列表

```shell
ws_bot.js
（仅装载目标插件）
```

**Comment by Yushu2606** [comment]
应该是没证书API

**Comment by Jaciezyt** [comment]
你可以等等nodejs

**Comment by yanhy2000** [comment]
nodejs？后面直接用nodejs来替代脚本引擎的js插件吗

**Comment by Yushu2606** [comment]
> nodejs？后面直接用nodejs来替代脚本引擎的js插件吗

建议先去了解一下

**Comment by yanhy2000** [comment]
好的，那目前问题解决了，我暂时使用ws带路径的方式解决了目前的需求，谢谢各位
