### ISSUE TITLE
1.2.0无法正常启动

### ISSUE THREAD

**Issue by CJYKK** [LiteLDev/LiteLoader#53]
依次打开SymDB2.bat和SymDB2.exe后，报错

SymDB format error detected!!
[Info] Loading Symbols
[Chakra Error] Can't load LiteLoader.dll!
[Chakra Error] Error Code:1114
[Chakra Error] A dynamic link library (DLL) initialization routine failed.

**Comment by dreamguxiang** [comment]
只需要打开SymDB2.bat

**Comment by yqs112358** [comment]
等待@WangYneos 修复
