### ISSUE TITLE
onMove事件不管玩家是否移动每个游戏刻都触发

### ISSUE THREAD

**Issue by XY0797** [LiteLDev/LiteLoader#530]
### 异常模块

ScriptEngine(脚本引擎)

### 操作系统

Windows 10

### LiteLoader版本

2.3.2

### BDS版本

1.19.2.02

### 发生了什么?

onMove事件不管玩家是否移动每个游戏刻都触发
我写了一个简单的脚本，监听onMove事件并且在回调事件里log()
mc.listen("onMove", onMove);
function onMove(pl, pos) {log(111);}
![QQ截图20220714105436](https://user-images.githubusercontent.com/98995022/178889086-8d20c3e9-086d-4875-b3d4-3e3f39323cc9.png)
按照文档的描述，该回调函数是在玩家移动时才触发
但是我进入游戏，手离开鼠标键盘，完全不动，控制台依然每个游戏刻显示一次
![QQ截图20220714105423](https://user-images.githubusercontent.com/98995022/178889159-61db30b4-d278-4b3f-9c44-8414522033bd.png)
这导致了很多问题，性能上的损失先不说，玩家进入服务器未完全进入时也会触发改事件，而且pl.xuid为null，这就导致了旧插件必须额外加上xuid==null的判断才能使用，而且某些混淆后的插件改都改不了.........
希望能尽快适配1.19.10并且修复该问题

### 复现此问题的步骤

1.在1.19.2.02的BDS中安装LL
2.创建一个"1.js"，UTF-8编码，两行代码：
mc.listen("onMove", onMove);
function onMove(pl, pos) {log(111);}
3.进入游戏，不移动，可以看到控制台仍在输出
4.关闭BDS，修改"1.js"的代码：
mc.listen("onMove", onMove);
function onMove(pl, pos) {
if(pl.xuid==null){log(111);}
}
5.再启动BDS，进入游戏，可以看到控制台输出了111，说明在玩家进入游戏的阶段改事件提供的pl对象的xuid成员出现了值为null的情况

### 有关的日志/输出

```shell
请看  发生了什么?  中的图文介绍
```

### 插件列表

```shell
请看  发生了什么?  中的图文介绍，仅加载一个插件
```

**Comment by Redbeanw44602** [comment]
此事件已弃用，请用 `setInterval` + `player.pos` 代替、
