### ISSUE TITLE
LLSE增加玩家经验监听项 

### ISSUE THREAD

**Issue by Chlna6666** [LiteLDev/LiteLoader#533]
### 您的建议是否与现存的某个问题相关?请描述问题?

在文档中似乎没有办法可以阻止玩家吸收经验

### 您认为还缺少什么?如何解决您的问题?

LLSE增加玩家经验监听

**Comment by Jaciezyt** [comment]
这个LL有，一会给LLSE加上

**Comment by Chlna6666** [comment]
谢谢

**Comment by StarsDream00** [comment]
need to close
