### ISSUE TITLE
LLSE希望添加冰霜行者监听项

### ISSUE THREAD

**Issue by Chlna6666** [LiteLDev/LiteLoader#547]
### 您的建议是否与现存的某个问题相关?请描述问题?

希望能有这个功能吧
谢谢

### 您认为还缺少什么?如何解决您的问题?

LLSE希望添加冰霜行者监听
以前onPlaceBlock似乎可以拦截

**Comment by Redbeanw44602** [comment]
可能暂时办不到，原因如下：
`Mob::frostWalk` 中使用了 `BlockSource::mayPlace` ，故原先可以用Place事件拦截，但是 mayPlace 并非所有方块放置都调用，所以新版本LL中换用了其他函数，这个冰霜行者的拦截也就失效了。
考虑到 Place 事件不能完美拦截的危害性，且找不到完美的点位，暂时只能作出妥协。

不过，如果你使用C++开发插件的话可以用 hook: `Mob::frostWalk` 来监控实体使用冰霜行者，或者 hook: `BlockSource::mayPlace` 来监控冰霜行者的方块设置。

**Comment by Chlna6666** [comment]
C++....没电脑
不过也没啥事（影响不大）
谢谢

**Comment by dreamguxiang** [comment]
可以手动hook（文档有API介绍），这类事件会无限触发，不考虑做进LL本体
