### ISSUE TITLE
onPlaceBlock事件部分新增问题

### ISSUE THREAD

**Issue by jiangyan03** [LiteLDev/LiteLoader#548]
### 异常模块

ScriptEngine（脚本引擎）

### 操作系统

Windows 10

### LiteLoader版本

2.4.0

### BDS版本

1.19.10.03

### 发生了什么?

使用yq的日志和放置板的时候，都调用了onPlaceBlock这个事件
但是新增了一个问题，就是当一个pc玩家拿着某个方块一直按着右键时候，玩家没有成功放置方块，但是日志和放置版都监听到了这个事件，日志在服务器端迅速刷屏，放置板增加数字一直增加。
属于是，玩家尝试放置但放置失败，但是依旧输出了。

### 复现此问题的步骤

生存或者创造模式，使用调用了onPlaceBlock事件的插件，如yq的行为日志。
然后拿着红石火把（其他方块都行），先放置一个方块面上，然后拿着红石火把，长按右键对着已经放置红石火把方块面上
就是对着这个方块尝试放置但是失败
观察yq行为日志输出

### 有关的日志/输出

```shell
下面是例子
20:52:45 INFO [BehaviorLog.lxl.js] [2022-07-15 20:52:45][破坏方块] 在Overworld  jiangyan03 (-108,71,-117)  破坏方块  minecraft:grass (-109,68,-117)

20:52:46 INFO [BehaviorLog.lxl.js] [2022-07-15 20:52:46][捡起物品] 在Overworld  jiangyan03 (-108,70,-116)  捡起物品  Dirt (-109,69,-116)  1个

20:52:46 INFO [BehaviorLog.lxl.js] [2022-07-15 20:52:46][放置方块] 在Overworld  jiangyan03 (-108,70,-117)  放置方块  minecraft:dirt (-109,67,-117)
[2022-07-15 20:52:46][使用物品] 在Overworld  jiangyan03 (-108,70,-117)  使用物品  Dirt  类型：minecraft:dirt

20:52:46 INFO [BehaviorLog.lxl.js] [2022-07-15 20:52:46][放置方块] 在Overworld  jiangyan03 (-108,70,-117)  放置方块  minecraft:dirt (-109,67,-117)

20:52:46 INFO [BehaviorLog.lxl.js] [2022-07-15 20:52:46][放置方块] 在Overworld  jiangyan03 (-108,70,-117)  放置方块  minecraft:dirt (-109,67,-117)

20:52:46 INFO [BehaviorLog.lxl.js] [2022-07-15 20:52:46][放置方块] 在Overworld  jiangyan03 (-108,70,-117)  放置方块  minecraft:dirt (-109,67,-117)

20:52:46 INFO [BehaviorLog.lxl.js] [2022-07-15 20:52:46][放置方块] 在Overworld  jiangyan03 (-108,70,-117)  放置方块  minecraft:dirt (-109,67,-117)

20:52:46 INFO [BehaviorLog.lxl.js] [2022-07-15 20:52:46][放置方块] 在Overworld  jiangyan03 (-108,70,-117)  放置方块  minecraft:dirt (-109,67,-117)

20:52:47 INFO [BehaviorLog.lxl.js] [2022-07-15 20:52:47][放置方块] 在Overworld  jiangyan03 (-108,70,-117)  放置方块  minecraft:dirt (-109,67,-117)

20:52:47 INFO [BehaviorLog.lxl.js] [2022-07-15 20:52:47][放置方块] 在Overworld  jiangyan03 (-108,70,-117)  放置方块  minecraft:dirt (-109,67,-117)

20:52:47 INFO [BehaviorLog.lxl.js] [2022-07-15 20:52:47][放置方块] 在Overworld  jiangyan03 (-108,70,-117)  放置方块  minecraft:dirt (-109,67,-117)

20:52:47 INFO [BehaviorLog.lxl.js] [2022-07-15 20:52:47][放置方块] 在Overworld  jiangyan03 (-108,70,-117)  放置方块  minecraft:dirt (-109,67,-117)

20:52:47 INFO [BehaviorLog.lxl.js] [2022-07-15 20:52:47][放置方块] 在Overworld  jiangyan03 (-108,70,-117)  放置方块  minecraft:dirt (-109,67,-117)

20:52:47 INFO [BehaviorLog.lxl.js] [2022-07-15 20:52:47][放置方块] 在Overworld  jiangyan03 (-108,70,-117)  放置方块  minecraft:dirt (-109,67,-117)

20:52:47 INFO [BehaviorLog.lxl.js] [2022-07-15 20:52:47][放置方块] 在Overworld  jiangyan03 (-108,70,-117)  放置方块  minecraft:dirt (-109,67,-117)
```

### 插件列表

```shell
ll list
20:52:54 INFO [Server] Plugin Lists [4]
20:52:54 INFO [Server] - LLMoney [v2.4.0] (LLMoney.dll)
20:52:54 INFO [Server]   EconomyCore for LiteLoaderBDS
20:52:54 INFO [Server] - ScriptEngine-Lua [v2.4.0] (LiteLoader.Lua.dll)
20:52:54 INFO [Server]   Lua ScriptEngine for LiteLoaderBDS
20:52:54 INFO [Server] - ScriptEngine-Js [v2.4.0] (LiteLoader.Js.dll)
20:52:54 INFO [Server]   Javascript ScriptEngine for LiteLoaderBDS
20:52:54 INFO [Server] - BehaviorLog.lxl.js [v1.0.0] (BehaviorLog.lxl.js)
20:52:54 INFO [Server]   BehaviorLog.lxl.js
20:52:54 INFO [Server]
20:52:54 INFO [Server] * Send command "ll list <Plugin Name>" for more information
20:52:54 INFO [BehaviorLog.lxl.js] [2022-07-15 20:52:54][执行后台命令]   执行后台命令  ll list
```

**Comment by Jaciezyt** [comment]
这个和#547 可能有一定关联

**Comment by Yushu2606** [comment]
> 这个和#547 可能有一定关联

他好像说的是放置失败时还会触发onPlaceBlock

**Comment by XY0797** [comment]
这个问题我昨天晚上发现了，哪怕拿着个木棍右键点地面也会触发这个事件，不管是否放置成功，都会触发一遍
幸运的是，这个事件可以正常拦截，至少领地插件还能用
我昨天发现问题想的是自己修
在\LiteLoader\Kernel\EventAPI.cpp里面寻找"PlayerPlaceBlockEvent"，找到了hook的函数
我把它改成了这样子
/////////////////// PlayerPlaceBlock ///////////////////
#include <MC/ItemUseInventoryTransaction.hpp>
TInstanceHook(__int64, "?onBlockPlacedByPlayer@VanillaServerGameplayEventListener@@UEAA?AW4EventResult@@AEAVPlayer@@AEBVBlock@@AEBVBlockPos@@_N@Z",Player, Player* pPlayer, Block* pBlk, BlockPos* pBlkpos) {
        IF_LISTENED(PlayerPlaceBlockEvent)
        {
        auto pl = pPlayer;
            PlayerPlaceBlockEvent ev{};
            ev.mPlayer = pl;
            ev.mBlockInstance = Level::getBlockInstance(pBlkpos, Level::getBlockSource(pl));
            if (!ev.call())
            {   // this pointer is not used.
                return 0;
            }
        }
        IF_LISTENED_END(PlayerPlaceBlockEvent)
        return original(this, pPlayer, pBlk, pBlkpos);
}
这个问题就修好了，**但是带来了更严重的问题**，这个函数似乎无法被拦截，所以说我还是没能解决问题
希望你们能找到一个新的且合适的hook函数

**Comment by XY0797** [comment]
有一种暂时的解决方案：改文档
保留之前的onPlaceBlock事件，但是文档增加备注：放置方块失败也会触发本事件
然后新增事件onPlacedBlock，加了个ed，其内容和onPlaceBlock事件一模一样，但是不可拦截
代码就是我上面的代码，事件改下名，删除if (!ev.call())的判断即可

当然，能找到合适的函数入口自然是最好的

**Comment by Yushu2606** [comment]
```c++
/////////////////// PlayerPlaceBlock ///////////////////
#include <MC/ItemUseInventoryTransaction.hpp>
TInstanceHook(__int64, "?onBlockPlacedByPlayer@VanillaServerGameplayEventListener@@UEAA?AW4EventResult@@AEAVPlayer@@AEBVBlock@@AEBVBlockPos@@_N@Z", Player, Player* pPlayer, Block* pBlk, BlockPos* pBlkpos) {
    IF_LISTENED(PlayerPlaceBlockEvent) {
        auto pl = pPlayer;
        PlayerPlaceBlockEvent ev{};
        ev.mPlayer = pl;
        ev.mBlockInstance = Level::getBlockInstance(pBlkpos, Level::getBlockSource(pl));
        if (!ev.call()) {
            // this pointer is not used.
            return 0;
        }
    }
    IF_LISTENED_END(PlayerPlaceBlockEvent)
    return original(this, pPlayer, pBlk, pBlkpos);
}
```
下次发代码记得用markdown

**Comment by Jaciezyt** [comment]
> 有一种暂时的解决方案：改文档 保留之前的onPlaceBlock事件，但是文档增加备注：放置方块失败也会触发本事件 然后新增事件onPlacedBlock，加了个ed，其内容和onPlaceBlock事件一模一样，但是不可拦截 代码就是我上面的代码，事件改下名，删除if (!ev.call())的判断即可
> 
> 当然，能找到合适的函数入口自然是最好的

这问题太离谱了 不是改文档就可以的

**Comment by XY0797** [comment]
![GA SI1YC_VH`7BEW4B5$8ER](https://user-images.githubusercontent.com/98995022/179340280-eeb4e5f3-9e87-42bb-83a5-698dc7486263.jpg)

**Comment by Redbeanw44602** [comment]
感谢各位的研究。

这个 `PlaceEvent` 问题是老大难问题，从远古版本贯穿到现在。

目前的事件即使放置失败也会触发，这个暂时无法解决，目前提到的解决办法是重新实现所有 `xxItem::_useOn()` 函数中的决定是否放置方块的逻辑（大概有30多个，短时间内恐怕没法完成）

不过鉴于各位对于此事件的需求，现在另加入了一个事件 `PlayerPlacedBlockEvent`，此事件不会在不该触发的时候触发，但是不能拦截（对于一般的方块类榜单插件和行为记录足矣），请等待 LL2.4.1更新。

**Comment by jiangyan03** [comment]
谢谢开发者

**Comment by Redbeanw44602** [comment]
![image](https://user-images.githubusercontent.com/29711228/221163772-69c26884-504a-4db6-8bc2-71cf2b476847.png)
