### ISSUE TITLE
runcmd/runcmdEx 部分指令无法执行

### ISSUE THREAD

**Issue by mrmagic2020** [LiteLDev/LiteLoader#553]
### 异常模块

ScriptEngine（脚本引擎）

### 操作系统

Windows Server 2019

### LiteLoader版本

2.4.0

### BDS版本

1.19.10

### 发生了什么?

在写插件的时候使用runcmdEx()方法向后台发送"execute xxx ~~~ locate biome plains"的时候发现返回的结果是syntax error，并且指向了>>biome<<。而当我在BDS后台手动输入完全一样的命令时，则能够正常返回locate结果。

### 复现此问题的步骤

1、编写插件使用runcmdEx()方法发送execute xxx ~~~ locate biome plains指令，并输出返回的结果
2、在BDS后台发送相同的命令
3、对比两者的输出

### 有关的日志/输出

```shell
Syntax error: Unexpected "structure": at "~~ locate >>structure<< ancientci"
Unexpected "biome": at "~~ locate >>biome<< plains"
```

**Comment by Redbeanw44602** [comment]
试试 `player:runcmd("locate biome plains")`

**Comment by Yushu2606** [comment]
~新语法不应该是`execute as xxx run xxx`吗（~
哦这是实验性玩法（（

**Comment by mrmagic2020** [comment]
> 新语法不应该是`execute as xxx run xxx`吗（

但是控制台输入和游戏内输入都没有问题诶

**Comment by Jaciezyt** [comment]
> > 新语法不应该是`execute as xxx run xxx`吗（
> 
> 但是控制台输入和游戏内输入都没有问题诶

总之你先试试他说的

**Comment by mrmagic2020** [comment]
> > > 新语法不应该是`execute as xxx run xxx`吗（
> > 
> > 
> > 但是控制台输入和游戏内输入都没有问题诶
> 
> 总之你先试试他说的

execute as xxx run locate village
显示语法错误，指向>>玩家ID<<

**Comment by dreamguxiang** [comment]
已修复
#859
