### ISSUE TITLE
关于mayfly能力给予后能力列表没有更新

### ISSUE THREAD

**Issue by xinge4088** [LiteLDev/LiteLoader#561]
### 异常模块

Core（核心）

### 操作系统

Windows 10

### LiteLoader版本

2.4.0

### BDS版本

1.19.10

### 发生了什么?

从1.19.2版本升级至1.19.10版本之后发下，给予mayfly能力之后，ability列表无法正常更新。一直显示的false，但还是可以飞行。这导致了插件判断出问题。无法检测是否开启飞行。

### 复现此问题的步骤

1.没有解锁ability指令得安装个强开启的插件
2.使用指令给予飞行
3.利用调试插件查看ability能力表

### 有关的日志/输出

```shell
无
```

### 插件列表

```shell
已排查插件问题
```

**Comment by KawaiiNahida** [comment]
在1.19.1x版本中ojang修改了飞行相关能力的校验逻辑，请自行检查相关代码逻辑以适配1.19.1x
