### ISSUE TITLE
客户端位置与服务器位置不同步

### ISSUE THREAD

**Issue by xinge4088** [LiteLDev/LiteLoader#562]
### 异常模块

Core（核心）

### 操作系统

Windows 10

### LiteLoader版本

2.4.0

### BDS版本

1.19.10

### 发生了什么?

更新1.19.10之后会出现移动问题，就是客户端显示在别的地方。怪物会一直攻击你之前所在的地方。并且无法对范围外的东西进行操作比如挖掘，捡起凋落物

### 复现此问题的步骤

随机触发，比较频繁

### 有关的日志/输出

```shell
无
```

### 插件列表

```shell
已排查插件问题
```

**Comment by dreamguxiang** [comment]
原版BDS尝试过吗

**Comment by ShrBox** [comment]
原版BDS的bug

**Comment by yqs112358** [comment]
这不太可能是插件这里的问题，主要的游戏逻辑我们没有作修改，请首先排除服务端自身问题
据描述感觉更像是 网络延迟 / 硬盘读写lag

**Comment by yqs112358** [comment]
而不是游戏的锅

**Comment by RimuruChan** [comment]
自行排查，有疑问重开此issue
