### ISSUE TITLE
提供在插件加载之前判断插件版本的接口

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LiteLoader#563]
### 您的建议是否与现存的某个问题相关?请描述问题?

目前LL无法在插件加载之前获取插件的相关版本信息（如插件编译时使用的SDK版本号等），如果可以的话将对插件适配等相关工作产生很大便利

### 您认为还缺少什么?如何解决您的问题?

在插件template中，用某种方式在编译时在某些地方导出插件此次编译所使用的SDK版本号，以及插件自身的版本号，以方便供LL读取
在加载插件之前可以读取其SDK版本信息判断插件是否兼容，如果不兼容可以给用户以更友好的提示信息（而不仅仅是127失败信息）
另外也可以用于未来设计的公共自动更新接口判断插件版本等

**Comment by futrime** [comment]
这个可以通过lip record解决

**Comment by futrime** [comment]
开发者直接在tooth.json填写版本号就行了

**Comment by futrime** [comment]
然后ll读取.lip/records内的json
