### ISSUE TITLE
LLSE加入底层接口支持，以及与C++接口互调

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LiteLoader#564]
脚本插件API目前较为缺乏，与C++插件隔离程度大，为了强化脚本接口以及统一两种插件生态，底层API支持以及接口互调势在必行
下面是设计思路

## 脚本调用底层API
包括hook symcall等基础底层API，以及可以方便地调用所有由头文件生成器生成的BDS API
#### 脚本层Hook symcall接口设计
使用dyncall轮子，实现动态调用
脚本部分基础语法示例：
![CQ3Q$}HYK4FIDM(ORH4Q1`U](https://user-images.githubusercontent.com/37969157/179505848-5c1d8caa-2215-450f-b022-780068849a7d.png)
接口如上设计即可

#### 结构体与指针
new char指针+偏移动态结构体
bytebuffer对接char*

#### 调用头文件生成的BDS API
由于自动导出的BDS API数量较大（数十万），每次更新变动数量较大，手动维护不切实际。因此考虑根据头文件生成器给出的originalData函数原型数据库进行自动化调用
首先，自动化调用，考虑通过各语言Proxy实现拦截不存在的调用，并实时逐层查找底层符号，取得函数地址和函数原型后直接使用dyncall进行动态调用
其次，originalData的原型信息也可以帮助上述hook symcall轮子，可以做到不用像上图那样手动填写每个参数的数据类型，而是根据函数原型动态识别参数类型
 
 
 
## 脚本与C++接口互调
脚本插件调用C++插件导出的API，或反之
相关实现思路如下：
#### cpp<>cpp接口互调
getPlugin  .getFunction (用dyncall动态构造函数) 
增加LL::export用以声明导出

#### cpp插件调用脚本插件接口
脚本导出json远调接口，cpp接口用模板封装远调

#### 脚本插件调用cpp插件接口
类似 **脚本调用底层API**，getPlugin获取C++插件信息并获取导出的API，调用时底层使用类似symcall的方法进行调用

**Comment by RimuruChan** [comment]
LiteLDev/ScriptEngine#16
