### ISSUE TITLE
LL一些功能优化与修复

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LiteLoader#568]
- [ ] pl.giveItem(item) 给玩家物品后，原来的物品对象会被设置为null
- [x] 优化getTileData实现（避免使用遍历检查）
- [ ] 事件监听研究更好的方案
- [ ] fmt输出花括号或者乱码崩服，暂时没找到正常输出花括号的方法
- [ ] LiteLDev/LiteLoader#7
- [ ] Logger改异步以提升性能（用IO完成端口？或者APC）
- [ ] 增加刷屏报错屏蔽功能
- [ ] fail to lookup 时提示发生问题的模块名（是哪个插件引起的）
- [ ] crashlogger 输出模块列表
- [ ] 修复部分内存泄漏
为NBT、新建对象等场景单独开辟缓冲区，使用定位new统一分配内存，记录地址；分析销毁过程，顺带delete
- [ ] i18n tr翻译增加内存缓存
- [ ] symdb 使用 Trie 进一步提升查找效率
- [ ] dev模式下不修改系统errormode，崩溃弹窗正常显示，以方便问题排查
- [ ] 内联symdb（忘记啥意思了先放这里记一笔）

**Comment by Yushu2606** [comment]
> 增加刷屏报错屏蔽功能

可以考虑合并重复报错
