### ISSUE TITLE
为addon提供加密服务

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LiteLoader#569]
应之前某位addon开发者的提议
由于addon资源无法进行混淆和加密，addon发行即默认于完全开源和失去所有权，一定程度上打击开发者的制作积极性
提供加密服务有助于与addon圈建立强联系，拓展插件圈生态范围
比如规定特定加密方式和密钥，在内存中实时解密加载

**Comment by LazuliKao** [comment]
👍🏻️

**Comment by StarsDream00** [comment]
NK相关实现
https://github.com/CloudburstMC/Nukkit/blob/master/src/main/java/cn/nukkit/network/protocol/ResourcePacksInfoPacket.java

**Comment by Redbeanw44602** [comment]
> NK相关实现 https://github.com/CloudburstMC/Nukkit/blob/master/src/main/java/cn/nukkit/network/protocol/ResourcePacksInfoPacket.java

这个应该是官方的加密addons

**Comment by dreamguxiang** [comment]
已实现官服材质包加密功能
