### ISSUE TITLE
`afterPlaceBlock`事件无法使用

### ISSUE THREAD

**Issue by lgc2333** [LiteLDev/LiteLoader#581]
### 异常模块

ScriptEngine（脚本引擎）

### 操作系统

Windows 11

### LiteLoader版本

2.4.1

### BDS版本

1.19.10

### 发生了什么?

注册afterPlaceBlock的监听时发现不存在该事件，翻了一下beta分支的commits，可能是忘记加了

### 复现此问题的步骤

```js
mc.listen('afterPlaceBlock', (player, block) => {
  // ...
});
```

### 有关的日志/输出

```shell
14:22:17 ERROR [LiteLoader] Event "afterPlaceBlock" No Found!

14:22:17 ERROR [LiteLoader] In Plugin: BanObsidian.lxl.js
```

**Comment by Redbeanw44602** [comment]
已修复，等待hotfix发布。
