### ISSUE TITLE
LLse pl.kick([msg])有几率失效

### ISSUE THREAD

**Issue by hhaipaap** [LiteLDev/LiteLoader#586]
### 异常模块

ScriptEngine（脚本引擎）

### 操作系统

Windows Server 2022

### LiteLoader版本

2.4.1

### BDS版本

1.19.10

### 发生了什么?

有几率失效

### 复现此问题的步骤

使用 pl.kick([msg])

### 有关的日志/输出

```shell
无
```

### 插件列表

```shell
无
```

**Comment by PA733** [comment]
无法复现
![image](https://user-images.githubusercontent.com/67588574/180011340-22202e56-e54d-430c-8301-5386cc2e7f04.png)
请检查pl是否成功获取，如果pl获取失败，则llse会返回NULL

**Comment by dreamguxiang** [comment]
自行排查，有疑问重开此issue
