### ISSUE TITLE
Docker容器日志提示错误：wine: could not load kernel32.dll, status c0000135

### ISSUE THREAD

**Issue by wlinto** [LiteLDev/LiteLoader#602]
### 异常模块

Core（核心）

### 操作系统

GNU/Linux with docker

### LiteLoader版本

2.4.1

### BDS版本

1.19.10

### 发生了什么?

我使用的是群晖NAS里的docker容器

拉取镜像和创建LiteLoader容器都没问题，就是启动不了。
使用命令 docker container start liteloader 启动容器立即就自动停止运行了，

在容器日志里显示：wine: could not load kernel32.dll, status c0000135

不知道怎么搞，LiteLoader容器启动不了，也进不去容器里，该怎么解决这个问题呢，谢谢！

### 复现此问题的步骤

docker container start liteloader

### 有关的日志/输出

```shell
wine: could not load kernel32.dll, status c0000135
```

### 插件列表

```shell
没有安装插件
```

**Comment by ShrBox** [comment]
Can not reproduce, because I don't have a Synology NAS and I cant reproduce it in normal x86 server
