### ISSUE TITLE
LLse 增加监听项“粒子生成”

### ISSUE THREAD

**Issue by hhaipaap** [LiteLDev/LiteLoader#607]
### 您的建议是否与现存的某个问题相关?请描述问题?

想要禁用某些粒子生成来优化性能
但没有这类api

### 您认为还缺少什么?如何解决您的问题?

增加监听项“粒子生成”

**Comment by dreamguxiang** [comment]
绝大部分粒子生成由客户端控制

**Comment by OEOTYAN** [comment]
建议使用去粒子材质。
