### ISSUE TITLE
提供与自带的Addons体系交互的能力

### ISSUE THREAD

**Issue by Redbeanw44602** [LiteLDev/LiteLoader#609]
### 您的建议是否与现存的某个问题相关?请描述问题?

目前，LL仍然没有 *注册物品*、*注册生物*、*注册方块* 等Addons相关能力，可以说是一块严重的短板。如果LL插件可以像Addons一样直接提供游戏内内容，那么LL插件平台必将像JE的Forge平台一样具有极高的可创造性。

目前MC自带的Addons系统存在以下问题：
 - Addons无可靠的源代码保护体系，开放=开源，势必破坏一部分Addon创作的积极性 #569 
 - Addons一些功能的实现要依赖自带的 **低效率** 的指令系统
 - 虽然自身有一些 Components，但依然可以看到部分 Addons 实现一些玩法时 **曲线救国**
 - 不能自由的保存数据
 - ...

LL目前缺少这方面功能，也有一些令人不快的问题：
 - 写玩法类插件困难，只用原版物品几乎做不成什么事
 - 表单功能过于单一，如果能与Addon交互或许可以改变这一情况
 - ...

### 您认为还缺少什么?如何解决您的问题?

 - 提供注册方块、注册生物、注册物品等功能
 - 考虑开发难度和维护难度，应当尽量沿用Addon系统的框架
 - 提供在LL插件内直接注册原版Addon的相关能力
 - 有待探讨...

**Comment by OEOTYAN** [comment]
https://[github.com/LiteLDev/LiteLoaderBDS/issues/1041](https://github.com/LiteLDev/LiteLoaderBDS/issues/1041)
