### ISSUE TITLE
PlayerInfoAPI cache&new API

### ISSUE THREAD

**Issue by Jaciezyt** [LiteLDev/LiteLoader#612]
### Is your feature request related to a problem? Please describe.

Current PlayerInfoAPI wont load data into memory, but query database each time.This may cost some time when querying player info.
btw, new APIs like `getAllPlayers` is required

### Describe the solution you'd like

Load player data into memory when server starts&Add APIs

**Comment by Yushu2606** [comment]
这API没做进LLSE里啊xwx
