### ISSUE TITLE
module is not defined in LLSE NodeJS

### ISSUE THREAD

**Issue by Jaciezyt** [LiteLDev/LiteLoader#624]
### Exceptions module

ScriptEngine

### Operating System

Windows Server 2019

### LiteLoader version

8b4efcd

### BDS version

1.19.10

### What happened?

`module` is not defined error in `module.exports` statement

### Steps to reproduce?

Unzip and put these into `/path/to/bds/plugins/nodejs/`
[nodejs.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/9224772/nodejs.zip)

### Relevant log output

```shell
module.exports.hello = hello;
^

ReferenceError: module is not defined
    at node:embedder_main_1:4:1
```

**Comment by yqs112358** [comment]
这是个疑难杂症问题，不过目前不影响正常插件开发。

### 问题描述
刚刚经过系统测试，发现问题如下：
> 如果某插件使用require加载内部含有module.exports代码的插件，这个require会成功，后续对导入进来的函数调用也没有问题
> 但是如果由LLSE直接加载的index.js中如果含有module.export，则会报错，提示module不存在

### 原因
这个问题其实是因为embedded NodeJs可能没有完全完成Node的某些模块加载机制流程所导致的问题。参考NodeJs中require的加载机制我们可以发现，被require的脚本在执行之前，**会先被套上一层`(function (exports, require, module, __filename, __dirname) {      })`**，然后使用vm.runInThisContext执行，这也就是为什么在脚本当中能够直接操作require以及module相关成员的原因
可以猜想NodeJs正常加载代码的过程中也会执行这样一套流程，因此在Node直接执行的源码中也可以使用module的全部功能。

但是由于embedded的NodeJs的启动代码是完全自行编写，因此没有这个操作进行还原，导致了这个问题。我也尝试阅读了一些node的启动流程相关的代码，但是并没有找到源码中执行相关操作的部分，可能要实现这个效果不是很容易，需要一些复杂的操作

### 问题部分解决
当然，一开始也说了，这个问题其实不影响正常插件开发。其实在测试包中使用的这种引用方式并不常见，一般来说插件引用局部代码都是使用如图结构：
![image](https://user-images.githubusercontent.com/37969157/182027525-fa250052-711a-4fcf-950d-5cae3d387c74.png)
也就是说**只存在一个入口点js，入口点js负责require所有其他的依赖js。依赖js当中会存在module.exports导出一些函数供其他文件使用，而入口点主文件中并不存在类似的导出**

这种行为其实是**比较合理**的，因为在入口点index.js中再进行module.exports导出函数并没有什么意义，入口点的调用者肯定是LLSE的nodejs backend引擎，而不是会有另外一个js去故意地“require"他。所以说测试用例其实相对牵强，一般正常代码编写也不会使用这种方式。如果使用如图的正常方式进行require和module.exports，则不会出现任何问题。

### 后续
后续在进行代码修复的时候可以尝试一些方法来修复此问题，如手动在JS层创建wrap模拟等等。不过目前这方面的问题并不是很大。
相关参考：深入NodeJs的模块加载机制 https://segmentfault.com/a/1190000023828613

**Comment by yqs112358** [comment]
Maybe fixed. @Jasonzyt 大佬有兴趣可以测试下

**Comment by Jaciezyt** [comment]
目前可以用了

**Comment by yqs112358** [comment]
关issue了
