### ISSUE TITLE
LLSE `File`类对象无法正常读取文件名为中文的文件

### ISSUE THREAD

**Issue by lgc2333** [LiteLDev/LiteLoader#625]
### 异常模块

ScriptEngine（脚本引擎）

### 操作系统

Windows 11

### LiteLoader版本

2.4.1

### BDS版本

1.19.10

### 发生了什么?

刚写的插件[NbsPlayer](https://github.com/lgc2333/LLSEPlugins/tree/main/NbsPlayer)无法打开正常打开中文文件

估计是字符编码问题

![image](https://user-images.githubusercontent.com/59048777/181902116-4f605402-3e67-4a71-93b6-46d1bb78ccaf.png)

### 复现此问题的步骤

[Code](https://github.com/lgc2333/LLSEPlugins/blob/main/NbsPlayer/NbsPlayer.lls.js#L73)

**Comment by Jaciezyt** [comment]
插件文件编码换一换试试？

**Comment by lgc2333** [comment]
> 插件文件编码换一换试试？

换成gbk吗？
不行啊……插件显示的文本都乱了……
![image](https://user-images.githubusercontent.com/59048777/181902747-08f34f44-e5fc-46ae-8bdc-19bb10f1813e.png)
![image](https://user-images.githubusercontent.com/59048777/181902748-ddc585bc-6417-4339-a161-2976891e0647.png)

**Comment by Jaciezyt** [comment]
最新QuickJS版本无法复现

**Comment by lgc2333** [comment]
我试试更新ll版本

**Comment by lgc2333** [comment]
经测试，更新ll到2.4.2依然会复现
代码
```js
const file = new File('测试中文文件.tmp', File.ReadMode);
file.close();
```
![image](https://user-images.githubusercontent.com/59048777/181903225-988749e5-a287-4be0-868f-2611db9c4bbf.png)

**Comment by Jaciezyt** [comment]
经测试`File.writeTo` `File.writeLine` `File.readFrom` 正常
但new File确实有问题，如果实在需要可以先用上面的代替

**Comment by lgc2333** [comment]
> 经测试`File.writeTo` `File.writeLine` `File.readFrom` 正常 但new File确实有问题，如果实在需要可以先用上面的代替

文件太大了……我需要用asyncRead

**Comment by Jaciezyt** [comment]
> > 经测试`File.writeTo` `File.writeLine` `File.readFrom` 正常 但new File确实有问题，如果实在需要可以先用上面的代替
> 
> 文件太大了……我需要用asyncRead

js自己也有Promise接口，另外183k真算不上大

**Comment by Jaciezyt** [comment]
Fixed in 7ac65e8
等自动close
