### ISSUE TITLE
PlaceBlock事件 放置坐标 以及 方块类型 错误

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LiteLoader#628]
### 异常模块

Core（核心）

### 操作系统

Windows Server 2019

### LiteLoader版本

2.4.2-patch1

### BDS版本

1.19.10

### 发生了什么?

如题，PlaceBlock事件 放置坐标 以及 方块类型 错误
坐标Y轴方向偏差一到两格，方块类型名错误

暂不清楚是getPos和getTypeName API错误还是事件返回的东西就是错的，有待检查
其他类似事件也需要进行检查

### 复现此问题的步骤

1. 安装行为日志插件BehaviorLog
2. 进入游戏
3. 放置一些方块
4. 看后台日志输出

**Comment by lgc2333** [comment]
#582

**Comment by Redbeanw44602** [comment]
see #548
