### ISSUE TITLE
Package Manager

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LiteLoader#641]
提供对插件以及加载器本身的分发功能
RT，如今即将开始内测

**Comment by Redbeanw44602** [comment]
暖暖

**Comment by AlexXuCN** [comment]
问：  
 * 这玩意是独立程序？还是dll插件 or LLSE插件  
 * 会支持插件热替换吗  
 * 会支持addons之类的安装吗  
 * repo怎么处理？  
或者说设计思路是怎样的？ 
 
以及
```
我 为 什 么 要 问 这 个🤔
```

**Comment by Jaciezyt** [comment]
@AlexXuCN 详细可以去https://github.com/LiteLDev/PackageManager 查看
LLPM是基于Lua的脚本, 需要Lua的 runtime 支持, 但不依赖BDS和LL

**Comment by Redbeanw44602** [comment]
由于方案有变，应关闭此issue。
