### ISSUE TITLE
FormUI表单StepSlider滑块minValue==maxValue问题

### ISSUE THREAD

**Issue by kkj9333** [LiteLDev/LiteLoader#642]
### 您的建议是否与现存的某个问题相关?请描述问题?

Liteloader 的FormUI中关于slider滑块有不合理的地方，如下图，当minValue>=maxValue时设置maxValue=minValue+1。
这实际上是不合理的，因为存在minValue==maxValue而使表单滑块不能滑动的需求。
这样写虽然保证了maxValue始终大于minValue而不会发生错误，但是却忽视了minValue==maxValue的情况，而这种情况下在bds内部同样是符合逻辑的。
![P(P0$O {_~OWWZ0 (8}$156](https://user-images.githubusercontent.com/51207072/183248043-bd6c66a7-f88c-4038-b82f-14c863201fba.png)
![2$C11W64MZXOOFVAB)NPEQ8](https://user-images.githubusercontent.com/51207072/183248056-880f8ed5-65f8-47db-95b0-28f0ce40d48e.png)

### 您认为还缺少什么?如何解决您的问题?

希望将
minValue>=maxValue   改成
minValue>maxValue
这样的话可以满足minValue==maxValue的需求。

**Comment by dreamguxiang** [comment]
试一下最新action还存在这个问题吗

**Comment by Jaciezyt** [comment]
> 试一下最新action还存在这个问题吗

应该还在, #572 只改了`if (minValue >= maxValue)`括号内的内容, 没有改if条件
