### ISSUE TITLE
已存在命令检查不兼容LLSE旧的假命令

### ISSUE THREAD

**Issue by Redbeanw44602** [LiteLDev/LiteLoader#643]
### 异常模块

Core（核心）

### 操作系统

Windows 10

### LiteLoader版本

actions #2563

### BDS版本

1.19.11.01

### 发生了什么?

![11](https://user-images.githubusercontent.com/29711228/183249676-2d8f4a90-b891-4f95-b16c-5083299debd4.png)
假命令注册重载的方式一般是
reg `cmd`
reg `cmd arg1`
reg `cmd arg2`

如图修改将导致兼容性问题

### 复现此问题的步骤

见上

### 有关的日志/输出

```shell
N\A
```

### 插件列表

```shell
N\A
```

**Comment by ShrBox** [comment]
最新构建 5cd9c34bac617fc4f65d8e26d83aba00ef18d944 无法复现
使用的插件是iland

**Comment by Redbeanw44602** [comment]
> 最新构建 [5cd9c34](https://github.com/LiteLDev/LiteLoaderBDS/commit/5cd9c34bac617fc4f65d8e26d83aba00ef18d944) 无法复现 使用的插件是iland

因为我注释了

**Comment by Jaciezyt** [comment]
既然已经注释掉了就没什么必要再开着了，后续反馈去#604 罢
