### ISSUE TITLE
插件名不能含有LiteLoader

### ISSUE THREAD

**Issue by LittleSaya** [LiteLDev/LiteLoader#644]
### 您的建议是否与现存的某个问题相关?请描述问题?

我在编写dll插件时，发现dll文件名会影响插件的加载情况，有时能加载，有时不能加载，似乎文件名中有下划线或者文件名太长都加载不了。

### 您认为还缺少什么?如何解决您的问题?

我希望文档或者README.md内能注明具体的插件名和插件文件名的命名规则。

**Comment by Jaciezyt** [comment]
不合理，具体如何复现你说的"有时能加载，有时不能加载"的问题？
列举一些你尝试过无法加载的名称

**Comment by LittleSaya** [comment]
> 不合理，具体如何复现你说的"有时能加载，有时不能加载"的问题？
> 列举一些你尝试过无法加载的名称

`SayaLLBDSPlugin.dll`可以加载，`Saya_s_LiteLoaderBDSPlugin.dll`和`Saya's LiteLoaderBDSPlugin.dll`不可以加载

**Comment by Jaciezyt** [comment]
@LittleSaya 额，复制一下你插件的绝对路径(从C:\开始一直到xxx.dll),看一下长度有没有超过260

**Comment by LittleSaya** [comment]
> @LittleSaya 额，复制一下你插件的绝对路径(从C:\开始一直到xxx.dll),看一下长度有没有超过260

应该没有，我的插件路径是这个：`D:\crafty-win64-_b4796523\servers\526c4b20-d47f-44ab-ab3e-3027c451c380\plugins\SayaLLBDSPlugin.dll`，只有98个字符

**Comment by Jaciezyt** [comment]
> > @LittleSaya 额，复制一下你插件的绝对路径(从C:\开始一直到xxx.dll),看一下长度有没有超过260
> 
> 应该没有，我的插件路径是这个：`D:\crafty-win64-_b4796523\servers\526c4b20-d47f-44ab-ab3e-3027c451c380\plugins\SayaLLBDSPlugin.dll`，只有98个字符

@LittleSaya 试着缩短一下目录看看？
顺便把你dll上传一下

**Comment by LittleSaya** [comment]
> @LittleSaya 试着缩短一下目录看看？
> 顺便把你dll上传一下

`D:\t\plugins\Saya's LiteLoaderBDSPlugin.dll`也加载不
[SayaLLBDSPlugin.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/9276146/SayaLLBDSPlugin.zip)
了

**Comment by Jaciezyt** [comment]
经调试发现，DLL插件名不能含有LiteLoader或LiteXLoader，在新版本发布前建议自行更改

**Comment by LittleSaya** [comment]
> 经调试发现，DLL插件名不能含有LiteLoader或LiteXLoader，在新版本发布前建议自行更改

谢谢，明白了
