### ISSUE TITLE
希望明确动态指令中枚举值的命名规范

### ISSUE THREAD

**Issue by LittleSaya** [LiteLDev/LiteLoader#649]
### 您的建议是否与现存的某个问题相关?请描述问题?

动态指令的枚举值似乎不支持大写字母，但是没有文档提及这一点。

以下这种写法，可以正常执行指令`/cmd a 1`和`/cmd b 1`，但是执行`/cmd C 1`会提示语法错误。

```c++
using ParamType = DynamicCommand::ParameterType;
using Param = DynamicCommand::ParameterData;
DynamicCommand::setup(
    "cmd",
    "cmd",
    {
        { "Module", { "a", "b", "C" } },
    },
    {
        Param("testEnum", ParamType::Enum, "Module"),
        Param("testInt", ParamType::Int, true),
    },
    {
        { "Module", "testInt" },
    },
    [](DynamicCommand const& command, CommandOrigin const& origin, CommandOutput& output,
        std::unordered_map<std::string, DynamicCommand::Result>& results) {
        output.success("Success");
    },
    CommandPermissionLevel::Any
);
```

### 您认为还缺少什么?如何解决您的问题?

在文档或者README中注明动态指令枚举值的命名规则

**Comment by dreamguxiang** [comment]
BDS不支持含有大写的枚举值，这也是为什么gamerule全是小写的原因

**Comment by LittleSaya** [comment]
> BDS不支持含有大写的枚举值，这也是为什么gamerule全是小写的原因

我才刚接触BDS，不太了解它的细节，可是我发现wiki里写的gamerule都是有大小写的，例如`drowningDamage`和`doMobLoot`，我实际使用gamerule命令时，也可以使用这些有大小写的命令，例如`gamerule keepInventory true`，为什么gamerule就可以使用带有大写的参数呢？

我试了一下，执行`/gamerule keepInventory true`会返回正常的`Game rule keepInventory has been updated to true`，执行`/gamerule keepInventoryyy true`会返回`Syntax error: Unexpected "keepInventoryyy": at "/gamerule >>keepInventoryyy<< true"`，就像输错了枚举参数一样。

我不太懂gamerule的参数和我自己注册的动态指令里的枚举有何区别，不过我还是希望能在README或者文档中注明一下这一点，或者在注册指令时遇到含有大写字母或者其他不允许的字符时给一个比较明显的错误提示。

**Comment by Jaciezyt** [comment]
@LittleSaya `gamerule`用的应该是SoftEnum枚举, 你也可以尝试一下

**Comment by LittleSaya** [comment]
> @LittleSaya `gamerule`用的应该是SoftEnum枚举, 你也可以尝试一下

SoftEnum似乎不会在输入命令时显示枚举的名称：

<img width="633" alt="softenum" src="https://user-images.githubusercontent.com/16049823/183433954-1e017905-dbea-43ac-8b4d-457851314438.png">

这是gamerule命令：

<img width="525" alt="gamerule" src="https://user-images.githubusercontent.com/16049823/183436990-4311d29b-9b10-4b99-b1b2-a69a9fab7035.png">

此外SoftEnum似乎也不会在输入未定义的枚举值时报错，我不清楚是不是我使用SoftEnum的做法有问题，感觉这套自定义命令的体系不是很直观：

```c++
auto command = DynamicCommand::createCommand("cmd1", PLUGIN_NAME, CommandPermissionLevel::Any);

command->setSoftEnum("Module", { "moduleA", "moduleB" });
command->setSoftEnum("GlobalInt", { "int1", "int2" });
command->setSoftEnum("GlobalBool", { "bool1", "bool2" });
command->setEnum("ModuleOp", { "config", "update", "reload" });
command->setEnum("VariableOp", { "set", "clear" });

command->mandatory("object", DynamicCommand::ParameterType::SoftEnum, "Module");
command->mandatory("object", DynamicCommand::ParameterType::SoftEnum, "GlobalInt");
command->mandatory("object", DynamicCommand::ParameterType::SoftEnum, "GlobalBool");
command->mandatory("op", DynamicCommand::ParameterType::Enum, "ModuleOp");
command->mandatory("op", DynamicCommand::ParameterType::Enum, "VariableOp");
command->optional("intValue", DynamicCommand::ParameterType::Int);
command->optional("boolValue", DynamicCommand::ParameterType::Bool);

command->addOverload({ "Module", "ModuleOp" });
command->addOverload({ "GlobalInt", "VariableOp", "intValue" });
command->addOverload({ "GlobalBool", "VariableOp", "boolValue" });

command->setCallback([](DynamicCommand const& command, CommandOrigin const& origin, CommandOutput& output, std::unordered_map<std::string, DynamicCommand::Result>& results) {
    output.success("Success");
});
DynamicCommand::setup(std::move(command));
```

**Comment by dreamguxiang** [comment]
softenum用法不对，请看https://github.com/LiteLDev/LiteLoaderBDS/blob/e607de786a650bf19fb458982d932afcf0b273d7/LiteLoader/Kernel/Command/DynamicCommandAPI.cpp#L496

的debug部分，拥有dycmd所有功能示例

这套指令系统已经是最容易简单，而且兼容llse的了，你也可以尝试继承方案（与BDS一致）

**Comment by LittleSaya** [comment]
> 的debug部分，拥有dycmd所有功能示例
> 
> 这套指令系统已经是最容易简单，而且兼容llse的了，你也可以尝试继承方案（与BDS一致）

是这样使用吗？

```c++
auto command = DynamicCommand::createCommand("cmd1", PLUGIN_NAME, CommandPermissionLevel::Any);

auto moduleEnum = command->setSoftEnum("ModuleEnum", {});

auto objectParam = command->mandatory("ObjectParam", DynamicCommand::ParameterType::SoftEnum, moduleEnum);

command->addOverload({ objectParam });

command->setCallback([](DynamicCommand const& command, CommandOrigin const& origin, CommandOutput& output, std::unordered_map<std::string, DynamicCommand::Result>& results) {
    output.success("Success");
});

auto instance = DynamicCommand::setup(std::move(command));

instance->setSoftEnum("ModuleEnum", { "a", "b", "C" });
instance->addSoftEnumValues("ModuleEnum", { "d", "e", "F" });
```

似乎还是不会显示枚举的名称，我参考的是这段代码：

<img width="671" alt="softenum2" src="https://user-images.githubusercontent.com/16049823/183537026-630ee2f5-efde-47d7-a3cb-548997de7f0c.png">

运行结果是这样的：

<img width="317" alt="softenum22" src="https://user-images.githubusercontent.com/16049823/183537048-50f5d51a-1713-4da1-929f-1a1ff5f2ec7e.png">

实在不行就算了吧，我试试能不能全部用表单来实现我想要的功能，命令就只留一个不带参数的顶层命令……
