### ISSUE TITLE
增加看门狗

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#658]
### 您认为还缺少什么?如何解决您的问题?

增加看门狗以应对不可预测的刻死锁或崩溃
如果可以的话，希望额外实现类似于GameTest的性能监视器

**Comment by StarsDream00** [comment]
如果可以的话，还可以实现类似于GameTest的性能监视器

**Comment by KawaiiNahida** [comment]
就算有watchdog也解决不了bds某些地方的性能问题

**Comment by KawaiiNahida** [comment]
插件带来的性能问题应该在开发周期内解决

**Comment by Yushu2606** [comment]
> 插件带来的性能问题应该在开发周期内解决

解决问题不一定很难，但问题是如何发现并分析问题来源
如果是崩溃还有堆栈可以看，但如果是卡顿就相对难分析很多

**Comment by KawaiiNahida** [comment]
如果是为了实现性能监视器，基于debugger的方案更优，现有大量已有解决方案，具体可以自行在网络上查找
