### ISSUE TITLE
文档站格式错误  Document format error

### ISSUE THREAD

**Issue by RainoutOvO** [LiteLDev/LiteLoader#661]
### 您的建议是否与现存的某个问题相关?请描述问题?

![image](https://user-images.githubusercontent.com/102637907/184074108-bd508a81-28ef-4736-8344-48dbd235db68.png)

**Comment by ShrBox** [comment]
请使用docs.litebds.com而不是lxl.litebds.com

**Comment by Jaciezyt** [comment]
https://docs.litebds.com/zh_CN/Development/
plz

**Comment by RainoutOvO** [comment]
> 请使用docs.litebds.com而不是lxl.litebds.com

谢谢，我发现贵项目在minebbs上面的简介中超链接设置错误。
tks! the hyperlink went wrong on minebbs
![image](https://user-images.githubusercontent.com/102637907/184074842-0cbb170c-e2fd-429b-a794-701757c2867f.png)

**Comment by ShrBox** [comment]
> > 请使用docs.litebds.com而不是lxl.litebds.com
> 
> 谢谢，我发现贵项目在minebbs上面的简介中超链接设置错误。 tks! the hyperlink went wrong on minebbs ![image](https://user-images.githubusercontent.com/102637907/184074842-0cbb170c-e2fd-429b-a794-701757c2867f.png)

Thanks feedback
