### ISSUE TITLE
简化开启服务器时的输出

### ISSUE THREAD

**Issue by MengYang8481** [LiteLDev/LiteLoader#662]
### 您的建议是否与现存的某个问题相关?请描述问题?

现在咱生态越来越强大插件越来越多，插件多了开服输出跟论文似的，可能会错过WARN这些必要提示

### 您认为还缺少什么?如何解决您的问题?

做个开服时日志等级，开服时仅输出 WARN 以上级别的日志，INFO就不输出了，插件加载完就一句“Plugin.js Loaded”就行了.

**Comment by Yushu2606** [comment]
> ### 您的建议是否与现存的某个问题相关?请描述问题?
> 现在咱生态越来越强大插件越来越多，插件多了开服输出跟论文似的，可能会错过WARN这些必要提示
> 
> ### 您认为还缺少什么?如何解决您的问题?
> 做个开服时日志等级，开服时仅输出 WARN 以上级别的日志，INFO就不输出了，插件加载完就一句“Plugin.js Loaded”就行了.

`plugins/LiteLoader/LiteLoader.json` -> `LogLevel`

**Comment by Jaciezyt** [comment]
> > ### 您的建议是否与现存的某个问题相关?请描述问题?
> > 现在咱生态越来越强大插件越来越多，插件多了开服输出跟论文似的，可能会错过WARN这些必要提示
> > ### 您认为还缺少什么?如何解决您的问题?
> > 做个开服时日志等级，开服时仅输出 WARN 以上级别的日志，INFO就不输出了，插件加载完就一句“Plugin.js Loaded”就行了.
> 
> `plugins/LiteLoader/LiteLoader.json` -> `LogLevel`

但他要求输出部分Info，去掉`XX plugin <xx> loaded`

**Comment by Redbeanw44602** [comment]
建议卸载输出跟论文似的的插件，此问题不应由加载器解决。盲目过滤INFO可能错过重要信息。

**Comment by yqs112358** [comment]
日志等级 LogLevel
0 不显示任何日志
1 仅显示FATAL
2 显示 FATAL ERROR
3 显示 FATAL ERROR WARN
4 显示 FATAL ERROR WARN INFO
5 显示 FATAL ERROR WARN INFO DEBUG
正常情况使用日志等级就够用
如果需要定制输出请使用 OutputFilter 选项自定义过滤

另外WARN在控制台输出为黄色，相当醒目，不会看不见

**Comment by MengYang8481** [comment]
> > > ### 您的建议是否与现存的某个问题相关?请描述问题?
> > > 现在咱生态越来越强大插件越来越多，插件多了开服输出跟论文似的，可能会错过WARN这些必要提示
> > > ### 您认为还缺少什么?如何解决您的问题?
> > > 做个开服时日志等级，开服时仅输出 WARN 以上级别的日志，INFO就不输出了，插件加载完就一句“Plugin.js Loaded”就行了.
> > 
> > 
> > `plugins/LiteLoader/LiteLoader.json` -> `LogLevel`
> 
> 但他要求输出部分Info，去掉`XX plugin <xx> loaded`

实际上是保留一个`XX plugin <xx> loaded`，然后如果有WARN就输出，是因为生态强所需插件多并非是单个插件论文式print（ 确认插件加载完没有错误即可，什么作者信息应该写在 `registerPlugin` 里

**Comment by yqs112358** [comment]
作者信息相关内容一般都是插件作者自行输出，加载器这里无法控制，加载器本身并不会输出任何插件相关信息
如果有需要过滤你可以使用output filter自定义你的过滤，过滤掉相关关键字
