### ISSUE TITLE
LLSE new Date() time bug 

### ISSUE THREAD

**Issue by BuslnwTH** [LiteLDev/LiteLoader#664]
### Exceptions module

ScriptEngine

### Operating System

Windows Server 2022

### LiteLoader version

2.5.0

### BDS version

1.19.20.02

### What happened?

Left time wrong

Left (Yellow) use new Date();
Right (Green) use system.getTimeStr();

![image](https://user-images.githubusercontent.com/17994537/184145198-b0836426-0d87-4b8b-9494-a48e8a28fce2.png)

```
mc.listen("onJoin", function (player) {
    setInterval(()=> {
        let time = new Date();
        let dateNew = "§e" + time.getFullYear() + "-" + time.getMonth() + "-" + time.getDate() + " " + time.getHours() + ":" + time.getMinutes() + ":" + time.getSeconds() + "§c || §a"
        let timeStr = system.getTimeStr();
        player.setBossBar(dateNew + timeStr, time.getSeconds(), 6);
    },1000)
})
```

**Comment by BuslnwTH** [comment]
GMT+0000 as it should be GMT+0700 (System Timezone)
![image](https://user-images.githubusercontent.com/17994537/184149614-92c6e522-2d1b-4b39-8663-37f118be242e.png)

**Comment by yqs112358** [comment]
QuickJs engine's bug about time, trying to fix...

Addition: Your call to `time.getMonth()` is wrong. Its range is [0,11] because of historical reasons. You need to +1

**Comment by yqs112358** [comment]
问题已定位，是quickjs源码未对win32平台制作相关实现
![image](https://user-images.githubusercontent.com/37969157/184279461-e703fc87-f6a2-4712-9112-74adf58bc01a.png)
稍后尝试修复

**Comment by yqs112358** [comment]
已修复，等待2.5.1版本更新
