### ISSUE TITLE
关于BDS原内容输出的i18n化

### ISSUE THREAD

**Issue by sheepxray** [LiteLDev/LiteLoader#665]
### 您的建议是否与现存的某个问题相关?请描述问题?

有些人总是不会善用翻译软件 也为了照顾多国人民（，我建议将BDS输出i18n化

### 您认为还缺少什么?如何解决您的问题?

将BDS固定输出的一些文字i18n化 例如:" To enable Server Telemetry, add the line 'emit-server-telemetry=true' to the server.properties file in the bds directory","INFO [Server] IPv4 supported, port: 63314
 INFO [Server] IPv6 supported, port: 63315"

**Comment by KawaiiNahida** [comment]
说实话不建议连电脑都用不明白的人开服

**Comment by sheepxray** [comment]
没办法 有的人是这样的
![图片](https://user-images.githubusercontent.com/73421829/184177156-ff4e30fb-1012-4820-9fcb-63762ea82835.png)

**Comment by yqs112358** [comment]
有机会会进行相关工作

**Comment by RimuruChan** [comment]
不支持，个人认为这种边缘功能应当自行编写插件实现。
