### ISSUE TITLE
NodeJs插件退出卸载后 stop 无法正常关服

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LiteLoader#666]
如题，可能是node环境销毁方面的问题
较为简单的解决方案是采用类似WineFix的方案，在已经完成quit的点位hook后直接执行exit(0)

**Comment by KawaiiNahida** [comment]
Fixed in https://github.com/LiteLDev/LiteLoaderBDS/commit/26bfb16ce6e402ebe3172efad30b60ca1d045689

**Comment by KawaiiNahida** [comment]
Waiting for native apis merge in 2.5.1

**Comment by yqs112358** [comment]
OK it's great
