### ISSUE TITLE
写中文文档时注意同步到 en 版本

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LiteLoader#667]
![image](https://user-images.githubusercontent.com/37969157/184274684-268e310b-60d9-49e8-bcae-e62773b10ce0.png)
如图，发现部分文档缺失，希望编写文档时同时完成双语，或者由专人负责维护

**Comment by yqs112358** [comment]
![image](https://user-images.githubusercontent.com/37969157/184275246-edde1ea9-59c1-4ce4-a8b6-6dde47f39a1a.png)
deepl翻译得比绝大多数人都要地道，请无脑使用 deepl.com ，基本不需要太多精校

**Comment by Redbeanw44602** [comment]
可以搞个自动机翻的脚本挂在actions，调用deepL接口每次修改时增量机翻。
