### ISSUE TITLE
liteloader.dll文件报错

### ISSUE THREAD

**Issue by xnhjs233** [LiteLDev/LiteLoader#669]
### 异常模块

Core（核心）

### 操作系统

Windows Server 2019

### LiteLoader版本

2.5.0

### BDS版本

1.19.20

### 发生了什么?

我在更新了bds1.19.20后安装liteloader2.5.0在启动后就报错

### 复现此问题的步骤

1.用bds1.19.20安装liteloader2.5.0
2.启动服务端

### 有关的日志/输出

```shell
无日志输出
```

**Comment by Jaciezyt** [comment]
请提供日志，个例难以复现

**Comment by xnhjs233** [comment]
![2](https://user-images.githubusercontent.com/111108745/184302150-44672658-ab0c-48f3-8633-3844e86d3201.PNG)
![1](https://user-images.githubusercontent.com/111108745/184302162-b49c38bc-c2bc-48af-ac7e-06a25b6b8896.PNG)

**Comment by Jaciezyt** [comment]
重新运行PeEditor了吗

**Comment by xnhjs233** [comment]
试过了不行

**Comment by Jaciezyt** [comment]
> 试过了不行

pdb确保是最新版本的？

**Comment by xnhjs233** [comment]
pdb忘更新了
现在解决了
谢谢
