### ISSUE TITLE
Node引擎无法启动

### ISSUE THREAD

**Issue by Sbaoor-fly** [LiteLDev/LiteLoader#673]
### 异常模块

ScriptEngine（脚本引擎）

### 操作系统

Windows Server 2022

### LiteLoader版本

2.5.0

### BDS版本

1.9.20

### 发生了什么?

放入.llplugin文件，启动BDS
出现如下字样，但是插件并没有加载，plugin文件夹的.llplugin文件也不见了
``` bash
09:23:52 INFO [LiteLoader] 1 个 Node.js 插件包已安装。
09:23:52 INFO [LiteLoader] 0 个 Node.js 插件已加载。
```

附上测试用的文件
[Plugin.zip](https://github.com/LiteLDev/LiteLoaderBDS/files/9330534/MiraiMCBE.zip)

### 插件列表

```shell
09:26:52 INFO [Server] 插件列表 [4]
09:26:52 INFO [Server] - LLMoney [v2.5.0] (LLMoney.dll)
09:26:52 INFO [Server]   EconomyCore for LiteLoaderBDS
09:26:52 INFO [Server] - ScriptEngine-Lua [v2.5.0] (LiteLoader.Lua.dll)
09:26:52 INFO [Server]   Lua ScriptEngine for LiteLoaderBDS
09:26:52 INFO [Server] - ScriptEngine-QuickJs [v2.5.0] (LiteLoader.Js.dll)
09:26:52 INFO [Server]   Javascript ScriptEngine for LiteLoaderBDS
09:26:52 INFO [Server] - ScriptEngine-NodeJs [v2.5.0] (LiteLoader.NodeJs.dll)
09:26:52 INFO [Server]   Node.js ScriptEngine for LiteLoaderBDS
09:26:52 INFO [Server]
09:26:52 INFO [Server]
09:26:52 INFO [Server] * 使用命令“ll list <Plugin Name>”来获取更多信息
```

**Comment by yqs112358** [comment]
正常安装后LL确实会删除.llplugin插件包，因为插件已经被解压安装到`plugins/nodejs/插件名`了
至于无法加载是压缩路径错误问题，llplugin压缩包根目录必须直接是源码文件（和package.json），而不能套一到两层目录，如图
![image](https://user-images.githubusercontent.com/37969157/184463865-4deec619-32d8-410b-94ee-5f621fea4022.png)
这个是错误的

**Comment by Sbaoor-fly** [comment]
已解决
