### ISSUE TITLE
关闭表单不会触发回调

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#674]
### 异常模块

ScriptEngine（脚本引擎）

### 操作系统

Windows Server 2022

### LiteLoader版本

2.5.0

### BDS版本

1.19.20.02

### 发生了什么?

关闭表单不会触发回调

**Comment by KawaiiNahida** [comment]
@StarsDream00 在2.5.1中已修复，请耐心等待
