### ISSUE TITLE
内置PermissionAPI

### ISSUE THREAD

**Issue by Jaciezyt** [LiteLDev/LiteLoader#676]
### 您的建议是否与现存的某个问题相关?请描述问题?

PermissionAPI没人用

### 您认为还缺少什么?如何解决您的问题?

将 LiteLDev/PermissionAPI 像LLSE一样内置到LiteLoader，并提供API

**Comment by KawaiiNahida** [comment]
我拒绝，解耦是好文明，非基础api就让它独立着

**Comment by yqs112358** [comment]
源码不内置无所谓，但是需要像LLMoney一样附带进Release发布
因为一个没有太多人使用的插件接口，没法给其他插件作者带来适配的动力

若不是因为LLMoney由LL附带发布，以及在LLSE做了经济API，可想而知也不会有多少人去使用，而是都会各自自己造轮子
