### ISSUE TITLE
当表单Slider的min为负数时，传入def参数=0会导致滑块在min的位置，而不是0的位置

### ISSUE THREAD

**Issue by LittleSaya** [LiteLDev/LiteLoader#679]
### 异常模块

Core（核心）

### 操作系统

Windows 10

### LiteLoader版本

2.4.2

### BDS版本

1.19.10.03

### 发生了什么?

这是我用来向玩家发送表单的代码：

```c++
Form::CustomForm("form name")
    .addSlider("sliderA", "A", 1, 9, 2, valueA)
    .addSlider("sliderB", "B", 1, 9, 2, valueB)
    .addSlider("sliderC", "C", 1, 9, 1, valueC)
    .addSlider("sliderD", "D", -9, 9, 1, valueD)
    .sendTo(player, /* calback */);
```

当`valueD`为`0`时，玩家看见的`sliderD`停留在`-9`的位置上，当`valueD`为`1`时，`sliderD`停留在`1`的位置上。

传入`0`时（`yOffset`就是上面代码中的`sliderD`）：

<img width="459" alt="error" src="https://user-images.githubusercontent.com/16049823/184521400-048c322a-97f2-4028-90c8-aa7daf1cca25.png">

传入`1`时（`yOffset`就是上面代码中的`sliderD`）：

<img width="461" alt="error" src="https://user-images.githubusercontent.com/16049823/184521426-d283bdbb-a01b-4e36-8b90-d57ed635e665.png">

更新：参数def≤0的时候都会有这种滑块位置实际位于min，而不是位于def的现象。

**Comment by Jaciezyt** [comment]
@LittleSaya 尝试更新2.5.1+1.19.20?

**Comment by LittleSaya** [comment]
> @LittleSaya 尝试更新2.5.1+1.19.20?

~~更新以后加载插件失败，提示“The specified procudure could not be found”，我build之前更新了SDK文件夹里的repo，也删除了bedrock_server_api.lib和bedrock_server_var.lib，重新选择了1.19.20.02版本服务器的pdb文件又生成了一遍lib文件~~

好像先运行`LLPeEditor.exe`再选pdb文件就没问题了

**Comment by LittleSaya** [comment]
更新到 2.5.1 以后就没有这个问题了

**Comment by LittleSaya** [comment]
更新到 2.5.1 以后就没有这个问题了
