### ISSUE TITLE
LLSE重载插件后指令重新注册会导致注册报错

### ISSUE THREAD

**Issue by MengYang8481** [LiteLDev/LiteLoader#689]
### 异常模块

ScriptEngine（脚本引擎）

### 操作系统

Windows Server 2019

### LiteLoader版本

2.5.1

### BDS版本

1.19.20

### 发生了什么?

RT

### 复现此问题的步骤

![J89R2Z~}JMXGT7YKVWGW{$G](https://user-images.githubusercontent.com/23436744/184595696-8be12dc9-e123-402f-a22f-76c478fd4958.jpg)

**Comment by Jasonzyt** [comment]
无法解决

**Comment by Jaciezyt** [comment]
这个的话，#604 #643

**Comment by Jaciezyt** [comment]
尝试 https://github.com/LiteLDev/LiteLoaderBDS/commit/6ba648848c578c15b6a0d11999d284b320a631ce
应该不会报错了

**Comment by yqs112358** [comment]
更新到最新版LL即可解决此问题
