### ISSUE TITLE
llse在某些情况无法获取堆栈

### ISSUE THREAD

**Issue by MengYang8481** [LiteLDev/LiteLoader#690]
### 异常模块

ScriptEngine（脚本引擎）

### 操作系统

Windows Server 2019

### LiteLoader版本

2.5.1

### BDS版本

1.19.20

### 发生了什么?

lse在某些情况无法获取堆栈（像是图片上）
[failed to get stacktrace]
![8{9_V9}Y7PBT KFFII9_7XF](https://user-images.githubusercontent.com/23436744/184596032-912d741c-630a-41bb-8685-4f11826f3dc3.jpg)

**Comment by yqs112358** [comment]
C++ 层异常时可能确实脚本处有一定概率无法获得traceback，因为异常并不在脚本运行过程中发生。但是插件开发者可以通过发生错误的API名字来查找到实际发生错误的代码位置，这个问题不是很大

其次你截图的这个问题的话，是由于LL命令注册检查的bug导致的，在LL2.5.1更新中已修复（ https://github.com/LiteLDev/LiteLoaderBDS/commit/f37142dbd28c426a17bbee5462e2981698e1cd1f ）
更新到LL 2.5.1即可解决此问题
