### ISSUE TITLE
添加NodeJS插件的热重载功能

### ISSUE THREAD

**Issue by Hesitate-P** [LiteLDev/LiteLoader#694]
### 您的建议是否与现存的某个问题相关?请描述问题?

在开发NodeJS插件时无法便捷地调试插件
添加热重载功能会让调试NodeJS插件更加方便

### 您认为还缺少什么?如何解决您的问题?

RT，添加NodeJS插件的热重载功能

**Comment by KawaiiNahida** [comment]
Nodejs不同于纯v8，启动步骤稍有不同，且embedded文档较少，我们还需在进一步研究

**Comment by yqs112358** [comment]
已完成，等待2.6.0发布
