### ISSUE TITLE
pl.getScore接口问题

### ISSUE THREAD

**Issue by timiya233** [LiteLDev/LiteLoader#697]
### 异常模块

ScriptEngine（脚本引擎）

### 操作系统

Windows Server 2019

### LiteLoader版本

2.5.1

### BDS版本

1.19.20

### 发生了什么?

特定玩家无法使用 pl.getScore 获取计分板数值

### 复现此问题的步骤

mc.listen("onJoin", (pl)=>{
    log(pl.getScore("money"));//特定玩家触发
});

### 有关的日志/输出

```shell
13:06:34 ERROR [LiteLoader] C++ Uncaught Exception Detected!
13:06:34 ERROR [LiteLoader] Bad ScoreboardId
13:06:34 ERROR [LiteLoader] [failed to obtain stacktrace]
13:06:34 ERROR [LiteLoader] In API: PlayerClass::getScore
```

**Comment by Jaciezyt** [comment]
这个是因为获取不到对应玩家的`ScoreboardId`
