### ISSUE TITLE
全局变量意外的提示

### ISSUE THREAD

**Issue by ImYoyoData** [LiteLDev/LiteLoader#703]
### 异常模块

ScriptEngine（脚本引擎）

### 操作系统

Windows 11

### LiteLoader版本

2.5.1

### BDS版本

1.19.20

### 发生了什么?

全局变量 const 或者 var 等 定义的 在其它函数内调用
提示 Objective yoyo not found 
貌似它又成功调用了  但是会抛出这样的意外信息

### 复现此问题的步骤

![e34b9934-10a1-401c-9393-c30421f63ccd](https://user-images.githubusercontent.com/16756946/185014402-c79f7f39-0a84-4da9-af6b-b7868af364ed.jpg)

**Comment by Yushu2606** [comment]
你这图……

**Comment by Jaciezyt** [comment]
图片大概被压缩了，建议重新上传

**Comment by Jaciezyt** [comment]
这个是计分板的计分项未找到错误，与全局变量无关

**Comment by ImYoyoData** [comment]
ok
