### ISSUE TITLE
quickJs插件内，Date不能从字符串中解析时间

### ISSUE THREAD

**Issue by OEOTYAN** [LiteLDev/LiteLoader#708]
### 异常模块

ScriptEngine（脚本引擎）

### 操作系统

Windows 11

### LiteLoader版本

2.5.1

### BDS版本

1.19.20

### 发生了什么?

![image_2022-08-18_15-10-53](https://user-images.githubusercontent.com/58554322/185340336-74d5baf3-f4f0-4f6e-b35d-1fc2b7e283b9.png)
![image](https://user-images.githubusercontent.com/58554322/185340507-db5c069c-f830-4064-a6ac-b702aa4b0b10.png)

从字符串new一个date对象，或者parse一个date字符串，都解析出NaN，在1.19.10不会出现此情况。

### 复现此问题的步骤

从字符串new一个date对象，或者parse一个date字符串。

**Comment by yqs112358** [comment]
哈哈，解析字符串的格式不对，这个是有标准格式的
详见MDN文档 https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date

举例：
![image](https://user-images.githubusercontent.com/37969157/186820521-6fe7e816-4dba-4332-8bbd-f1ab802bab51.png)

**Comment by yqs112358** [comment]
![image](https://user-images.githubusercontent.com/37969157/186820655-1afa5659-d1b1-49a1-be7b-ac056a29c864.png)

**Comment by yqs112358** [comment]
我看一下能不能改他那个算法，他那玩意挺复杂的，如果改不了就只能这样了

**Comment by yqs112358** [comment]
![image](https://user-images.githubusercontent.com/37969157/186837341-0279a42b-e046-453d-a17f-986b165094a8.png)
目测没问题了
