### ISSUE TITLE
在Dev模式下捕获SEH异常时将异常重新抛出

### ISSUE THREAD

**Issue by Redbeanw44602** [LiteLDev/LiteLoader#709]
### 您的建议是否与现存的某个问题相关?请描述问题?

现在，程序引发SEH异常时会直接被捕获，调试器都抓不到，实属不方便。

### 您认为还缺少什么?如何解决您的问题?

如题，便于调试

**Comment by Jasonzyt** [comment]
给所有catch加个宏就好了

**Comment by Redbeanw44602** [comment]
现在所有用到SEH的地方好像又有宏了吧，直接在宏里面加就行了

**Comment by yqs112358** [comment]
> 现在所有用到SEH的地方好像又有宏了吧，直接在宏里面加就行了

确实，这样最好，尽量改宏
