### ISSUE TITLE
FormID prints uuid not int ( over LiteLoaderBDS 2.5.0+ )

### ISSUE THREAD

**Issue by mandong1240** [LiteLDev/LiteLoader#710]
### Exceptions module

Core

### Operating System

Windows 10

### LiteLoader version

2.5.1

### BDS version

1.19.20

### What happened?

When I output onSelectForm from BDSpyrunner.dll, the character that was previously output in int format is output as uuid. I thought this was a BDSpyrunner.dll problem, but after many trials and errors, I think it was a LiteLoader.dll problem. This problem has occurred since 1.19.20 (LiteLoaderBDS 2.5.0 and above) and is very fatal to me. Please change the form of Form ID exactly like 1.19.11.

**Comment by ShrBox** [comment]
In the latest LiteLoaderBDS, `mFormId` is still unsigned int
![image](https://user-images.githubusercontent.com/53301243/185381210-b1870994-28cf-4a0c-a0a0-3269e43c7eae.png)
