### ISSUE TITLE
node.js 修改控制台

### ISSUE THREAD

**Issue by ImYoyoData** [LiteLDev/LiteLoader#713]
### 异常模块

ScriptEngine（脚本引擎）

### 操作系统

Windows 11

### LiteLoader版本

2.5.1

### BDS版本

1.19.20

### 发生了什么?

。。。就是用 node.js 监听控制台 data 会出现问题

**Comment by yqs112358** [comment]
请具体描述此问题，给出复现代码，否则无法进行检查
