### ISSUE TITLE
LLSE中运行命令tp facing朝向有一定偏差

### ISSUE THREAD

**Issue by Soirks** [LiteLDev/LiteLoader#715]
### 异常模块

ScriptEngine（脚本引擎）

### 操作系统

Windows Server 2016

### LiteLoader版本

2.5.1

### BDS版本

1.19.20

### 发生了什么?

**如视频所示，当直接runcmd运行tp后朝向斜上方，而将相同的命令直接输入控制台后，则视角垂直向上。**
http://159.75.112.131:8080/down/NxMi7YvWy5VI

### 复现此问题的步骤

mc.regPlayerCmd("/test","test",()=>{
    let pl=mc.getPlayer("Soirks")
    let x=pl.pos.x
    let y=pl.pos.y;
    let z=pl.pos.z
    mc.runcmd("tp "+pl.name+" "+x+" "+y+" "+z+" facing "+x+" "+(y+10)+" "+z+" true")
    log("tp "+pl.name+" "+x+" "+y+" "+z+" facing "+x+" "+(y+10)+" "+z+" true")
})

### 插件列表

```shell
仅测试插件一个
```

**Comment by KawaiiNahida** [comment]
runcmd问题为mc自身问题，请自行解决
另llse有传送相关api

**Comment by Soirks** [comment]
llse提供的teleport中并没有调整朝向的参数，我看看玩家nbt中有没有相关的办法吧

**Comment by dreamguxiang** [comment]
2.8.0已修复
#859
