### ISSUE TITLE
LL 計分板"ob"

### ISSUE THREAD

**Issue by omscsamilcup** [LiteLDev/LiteLoader#742]
### 异常模块

ScriptEngine（脚本引擎）

### 操作系统

Windows 10

### LiteLoader版本

2.5.1

### BDS版本

1.19.20

### 发生了什么?

我在插件使用"ob"(計分板變數)
但是卻沒有任何的用途

### 复现此问题的步骤

我使用
function money() {
    let ob = mc.getScoreObjective("money")
    ob.getScore(en.name, 1)
    return ob
}
mc.listen('onPlayerDie', (pl, source) {
    let en = source
    money
})
但是卻沒有任何用途
不會加計分板的分數

### 有关的日志/输出

```shell
沒有顯示任何的日志/輸出
```

**Comment by yqs112358** [comment]
你的Js代碼邏輯存在較大問題，請先把語法學完並且使用熟練~
