### ISSUE TITLE
迁移编译流程到 cmake

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LiteLoader#756]
RT，由于移除了VS项目，因此需要将编译流程迁移到cmakelist，同时简化一些为了兼容VS而制作的机制

- [x] 移除x64目录，删除重设LIBRARY_OUTPUT_PATH以及TARGET_DIR，将生成位置统一到默认的build目录（行业规范）
- [x] 编写cmake代码，在生成前先submodule下载所有依赖，然后调用LibraryBuilder生成必要lib
- [x] 编写cmake代码，将编译成品直接复制到RELEASE，debug模式自动一同复制PDB过去，release模式则不复制PDB
- [x] 删除PackRelease脚本（或者仅保留打包zip功能，删去产物复制）
- [x] 修改上述所有相关的gitignore

**Comment by RimuruChan** [comment]
我的建议是打包啊什么的还是放脚本，合并到CMake编译流程内没必要
可以写一个类似build.sh的编译脚本来完成工作调度

**Comment by yqs112358** [comment]
> 我的建议是打包啊什么的还是放脚本，合并到CMake编译流程内没必要 可以写一个类似build.sh的编译脚本来完成工作调度

也行的，我改一下，让cmake直接调用脚本就行

**Comment by yqs112358** [comment]
> 我的建议是打包啊什么的还是放脚本，合并到CMake编译流程内没必要 可以写一个类似build.sh的编译脚本来完成工作调度

其实写在cmakelist里面的本意是方便修改要复制的产物，现在那个PackRelease经常因为忘记改而出问题（上个版本刚撤包过），所以写在cmakelist里面的话，改cmakelist的时候就会顺便想到改
有无更好的设计想法

**Comment by yqs112358** [comment]
当时使用脚本是因为VS的生成前、生成后事件只能跑命令，因此只能用脚本处理；到cmake这里可以在项目源码里面直接写逻辑了，因此脚本的存在目前看来已经意义不大
况且因为现在整个编译流程都完全依赖cmake的话，也不会有手动跑脚本的需求了。无脑点击生成即可

**Comment by RimuruChan** [comment]
CMake 要实现实际上也是跑命令吧

**Comment by yqs112358** [comment]
> CMake 要实现实际上也是跑命令吧

是的，但是在cmakelist里面写命令有助于改构建的时候一起改命令，不至于忘记
况且也可以用某些构建参数简化命令的编写

**Comment by yqs112358** [comment]
比如，在LL的cmakelist里面写产物复制就只写LL的产物，把LLSE的产物写到LLSE的cmakelist里面去，这样分开也有助于维护和理解
