### ISSUE TITLE
I cant use player.lastDeathPos

### ISSUE THREAD

**Issue by BuslnwTH** [LiteLDev/LiteLoader#759]
### Exceptions module

ScriptEngine

### Operating System

Windows Server 2022

### LiteLoader version

2.6.2

### BDS version

1.19.22.01

### What happened?

i dont get data for player.lastDeathPos return data undefined(NULL)

```
mc.listen("onJoin", function(player){
    log(player.lastDeathPos)
}
```

**Comment by ghost** [comment]
**It works correctly.** The player has just entered, there is no data on the position of the last death.

**Comment by BuslnwTH** [comment]
Old player(with death) joined. no position lastdeathPos value?

**Comment by ghost** [comment]
> Old player(with death) rejoined. no position lastdeathPos value?

When you exit the server, the data on the position of the last death is erased.

**Comment by BuslnwTH** [comment]
I understand Thanks.

**Comment by Jaciezyt** [comment]
@shishkevichd Thanks for reply!
