### ISSUE TITLE
Workflow `CMake` not working.

### ISSUE THREAD

**Issue by ghost** [LiteLDev/LiteLoader#761]
### Exceptions module

Core

### Operating System

Windows Server 2022

### LiteLoader version

2.6.2

### BDS version

None

### What happened?

In the latest commits in the beta branch, `PackRelease.cmd` was changed to `CopyRelease.cmd`, in the `CMake (self-hosted)` workflow it was changed, and in the `CMake` workflow they forgot to change it.
As a result, the project is not building.

### Steps to reproduce?

1. Run `CMake` workflow across Github Actions

### Relevant log output

```shell
cd Scripts
./PackRelease.cmd action
'.' is not recognized as an internal or external command, operable program or batch file.
```

**Comment by Jaciezyt** [comment]
Fixed in 423efcd
