### ISSUE TITLE
Add setDisplayName() to Item Object Interface

### ISSUE THREAD

**Issue by Colton1070** [LiteLDev/LiteLoader#764]
### Is your feature request related to a problem? Please describe.

Currently, Items don't have a method for changing their display name. We can change their Lore using `it.setLore()`, but the only way to modify an item's display name, is by using NBT. I am utilizing LLSE JS.

### Describe the solution you'd like

Add a new method to the Item Object. perhaps called "setDisplayName(String)" which accepts a String parameter. This set's the Item's Display Name and allows for the use of Formatted Colors.

**Comment by Jaciezyt** [comment]
Fixed in PR #766
