### ISSUE TITLE
增加玩家打开背包时触发的事件

### ISSUE THREAD

**Issue by futrime** [LiteLDev/LiteLoader#767]
### 您认为还缺少什么?如何解决您的问题?

希望能够在玩家打开背包时触发事件，而不是在打开任何容器或任何容器GUI时触发

**Comment by Jaciezyt** [comment]
Maybe `?openInventory@ServerPlayer@@UEAAXXZ`

**Comment by LazuliKao** [comment]
> Maybe `?openInventory@ServerPlayer@@UEAAXXZ`

已测试过，该符号可用，且可以拦截，大佬们放心添加

**Comment by Jaciezyt** [comment]
Fixed in af8514584
