### ISSUE TITLE
添加获取一定范围的实体的API

### ISSUE THREAD

**Issue by futrime** [LiteLDev/LiteLoader#768]
### 您认为还缺少什么?如何解决您的问题?

需要一个获取一个长方体、或一个圆柱体、或一个球、或一个半球体内所有实体的API，建议在Level实现，并命名为getEntitesInABall、getEntitiesInACylinder、getEntitesInACuboid、等

**Comment by Redbeanw44602** [comment]
994b35cf258964a6bf22e07a937a56244fb880db
