### ISSUE TITLE
my DBS server is 1.19.22.01，when l install LLB2.6.2,l cant join the world

### ISSUE THREAD

**Issue by zhouchengji** [LiteLDev/LiteLoader#771]
my DBS server is 1.19.22.01，when l install LLB2.6.2,l cant join the world. And l reset the DBS,it is also wrong.

**Comment by quizhizhe** [comment]
> my DBS server is 1.19.22.01，when l install LLB2.6.2,l cant join the world. And l reset the DBS,it is also wrong.

截图发一下看看

**Comment by Yushu2606** [comment]
IT IS **BDS** NOT **DBS**

**Comment by ShrBox** [comment]
Please use template to create an issue and describe it in detail
