### ISSUE TITLE
增加玩家尝试进行一些操作时触发的事件

### ISSUE THREAD

**Issue by futrime** [LiteLDev/LiteLoader#784]
### 您的建议是否与现存的某个问题相关?请描述问题?

目前没有监听玩家尝试各种操作时触发的事件。

### 您认为还缺少什么?如何解决您的问题?

需要PlayerAttackEvent、PlayerUseEvent、PlayerAttemptToDropItemEvent（这个事件需要在手中没有物品时也能触发）

以上事件应当可以拦截，且触发顺序最好先于其它相关事件。

**Comment by yqs112358** [comment]
LiteLDev/ScriptEngine#16 
LiteLDev/LeviLamina#566

**Comment by Redbeanw44602** [comment]
前两个事件没有吗

**Comment by dreamguxiang** [comment]
> 事件需要在手中没有物品

无物品触发
