### ISSUE TITLE
规范插件行为、插件系统目录结构等架构性原则

### ISSUE THREAD

**Issue by futrime** [LiteLDev/LiteLoader#788]
### 您的建议是否与现存的某个问题相关?请描述问题?

目前没有给出插件行为规范，导致各种插件使用了不同的路径存放相关文件，产生了潜在的冲突问题。
同时，LiteLoaderBDS本身也不够规范，在plugins目录内存在lib、nodejs等文件夹。

### 您认为还缺少什么?如何解决您的问题?

在开发文档内给出一个指导性的规范，并提供相关API接口，例如配置文件写入接口、插件目录获取接口、数据库接口、日志输出接口等。
另外，针对每种语言插件规定lip包结构和依赖处理机制，完成插件设计模板，保证ll3可以正常加载并运行插件、拉取依赖

**Comment by RimuruChan** [comment]
> 另外需要规范到底用LiteLoader还是LiteLoaderBDS。

LiteLoaderBDS是项目名
LiteLoader是隶属于LLBDS的组件（main）

**Comment by RimuruChan** [comment]
plugins
  - name
    - config
    - data
    - name.dll
    - manifest.json
