### ISSUE TITLE
PlayerClass::getScore Error

### ISSUE THREAD

**Issue by ImYoyoData** [LiteLDev/LiteLoader#791]
### 异常模块

ScriptEngine（脚本引擎）

### 操作系统

Windows 11

### LiteLoader版本

2.6.2

### BDS版本

1.19.22

### 发生了什么?

![image](https://user-images.githubusercontent.com/16756946/189810751-18966685-b89f-4b25-98e8-2248f2d519e5.png)
我已创建该计分项,但是api任然获取不了 提示报错

### 有关的日志/输出

```shell
ERROR [LiteLoader] [failed to obtain stacktrace]
12:47:07 ERROR [LiteLoader] In API: PlayerClass::getScore
12:47:07 ERROR [LiteLoader] In Plugin: BetterSidebar
12:47:08 ERROR [LiteLoader] C++ Uncaught Exception Detected!
12:47:08 ERROR [LiteLoader] Bad ScoreboardId
```

### 插件列表

```shell
12:48:51 INFO [Server] - BetterSidebar [v1.0.0] (BetterSidebar.lxl.js)
```

**Comment by quizhizhe** [comment]
@ImYoyoData 截图看一下getScore部分

**Comment by xialiag** [comment]
是#636的原因吧

**Comment by Redbeanw44602** [comment]
fixed in 2f6ed48d5f2813ebdc5be7f79a780649b02c6d22
