### ISSUE TITLE
Migrate to historic versions of BDS

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LiteLoader#796]
### Discussed in https://github.com/LiteLDev/LiteLoaderBDS/discussions/795

<div type='discussions-op-text'>

<sup>Originally posted by **gentlegiantJGC** August 10, 2022</sup>
### Is your feature request related to a problem? Please describe.

It this supposed to work with historic versions of the Bedrock server?
I am trying to use this to export information from the server (block, biome, ...).
It works correctly with the new version of the server but the old versions give errors when loading the server.

Creating bedrock_server_mod.exe works correctly and I can compile the plugin using the 1.9 pdb file but I get errors that symbols cannot be found when running bedrock_server_mod.exe

Do I need to generate an old version of the [SDK](https://github.com/LiteLDev/LiteLoaderSDK) or compile other code against the old version. If so how do I do that?
![image](https://user-images.githubusercontent.com/11940194/183909509-b05756a3-78eb-4d84-92cd-220b8658f616.png)

### Describe the solution you'd like

I would like to use this for every version since debug symbols were included.</div>

**Comment by gentlegiantJGC** [comment]
I can understand not wanting to officially support historic versions with the higher level API but I believe the tools are there to expose the lower level API of past versions.
