### ISSUE TITLE
Wine中无法在同一用户下多开

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#798]
### 异常模块

Core（核心）

### 操作系统

GNU/Linux with wine

### LiteLoader版本

2.6.2 Actions#90 fe044ca

### BDS版本

1.19.22.01

### 发生了什么?

无法在同一用户下多开
Wine 7.17+Kernel 5.19.8

### 复现此问题的步骤

同时启动两个服务器
一个正常启动，另一个会卡死

### 有关的日志/输出

```log
0590:err:seh:NtRaiseException Unhandled exception code c0000409 flags 1 addr 0x235e2bd
```
![image](https://user-images.githubusercontent.com/100036558/190044360-e00e59a5-3ac0-45c8-ab2c-811478e67cc3.png)

**Comment by KawaiiNahida** [comment]
无足够backtrack信息，无法定位错误
