### ISSUE TITLE
添加插件实例等现代OOP设计

### ISSUE THREAD

**Issue by RimuruChan** [LiteLDev/LiteLoader#799]
### 您的建议是否与现存的某个问题相关?请描述问题?

当前对于插件相关规范困难，插件活动生命周期管理困难。

### 您认为还缺少什么?如何解决您的问题?

通过创建标准化插件实例，可以促进规范应用且提供更OOP的接口。
添加OOP后可以聚焦信息且更好的管理插件等等
此功能还需要进一步设计

另外现有API比较散乱，需要有新的相关设计
实现时需要注意采用PImpl等相关设计规避ABI变动问题。

**Comment by futrime** [comment]
@RimuruChan PluginTemplate和Tutorials已经有了
