### ISSUE TITLE
Consider using Ninja to build

### ISSUE THREAD

**Issue by RimuruChan** [LiteLDev/LiteLoader#807]

**Comment by ShrBox** [comment]
It will take more time when using Ninja to compile LL in our servers

**Comment by RimuruChan** [comment]
> It will take more time when using Ninja to compile LL in our servers

## Result tested on my PC

### Vs Generator
7 mins.

### Ninja
6 mins.

**Comment by RimuruChan** [comment]
> It will take more time when using Ninja to compile LL in our servers

And ninja's behavior is more standard in cmake

**Comment by Jaciezyt** [comment]
> > It will take more time when using Ninja to compile LL in our servers
> 
> 
> 
> ## Result tested on my PC
> 
> 
> 
> ### Vs Generator
> 
> 7 mins.
> 
> 
> 
> ### Ninja
> 
> 6 mins.

不管怎样反正在Actions的速度比VS慢（（
