### ISSUE TITLE
MobHurtEvent not changing damage.

### ISSUE THREAD

**Issue by ghost** [LiteLDev/LiteLoader#812]
### Exceptions module

Core

### Operating System

Windows 11

### LiteLoader version

https://github.com/LiteLDev/LiteLoaderBDS/releases/tag/2.6.2

### BDS version

1.19.22

### What happened?

MobDamageEvent not changing damage to the player.
https://youtu.be/CO1v3UYMDmc
Same with PlayerAttackEvent

### Steps to reproduce?

1. Write a simple plugin that changes `mDamage` on `Event::MobHurtEvent` ![kartina](https://user-images.githubusercontent.com/60012371/190949552-36e44277-979c-44de-85d8-ec9758a14019.png)
2. Build
3. Test on player.

### Relevant log output

```shell
None.
```

### Plugin list

```shell
None.
```

**Comment by futrime** [comment]
@hausemaster3734 You should use a reference to the event object

**Comment by RimuruChan** [comment]
Use `MobHurtEvent& event` to avoid copy.
