### ISSUE TITLE
onMobHurt事件中en.hurt伤害丢失问题

### ISSUE THREAD

**Issue by FBQingYi** [LiteLDev/LiteLoader#817]
### 异常模块

ScriptEngine（脚本引擎）

### 操作系统

Windows 10

### LiteLoader版本

2.6.2

### BDS版本

1.19.22.01

### 发生了什么?

onMobHurt事件中，不延时调用en.hurt(damage,type)这个接口会导致某次伤害丢失
![image](https://user-images.githubusercontent.com/82281127/191215819-9bbeb234-873a-449b-8465-7d13b977295b.png)
![image](https://user-images.githubusercontent.com/82281127/191215963-8483b830-4700-4412-ab97-fac8dc8b7afa.png)
使用setTimeout延时至500毫秒后执行正常。
![image](https://user-images.githubusercontent.com/82281127/191216363-bf98c945-ca43-4d44-ba34-0b8ba85c37fe.png)
![image](https://user-images.githubusercontent.com/82281127/191216278-bbb48a23-da59-48ae-9f13-96c751cf9523.png)

**Comment by ShrBox** [comment]
Minecraft的限制，不能在同一游戏刻里受到两次伤害
