### ISSUE TITLE
ll 2.7.0 colorlog输出异常（非操作系统低）

### ISSUE THREAD

**Issue by ghost** [LiteLDev/LiteLoader#824]
### 异常模块

Core（核心）

### 操作系统

Windows 10

### LiteLoader版本

2.7.0 release

### BDS版本

1.19.30.04

### 发生了什么?

![image](https://user-images.githubusercontent.com/69241946/191661152-03ac8397-53f5-49e2-bf0a-b769cd12207f.png)

如图，ll前半部分colorlog有问题，后半部分正常

### 复现此问题的步骤

运行bedrock_server_mod.exe

### 有关的日志/输出

```shell
如上图
```

**Comment by RimuruChan** [comment]
Fixed in e2bb8003878560dfb247c6dcc6ad4051eab91307
