### ISSUE TITLE
Not starting on Linux with Wine

### ISSUE THREAD

**Issue by ghost** [LiteLDev/LiteLoader#83]
**Describe the bug**
- Not starting server.

**To Reproduce**
Start LiteLoader with Wine

**Expected behavior**
- None

**Screenshots or log**
- I pinned ![Screenshot_20211108_095945](https://user-images.githubusercontent.com/60012371/140686698-f3b3e8da-2b30-43c2-8d30-f648a26cccf6.png)
e

**Environment (please complete the following information):**
- OS: Ubuntu 20.

**Additional context**
- Non

**Comment by mikhaillav** [comment]
It problem on windows too, try install LL one more time. Also u can use LL-loader(https://github.com/Development-studio/LL-Loader)

**Comment by ghost** [comment]
> It problem on windows too, try install LL one more time. Also u can use LL-loader(https://github.com/Development-studio/LL-Loader)

Та же проблема, очень странно...
Я установил llbds с помощью вашего скрипта.

**Comment by ShrBox** [comment]
How much RAM does your server have?

Run `ls -lh` to view the size of `bedrock_server.symdb2`

**Comment by ghost** [comment]
> How much RAM does your server have?
> 
> Run `ls -lh` to view the size of `bedrock_server.symdb2`

Thanks for help. Problem was solved.

**Comment by KawaiiNahida** [comment]
Fixed in [0cd08b75](https://github.com/LiteLDev/LiteLoaderBDS/commit/0cd08b7559c5a42d06a21e9b24fdfc9238ee10d9)
