### ISSUE TITLE
与玩家有关的物品对象问题

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#834]
### 异常模块

ScriptEngine（脚本引擎）

### 发生了什么?

`pl.giveItem`一次只能给予64个物品，超出会被忽略
`pl.clearItems`只能将有关物品全部清除

**Comment by dreamguxiang** [comment]
@StarsDream00 unsigned __int8

**Comment by StarsDream00** [comment]
> @StarsDream00 unsigned __int8

虽然但是，文档内并没有标识出来
或者LLSE做些处理适配下int

**Comment by StarsDream00** [comment]
need reopen

**Comment by Redbeanw44602** [comment]
新加了一个可选参数

`pl.giveItem(item[, amount])` 如果提供amount参数，原本itemstack的count属性会被忽略。

至于`mc.newItem`，我感觉没有必要，且会造成breaking changes

**Comment by StarsDream00** [comment]
> 新加了一个可选参数
> 
> `pl.giveItem(item[, amount])` 如果提供amount参数，原本itemstack的count属性会被忽略。
> 
> 至于`mc.newItem`，我感觉没有必要，且会造成breaking changes

既然如此，也给容器对象整一下？

**Comment by Redbeanw44602** [comment]
现在容器对象的 addItem 会先检查容器空间是否足够的....

emm本来给这个加amount参数就是考虑到原版give指令会在空间不够时drop，容器的感觉还是不太一样，加的话还是有些奇怪的。

**Comment by StarsDream00** [comment]
> 现在容器对象的 addItem 会先检查容器空间是否足够的....
> 
> emm本来给这个加amount参数就是考虑到原版give指令会在空间不够时drop，容器的感觉还是不太一样，加的话还是有些奇怪的。

`hasRoomFor`呢？

**Comment by Redbeanw44602** [comment]
没有必要，Conatiner的addItem会先调用hasRoomFor检查的（所以没必要先检查一次）如果里面hasRoomFor失败会直接返回false

**Comment by StarsDream00** [comment]
> 没有必要，Conatiner的addItem会先调用hasRoomFor检查的（所以没必要先检查一次）如果里面hasRoomFor失败会直接返回false

？？？

**Comment by StarsDream00** [comment]
newItem只能创建[0,256)个物品，那怎么判断能否放下>255个物品？

**Comment by StarsDream00** [comment]
`mc.newItem`只能创建[0,256)个物品，`pl.giveItem`能给任意（理论）多个物品，那`hasRoomFor`怎么判断能否放下>255个物品？或者把容器与玩家的`hasRoomFor`分开？

**Comment by Redbeanw44602** [comment]
确实应该加一下，我晚点做

**Comment by StarsDream00** [comment]
need reopen

**Comment by StarsDream00** [comment]
还有`pl.clearItems`只能将有关物品全部清除，最好像`/clear`命令那样加个数量参数🤔
