### ISSUE TITLE
LLSE比较物品的API

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#836]
### 您的建议是否与现存的某个问题相关?请描述问题?

目前比较两个对象很麻烦，例如物品要比较类型、特殊值、附魔、NBT等

### 您认为还缺少什么?如何解决您的问题?

例如`item1 == item2`这样判断类型是否完全相同的对象的操作符

**Comment by Redbeanw44602** [comment]
这个在哪能用到啊

**Comment by Yushu2606** [comment]
> 这个在哪能用到啊

统计物品数量和只清除同类物品

**Comment by wzyyyyyyy** [comment]
@StarsDream00 建议直接对比nbt

**Comment by Yushu2606** [comment]
> @StarsDream00 建议直接对比nbt

想忽略数量，但是要生成新nbt对象太浪费性能

**Comment by wzyyyyyyy** [comment]
@StarsDream00 过于复杂的东西建议用cpp写 性能高还可以用bds自己的附魔类等

**Comment by Redbeanw44602** [comment]
看看掉落物合并？ItemActor::tick

**Comment by Yushu2606** [comment]
> @StarsDream00 过于复杂的东西建议用cpp写 性能高还可以用bds自己的附魔类等

但凡cpp好用点吧😭
不想被虚空bug折磨

**Comment by wzyyyyyyy** [comment]
@StarsDream00 哈哈 被调教好了就跟用ios一样顺畅(雾

**Comment by RimuruChan** [comment]
@StarsDream00 cpp好不好用得看你会不会用😂

**Comment by Yushu2606** [comment]
> @StarsDream00 cpp好不好用得看你会不会用😂

上次有个虚空bug搞了半天没整好，保错也没多少有用信息，到头来发现是包含目录的锅（恼）
用惯了csharp再回头看cpp的头文件就已经完全受不了了😵‍💫

**Comment by Redbeanw44602** [comment]
你可以用这个 `bool ItemStackBase::matchesItem(class ItemStackBase const & __ptr64)`

**Comment by Redbeanw44602** [comment]
![2](https://user-images.githubusercontent.com/29711228/192107884-9feaf1d7-dc7d-48f1-85c5-70b67c220a81.png)
本来就有啊，，下次麻烦自己先找下

**Comment by Yushu2606** [comment]
> ![2](https://user-images.githubusercontent.com/29711228/192107884-9feaf1d7-dc7d-48f1-85c5-70b67c220a81.png)
> 
> 本来就有啊，，下次麻烦自己先找下

LLSE？

**Comment by Redbeanw44602** [comment]
llse先用symcall调用吧

**Comment by Yushu2606** [comment]
话说`bool ItemStackBase::matchesItem(class ItemStackBase const & __ptr64)`与
![](https://user-images.githubusercontent.com/29711228/192107884-9feaf1d7-dc7d-48f1-85c5-70b67c220a81.png)
是相同的实现吗

**Comment by Redbeanw44602** [comment]
是的

**Comment by Yushu2606** [comment]
> 是的

用==操作符试了下，还不能判断同类物品
