### ISSUE TITLE
同名不同后缀的两个插件无法同时加载

### ISSUE THREAD

**Issue by chfwd** [LiteLDev/LiteLoader#849]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.7.2

### BDS 版本

1.19.30.04

### 发生了什么?

加载插件时，如果存在了与插件同名但不同后缀的插件，则只加载第一个同名插件

### 复现此问题的步骤

1.装载一个名为a.dll的插件
2.装载一个名为a.js的插件
3.开启服务器
4.加载插件
5.输入ll list发现a.js并未加载

**Comment by Yushu2606** [comment]
#510

**Comment by Redbeanw44602** [comment]
![image](https://user-images.githubusercontent.com/29711228/212554419-1c59a46f-0641-440b-b8bc-094b084b2f53.png)
无法复现

**Comment by chfwd** [comment]
LL2.9.1复现成功
![IMG_20230116_135536](https://user-images.githubusercontent.com/52685084/212612070-e5dc66b6-d878-4ade-a603-ddc4cd0f8068.jpg)
ChainMiner.js
![IMG_20230116_142623](https://user-images.githubusercontent.com/52685084/212612101-bc2f2074-1a2b-4b6d-acc1-a07572693439.jpg)
[ChainMiner.dll](https://github.com/HJH201314/ChainMiner/releases/download/v0.2.5.7/ChainMiner.dll)

**Comment by Redbeanw44602** [comment]
使用最新的actions再试一下？https://github.com/LiteLDev/LiteLoaderBDS/actions/runs/3927027240

**Comment by chfwd** [comment]
还是不行
![IMG_20230116_155121.jpg](https://user-images.githubusercontent.com/52685084/212625165-b1909f10-17eb-4ca0-b026-dcb588d26ada.jpg)

**Comment by Yushu2606** [comment]
> ![image](https://user-images.githubusercontent.com/29711228/212554419-1c59a46f-0641-440b-b8bc-094b084b2f53.png)
> 
> 无法复现

可能是因为注册名不同
