### ISSUE TITLE
LLSE中.giveItem的相关问题

### ISSUE THREAD

**Issue by FBQingYi** [LiteLDev/LiteLoader#850]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows 10

### LiteLoader 版本

2.7.2

### BDS 版本

1.19.30

### 发生了什么?

.giveItem API会重置修改后的nbt，经过测试，同一个nbt生成的同一个物品对象，.giveItem会变成原版nbt。而使用mc.spawnItem生成掉落物一切正常！

### 复现此问题的步骤

1，修改一个物品nbt并用它生成一个新的物品对象。
2，使用pl.giveItem给予玩家这个物品。
3，获取打印给予玩家的这个物品nbt。

![屏幕截图 2022-10-01 201452](https://user-images.githubusercontent.com/82281127/193409337-80c402ec-4a63-494f-9679-968db9a4fabe.png)
![屏幕截图 2022-10-01 201532](https://user-images.githubusercontent.com/82281127/193409340-aa4c57be-dd75-459f-80e8-a48430e74a55.png)

**Comment by Redbeanw44602** [comment]
7271a9c069228c9cdce42bd37cf1263f3545f61c 可以试下最新的actions。
