### ISSUE TITLE
NodeJS插件无法使用mc.runcmdEx重载自身

### ISSUE THREAD

**Issue by timiya233** [LiteLDev/LiteLoader#854]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows 10

### LiteLoader 版本

2.7.2

### BDS 版本

1.19.30

### 发生了什么?

NodeJs 插件Test.js
(已用ll.registerPlugin注册名称为文件名：Test.js)
通过mc.runcmdEx执行/ll reload Test.js
无法正常重载插件

### 有关的日志/输出

```raw
13:39:40 INFO [LiteLoader] NodeJs plugin Test.js exited.
13:39:41 INFO [LiteLoader] Test.js unloaded.
13:39:41 ERROR [LiteLoader] Fail to load plugins\nodejs\Test!
13:39:41 ERROR [LiteLoader] create V8Engine with an existing EngineScope
13:39:41 INFO [LiteLoader] NodeJs plugin Test.js exited.
```

### 插件列表

```raw
无关
```

**Comment by timiya233** [comment]
![image](https://user-images.githubusercontent.com/70333491/193743823-0906955a-5aab-4825-9ce2-9aa66bec6139.png)
![image](https://user-images.githubusercontent.com/70333491/193743968-d62254f4-409e-42ea-bc0c-ad03bf43aa1b.png)

**Comment by shishkevichd** [comment]
Node.js plugins are automatically registered. `ll.registerPlugin` is needed for QuickJS or Lua plugins
