### ISSUE TITLE
PlayerInfo行为异常

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#856]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows Server 2022

### LiteLoader 版本

2.7.2-dev.0+32957b3

### BDS 版本

1.19.31.01

### 发生了什么?

每次启动时都会提示`Converting old PlayerInfo to new one, please wait.`
实测PlayerInfo是空的

### 复现此问题的步骤

启动服务器

### 有关的日志/输出

```raw
Converting old PlayerInfo to new one, please wait.
```

**Comment by ShrBox** [comment]
有问题的PlayerDB.db可否发一份

**Comment by StarsDream00** [comment]
> 有问题的PlayerDB.db可否发一份

见Telegram

**Comment by ShrBox** [comment]
使用最新的dev版本或对你的PlayerDB.db执行以下命令
**执行前请备份数据**
```sqlite
DELETE FROM player WHERE name IN (SELECT name FROM player GROUP BY xuid HAVING COUNT(*)>1);
```
