### ISSUE TITLE
runcmdEx不适配新版/structure load指令

### ISSUE THREAD

**Issue by superx101** [LiteLDev/LiteLoader#858]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows 10

### LiteLoader 版本

2.7.2

### BDS 版本

1.19.31.01

### 发生了什么?

使用mc.runcmdEx执行新版structure load时, 无法识别新参数 **[waterlogged: Boolean]**
当执行命令
`/structure load "test" 0 100 0 0_degrees none false true false 100`
output输出如下
 `Syntax error: Unexpected "false": at "alse true >>false<< 100"`

**Comment by Jaciezyt** [comment]
#553

**Comment by dreamguxiang** [comment]
已修复
#859

**Comment by Jaciezyt** [comment]
Duplicate of #553
