### ISSUE TITLE
LLSE 命令注册 API 目标选择器ParamType.Player&ParamType.Actor导致选择器条件失效

### ISSUE THREAD

**Issue by Doren12345** [LiteLDev/LiteLoader#870]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows 10

### LiteLoader 版本

2.7.2

### BDS 版本

1.19.31.01

### 发生了什么?

只要創建一個真命令，並且mandatory的ParamType是Player類別時，所有原版的目標選擇器就會沒用
例如@a[tag=test] 就會出現 語法錯誤: @a>>[<<tag=test]
`   cmd.mandatory("player", ParamType.Player) ` 只要真命令註冊中有這種ParamType.Player就會導致原版的目標選擇器失效

### 复现此问题的步骤

1. 建立一個真命令
2. cmd.mandatory("player", ParamType.Player)
3. cmd.overload(["player"]);
4. cmd.setup()
5. 打開Server進入世界
6. 輸入./say @a[tag=a] 即可複現錯誤

### 有关的日志/输出

```raw
語法錯誤: @a>>[<<tag=test]
```

### 插件列表

```raw
(無)
```

**Comment by dreamguxiang** [comment]
检查是否有插件 RawText后还跟了参数，RawText后面跟任何参数都会造成此问题
