### ISSUE TITLE
存在监听onMoneyTrans时，任意money变动都会触发该监听函数。

### ISSUE THREAD

**Issue by Jotalz** [LiteLDev/LiteLoader#887]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows 10

### LiteLoader 版本

2.3.2

### BDS 版本

1.19.1.01

### 发生了什么?

某js插件中包含`mc.listen("onMoneyTrans",function(from,to,num){...code...}`函数，在游戏内进行增加或减少money的操作，而非转账操作时，也会触发该函数，导致该插件的某段无法获取正确pl对象（由于实际并未操作转账，所以返回的to参数是undefined)，从而导致后续代码报错。

### 复现此问题的步骤

1.安装上述版本（我不确定在其他版本中有没有同样问题）
2.任意编辑一个js插件，加入代码`mc.listen("onMoneyTrans",function(from,to,num)
{
  log('我无端的被执行啦！！！');
});`
3.添加例如TMEssential这种可操作经济插件
4.任意进行一次money增加或减少,查看控制台输出,会发现该log被输出
另：经测试，发现涉及到Money的经济变动事件都会被响应。例如onMoneyReduce在money增加时也会被触发

### 有关的日志/输出

```raw
15:21:39 ERROR [LiteLoader] Event Callback Failed!
15:21:39 ERROR [LiteLoader] Uncaught TypeError: Cannot read property 'xuid' of undefined
```

### 插件列表

```raw
15:39:41 INFO [Server] Plugin Lists [6]
15:39:41 INFO [Server] - LLMoney [v2.3.0] (LLMoney.dll)
15:39:41 INFO [Server]   EconomyCore for LiteLoaderBDS
15:39:41 INFO [Server] - ScriptEngine-Lua [v2.3.2] (LiteLoader.Lua.dll)
15:39:41 INFO [Server]   Lua ScriptEngine for LiteLoaderBDS
15:39:41 INFO [Server] - TMEssential.js [v1.3.0] (TMEssential.js)
15:39:41 INFO [Server]   新时代多功能基础插件
15:39:41 INFO [Server] - ScriptEngine-Js [v2.3.2] (LiteLoader.Js.dll)
15:39:41 INFO [Server]   Javascript ScriptEngine for LiteLoaderBDS
15:39:41 INFO [Server] - LLtoSC [v0.0.1] (LLtoSC.js)
15:39:41 INFO [Server]   经济同步
15:39:41 INFO [Server] - Tsidebar.js [v2.0.1] (Tsidebar.js)
15:39:41 INFO [Server]   快来自定义你的侧边栏吧
15:39:41 INFO [Server]
15:39:41 INFO [Server] * Send command "ll list <Plugin Name>" for more information
```

**Comment by ShrBox** [comment]
这是LLMoney本来的设计，[详见](https://github.com/LiteLDev/LLEssentials/blob/6b8c166a976cc83b56f301eba8dd4fa2c7cedcf9/LLMoney/api.cpp#L186)，你可以通过`if`来判断to是否为undefined来避免错误发生

**Comment by Jotalz** [comment]
好吧，原来如此，建议在开发文档中说明一下呢
