### ISSUE TITLE
玩家Ability修复

### ISSUE THREAD

**Issue by KobeBryant114514** [LiteLDev/LiteLoader#890]
### 您的建议是否与现存的某个问题相关?请描述问题?

似乎现在通过/ability无法给非op玩家飞行权限，能否修复这个问题和开放一个相关API。
LiteLoaderSDK从2.7.0结构进行了一定修改后，不再有AdventureSettingsPacket.hpp，能否恢复？

### 您认为还缺少什么?如何解决您的问题?

希望修复Ability无法应用于非op玩家，开放一个快速修改玩家Ability的API。
希望能修改玩家飞行权限并正常应用。AdventureSettingsPacket.hpp在新的SDK找不到。

**Comment by dreamguxiang** [comment]
AdventureSettingsPacket已被mc弃用,updateAdventureSettingPacket取代

**Comment by dreamguxiang** [comment]
已完成
