### ISSUE TITLE
获取未加载区块实体

### ISSUE THREAD

**Issue by KobeBryant114514** [LiteLDev/LiteLoader#894]
### 您的建议是否与现存的某个问题相关?请描述问题?

Level.hpp中获取全部实体只能获取到已加载区块实体。
如何获取未加载区块实体的数据？
能否在Level中添加关于未加载区块实体数据的获取？

### 您认为还缺少什么?如何解决您的问题?

获取未加载区块的实体的API，建议放在Level.hpp

**Comment by xinge4088** [comment]
这个得对存档结构需要比较熟悉了，幻化成疯 老哥在存档结构改版之前，写过一个删除传送门实体列表。用来修生电跨纬度导致的实体堆积问题。和这个功能的本质上应该差不多

**Comment by OEOTYAN** [comment]
并不通用，需求很少，不应内置在LL内。
