### ISSUE TITLE
新增已完成吃下东西的事件。

### ISSUE THREAD

**Issue by KobeBryant114514** [LiteLDev/LiteLoader#895]
### 您的建议是否与现存的某个问题相关?请描述问题?

Evevt::PlayerEatEvent监听到的是玩家正在吃东西，没有与之对应的已经吃完东西的监听。

### 您认为还缺少什么?如何解决您的问题?

新增一个对应的事件，与之对应，玩家已经完成吃下某个东西。
建议依旧在EvevtAPI.hpp

**Comment by KobeBryant114514** [comment]
目前的解决方案
THook(Item* , "?useTimeDepleted@FoodItemComponentLegacy@@UEAAPEBVItem@@AEAVItemStack@@AEAVPlayer@@AEAVLevel@@@Z",FoodItemComponentLegacy* _this, ItemStack* a, Player* b, Level* c){
	return original(_this, a, b, c);
}

**Comment by Jaciezyt** [comment]
既然已经找到了符号，建议交PR @Tsubasa6848

**Comment by ShrBox** [comment]
Thx
c5831ebff0e9dc013afe1601704d9df9cb612aba

**Comment by Jaciezyt** [comment]
此issue仍有两个问题：
1. 缺少LLSE的事件支持
2. (style)使用TInstanceHook代替THook(…, _this)

**Comment by KobeBryant114514** [comment]
好的我改一下等会重新PR

**Comment by ShrBox** [comment]
> 好的我改一下等会重新PR

Thx，建议使用git以方便进行pr（vs, clion均已内置）
