### ISSUE TITLE
llse的Websocket客户端接收的数据大小有限制

### ISSUE THREAD

**Issue by Hurry1027** [LiteLDev/LiteLoader#896]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2019

### LiteLoader 版本

2.8.0

### BDS 版本

1.19.40

### 发生了什么?

我正在做一个跨服背包同步插件。
我尝试用nodejs插件开设Websocket服务端，而在另一个BDS 用llse插件的Websocket api 做客户端。
当服务端发送的数据量大于60KB（大约）时，llse插件的 Websocket客户端会假死，只能发送发送数据，不能接收数据，甚至断连。

而我用nodejs的ws模块作为客户端时就没有问题。

推测原因在于Websocket协议的数据帧有数据大小限制，而llse的api没有对大数据分帧传输做优化。
知乎找到的类似问题
https://www.zhihu.com/question/62929340

### 复现此问题的步骤

1. 一个BDS 用Nodejs插件 用ws模块 开设Websocket服务端。
2. 另一个BDS 用llse插件，用自带的Websocket api 做客户端。
3. 当服务端向客户端发送的数据大于 60KB时，客户端会假死，只能发送发送数据，不能接收数据，甚至断连。
4. 重启客户端BDS可以解除假死。
5. 更换客户端api为Nodejs 插件的ws模块，则不会出现此问题。

### 有关的日志/输出

```raw
无
```

**Comment by Jaciezyt** [comment]
@Hurry1027 我建议按照知乎回答所说的超过65535字节部分自行处理一下

**Comment by Hurry1027** [comment]
> @Hurry1027 我建议按照知乎回答所说的超过65535字节部分自行处理一下

这当然是一种解决方法，不过过于繁琐，所以我还是放弃使用llse api ，而选择使用nodejs的ws模块做客户端。

我又想了想，可能是不同的Websocket模块对大数据切片传输的方法不同，导致llse客户端 和 nodejs ws服务端不兼容。
llse不能处理和整合由服务端发来的分片数据，导致llse客户端卡死。

**Comment by Jaciezyt** [comment]
Duplicate of LiteLDev/ScriptEngine#27
