### ISSUE TITLE
SEH Exception when i trying to getSkin

### ISSUE THREAD

**Issue by VinkyV** [LiteLDev/LiteLoader#897]
### Exceptions module

Core

### Operating System

Windows 10

### LiteLoader version

2.8.0-2.8.1

### BDS version

1.19.40-1.19.41

### What happened?

When i trying to get players skin in PlayerPreJoinEvent or PlayerJoinEvent it doesn't work and logs out SEH Exception.
![image](https://user-images.githubusercontent.com/75137786/200193935-0aaff1db-f289-491a-b186-1ee3c922a42c.png)

### Steps to reproduce?

1. Write a simple LL plugin
2. Create PlayerPreJoinEvent or PlayerJoinEvent
3. Try to getSkin from player via SerializedSkin SkinData = ev.mPlayer->getSkin();
4. Get an SEH Exception

### plugin.cpp
```cpp
#include <llapi/EventAPI.h>
#include <llapi/LLAPI.h>
#include <llapi/LoggerAPI.h>
#include <llapi/ServerAPI.h>
#include <llapi/mc/Player.hpp>
#include <llapi/mc/SerializedSkin.hpp>

#include "version.h"

// We recommend using the global logger.
extern Logger logger;

bool onPlayerPreJoin(Event::PlayerPreJoinEvent ev) {
    Player* pl = ev.mPlayer;
    SerializedSkin SkinData = pl->getSkin();
    return true;
}

void PluginInit() {
    logger.info("Hello, world!");
    Event::PlayerPreJoinEvent::subscribe(onPlayerPreJoin);
}
```

### Relevant log output

```raw
23:37:17 INFO [Server] Player connected: VinkW, xuid: 2535421698612346
23:37:17 ERROR [LiteLoader] Uncaught SEH Exception Detected!
23:37:17 ERROR [LiteLoader] Error: Code [-1066598274] SEH_UNKNOW_ERROR
23:37:17 ERROR [LiteLoader] In Event (class Event::PlayerPreJoinEvent)
23:37:17 ERROR [LiteLoader] In Plugin <SkinLoader 0.1.0>
23:37:20 INFO [Server] Player Spawned: VinkW xuid: 2535421698612346
```

### Plugin list

```raw
23:36:52 INFO [Server] - SkinLoader [v0.1.0] (SkinLoader.dll)
23:36:52 INFO [Server]   Saving Player Skins
23:36:52 INFO [Server] - PermissionAPI [v2.8.0] (PermissionAPI.dll)
23:36:52 INFO [Server]   Builtin & Powerful permission API for LiteLoaderBDS
```

**Comment by dreamguxiang** [comment]
update header

**Comment by dreamguxiang** [comment]
![image](https://user-images.githubusercontent.com/62042544/200217788-60a5793c-f233-497e-9d79-98f0760b498b.png)
![image](https://user-images.githubusercontent.com/62042544/200217808-0533463b-e652-4d76-9188-03302a455f61.png)
