### ISSUE TITLE
粒子生成器只在主世界生效

### ISSUE THREAD

**Issue by mrmagic2020** [LiteLDev/LiteLoader#904]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows Server 2016

### LiteLoader 版本

2.8.1

### BDS 版本

1.19.41

### 发生了什么?

粒子生成器ParticleSpawner只能在主世界生成粒子，尝试在其他维度生成时报错。

### 复现此问题的步骤

1、生成粒子生成器；
2、在下界或末地生成粒子；
3、报错。
具体代码：
let ps = mc.newParticleSpawner();
let pos = mc.newFloatPos(0,0,0,1);
ps.drawCuboid(pos);

### 有关的日志/输出

```raw
16:10:56 ERROR [LiteLoader] Error occurred in setInterval-Function
16:10:56 ERROR [LiteLoader] SEH Uncaught Exception Detected!
16:10:56 ERROR [LiteLoader] SEH_UNKNOW_ERROR
16:10:56 ERROR [LiteLoader] In Plugin: MLand
```

**Comment by OEOTYAN** [comment]
不存在此bug。
