### ISSUE TITLE
新增获取玩家/实体所在的结构的API和获取最近的结构的API

### ISSUE THREAD

**Issue by KobeBryant114514** [LiteLDev/LiteLoader#909]
### 您的建议是否与现存的某个问题相关?请描述问题?

无法获取玩家所在的结构，或者获取玩家最近的结构。
（类似于/locate structure 并且功能更强？）

比如说获取距离玩家最近的Ancient City
比如说获取玩家所在的结构，例如玩家在某个地方，获取是否在某个结构里面。

### 您认为还缺少什么?如何解决您的问题?

新增对应的API，希望不仅在Player.hpp，对应的Actor.hpp也能新增对应的API。
比如说
Player::getStructureName
Player::getNearestStructure
Player::isInStructure

等等

**Comment by quizhizhe** [comment]
🤔这些功能视乎使用原版指令都能够实现

**Comment by OEOTYAN** [comment]
无法对结构本身范围进行合理判定，并且不通用。
