### ISSUE TITLE
LiteLoaderBDS Support Minecraft Preview

### ISSUE THREAD

**Issue by BuslnwTH** [LiteLDev/LiteLoader#910]
### Is your feature request related to a problem? Please describe.

Currently Minecraft Bedrock have released Bedrock Server Preview now.
https://www.minecraft.net/en-us/download/server/bedrock

[I understand the development team is busy right now]

**Comment by dreamguxiang** [comment]
I will only support it in the last preview（like 1.19.50.25）
quickly update to the release version

**Comment by Jaciezyt** [comment]
> I will only support it in the last preview（like 1.19.50.25） quickly update to the release version

Pre-release better
