### ISSUE TITLE
pl.giveitem新增可以給物品訂名字

### ISSUE THREAD

**Issue by omscsamilcup** [LiteLDev/LiteLoader#914]
### 您的建议是否与现存的某个问题相关?请描述问题?

pl.giveitem(item,[amount,itemname]) 
可以幫助一些要寫mc.listen("onUseItemOn")選單的給物品名字(例如指南針的名字可以更改為pl.giveitem("minecraft:compass",1,"選單")

**Comment by OEOTYAN** [comment]
可以新建物品对象后 setDisplayName 再给玩家。
