### ISSUE TITLE
给LLSE的效果监听器增加更多信息

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#922]
### 您的建议是否与现存的某个问题相关?请描述问题?

LLSE的效果（Effect）监听器只有玩家与`ComponentName`，缺少更多实用的信息

### 您认为还缺少什么?如何解决您的问题?

增加效果监听器回调函数的参数

**Comment by KobeBryant114514** [comment]
效果的其他信息全在玩家NBT里面的啊，直接获取Player的NBT不就得了？

**Comment by Yushu2606** [comment]
> 效果的其他信息全在玩家NBT里面的啊，直接获取Player的NBT不就得了？

有方便的可能性干嘛要用麻烦的（x

**Comment by KobeBryant114514** [comment]
> ### 您的建议是否与现存的某个问题相关?请描述问题?
> LLSE的效果（Effect）监听器只有玩家与`ComponentName`，缺少更多实用的信息
> 
> ### 您认为还缺少什么?如何解决您的问题?
> 增加效果监听器回调函数的参数

你是说什么参数？
效果等级？效果时长？

**Comment by Yushu2606** [comment]
> > ### 您的建议是否与现存的某个问题相关?请描述问题?
> > LLSE的效果（Effect）监听器只有玩家与`ComponentName`，缺少更多实用的信息
> > ### 您认为还缺少什么?如何解决您的问题?
> > 增加效果监听器回调函数的参数
> 
> 你是说什么参数？ 效果等级？效果时长？

是的
