### ISSUE TITLE
LLSE中监听实体自然生成的BUG

### ISSUE THREAD

**Issue by FBQingYi** [LiteLDev/LiteLoader#930]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows 10

### LiteLoader 版本

2.9.0-beta-1

### BDS 版本

1.19.50

### 发生了什么?

刷怪笼因亮度无法刷怪时会一直尝试生成实体，此接口也会一直被回调！

### 复现此问题的步骤

`mc.listen("onMobSpawn", (typeName, pos) => {
    log(pos, typeName)
    return false;
})`

然后放置一个刷怪笼并在附近放上火把。

**Comment by Redbeanw44602** [comment]
`aavAC`?

Probably a bug in your AntiCheat plugin.
