### ISSUE TITLE
LLSE player.gameMode not get Spectator mode (6)

### ISSUE THREAD

**Issue by BuslnwTH** [LiteLDev/LiteLoader#932]
### Exceptions module

ScriptEngine

### Operating System

Windows Server 2022

### LiteLoader version

2.9.0 beta

### BDS version

1.19.50.02

### What happened?

player.gameMode not get gamemode 6 Spectator

**Comment by ShrBox** [comment]
![image](https://user-images.githubusercontent.com/53301243/205624209-2390abcd-6c37-4f2d-a3a2-ba4bc1a413e2.png)

**Comment by BuslnwTH** [comment]
How to check players the game mode players in the Spectator or player.gameMode send as survival, creative, adventure, spectator instead of sending an ID

**Comment by BuslnwTH** [comment]
player.setGamemode(6) is work for this version
