### ISSUE TITLE
Selectors aren`t working correctly.

### ISSUE THREAD

**Issue by VeryWeirdUser** [LiteLDev/LiteLoader#937]
### Exceptions module

ScriptEngine

### Operating System

Windows 11

### LiteLoader version

2.9.0

### BDS version

1.19.50

### What happened?

Selectors aren`t working correctly.
The reason for the error is in this code
```
mc.listen("onServerStarted", () => {
    FkickC = mc.newCommand("fkick", "Принудительно выгнать игрока", PermType.GameMasters)
    FkickC.optional("reason", ParamType.RawText, "Reason", 1);
    FkickC.setEnum("Pl", ["player"]);
    FkickC.setEnum("Reason", ["reason"]);
    FkickC.mandatory("pl", ParamType.Player, "Pl", 1);
    FkickC.overload(["Pl", "Reason"]);
    FkickC.setCallback((_cmd, _ori, out, res) => {
        if (res.reason != null) {
            res.pl[0].disconnect("Ты кикнут с этого сервера по причине:\n" + res.reason)
            return
        }
        res.pl[0].disconnect("Ты кикнут с этого сервера")
    });
    FkickC.setup();
})
```

### Steps to reproduce?

[download plugin](https://www.mediafire.com/file/w9r9eob5djnx1jq/t.js/file) and enter this command to the console: xp 5l @a[r=5]

### Relevant log output

Syntax error: Unexpected "[": at "/xp 5l >>[<<"

### Plugin list

14:58:53 INFO [Server] - ScriptEngine-QuickJs [v2.9.0] (LiteLoader.Js.dll)
14:58:53 INFO [Server]   Javascript ScriptEngine for LiteLoaderBDS
14:58:53 INFO [Server] - t [v1.0.0] (t.js)
14:58:53 INFO [Server]   t
14:58:53 INFO [Server] - ScriptEngine-NodeJs [v2.9.0] (LiteLoader.NodeJs.dll)
14:58:53 INFO [Server]   Node.js ScriptEngine for LiteLoaderBDS
14:58:53 INFO [Server] - ScriptEngine-Lua [v2.9.0] (LiteLoader.Lua.dll)
14:58:53 INFO [Server]   Lua ScriptEngine for LiteLoaderBDS

**Comment by KobeBryant114514** [comment]
The problem cannot be reproduced. Please do not capitalize in selectors.

问题无法复现。经测试目标选择器正常。

**Comment by VeryWeirdUser** [comment]
this is github, not me

**Comment by VeryWeirdUser** [comment]
i found the cause of this problem
