### ISSUE TITLE
Add mc.queryEntities() method to query entities with extended Minecraft selector grammar

### ISSUE THREAD

**Issue by futrime** [LiteLDev/LiteLoader#939]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

For example, we can query all entities with mc.queryEntities('@e'), all players with mc.queryEntities('@a'), or all players within 10 meters with mc.queryEntities('@a[r=10]').

**Comment by Redbeanw44602** [comment]
感觉很难实现
