### ISSUE TITLE
PlayerPlaceBlockEvent mBlockInstance returns clicked block

### ISSUE THREAD

**Issue by JustStevee** [LiteLDev/LiteLoader#952]
### Exceptions module

Core

### Operating System

Windows 10

### LiteLoader version

2.9.0

### BDS version

1.19.50

### What happened?

PlayerPlaceBlockEvent mBlockInstance returns clicked block, not block that player is trying to place 

### Steps to reproduce?

Write a simple plugin (on C++ or LLSE) that send you a message with type name of mBlockInstance

https://user-images.githubusercontent.com/98705108/207862912-aa8f2520-6666-42d3-96f1-6438d4be2d6f.mp4

### Relevant log output

```raw
I will send a video
```

**Comment by Redbeanw44602** [comment]
duplicate: #548 

If you don't need to intercept the place of block, please use `afterPlaceBlock`

**Comment by Jaciezyt** [comment]
Duplicate of #548
