### ISSUE TITLE
DLL插件跨版本支持

### ISSUE THREAD

**Issue by smartcreeper192** [LiteLDev/LiteLoader#953]
### 您的建议是否与现存的某个问题相关?请描述问题?

DLL插件不少接口都是直接调用BDS函数，这导致插件无法跨版本运行，能不能做一个兼容层，由它调用BDS函数，插件调用兼容层，来屏蔽BDS版本差异
作为一个有十多个DLL插件的腐竹，更新时简直是噩梦，不用DLL还会影响性能

**Comment by futrime** [comment]
@smartcreeper192 原生插件中，所有的LLAPI都是跨版本兼容的

**Comment by Redbeanw44602** [comment]
BDS每个版本都会改动大量函数，压根不可能做出所谓跨版本兼容。

常用的函数在LL内部可能有封装，尽量使用LL封装的函数可以减轻ABI变更导致的不兼容。

**Comment by Yushu2606** [comment]
你可能要找的是：LLAPI
