### ISSUE TITLE
ES Module Error

### ISSUE THREAD

**Issue by VoryWork** [LiteLDev/LiteLoader#957]
### Exceptions module

ScriptEngine

### Operating System

Windows Server 2022

### LiteLoader version

Latest

### BDS version

1.19.51

### What happened?

a.js
```
import dd1 from "/orgEX/db.js";

ll.registerPlugin(
    /* name */ "orgEX",
    /* introduction */ "综合的玩家组织插件",
    /* version */ [0,0,1],
    /* otherInformation */ {}
); 

dd1();
```
./orgEX/db.js

```
//LiteLoaderScript Dev Helper
/// <reference path="c:/Users/xmmpp/Desktop/程序工程/lxl/dts/HelperLib-master/src/index.d.ts"/>

let dd = ()=> {
  log("测试输出");
}

export default dd
```

04:37:54 ERROR [LiteLoader] Fail in Loading Script Plugin!

04:37:54 ERROR [LiteLoader] Fail to load c:\Users\xmmpp\Desktop\MC相关\bedrock-server-1.19.51.01-windows\plugins\orgEX.lxl.js!
04:37:54 ERROR [LiteLoader] In Plugin: orgEX
04:37:54 ERROR [LiteLoader] script::Exception expecting '('
    at c:\Users\xmmpp\Desktop\MC相关\bedrock-server-1.19.51.01-windows\plugins\orgEX.lxl.js:4

04:37:54 ERROR [Server] 插件 c:\Users\xmmpp\Desktop\MC相关\bedrock-server-1.19.51.01-windows\plugins\orgEX.lxl.js 加载失败

### Steps to reproduce?

编写以下插件放入plugins

### Relevant log output

```raw
04:37:54 ERROR [LiteLoader] Fail in Loading Script Plugin!

04:37:54 ERROR [LiteLoader] Fail to load c:\Users\xmmpp\Desktop\MC相关\bedrock-server-1.19.51.01-windows\plugins\orgEX.lxl.js!
04:37:54 ERROR [LiteLoader] In Plugin: orgEX
04:37:54 ERROR [LiteLoader] script::Exception expecting '('
    at c:\Users\xmmpp\Desktop\MC相关\bedrock-server-1.19.51.01-windows\plugins\orgEX.lxl.js:4


04:37:54 ERROR [Server] 插件 c:\Users\xmmpp\Desktop\MC相关\bedrock-server-1.19.51.01-windows\plugins\orgEX.lxl.js 加载失败
```

**Comment by dreamguxiang** [comment]
@VoryWork 这61是什么jb

**Comment by lgc2333** [comment]
#851

**Comment by yqs112358** [comment]
已在 LiteLDev/LeviLamina#1052 修复，等待下个版本更新即可正常在QuickJs插件中使用ESM
