### ISSUE TITLE
mc.explode()若参数isDestroy=true,无论isFire=true/false都会产生火焰

### ISSUE THREAD

**Issue by mrmagic2020** [LiteLDev/LiteLoader#959]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows Server 2019

### LiteLoader 版本

2.9.0

### BDS 版本

1.19.50

### 发生了什么?

使用函数mc.explode(pos,source,power,range,isDestroy,isFire)制造爆炸时，只要isDestroy=true，则产生的爆炸都会有火焰，忽视isFire的值。

### 复现此问题的步骤

1. mc.explode(pos,source,power,range,true,false);
2. 爆炸留下燃烧的火焰

**Comment by Redbeanw44602** [comment]
最后一个参数 `isFire` 似乎失效了，目前是
```
isBreaking = true，isFire = false ---> 破坏方块 + 创建火
isBreaking = false，isFire = true ---> 不破坏方块 + 不创建火
```

**Comment by KobeBryant114514** [comment]
@Redbeanw44602 并不是LiteLoader本体的问题，而是 Level::createExplosion 这个API变了，而脚本引擎没有做出对应的调整。
实际上最后一个参数isFire实际上传入的是 maxResistance，而参数range 传入的才是 isFire。
range这个参数并不存在。
