### ISSUE TITLE
Add in-game `/ll list` command

### ISSUE THREAD

**Issue by 7Wdev** [LiteLDev/LiteLoader#961]
it would be very useful and helpful
if you add native /plugins commands wich shows all the plugins that are added to the server as well as the loaded ones and not, exactly as in pocketmine

**Comment by KobeBryant114514** [comment]
Use "/ll list" pls

**Comment by 7Wdev** [comment]
There is no such command as /ll list ingame

**Comment by mrmagic2020** [comment]
> There is no such command as /ll list ingame

why use it ingame

**Comment by 7Wdev** [comment]
> > There is no such command as /ll list ingame
> 
> why use it ingame

It just will make the life easier.

**Comment by Zaitonn** [comment]
you should use in console
and it's not safe to let players to know the list of plugins maybe (they can attack server through plugins' bugs)

**Comment by Jaciezyt** [comment]
@7Wdev obviously it is not a good idea
currently wontfix
maybe we will interface PermissionAPI in the future

**Comment by 7Wdev** [comment]
> @7Wdev obviously it is not a good idea currently wontfix maybe we will interface PermissionAPI in the future

Yea, of course it shouldn't be accessible by anyone, only ops and people who have permission.
A permissionAPI would be great implementation

**Comment by KobeBryant114514** [comment]
Add a line "op-permission-level=4" in server.properties, and you can use it in game.
