### ISSUE TITLE
冗余功能

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#968]
### 您的建议是否与现存的某个问题相关?请描述问题?

LL的一些功能BDS已经修复/实现了

### 您认为还缺少什么?如何解决您的问题?

移除冗余功能

**Comment by wzyyyyyyy** [comment]
@StarsDream00 你认为冗余功能都有什么

**Comment by Yushu2606** [comment]
> @StarsDream00 你认为冗余功能都有什么

目前确定的有ClientChunkPreGeneration（对应1.19.50增加的client-side-chunk-generation-enabled）
不确定的可能还有一部分崩溃漏洞

**Comment by ShrBox** [comment]
61b77160082ca6504ea7911ab3449b2e7795b6a8

**Comment by Yushu2606** [comment]
`FixListenPort`可能也不再需要了
