### ISSUE TITLE
在llse环境中，尝试访问类名会被返回未定义错误

### ISSUE THREAD

**Issue by harry-xi** [LiteLDev/LiteLoader#974]
### 您的建议是否与现存的某个问题相关?请描述问题?

如题，在llse的js环境中，尝试访问类名会被返回未定义错误。
我认为这是个llse未实现的功能，所有没有将此问题作为一个bug来反馈

### 您认为还缺少什么?如何解决您的问题?

在llse中，是否有可能使得自定义类型等的特性更接近JavaScript中的行为？

**Comment by Jaciezyt** [comment]
什么叫访问类名？

**Comment by harry-xi** [comment]
> 什么叫访问类名？

我发现我在提这个需求的时候犯了一些错误，很抱歉打扰到您。
