### ISSUE TITLE
添加离线玩家计分板操作API

### ISSUE THREAD

**Issue by kkj9333** [LiteLDev/LiteLoader#976]
### 您的建议是否与现存的某个问题相关?请描述问题?

目前大多数计分板经济在玩家离线时会采用使用假名计分板或者外部存储的方式进行运作，但是这样这样会带来一些冲突，比如tmessential插件在玩家上线时会将离线账户的金钱记录直接覆盖到玩家的对应金钱的计分板项目上，如果此时在上线时进行其他金钱操作（比如指令进行上线给钱操作），且这个操作在TM插件覆盖之前进行，会导致该操作无效，因为会直接被TM插件的离线账户的金钱记录覆盖，这是一个非常严重的冲突，如果存在多个插件如此操作，则会导致计分板经济系统崩溃。
另外一个考虑是插件功能性因素，对于经济排行榜，如果玩家的经济记录在离线账户而不是自己的对应计分板项目上，会导致经济排行榜不够准确，除非玩家上线更新，如果提供了离线计分板玩家经济操作API，则可以实时反馈金钱变化量，从而完善插件功能性；对于转账操作，如果提供了离线玩家计分板操作API，也就从而可以实现直接转账到玩家账户，而非转移到临时的离线账户或者外部存储文件里。
综上所述，希望能提供离线玩家计分板操作API，以规范插件开发者对离线玩家经济账户的操作行为和提供给计分板经济更便捷的操作。

### 您认为还缺少什么?如何解决您的问题?

希望能提供离线玩家计分板操作API，以规范插件开发者对离线玩家经济账户的操作行为。
具体应包括离线玩家计分板经济的查询，修改功能。

**Comment by futrime** [comment]
@kkj9333 不推荐使用计分板经济，可以的话请使用llmoney

**Comment by Jaciezyt** [comment]
@kkj9333 受限于ScoreboardId，不好解决，建议使用player.realName + " "作为id或者player.xuid作为id

**Comment by kkj9333** [comment]
但是会有腐竹使用，如果有人用插件就必须提供计分板经济模式，这就无法避免这些问题，所以希望能加入该api；
至于ScoreboardId，实际上基于离线玩家nbt获取已经可以实现查询修改创建了，稍后PR

**Comment by kkj9333** [comment]
(我刚刚已经PR了一份实现方案，可在这里查看：https://github.com/LiteLDev/LiteLoaderBDS/pull/977)

**Comment by kkj9333** [comment]
请问一下，clang-format的这个问题如何解决，只是输入“;”就会报错
![image](https://user-images.githubusercontent.com/51207072/210131615-e3b77f69-5c66-4d69-83d3-b93607c9c622.png)

**Comment by kkj9333** [comment]
另外就是从github下载的LiteLoaderBDS用cmake构建完后，我在项目根目录并没有找到‘PackRelease.cmd’这个文件
![image](https://user-images.githubusercontent.com/51207072/210131720-dce3d26c-e794-4778-a922-f2a10aa11c6a.png)
![image](https://user-images.githubusercontent.com/51207072/210131743-70aacc1a-311b-4f22-aac1-c2fcd48cc33b.png)
