### ISSUE TITLE
明确事件系统应当提供的信息

### ISSUE THREAD

**Issue by Redbeanw44602** [LiteLDev/LiteLoader#980]
### 异常模块

LiteLoader (本体)

### 操作系统

Windows Server 2022

### LiteLoader 版本

not important.

### BDS 版本

not important.

### 发生了什么?

1. 目前部分假人（模拟玩家）操作会触发事件，但是假人没有XUID
2. 部分事件**经常**发生莫名其妙的提供无效参数的情况

#### *事件系统应当保证参数是可用的*
>  考虑到简化插件开发复杂度，**相关参数可用性检查应当由LL完成**  
> 因此，应为大部分事件添加参数可用性检查，若参数无效则不把事件广播给插件

### 复现此问题的步骤

iland时常有这方面的问题报告

https://github.com/LiteLScript-Dev/iLand-Core/issues/46
https://github.com/LiteLScript-Dev/iLand-Core/issues/45

### 有关的日志/输出

```raw
略
```

### 插件列表

```raw
not important.
```

**Comment by harry-xi** [comment]
有没有可能为模拟玩家创建的假人的XUID提供一个有效值（可以是类似于在开启xboxid的情况下通关公钥进服的假人的负xiud等），或者提供一个特殊值（不过显然一样是个会带来兼容性问题的更改），我想这可能可以更有效的解决问题。
因为即便不在监听器里，意外的null都是灾难性的。

**Comment by OEOTYAN** [comment]
已提供XUID。

**Comment by Redbeanw44602** [comment]
无效参数问题是否修复？

**Comment by OEOTYAN** [comment]
能否描述的更加明确一些？

**Comment by Redbeanw44602** [comment]
具体来说，就是事件系统提供的参数有时是无效的（null），这个问题暂时没有稳定复现的方法但是经常出现，建议在新事件系统中为每个参数判空。

**Comment by harry-xi** [comment]
> 具体来说，就是事件系统提供的参数有时是无效的（null），这个问题暂时没有稳定复现的方法但是经常出现，建议在新事件系统中为每个参数判空。

你希望判空之后，引擎做出什么动作呢？我觉得参数无效不代表事件没发生把？
- 倒是或许可以考虑允许提供两个回调函数分别处理参数有效/无效的情况。
或者简单点来说，决定是否不接受参数无效的事件的主动权应该在插件。

**Comment by OEOTYAN** [comment]
> 

哈哈 那我就更不懂了 这不是更应该让插件开发者自己去判空确定需要什么操作么

**Comment by OEOTYAN** [comment]
就比如我写we获取右键事件有时候得到blockinstance是 null 有的时候我需要选择视线对应的方块 我不需要null 我给判定扔掉 有的时候我需要右键选择当前脚下方块就又需要null 显然null判定是插件开发者自己的事情

**Comment by harry-xi** [comment]
> > 
> 
> 哈哈 那我就更不懂了 这不是更应该让插件开发者自己去判空确定需要什么操作么

这条issues的提起者明显是希望LL对空参数作判断。不过我觉得是应该完全由插件作者自行处理的。

**Comment by OEOTYAN** [comment]
> > 哈哈 那我就更不懂了 这不是更应该让插件开发者自己去判空确定需要什么操作么
> 
> 这条issues的提起者明显是希望LL对空参数作判断。不过我觉得是应该完全由插件作者自行处理的。

我也觉得，而且我也举例了null并不一定意味没用

**Comment by RimuruChan** [comment]
关键在于对成员是否可以为空和其空的含义写入文档，并结合实际情况调用或不调用事件，剩下的交给开发者。可以为空的可以考虑使用optional，避免出现空指针引用

**Comment by OEOTYAN** [comment]
> @OEOTYAN 关键在于对成员是否可以为空和其空的含义写入文档

这个可以做

**Comment by Redbeanw44602** [comment]
很明显二位没有理解我的意思。在[这里](https://github.com/LiteLScript-Dev/iLand-Core/issues/45) onMobHurt事件中生物指针竟然为空，这是不正常的（很明显在任何情况下生物指针都不应为空）所以这个生物指针算是一个“事件系统应当提供的信息”，不应该交由插件处理。

**Comment by OEOTYAN** [comment]
> 很明显二位没有理解我的意思。在[这里](https://github.com/LiteLScript-Dev/iLand-Core/issues/45) onMobHurt事件中生物指针竟然为空，这是不正常的（很明显在任何情况下生物指针都不应为空）所以这个生物指针算是一个“事件系统应当提供的信息”，不应该交由插件处理。

彳亍

**Comment by OEOTYAN** [comment]
> 很明显二位没有理解我的意思。在[这里](https://github.com/LiteLScript-Dev/iLand-Core/issues/45) onMobHurt事件中生物指针竟然为空，这是不正常的（很明显在任何情况下生物指针都不应为空）所以这个生物指针算是一个“事件系统应当提供的信息”，不应该交由插件处理。

那你直接说哪个事件不就好了…… 知道确切位置了那就好办了

**Comment by Redbeanw44602** [comment]
总结一下：即引擎应为不可能为空的参数事先判空，若发现异常应直接丢弃事件。

*不丢弃也没有意义啊，还会让下游的插件出错*

**Comment by Redbeanw44602** [comment]
> > 很明显二位没有理解我的意思。在[这里](https://github.com/LiteLScript-Dev/iLand-Core/issues/45) onMobHurt事件中生物指针竟然为空，这是不正常的（很明显在任何情况下生物指针都不应为空）所以这个生物指针算是一个“事件系统应当提供的信息”，不应该交由插件处理。
> 
> 那你直接说哪个事件不就好了…… 知道确切位置了那就好办了

我只是举个例子，iland这里不少事件多多少少都有点提供空参数的报告（也不知道为什么会这样）所以我的想法是给所有事件上保护。

这个应该可以用宏来处理，有些不能判的就不管了，能判的判。
