### ISSUE TITLE
LLSE新增修改玩家朝向方法

### ISSUE THREAD

**Issue by superx101** [LiteLDev/LiteLoader#982]
### 您的建议是否与现存的某个问题相关?请描述问题?

当需要精确控制玩家朝向时，只有通过指令:
`teleport <destination: x y z> [yRot: value] [xRot: value] [checkForBlocks: Boolean]`
`teleport <destination: x y z> facing <lookAtPosition：x y z> [checkForBlocks: Boolean]`
如果可以直接修改玩家朝向将极大方便开发

### 您认为还缺少什么?如何解决您的问题?

希望新增修改玩家朝向的方法

**Comment by PA733** [comment]
@superx101 请使用execute

**Comment by PA733** [comment]
> @superx101 请使用execute

这是对你编辑前内容的回复。
如果需要更改issue，建议跟帖而不是直接修改原issue。

**Comment by superx101** [comment]
> @superx101 请使用execute

感谢大佬指点，用的确实是execute
经过测试后发现：
1.19.50以前execute可以正常执行，即在下界中使用tp后依然在下界
1.19.50后版本中后台指令似乎无法正常工作，以下是测试内容与结果：
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

</head>
<body>



在下界中执行指令 | 后台执行效果 | mc.runcmd执行效果 | 游戏内执行效果
-- | -- | -- | --
execute run /tp steve ~ ~ ~ | 传送到主世界 | 传送到主世界 | 传送到下界
execute as steve run /tp `@s` ~ ~ ~ | 传送到主世界 | 传送到主世界 | 传送到下界
execute in nether as steve run tp `@s` ~ ~ ~ | 传送到下界0 0 0位置(不等于传送前坐标) | 传送到下界0 0 0位置(不等于传送前坐标) | 传送到下界(等于传送前坐标)



</body>
</html>

**Comment by PA733** [comment]
```
execute at PA733 run tp PA733 ~ ~ ~
execute positioned as PA733 in nether run tp PA733 ~ ~ ~
```
均可以实现上述需求。
据您目前的描述来看，我不认为这像是一个ll的问题。

**Comment by superx101** [comment]
> ```
> execute at PA733 run tp PA733 ~ ~ ~
> execute positioned as PA733 in nether run tp PA733 ~ ~ ~
> ```
> 
> 均可以实现上述需求。 据您目前的描述来看，我不认为这像是一个ll的问题。

感谢回复。
根据您提供的指令中
后台验证`execute at steve run tp steve ~ ~ ~`可达到预期效果
后台验证`execute positioned as steve in nether run tp steve ~ ~ ~`时并未实现预期效果。
后台输出如下：(ll: 2.9.0 bds: 1.19.50.02)
例1.1：
```
16:25:05 INFO [Command] <steve> /tp @s 10 10 10
execute positioned as steve in nether run tp steve ~ ~ ~ 
16:25:14 INFO [Server] Teleported steve to 1.31, 10.00, 1.31
```
例1.2：
```
16:47:05 INFO [Command] <steve> /tp @s 10 80 10
execute positioned as steve in nether run tp steve ~ ~ ~ 
16:47:27 INFO [Server] Teleported steve to 1.31, 80.00, 1.31
```
返回原版bds中测试：(bds: 1.19.50.02, 1.19.51.01)
例2.1：
```
//此时玩家位于10 10 10
execute positioned as steve in nether run tp steve ~ ~ ~
Teleported steve to 1.34, 10.00, 1.29
```
例2.2：
```
//此时玩家位于10 80 10
execute positioned as steve in nether run tp steve ~ ~ ~
Teleported steve to 1.30, 80.22, 1.30
```
根据上述结果看，这并不是一个ll问题。
但在1.19.50和1.19.51中无法正确执行`execute positioned as name in nether run tp name ~ ~ ~`
显然，通过形如`execute at name run tp name x1 y1 z1 facing x2 y2 z2 `等形式的指令可以对玩家朝向进行控制，但还是希望在不占用过多项目开发周期的情况下，添加直接对朝向修改的方法。
