### ISSUE TITLE
LLSE "onMobHurt"监听增加实际伤害参数

### ISSUE THREAD

**Issue by Hesitate-P** [LiteLDev/LiteLoader#991]
### 您的建议是否与现存的某个问题相关?请描述问题?

在一些插件中需要使用

### 您认为还缺少什么?如何解决您的问题?

RT，在"onMobHurt"监听中增加实际伤害参数

**Comment by Redbeanw44602** [comment]
这个不是真伤吗，翻了下反汇编感觉是真实伤害。

```
Player::attack 82 -> Actor::calculateAttackDamage()
Player::attack 110 -> Actor::hurt()
Actor::hurt() 8 -> Actor::_hurt() 此事件hook的函数
```

**Comment by Hesitate-P** [comment]
> 这个不是真伤吗，翻了下反汇编感觉是真实伤害。
> 
> ```
> Player::attack 82 -> Actor::calculateAttackDamage()
> Player::attack 110 -> Actor::hurt()
> Actor::hurt() 8 -> Actor::_hurt() 此事件hook的函数
> ```

我这里需要的是减去护甲值所获得的伤害，而llse返回的参数是原始伤害
至于如何验证是否是实际伤害，可以在监听下面输出返回的伤害值和玩家前后血量对比是否一致，若一致，则说明这个数值并非实际伤害值而是原始伤害。
