### ISSUE TITLE
LLSE获取插件自身路径返回null

### ISSUE THREAD

**Issue by ImYoyoData** [LiteLDev/LiteLoader#995]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows 11

### LiteLoader 版本

2.9.1

### BDS 版本

1.19.51

### 发生了什么?

根据 LL 2.2.4 增加的新功能  LLSE获取插件自身名称 [#404](https://github.com/LiteLDev/LiteLoaderBDS/issues/404)

根据 llse 举例
`let info = ll.getPluginInfo("MyPlugin");
info.filePath;`
我测试了 js 和 nodejs

得到的均为 null

**Comment by Redbeanw44602** [comment]
```
jsdebug
16:41:48 INFO [LiteLoader] Debug mode begins
> ll.getPluginInfo("iLand").filePath
Project\iLand\iland-core.lua
```
无法复现，`MyPlugin` 是不是没有注册？
