### ISSUE TITLE
添加适用于1.19.50的方块类型参数

### ISSUE THREAD

**Issue by superx101** [LiteLDev/LiteLoader#996]
### 您的建议是否与现存的某个问题相关?请描述问题?

命令系统注册命令：
`Command.mandatory(name,type[,enumName,identifier,enumOptions])`
中的type项的`ParamType.Block`于1.19.50后被删除，在新版中无法注册有关方块的命令

**Comment by KobeBryant114514** [comment]
我记得旧的符号应该是在1.19.50被移除了，应该暂时无法直接注册方块参数。
你可以暂时使用String作为参数，手动解析方块类型

**Comment by superx101** [comment]
对的，在1.19.50被移除了，希望能添加一个新参数在1.19.50以后使用

**Comment by dreamguxiang** [comment]
已修复，LLSE CommandAPI不变，原生插件自行调整（参考LLSE）
